### PR TITLE
docs: Correct field name.

### PR DESCRIPTION
**Pull request by maya-r**
A single entry is a storageClassDeviceSet in the code, but in YAML
the name that appears is the one of the whole array.

### CODE REVIEW

**Review by subhamkrai — CHANGES_REQUESTED** [review]
@maya-r Thanks for the PR. Can you update other instances of `StorageClassDeviceSet`in the same file there are 4 or 5 more of this? Thanks

**Comment by subhamkrai** [comment]
@maya-r also see commitlint error
```console
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
✖   subject may not end with full stop [subject-full-stop]

✖   found 2 problems, 0 warnings
```
for details see this https://rook.io/docs/rook/master/development-flow.html#commit-structure

**Comment by maya-r** [comment]
I'm not sure that it's correct to change those - the other references seem to be talking about a single element of the array

**Review by leseb — CHANGES_REQUESTED** [review]
Looks like `Documentation/ceph-cluster-crd.md` and `Documentation/ceph-osd-mgmt.md` need fixes too.

**Review by leseb — APPROVED** [review]

**Review by subhamkrai — APPROVED** [review]

**Pull request merged**
