### PR TITLE
external: add support for rados namespace for rbd ec pools

### PR DESCRIPTION
**Pull request by parth-gr**
currently addded the support for rados namesapce
for rbd ec pools upstream

closes: https://github.com/rook/rook/issues/13633

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by parth-gr** [comment]
@bauerjs1  any feedback?

**Comment by bauerjs1** [comment]
@parth-gr the "missing rados namespace" error is gone! However I am still experiencing another error:
> The provided rgw Endpoint, 'rgw.example.org:443', is invalid.

I added some debugging output to that location in the script and it turns out that this request just gets an HTTP 403 response. Not sure if that is somehow related to https://github.com/rook/rook/pull/13856#issuecomment-2013173895

Another thing that looks suspicious to me are some of the client caps, e.g.:
```
Execute: 'ceph auth get-or-create client.csi-rbd-node-staging... mon profile rbd, allow command 'osd blocklist' osd profile rbd pool=ceph-hdd-block namespace=staging'
Execute: 'ceph auth get-or-create client.csi-rbd-provisioner-staging... mon profile rbd, allow command 'osd blocklist' mgr allow rw osd profile rbd pool=ceph-hdd-block namespace=staging'
```
(from the dry-run output)

Since `pool=ceph-hdd-block` is an erasure-coded pool, there will be no `namespace=staging`. The namespace is only present in the metadata pool.

**Comment by parth-gr** [comment]
> @parth-gr the "missing rados namespace" error is gone! However I am still experiencing another error:
> 
> > The provided rgw Endpoint, 'rgw.example.org:443', is invalid.
> 
> I added some debugging output to that location in the script and it turns out that this request just gets an HTTP 403 response. Not sure if that is somehow related to [#13856 (comment)](https://github.com/rook/rook/pull/13856#issuecomment-2013173895)
> 
> Another thing that looks suspicious to me are some of the client caps, e.g.:
> 
> ```
> Execute: 'ceph auth get-or-create client.csi-rbd-node-staging... mon profile rbd, allow command 'osd blocklist' osd profile rbd pool=ceph-hdd-block namespace=staging'
> Execute: 'ceph auth get-or-create client.csi-rbd-provisioner-staging... mon profile rbd, allow command 'osd blocklist' mgr allow rw osd profile rbd pool=ceph-hdd-block namespace=staging'
> ```
> 
> (from the dry-run output)
> 
> Since `pool=ceph-hdd-block` is an erasure-coded pool, there will be no `namespace=staging`. The namespace is only present in the metadata pool.

Can you paste the exact command ou used to run the script and the exact output,

And I believe the original issue is fixed and we are good with the pr

**Comment by parth-gr** [comment]
@bauerjs1 we did the fix https://github.com/rook/rook/pull/13982 thanks for reporting, would you like to try the rados namespace now?

**Comment by parth-gr** [comment]
@travisn I believe we are good with this fix.

**Review by travisn — APPROVED** [review]

**Pull request merged**
