### PR TITLE
test: rm canary/integration "Free Disk Space" step

### PR DESCRIPTION
**Pull request by jhoblitt**
This step consumes several minutes per job.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by jhoblitt** [comment]
I was intending to change the mon disk free lmits as follows:

```
+++ b/deploy/examples/cluster-test.yaml
@@ -14,6 +14,10 @@ metadata:
   namespace: rook-ceph # namespace:cluster
 spec:
   dataDirHostPath: /var/lib/rook
+  cephConfig:
+    mon:
+      mon_data_avail_warn: "2"
+      mon_data_avail_crit: "1"
   cephVersion:
     image: quay.io/ceph/ceph:v19
     allowUnsupported: true
```

but it appears that this isn't necessary.  I would be happy add that change on as additional safety margin.

**Comment by travisn** [comment]
Sounds great if we don't need this action anymore to save the time on every test run of several minutes. @subhamkrai please review

@jhoblitt If needed, sounds good to change the warning limit in the test cluster. But perhaps the runners have increased their space recently so hopefully we don't need that.

**Comment by subhamkrai** [comment]
> Sounds great if we don't need this action anymore to save the time on every test run of several minutes. @subhamkrai please review
> 
> @jhoblitt If needed, sounds good to change the warning limit in the test cluster. But perhaps the runners have increased their space recently so hopefully we don't need that.

sounds good for now, I'll merge this and we can revisit this if needed.

**Comment by jhoblitt** [comment]
The rgw-multisite-testing canary is being unreliable again.  I will keep clicking rebuild until is passes.

**Review by subhamkrai — APPROVED** [review]
Approving it

**Pull request merged**
