### PR TITLE
add clusterNamespace and associated comment to explain its necessity

### PR DESCRIPTION
**Pull request by zcourts**
supersedes #1619 

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [x] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.

[skip ci]

### CODE REVIEW

**Comment by zcourts** [comment]
@travisn mind taking a look?
Where is it getting the email for the DCO check and how do I get it to use my updated email?

**Comment by jbw976** [comment]
@zcourts it looks like the Author field of the commit is `courtney@crlog.info`, while the DCO sign-off in the commit message is using `courtney.robinson@hypi.io`:
```
> git log -n 1 --format=fuller
commit a263b84d70df9c0b8b6947fde992519e7f39b530 (HEAD, zcourts/feature/doc-minor-patch)
Author:     zcourts <courtney@crlog.info>
AuthorDate: Wed Jun 20 02:42:41 2018 +0200
Commit:     zcourts <courtney@crlog.info>
CommitDate: Wed Jun 20 02:42:41 2018 +0200

    add clusterNamespace and associated comment to explain its necessity

    Signed-off-by: zcourts <courtney.robinson@hypi.io>
```

Which one is the correct one to use?  You either need to [amend the commit author](https://stackoverflow.com/a/3042512/467462) or [amend the commit message](https://help.github.com/articles/changing-a-commit-message/) to fix the incorrect one. Hope that helps.

**Comment by travisn** [comment]
@zcourts looks good, force commits to a fork for a PR are actually common

**Comment by jbw976** [comment]
cool @zcourts, thanks for getting the commit updated and congratulations on your first contribution to the Rook project! 💪

**Pull request merged**
