### PR TITLE
ceph: increase liveness probe start delay on OSD

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

When the cluster is loaded and we restart an OSD, it will need some time
to respond to socket calls, basically more to be ready.
Increasing the initialDelaySeconds of the liveness probe fixes that
issue. For OSD, it waits for 45 sec, where other daemons 10 sec.

Closes: https://github.com/rook/rook/issues/5492
Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/rook/rook/issues/5492

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]

### CODE REVIEW

**Comment by dimm0** [comment]
This is not configurable, is it? What if I need more? 😇

**Comment by leseb** [comment]
> This is not configurable, is it? What if I need more? 😇

Do you? :-)

**Comment by dimm0** [comment]
Yes... We have 2 nodes with older slower 5400RPM drives, and as I'm updating rook, one of those nodes OSDs started crashlooping... Took me a day to find that it's the liveness probe
I'm going to exclude these nodes most likely to speed up the cluster, but I might hit this again with some other slower nodes

**Comment by leseb** [comment]
> Yes... We have 2 nodes with older slower 5400RPM drives, and as I'm updating rook, one of those nodes OSDs started crashlooping... Took me a day to find that it's the liveness probe
> I'm going to exclude these nodes most likely to speed up the cluster, but I might hit this again with some other slower nodes

Yes that's a problem if the pod starts CLBO as soon as the drives get slower that's a problem...

**Comment by Negashev** [comment]
@leseb 
Hi, we also searched for this problem for a long time, 12 hours. How can I adjust the livenessProbe?

**Comment by dimm0** [comment]
https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#health-settings

**Pull request merged**
