### PR TITLE
docs: update ROOK_MON_HEALTHCHECK_INTERVAL

### PR DESCRIPTION
**Pull request by LinuxGit**
**Description of your changes:**
design docs: update ROOK_MON_HEALTHCHECK_INTERVAL

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

[skip ci]

### CODE REVIEW

**Comment by BlaineEXE** [comment]
@travisn This PR is modifying the design doc to reflect the current healthcheck interval which is 45 seconds. I'm not sure if we want to retroactively change design docs or not. At any rate, I'm curious if there was a particular decision made to change the healthcheck interval 45 seconds.

**Comment by galexrt** [comment]
@travisn @jbw976 Should design docs be updated later on as in this PR?

**Comment by travisn** [comment]
@BlaineEXE @galexrt I would recommend keeping the design docs updated as long as they are still relevant. Some of the design docs are not relevant anymore, so perhaps we should mark them as outdated if we aren't planning on updating them.

In this case, the latest default values are 45 seconds refresh interval and failover is 10 minutes, so it would be good to update the latter value at the same time as well. @LinuxGit would you mind updating that as well? Apologies for losing track of this over the break.

**Comment by LinuxGit** [comment]
@travisn I found that the  monOutTimeout in rook chart and [mon pkg](https://github.com/rook/rook/blob/b4c90b651f2d14f7c6b721cb85f2a818e87ea02c/pkg/operator/ceph/cluster/mon/health.go#L36) is "300s", monOutTimeout in [operator yaml example](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L464) is 600s. I'm not sure failover timeout in all these files should be updated to 10 minutes.

**Comment by travisn** [comment]
@LinuxGit Yes, would be great to update these so they're consistent at 600s.

**Comment by LinuxGit** [comment]
@travisn Done

**Comment by travisn** [comment]
@LinuxGit Looks good, except there is a merge commit. Could you [rebase](https://rook.io/docs/rook/v0.9/development-flow.html#updating-your-fork) to avoid the merge commit? thanks

**Comment by LinuxGit** [comment]
@travisn OK. Thanks. I've remove the merge commit.

**Pull request merged**
