### PR TITLE
docs: Remove obsolete section of upgrade guide

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
The bluestore_fsck_quick_fix_on_mount fix was only needed when upgrading to
versions of Ceph older than v16.2.6. Everyone on pacific should now be
on v16.2.7, so we can remove this section from the v1.9 upgrade guide.

Also cleaning up a few other small issues in the guide.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
I'm not sure if we can really assume people are on 16.2.7 now. Unless Rook drops support for 16.2.6 and below, I think we need to include it and should leave that section.

**Comment by travisn** [comment]
> I'm not sure if we can really assume people are on 16.2.7 now. Unless Rook drops support for 16.2.6 and below, I think we need to include it and should leave that section.

I'm not assuming everyone is on 16.2.7, but my assumption is that if anyone updates to Pacific, they should just straight to the latest 16.2.7+. That issue only occurred if upgrading **to** 16.2.0-16.2.6, so it doesn't seem so relevant anymore.

**Comment by BlaineEXE** [comment]
I guess that's fair. I wonder if it would save us headache with any confused users put a small note about recommending to upgrade to 16.2.7+, and if users intend to go lower, they should refer to the v1.8 docs? That way we clear space but hopefully don't open ourselves up to more confused people on slack/github?

**Comment by travisn** [comment]
Sure, I'll mention it briefly add a link back to the 1.8 guide just in case.

**Review by BlaineEXE — APPROVED** [review]

**Pull request merged**
