### PR TITLE
Update controller.go

### PR DESCRIPTION
**Pull request by OmriShiv**
Description of your changes:
Typo fix in provisioner controller

Which issue is resolved by this Pull Request:
Resolves # N/A

Checklist:
- [X] Documentation has been updated, if necessary.
- [X] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by bassam** [comment]
@OmriShiv thanks! Please sign off on the commit using `git commit -s`. See https://github.com/rook/rook/blob/master/CONTRIBUTING.md#certificate-of-origin

**Comment by OmriShiv** [comment]
@bassam thank you, but I'm not sure if I did that right.

**Comment by jbw976** [comment]
@OmriShiv, we'd like to get the commits for this PR (https://github.com/rook/rook/pull/1479/commits) squashed to just a single commit that has the sign-off.  This link may help you convert the merge commit to a regular commit and then squash them all down to a single commit:  https://stackoverflow.com/a/32842174/467462

When squashing, note that the commit you'd want to preserve is the one that has the sign-off.  Thanks for your efforts.

**Comment by OmriShiv** [comment]
I'm having issues with this, closed and updated in #1482

**Pull request closed without merging**
