### PR TITLE
build: upgrade to go 1.22

### PR DESCRIPTION
**Pull request by subhamkrai**
this commit upgrade to go 1.22 in go mod file and ci related files. Also remove go 1.21 support

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by parth-gr — APPROVED** [review]

**Review by travisn — CHANGES_REQUESTED** [review]
The changes look good. How about if we just wait to merge this until the PR is ready for updating the go modules as well?

**Review by travisn — APPROVED** [review]
Per discussion, go ahead and merge this when ready, with the goal next to get the dependabot PRs merged based on 1.22.

**Comment by BlaineEXE** [comment]
Should we bp this?

**Comment by travisn** [comment]
> Should we bp this to 1.14? Seems like yes?

My thought is to only make the needed go module updates for 1.15 and keep this in master, unless there is a need to backport.

**Pull request merged**
