### PR TITLE
ceph: Fix volume attachment timeouts by allowing configmap updates (fixes #4814)

### LINKED ISSUE #4814: Ceph volume attachment timeout
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When a Pod is created a CephFS volume attachment runs into a timeout. The csi-attacher logs in csi-cephfsplugin-provisioner show:

```
E0205 09:14:05.479583       1 leaderelection.go:341] Failed to update lock: configmaps "external-attacher-leader-rook-ceph-cephfs-csi-ceph-com" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-cephfs-provisioner-sa" cannot update resource "configmaps" in API group "" in the namespace "rook-ceph"
I0205 09:14:05.479627       1 leaderelection.go:222] failed to acquire lease rook-ceph/external-attacher-leader-rook-ceph-cephfs-csi-ceph-com
```

Maybe #3975 is related.

**Expected behavior:**
Volume attachments succeed.

**How to reproduce it (minimal and precise):**

Not sure. Rook Ceph Operator was provisioned with some 1.2.x version and has since been upgraded to the latest version.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS
* Kernel (e.g. `uname -a`): `Linux n0200 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): `v1.2.3`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.6 (f0aa067ac7a02ee46ea48aa26c6e298b5ea272e9) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 1.15.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `kubeadm`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN` (`1 pools have too few placement groups`)

### PR DESCRIPTION
**Pull request by stephan2012**
**Description of your changes:**
Fix for Ceph volume attachment timeouts due to missing permissions.

**Which issue is resolved by this Pull Request:**
Resolves #4814

**Checklist:**

- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

### CODE REVIEW

**Comment by stephan2012** [comment]
> 
> 
> @stephan2012 The change itself looks good to fix the error in #4814.
> These RBAC settings need to also be applied in two other places besides the helm chart:
> 
>     * [common.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml): for non-helm chart deployments
> 
>     * [ceph_manifests.go](https://github.com/rook/rook/blob/master/tests/framework/installer/ceph_manifests.go): the integration tests have separate manifests

Just added.

**Comment by travisn** [comment]
@stephan2012 LGTM, thanks. Could you just squash to a single commit? Also, the commitlint bot is asking for a commit message such as:
```
ceph: <change title>

<sentence or short paragraph describing the fix>
```

**Comment by Madhu-1** [comment]
@stephan2012 @travisnI would like to review this one (not possible today for me)

because leader election should not use configmap it should use leases object.

**Comment by leseb** [comment]
> sorry to say that, this should not be the fix we should do, see [#4814 (comment)](https://github.com/rook/rook/issues/4814#issuecomment-583228691)

If it's not the right fix, should we close? @stephan2012 are you going to work on the "right" fix? Thanks

**Comment by stephan2012** [comment]
> If it's not the right fix, should we close? @stephan2012 are you going to work on the "right" fix? 

Yes, it makes sense to close this PR and leave the issue open. I'll work on the “right fix” but my “processing performance” on this topic may vary.

**Pull request closed without merging**
