### PR TITLE
Add golang 1.10 to supported list, minor updates to dev flow instruct…

### PR DESCRIPTION
**Pull request by jbw976**
…ions

Description of your changes: Add golang 1.10 to supported list, minor updates to dev flow instructions

Checklist:
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by bassam** [comment]
could we upgrade the cross build container to golang 1.10 too?

**Comment by jbw976** [comment]
I'm trying to test the cross container with `build/run make -j4` but the build keeps failing with the below and then getting me into the `Error response from daemon: Bad response from Docker engine` state described in https://github.com/docker/for-mac/issues/1734#issuecomment-366537399.
```
=== docker build build-6a9031da/toolbox-amd64
sha256:6be865e5bee2d0aa742143d7c4d38d31fdfd33385acd16b8b0a63fee0ce0a46d
=== caching image build-6a9031da/toolbox-base-amd64
docker: Error response from daemon: Bad response from Docker engine.
See 'docker run --help'.
ERROR: rsyncd did not come up
```

**Comment by bassam** [comment]
are you running an "edge" version of docker for mac?

**Comment by jbw976** [comment]
I'm on a stable version.  When my docker for mac machine gets in this state, I see hyperkit using 300%+ CPU on my mac.  Connecting to the hyperkit machine is tough because the only way i found to do it is with `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty` and that gives you a small/constrained terminal experience.  I see a lot of memory in use and I see 24% CPU in top by kswapd.  Thinking it's a memory usage causing excessive swapping, I upped the memory to 4GB and I still see this issue.

**Pull request merged**
