### PR TITLE
core: sync ceph fsid on cephcluster status

### PR DESCRIPTION
**Pull request by parth-gr**
FSID will be updated with cephcluster CR status
when monitoring check get start

Signed-off-by: parth-gr <paarora@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
Simple code is beautiful. :) 
Could you just show in a comment what the status looks like in a test cluster now with the fsid?

**Review by leseb — CHANGES_REQUESTED** [review]
I think it's better to do this in `toCustomResourceStatus` and just do:

```go
s.FSID = newStatus.FSID
```

`newStatus` contains the FSID since it comes from `ceph status` so it's better than `clusterInfo` even though it won't change :), I think it just sticks better with how things are being generated.

**Comment by parth-gr** [comment]
> Simple code is beautiful. :) Could you just show in a comment what the status looks like in a test cluster now with the fsid?

```
status:
  ceph:
    capacity: {}
    details:
      MON_CLOCK_SKEW:
        message: clock skew detected on mon.b
        severity: HEALTH_WARN
      TOO_FEW_OSDS:
        message: OSD count 0 < osd_pool_default_size 3
        severity: HEALTH_WARN
    health: HEALTH_WARN
    lastChecked: "2022-03-07T14:40:53Z"
    versions:
      mgr:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 2
      mon:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 3
      overall:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 5
  conditions:
  - lastHeartbeatTime: "2022-03-07T14:39:26Z"
    lastTransitionTime: "2022-03-07T14:39:26Z"
    message: Configuring Ceph Mgr(s)
    reason: ClusterProgressing
    status: "True"
    type: Progressing
  - lastHeartbeatTime: "2022-03-07T14:40:54Z"
    lastTransitionTime: "2022-03-07T06:50:14Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  fsid: 07be65d7-0c80-459a-a273-0fc3bfa8a3a4
  message: Cluster created successfully
  phase: Ready
  state: Created
  version:
    image: quay.io/ceph/ceph:v16.2.7
    version: 16.2.7-0

```

**Review by BlaineEXE — CHANGES_REQUESTED** [review]
IMO, we should not be referencing downstream issues here. We should remove `Closes: https://issues.redhat.com/browse/RHSTOR-2776` from the commit.

**Comment by parth-gr** [comment]
> I think it's better to do this in `toCustomResourceStatus` and just do:
> 
> ```go
> s.FSID = newStatus.FSID
> ```
> 
> `newStatus` contains the FSID since it comes from `ceph status` so it's better than `clusterInfo` even though it won't change :), I think it just sticks better with how things are being generated.

@leseb ceph status doesn't contain `fsid` with it
```bash
sh-4.4$ ceph status
  cluster:
    id:     07be65d7-0c80-459a-a273-0fc3bfa8a3a4
    health: HEALTH_WARN
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 3 daemons, quorum a,b,c (age 49m)
    mgr: b(active, since 21h), standbys: a
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs: 
```

So ig sticking to older way would be suitable, right?

**Comment by travisn** [comment]
> IMO, we should not be referencing downstream issues here. We should remove `Closes: https://issues.redhat.com/browse/RHSTOR-2776` from the commit.

Let's even remove the description of the downstream requirement, and just keep the upstream commit description. Basically, upstream can also benefit by having the fsid to make it simpler to identify the cluster with the fsid in the status.

**Review by leseb — APPROVED** [review]

**Comment by parth-gr** [comment]
@travisn Good to go with this change, I was manually testing with the older cluster deployment, with a fresh cluster deployment is set perfectly.
Thankx!
```
status:
    ceph:
      capacity: {}
      details:
        TOO_FEW_OSDS:
          message: OSD count 0 < osd_pool_default_size 3
          severity: HEALTH_WARN
      fsid: a3383131-e972-40de-aa97-4706795626fe
      health: HEALTH_WARN
      lastChecked: "2022-03-09T16:24:28Z"
      versions:
        mgr:
          ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 2
        mon:
          ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 3
        overall:
          ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 5
    conditions:
    - lastHeartbeatTime: "2022-03-09T16:24:29Z"
      lastTransitionTime: "2022-03-09T16:16:20Z"

```

**Comment by parth-gr** [comment]
> > IMO, we should not be referencing downstream issues here. We should remove `Closes: https://issues.redhat.com/browse/RHSTOR-2776` from the commit.
> 
> Let's even remove the description of the downstream requirement, and just keep the upstream commit description. Basically, upstream can also benefit by having the fsid to make it simpler to identify the cluster with the fsid in the status.

Updated

**Review by travisn — APPROVED** [review]

**Review by BlaineEXE — APPROVED** [review]

**Pull request merged**
