### PR TITLE
Update snapshotter to 2.0.0

### PR DESCRIPTION
**Pull request by c3y1huang**
**Description of your changes:**
Kubernetes CSI snapshotter graduated from alpha to beta from K8s 1.17. This to align the external-snapshotter version to adopt to v1beta1.

Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

[test ceph]

### CODE REVIEW

**Comment by Madhu-1** [comment]
@c3y1huang snapshot is still in the alpha state in ceph-csi  we are working on changing the internal implementation, once it's done we will move it to beta  https://github.com/ceph/ceph-csi/issues/849

**Comment by Madhu-1** [comment]
there is much more needed for moving to beta
* update ceph-csi to new release which supports snapshot beta
* Provide documentation for upgrade
* Documentation on what to do with old snapshots
* Rework snapshot documentation in rook (on how to consume snapshots)

**Comment by c3y1huang** [comment]
rebased.

**Comment by c3y1huang** [comment]
closing this as snapshotter versions are fixed.

**Pull request closed without merging**
