### PR TITLE
ceph: add monitoring rules for octopus

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

Add monitoring rules for octopus clusters.

Closes: https://github.com/rook/rook/issues/5897
Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/rook/rook/issues/5897

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[skip ci]

### CODE REVIEW

**Comment by leseb** [comment]
> > This looks fine.
> > I saw https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mgr/mgr.go#L48 but no reference to it.
> > https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mgr/mgr.go#L357-L359 is where the file is referenced. Shouldn't this new file be added here?
> 
> It's unrelated to this PR and can be a follow-up.

Not sure I understand, are you saying the external rule does not work?

**Comment by travisn** [comment]
@leseb since this merged I'm getting this error locally:
```
=== container build build-a63aad4e/ceph-amd64
cp: ../../cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules-external.yaml: No such file or directory
cp: ../../cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules.yaml: No such file or directory
make[2]: *** [do.build] Error 1
make[1]: *** [ceph.linux_amd64] Error 2
make: *** [build] Error 2
```
must be specific to the mac when the files are copied in the docker build.

**Comment by leseb** [comment]
> @leseb since this merged I'm getting this error locally:
> 
> ```
> === container build build-a63aad4e/ceph-amd64
> cp: ../../cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules-external.yaml: No such file or directory
> cp: ../../cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules.yaml: No such file or directory
> make[2]: *** [do.build] Error 1
> make[1]: *** [ceph.linux_amd64] Error 2
> make: *** [build] Error 2
> ```
> 
> must be specific to the mac when the files are copied in the docker build.

Weird, it built on Linux for sure. I'll look tomorrow if I have time.

**Comment by umangachapagain** [comment]
> > > This looks fine.
> > > I saw https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mgr/mgr.go#L48 but no reference to it.
> > > https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mgr/mgr.go#L357-L359 is where the file is referenced. Shouldn't this new file be added here?
> > 
> > 
> > It's unrelated to this PR and can be a follow-up.
> 
> Not sure I understand, are you saying the external rule does not work?

It won't be automatically deployed when `monitoring:enabled:true` is set.

**Pull request merged**
