### PR TITLE
ceph: bump controller runtime and k8s version(backport-8087)

### PR DESCRIPTION
**Pull request by subhamkrai**
this commit bump controller runtime version
to 0.9 and kubernetes version to v1.21.1.

Signed-off-by: subhamkrai <srai@redhat.com>
(cherry picked from commit 382ca4accaa644a88590d7a1d87fa6bb9d35377f)

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by leseb** [comment]
@travisn @subhamkrai do we really want to backport this? Is it fixing anything?

**Review by leseb — CHANGES_REQUESTED** [review]
@travisn @subhamkrai do we really want to backport this? Is it fixing anything for 1.6?

**Comment by subhamkrai** [comment]
> @travisn @subhamkrai do we really want to backport this? Is it fixing anything for 1.6?

it is not fixing anything right now if I'm not wrong, but if we want the `v1beta1` to `v1` PRs to get in 1.6 then this needs to be in 1.16.

**Comment by leseb** [comment]
> > @travisn @subhamkrai do we really want to backport this? Is it fixing anything for 1.6?
> 
> it is not fixing anything right now if I'm not wrong, but if we want the `v1beta1` to `v1` PRs to get in 1.6 then this needs to be in 1.16.

It's a big chance which could make our lives a bit difficult for subsequent backport downstream. So if we don't need it I'd vote to let it in master instead.

**Comment by subhamkrai** [comment]
> > > @travisn @subhamkrai do we really want to backport this? Is it fixing anything for 1.6?
> > 
> > 
> > it is not fixing anything right now if I'm not wrong, but if we want the `v1beta1` to `v1` PRs to get in 1.6 then this needs to be in 1.16.
> 
> It's a big chance which could make our lives a bit difficult for subsequent backport downstream. So if we don't need it I'd vote to let it in master instead.

okay, let's @travisn confirm, then I'll close this PR.

**Comment by travisn** [comment]
I'd like to backport this so we can also backport the fixes for bumping the resources to v1 from v1beta1 that are raising warnings, such as the csi drivers, PDBs, and jobs. It looks like the v1beta1 csi driver won't even be available anymore in K8s 1.22, which will be releases in the same timeframe as Rook v1.7. We really should get these issues fixed in v1.6 so we don't cut it to close for those updating to the latest K8s. 

Will the merge conflicts really be that much? Most PRs don't update the go.sum, right? Or at least most PRs being backported to v1.6 now would be smaller and less likely to update it.

**Comment by leseb** [comment]
> I'd like to backport this so we can also backport the fixes for bumping the resources to v1 from v1beta1 that are raising warnings, such as the csi drivers, PDBs, and jobs. It looks like the v1beta1 csi driver won't even be available anymore in K8s 1.22, which will be releases in the same timeframe as Rook v1.7. We really should get these issues fixed in v1.6 so we don't cut it to close for those updating to the latest K8s.
> 
> Will the merge conflicts really be that much? Most PRs don't update the go.sum, right? Or at least most PRs being backported to v1.6 now would be smaller and less likely to update it.

I was just worried about downstream but it looks like this is needed in 1.6 so problem solved 🙂

**Review by leseb — APPROVED** [review]

**Review by travisn — CHANGES_REQUESTED** [review]
Holding until the v1.6.5 release is out, just to give it more bake time first

**Review by travisn — APPROVED** [review]

**Pull request merged**
