### PR TITLE
Bump csi resizer and volume replication images

### PR DESCRIPTION
**Pull request by sathieu**
**Description of your changes:**

| Package | Update | Change |
|---|---|---|
| k8s.gcr.io/sig-storage/csi-resizer | minor | `v1.3.0` -> `v1.4.0` |
| quay.io/csiaddons/volumereplication-operator | minor | `v0.1.0` -> `v0.3.0` |

Detailed changelogs:

- https://github.com/kubernetes-csi/external-resizer/blob/release-1.4/CHANGELOG/CHANGELOG-1.4.md
- https://github.com/csi-addons/volume-replication-operator/tree/v0.2.0
- https://github.com/csi-addons/volume-replication-operator/tree/v0.3.0

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by leseb — CHANGES_REQUESTED** [review]
The commit message is empty

**Comment by sathieu** [comment]
@leseb What do you want in the commit body that is not in the commit subject?

**Comment by leseb** [comment]
> @leseb What do you want in the commit body that is not in the commit subject?

Everything that is in the PR description.

**Comment by sathieu** [comment]
@leseb Commit message updated. Please review again :pray:.

**Review by leseb — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
