### PR TITLE
Suggest dataDirHostPath value for minikube

### PR DESCRIPTION
**Pull request by kokhang**
Fixes https://github.com/rook/rook/issues/1192
[skip ci]

### CODE REVIEW

**Comment by kokhang** [comment]
@galexrt there is no `minikube clean`. If you are referring to the `minikube.sh clean`, this will call `minikube delete` which will delete the content. For more information: https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md#persistent-volumes

**Comment by kokhang** [comment]
@travisn i dont think we should put a hack just so that it works with minikube. That would be even more confusing for the users and the developers when they see the code.

I think this proposed method is much more clear to the user what is happening. And this is why minikube has added these directories to be used as persisted. https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md#persistent-volumes

**Comment by travisn** [comment]
@kokhang my point is that adding a comment to the yaml will not be noticed by most users. The minikube users will still have a problem by default. How can we make it work for minikube by default in the example yaml? 

The philosophy we have been following is:
- Docs should show examples for settings for production environments
- Examples in the `cluster/examples/kubernetes` folder should work by default in a single-node or minikube environment so that they work smoothly for anyone trying them out.

I am leaning towards us changing the example to have a blank dataDirHostPath with a big comment that says you should set it, but leave it set in the docs. But if there is a better solution to have it work by default, I'm all ears.

**Comment by kokhang** [comment]
@travisn from the meeting we had, it was decided to have a comment on the yaml. Lets revisit this fix again.

**Comment by jbw976** [comment]
@kokhang, we also discussed adding a note in the documentation flow somewhere reasonable/helpful/easy to find.  Can you please add that?

**Pull request merged**
