### PR TITLE
ci: change `yq` path to /usr/local/bin/yq

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

So it will override any existing installation.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by leseb** [comment]
Without this, the CI is currently broken for all the canaries using `yq`.

**Review by subhamkrai — APPROVED** [review]
Example run where it is failing?

**Comment by subhamkrai** [comment]
> Example run where it is failing?
Ohh...so it was failing to build.

**Comment by leseb** [comment]
> Example run where it is failing?

https://github.com/rook/rook/pull/8351/checks?check_run_id=3123555248

With:

```bash
+ yq w -i -d1 cluster-test.yaml spec.dashboard.enabled false
Error: unknown command "w" for "yq"
Run 'yq --help' for usage.
```

The problem is that somehow Ubuntu got upgraded and has `/usr/local/bin/yq` version 4.
See:

```
runner@fv-az120-208:~/work/rook/rook$ yq -V
yq (https://github.com/mikefarah/yq/) version 4.11.0
runner@fv-az120-208:~/work/rook/rook$ /usr/bin/yq -V
yq version 3.4.1
runner@fv-az120-208:~/work/rook/rook$ which yq
/usr/local/bin/yq
```

**Comment by subhamkrai** [comment]
> > Example run where it is failing?
> 
> https://github.com/rook/rook/pull/8351/checks?check_run_id=3123555248
> 
> With:
> 
> ```shell
> + yq w -i -d1 cluster-test.yaml spec.dashboard.enabled false
> Error: unknown command "w" for "yq"
> Run 'yq --help' for usage.
> ```
> 
> The problem is that somehow Ubuntu got upgraded and has `/usr/local/bin/yq` version 4.
> See:
> 
> ```shell
> runner@fv-az120-208:~/work/rook/rook$ yq -V
> yq (https://github.com/mikefarah/yq/) version 4.11.0
> runner@fv-az120-208:~/work/rook/rook$ /usr/bin/yq -V
> yq version 3.4.1
> runner@fv-az120-208:~/work/rook/rook$ which yq
> /usr/local/bin/yq
> ```

Got it, thanks

**Review by travisn — APPROVED** [review]

**Pull request merged**
