### PR TITLE
core: update rbac for rook-ceph-system role

### LINKED ISSUE #12002: failed to reconcile CephCluster: cannot deletecollection resource
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```
ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph osds: failed to reconcile key rotation cron jobs: failed to delete key rotation cron jobs: cronjobs.batch is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot deletecollection resource "cronjobs" in API group "batch" in the namespace "rook-ceph"
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

Looks like the `deletecollection` is missing from https://github.com/rook/rook/blob/305aae552b9149f47222601468de100094d103a5/deploy/examples/common.yaml#L902-L907.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

### PR DESCRIPTION
**Pull request by sp98**
add deletecollection action for cronjobs resource

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #12002

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
LGTM, but would be great to verify repro steps to confirm the issue is fixed now.

**Comment by sp98** [comment]
> LGTM, but would be great to verify repro steps to confirm the issue is fixed now.

Sure. I'll test this out.

**Review by Rakshith-R — CHANGES_REQUESTED** [review]
This is not required
Please see comment here https://github.com/rook/rook/issues/12002#issuecomment-1491386663

**Comment by uhthomas** [comment]
> This is not required Please see comment here [#12002 (comment)](https://github.com/rook/rook/issues/12002#issuecomment-1491386663)

Just to close the loop, this is not true. The error message `User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot deletecollection resource` states the service account `rook-ceph-system`, which is associated with the role `rook-ceph-system` does not have the appropriate permission. The cluster role has nothing to do with this.

**Pull request closed without merging**
