### PR TITLE
ceph: add phase to cephfilesystems crd

### PR DESCRIPTION
**Pull request by jshen28**
add a Phase to columns that should be printed

Signed-off-by: shenjiatong <yshxxsjt715@gmail.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@jshen28 now we auto-generate our crds(crds.yaml and resouces.yaml using `make crds`)

**Comment by jshen28** [comment]
@subhamkrai ah, thank you for telling me. so what should I do if I want to add a property? can you share me a link? thank you.

**Comment by leseb** [comment]
> @subhamkrai ah, thank you for telling me. so what should I do if I want to add a property? can you share me a link? thank you.

You need to add a marker in the `pkg/apis/ceph.rook.io/v1/types.go`, see https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L887

**Review by subhamkrai — CHANGES_REQUESTED** [review]
please run `make crds` to apply changes to crds

**Comment by subhamkrai** [comment]
> @jshen28 please run `make crds` to apply these changes to crds

whenever we do changes in `**/types.go` file we run `make crds`(and after running `make crds` we add `resources.yaml` and `crds.yaml` which will be auto-generated) to apply the changes.

**Comment by jshen28** [comment]
@subhamkrai thank you, I will do that.

**Comment by leseb** [comment]
Run `make cvs-clean && make crds` locally and resubmit.

**Comment by jshen28** [comment]
sorry, but I cannot find target `cvs-clean`...

**Comment by leseb** [comment]
> sorry, but I cannot find target `cvs-clean`...

`csv-clean`

**Comment by BlaineEXE** [comment]
@jshen28 is it your intent that this be included in v1.6.z?

**Comment by jshen28** [comment]
@BlaineEXE I think it is good to have this, but I still need to figure out how to use `make crds`...

**Comment by leseb** [comment]
@jshen28 please rebase.

**Review by leseb — APPROVED** [review]

**Pull request merged**
