### PR TITLE
ceph: lift minimum supported version of ceph csi to v3.3.0

### PR DESCRIPTION
**Pull request by humblec**
With the release of Ceph CSI 3.4.0, Ceph CSI project came up
    with a new support policy where we support only versions >= 3.3.0
    
    The supported window of Ceph CSI versions is known as "N.(x-1)":
     (N (Latest major release) . (x (Latest minor release) - 1)).
    
    For example, if Ceph CSI latest major version is 3.4.0 today,
    support is provided for the versions above 3.3.0.
    If users are running an unsupported Ceph CSI version, they will be
    asked to upgrade when requesting support for the cluster.
    
    This PR lift the minimum supported version of Ceph CSI to 3.3.0
    in this repo.
    
    Fix https://github.com/rook/rook/issues/8709
    
    Ref #
    https://github.com/ceph/ceph-csi/releases/tag/v3.4.0
    https://github.com/ceph/ceph-csi/#known-to-work-co-platforms
    
    Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
    (cherry picked from commit 731b0f5274759eeb9ba5b513533900b440f48ab5)

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by leseb — CHANGES_REQUESTED** [review]
Please use `cherry-pick -x`

**Comment by humblec** [comment]
> Please use `cherry-pick -x`

sure, done. ptal @leseb

**Review by leseb — APPROVED** [review]

**Comment by travisn** [comment]
@humblec The build is failing with:
```
=== go vet
diff -u pkg/operator/ceph/csi/spec.go.orig pkg/operator/ceph/csi/spec.go
--- pkg/operator/ceph/csi/spec.go.orig	2021-09-23 07:47:07.000000000 +0000
+++ pkg/operator/ceph/csi/spec.go	2021-09-23 07:47:07.000000000 +0000
@@ -312,7 +312,7 @@
 	if err != nil {
 		return errors.Wrap(err, "failed to load CSI_PROVISIONER_PRIORITY_CLASSNAME setting")
 	}
-	
+
 	enableOMAPGenerator, err := k8sutil.GetOperatorSetting(clientset, controllerutil.OperatorSettingConfigMapName, "CSI_ENABLE_OMAP_GENERATOR", "false")
 	if err != nil {
 		return errors.Wrap(err, "failed to load CSI_ENABLE_OMAP_GENERATOR setting")
```

**Review by travisn — CHANGES_REQUESTED** [review]
See the CI

**Comment by humblec** [comment]
@travisn should be good to go. thanks !

**Comment by humblec** [comment]
@travisn multi cluster mirroring failure looks to be outside of this PR scope..  

```

Run timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
+ timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
Defaulted container "fs-mirror" out of: fs-mirror, chown-container-data-dir (init)
waiting for connection to peer
```

**Review by travisn — APPROVED** [review]

**Pull request merged**
