### PR TITLE
object: remove region option from OBC StorageClass

### PR DESCRIPTION
**Pull request by thotz**
**Description of your changes:**
The AWS go lang SDK needs value for the region, it is set differently in
various parts of the current code. With PR the value is always `us-east-1` so
that it will work RGW server without any issues.

This reverts commit 280c29f330e03a08d23c1fda1f1b26574c1b9bdb.

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
LGTM, nice to see we can simplify and remove the region. I'll wait for blaine to approve.

**Comment by BlaineEXE** [comment]
This looks good but doesn't track that this reverts 280c29f330e03a08d23c1fda1f1b26574c1b9bdb.

Please add (precisely) `This reverts commit 280c29f330e03a08d23c1fda1f1b26574c1b9bdb.` above the signed-off-by line of the commit body.

**Review by leseb — COMMENTED** [review]
Can you first revert https://github.com/rook/rook/commit/280c29f330e03a08d23c1fda1f1b26574c1b9bdb in a commit and then put the changes needed in another commit? Just for clarity.

**Comment by thotz** [comment]
> Can you first revert [280c29f](https://github.com/rook/rook/commit/280c29f330e03a08d23c1fda1f1b26574c1b9bdb) in a commit and then put the changes needed in another commit? Just for clarity.

@leseb : It was not simple revert of [280c29f](https://github.com/rook/rook/commit/280c29f330e03a08d23c1fda1f1b26574c1b9bdb), I will end up having most of the code changes of this commit to reverting as well, since bucket notification changes are added later. Then second commit mostly have documentation related changes

**Comment by leseb** [comment]
> > Can you first revert [280c29f](https://github.com/rook/rook/commit/280c29f330e03a08d23c1fda1f1b26574c1b9bdb) in a commit and then put the changes needed in another commit? Just for clarity.
> 
> @leseb : It was not simple revert of [280c29f](https://github.com/rook/rook/commit/280c29f330e03a08d23c1fda1f1b26574c1b9bdb), I will end up having most of the code changes of this commit to reverting as well, since bucket notification changes are added later. Then second commit mostly have documentation related changes

Ok thanks for the clarification.

**Review by leseb — COMMENTED** [review]
LGTM. Are we planning to backport this? If not, I'd add a note to the release note about this removal and that the region is not configurable anymore.

**Comment by BlaineEXE** [comment]
> LGTM. Are we planning to backport this? If not, I'd add a note to the release note about this removal and that the region is not configurable anymore.

I think we should backport to v1.8 for sure.

**Comment by BlaineEXE** [comment]
> This looks good but doesn't track that this reverts [280c29f](https://github.com/rook/rook/commit/280c29f330e03a08d23c1fda1f1b26574c1b9bdb).
> 
> Please add (precisely) `This reverts commit 280c29f330e03a08d23c1fda1f1b26574c1b9bdb.` above the signed-off-by line of the commit body.

Also @thotz the commit message does not contain **precisely** the text I requested before (quoted above). The text you added only contains the short hash, and there is no period. Please also remove `as well` from the next line.

**Comment by thotz** [comment]
> This reverts commit 280c29f330e03a08d23c1fda1f1b26574c1b9bdb

I have added in my commit message and PR, but git shortens above has value

**Review by BlaineEXE — APPROVED** [review]

**Comment by BlaineEXE** [comment]
I updated the title to better reflect changes from the user perspective as it will show up in the changes when the next 1.8 update is released.

**Pull request merged**
