### PR TITLE
Assigned Phase variable with State variable

### LINKED ISSUE #3859: Rename ClusterStatus.State to ClusterStatus.Phase in CephCluster CRD
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Change the CephCluster CRD status spec from ClusterStatus.State to ClusterStatus.Phase. This does not bring in new functionality but helps to integrate CephCluster Status into OLM user Interface.

**What is use case behind this feature:**
Currently, CephCluster stores system state in .Status.State spec. However, OLM expects it to be at .Status.Phase (it is very opioniated). So, by renaming `state` to `phase`, we get the best of both worlds. This makes experience much smoother to the OLM users without any impact on others.

**Environment**:

Kubernetes/Openshift with OLM deployed.

### PR DESCRIPTION
**Pull request by nizamial09**
**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #3859 

**Checklist:**

- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

### CODE REVIEW

**Comment by nizamial09** [comment]
> What is the context for this change? Why should we copy the `state` to the `phase`?

Currently, CephCluster stores system state in .Status.State spec. However, OLM expects it to be at .Status.Phase (it is very opioniated). So, by renaming state to phase, we get the best of both worlds. This makes experience much smoother to the OLM users without any impact on others.

**Comment by nizamial09** [comment]
@umangachapagain Please take a look at this and kindly verify it.

**Comment by travisn** [comment]
Per comments in #3859 I'm not seeing that we should make this change.

**Comment by travisn** [comment]
@nizamial09 If this is still needed let's re-open and discuss, thanks

**Pull request closed without merging**
