### PR TITLE
Making script backward compatible with python2

### PR DESCRIPTION
**Pull request by aruniiird**
Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>

**Description of your changes:**
As `exec` is an internal builtin function for python2 there were some errors thrown while running the script with python2.
Changed the variable name to `execErr`.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by leseb — CHANGES_REQUESTED** [review]
Please change the commit title and add a commit message. Otherwise LGTM

**Review by leseb — APPROVED** [review]

**Review by travisn — CHANGES_REQUESTED** [review]
Looks like the external cluster test script is failing:

```
+ timeout 10 sh -c 'until kubectl -n rook-ceph exec rook-ceph-tools-78cdfd976c-g84kv -- python3 /etc/ceph/create-external-cluster-resources.py --rbd-data-pool-name replicapool; do echo '\''waiting for script to succeed'\'' && sleep 1; done'
</html>Execution Failed: unable to connect to endpoint: 172.17.0.8:9283
Traceback (most recent call last):
  File "/etc/ceph/create-external-cluster-resources.py", line 907, in <module>
    raise err
  File "/etc/ceph/create-external-cluster-resources.py", line 904, in <module>
    rjObj.main()
  File "/etc/ceph/create-external-cluster-resources.py", line 885, in main
    generated_output = self.gen_json_out()
  File "/etc/ceph/create-external-cluster-resources.py", line 691, in gen_json_out
    self._gen_output_map()
  File "/etc/ceph/create-external-cluster-resources.py", line 672, in _gen_output_map
    self.out_map['MONITORING_ENDPOINT_PORT'] = self.get_active_and_standby_mgrs()
  File "/etc/ceph/create-external-cluster-resources.py", line 422, in get_active_and_standby_mgrs
    self.endpoint_dial(monitoring_endpoint)
  File "/etc/ceph/create-external-cluster-resources.py", line 267, in endpoint_dial
    "unable to connect to endpoint: {}".format(endpoint_str))
```

**Comment by aruniiird** [comment]
Can we do a retest? I highly doubt this failure has anything to do with current change...

**Review by travisn — APPROVED** [review]
Rerunning the CI did not repro the error, and the error was also seen in a [separate run](https://github.com/red-hat-storage/rook/pull/17/checks?check_run_id=3475674224) from this PR, so it is unrelated.

**Pull request merged**
