### PR TITLE
test: add xtrace logging to github actions

### PR DESCRIPTION
**Pull request by BlaineEXE**
For all Rook-maintained GH actions, use a default shell that has xtrace
enabled to help debug any errors.

Enable xtrace on all actions except these that use only external tools:
- codespell
- commitlint (wagoid/commitlint)
- golangci-lint
- helm-lint (chart-testing)
- stale
- yamllint

Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Help debug https://github.com/rook/rook/issues/8126

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by travisn — APPROVED** [review]
This would likely be useful across other tests as well

**Review by subhamkrai — APPROVED** [review]

**Review by leseb — APPROVED** [review]
@BlaineEXE Do you want to debug over that PR and eventually remove the `set -x`?

**Comment by BlaineEXE** [comment]
> Do you want to debug over that PR and eventually remove the `set -x`?

> This would likely be useful across other tests as well

In response to both comments, I think i am more inclined to share Travis' thought that using `set -x` before our GH action scripts might be a good thing to do generally.

**Comment by BlaineEXE** [comment]
Finally saw a repro of the issue with xtrace here. It could be related to this Ceph bug: https://tracker.ceph.com/issues/44612

```
++ kubectl get pod -l app=rook-ceph-tools -n rook-ceph -o 'jsonpath={.items[0].metadata.name}'
+ toolbox=rook-ceph-tools-78cdfd976c-7cwq4
++ kubectl -n rook-ceph exec rook-ceph-tools-78cdfd976c-7cwq4 -- ceph mgr dump -f json
++ jq --raw-output .active_addr
+ mgr_raw='(unrecognized address family 0)/0'
+ timeout 60 sh -c 'until kubectl -n rook-ceph exec rook-ceph-tools-78cdfd976c-7cwq4 -- curl --silent --show-error (unrecognized address family 0)/0:9283; do echo '\''waiting for mgr prometheus exporter to be ready'\'' && sleep 1; done'
sh: 1: Syntax error: "(" unexpected (expecting "do")
Error: Process completed with exit code 2.
```

**Comment by leseb** [comment]
> Finally saw a repro of the issue with xtrace here. It could be related to this Ceph bug: https://tracker.ceph.com/issues/44612
> 
> ```
> ++ kubectl get pod -l app=rook-ceph-tools -n rook-ceph -o 'jsonpath={.items[0].metadata.name}'
> + toolbox=rook-ceph-tools-78cdfd976c-7cwq4
> ++ kubectl -n rook-ceph exec rook-ceph-tools-78cdfd976c-7cwq4 -- ceph mgr dump -f json
> ++ jq --raw-output .active_addr
> + mgr_raw='(unrecognized address family 0)/0'
> + timeout 60 sh -c 'until kubectl -n rook-ceph exec rook-ceph-tools-78cdfd976c-7cwq4 -- curl --silent --show-error (unrecognized address family 0)/0:9283; do echo '\''waiting for mgr prometheus exporter to be ready'\'' && sleep 1; done'
> sh: 1: Syntax error: "(" unexpected (expecting "do")
> Error: Process completed with exit code 2.
> ```

It seems that we can work around it.

**Comment by travisn** [comment]
LGTM!

**Pull request merged**
