### PR TITLE
mon: fix bind addr when IPv6 and msgr2 are enabled

### PR DESCRIPTION
**Pull request by BlaineEXE**
When IPv6-only network mode is enabled and when mons are configured to listen only on msgrV2 port, Rook has to add the port to the mon --public-bind-addr in order to force mons to stop listening on the msgrV1 port. This can cause problems for IPv6 clusters where adding ':<port>' to the end of an IP addr looks like a valid IPv6 address.

In IPv6 mode, Rook needs to set this to `[<ip>]:<port>` with the brackets to be a non-ambiguous IPv6 address.

In IPv4 mode, Rook needs to keep its existing behavior. IPv4 mode should also continue to be the defualt assumption if the network config isn't specified.

If `dualStack: true` is specified, Rook is informed that the environment is dual stack, but Rook doesn't know which IP family to expect from the pod IP. In this scenario, it is safest for Rook not to apply the port, since assuming either IPv4 or IPv6 format could be incorrect. In this scenario, mons may still listen on msgrV1 ports, but this is preferable to an environment where mons perpetually crash.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
LGTM, I'll just wait to approve after it's confirmed tested in an ipv6 env.

**Comment by matthewpi** [comment]
I've tested this fix and it seems to work on my IPv6 cluster, however I was running my fix from #14255 first, so I'm not sure if the deployments have been properly reconciled.

**Comment by BlaineEXE** [comment]
I think we can check something simple to make sure the fix is applied. Could you list the labels on any of your mon **deployments**? There should be a `rook-version=` label. And, show the output of running `kubectl -n rook-ceph exec deploy/rook-ceph-operator -- rook version` (which should show the Rook operator version number). As long as those match, we should be confident that the fix from this PR was applied and works.

**Comment by matthewpi** [comment]
> version

```bash
$ kubectl get deployment -n rook-ceph rook-ceph-mon-a --output='go-template' --template '{{ index .metadata.labels "rook-version" }}'
v1.14.0-alpha.0.138.g573a47e73

$ kubectl -n rook-ceph exec deploy/rook-ceph-operator -- rook version
2024/05/22 22:52:02 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
rook: v1.14.0-alpha.0.138.g573a47e73
go: go1.22.2
```

It works.  It has the short-commit id from this PR.

**Comment by BlaineEXE** [comment]
Great! I think this is ready to merge then.

**Review by sp98 — APPROVED** [review]

**Pull request merged**
