### PR TITLE
Correct indentation level for pool rules

### LINKED ISSUE #10653: prometheus-ceph-rules definition invalid in deploy/examples/localrules.yaml
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
PrometheusRule examples in localrules.yaml are not valid, with an incorrect indentation level starting at line 749 and continuing through 759.
https://github.com/rook/rook/blob/master/deploy/examples/monitoring/localrules.yaml#L749,L759

**Expected behavior:**
YAML files are valid and and indentation is consistent across an array.

**How to reproduce it (minimal and precise):**
Try to deploy the PrometheusRules from deploy/examples/monitoring/localrules.yaml

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
N/A
* Operator's logs, if necessary
N/A
* Crashing pod(s) logs, if necessary
N/A

**Environment**:
N/A

**NOTE**:
I have no idea if any other PrometheusRules are also indented wrongly. The helm chart updated in the [same PR](https://github.com/rook/rook/pull/10626) doesn't appear to have wrong indentation, but I'm not deploying this way so have no error to report.

### PR DESCRIPTION
**Pull request by solacelost**
**Description of your changes:**
Aligns the indentation of the rule definition for the pool rules array uniformly.

**Which issue is resolved by this Pull Request:**
Resolves #10653

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by solacelost** [comment]
Also - could this be backported into release-1.9 as the PR that introduced this issue was? That's what's holding up my deployments right now. :)

**Review by travisn — COMMENTED** [review]
This looks correct to me. Were you getting an error during install?
@anthonyeleven PTAL

**Comment by anthonyeleven** [comment]
> This looks correct to me. Were you getting an error during install? @anthonyeleven PTAL

I was getting all manner of grief from the linter.  I defer to you.

**Comment by solacelost** [comment]
> This looks correct to me. Were you getting an error during install? @anthonyeleven PTAL

Yes. YAML errors, complaining about the unexpected indentation of the array member. I point an Ansible `kubernetes.core.k8s` at the raw manifests on the branch in `apply` mode, and it parses the YAML down to a python object before applying it at the API as JSON - so the errors I was getting were for `pyyaml` as a dependency of the `kubernetes` python library.

> I was getting all manner of grief from the linter. I defer to you.

Do you mean in this version or pre-PR? The only grief I get on the file as it is after this PR are line-length and document-start.

**Comment by anthonyeleven** [comment]
yes, do what's right

**Review by travisn — APPROVED** [review]

**Pull request merged**
