### PR TITLE
doc: fix broken links

### PR DESCRIPTION
**Pull request by karthik-us**
Fixing the broken links in the docs.

### CODE REVIEW

**Review by subhamkrai — CHANGES_REQUESTED** [review]
please run `make docs-build` locally

**Review by subhamkrai — APPROVED** [review]

**Comment by travisn** [comment]
@karthik-us @subhamkrai Actually we need to revert this change. This readme is intended to be rendered from the [website docs](https://rook.github.io/docs/rook/latest/Getting-Started/intro/). These links were working fine from that site. Did they appear broken from the unrendered page [here](https://github.com/rook/rook/blob/master/Documentation/README.md)? That's not the intended source for users to see the docs, so unfortunately it will remain broken there. But for the rendered docs, we don't want these links to point back to the github URL.

**Comment by travisn** [comment]
> Thanks for the clarification @travisn. That makes sense. Reverted it here: #13840.

Thanks for the concern about the broken links, this README is just "special".

**Comment by karthik-us** [comment]
> > Thanks for the clarification @travisn. That makes sense. Reverted it here: #13840.
> 
> Thanks for the concern about the broken links, this README is just "special".

Actually this can be fixed and we can keep it happy at both the places.
Attempted to fix it here with a different approach: https://github.com/rook/rook/pull/13845
(Am okay if are are not willing to take this in. Just wanted to know whether it is fixable or not)

**Pull request merged**
