### PR TITLE
ceph: use Nautilus for operator image

### PR DESCRIPTION
**Pull request by BlaineEXE**
Now that Nautilus is available, use it as the base for the operator
image.

Signed-off-by: Blaine Gardner <blaine.gardner@suse.com>

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by BlaineEXE** [comment]
Evidently it isn't :]

**Comment by dimm0** [comment]
Could you guys update the toolbox image too please?

**Comment by travisn** [comment]
@dimm0 actually the toolbox uses the same image as the operator now, I believe since 0.9.

**Comment by dimm0** [comment]
Ah, great

**Pull request closed without merging**
