### PR TITLE
[MASTER] Bugfix RBAC second cluster

### PR DESCRIPTION
**Pull request by smasset-orange**
**Description of your changes:**
Added missing RoleBindings in examples or deploying CephClusters in multiple namespaces.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
Could you squash the commits into one and make sure the subjects aren't more than 40 chars long

**Comment by travisn** [comment]
The fix looks good for the non-helm case. Just note that you might consider installing with the helm chart since this RBAC should all be created for you with the chart.

**Comment by smasset-orange** [comment]
@BlaineEXE @travisn, thanks for the quick review.

Just pushed following changes:
- added extra rook-ceph-rgw-psp (missed it as I was testing this with 1.7 and 1.8 branches)
- squashed commits
- shortened the commit message

I have similar branches for 1.9 and 1.8, I'll open the PRs when this one is lgtm'ed. Struggling a bit more with 1.7 but I'm not sure if you are still accepting PRs for 1.7.

**Comment by travisn** [comment]
> I have similar branches for 1.9 and 1.8, I'll open the PRs when this one is lgtm'ed. Struggling a bit more with 1.7 but I'm not sure if you are still accepting PRs for 1.7.

This change in the examples yaml isn't used commonly, so it's a low enough risk to backport. We can backport back to the 1.7 branch, though we aren't planning another patch release from that branch. I've added the backport labels so a bot will open those backport PRs after it's merged here. If you could just confirm when you're done testing the changes, I think we'll be ready to merge.

**Comment by smasset-orange** [comment]
I'm done with my changes although I do have some doubts about the presence of a `ClusterRoleBinding` for `rook-ceph-osd-external` instead of a `RoleBinding` since this file is otherwise namespace bound (but this can be handled in a separate PR).

Regarding automatic backports, it should be fine for 1.9 but for 1.8, please have a look at [bugfix/rbac-second-cluster-1.8](https://github.com/smasset-orange/rook/commits/bugfix/rbac-second-cluster-1.8) (and more specifically smasset-orange/rook@9a04688b2431d0694bbc7d1c3df09efb81c29004) where I had to backport and adapt earlier changes before implementing the same set of changes brought by this PR.

**Comment by travisn** [comment]
> I'm done with my changes although I do have some doubts about the presence of a `ClusterRoleBinding` for `rook-ceph-osd-external` instead of a `RoleBinding` since this file is otherwise namespace bound (but this can be handled in a separate PR).

The `rook-ceph-osd-external` is a ClusterRoleBinding because it is for a cluster resource `nodes`, so it's expected.

> Regarding automatic backports, it should be fine for 1.9 but for 1.8, please have a look at [bugfix/rbac-second-cluster-1.8](https://github.com/smasset-orange/rook/commits/bugfix/rbac-second-cluster-1.8) (and more specifically [smasset-orange/rook@9a04688](https://github.com/smasset-orange/rook/commit/9a04688b2431d0694bbc7d1c3df09efb81c29004)) where I had to backport and adapt earlier changes before implementing the same set of changes brought by this PR.

We could just see what merge conflicts exist when the bot opens the backports and then either fix them, or open separate PRs. I'm not clear what you're saying with these commits though.

**Comment by smasset-orange** [comment]
@travisn, @BlaineEXE should I rebase against latest master branch before merging this PR ?

**Comment by travisn** [comment]
> @travisn, @BlaineEXE should I rebase against latest master branch before merging this PR ?

Oh, missed merging this a while back. Yes, please go ahead and rebase and we'll get it merged, thanks!

**Review by BlaineEXE — APPROVED** [review]

**Pull request merged**
