### PR TITLE
doc: fix links in the bug report template

### PR DESCRIPTION
**Pull request by parth-gr**
Signed-off-by: parth-gr <paarora@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by parth-gr** [comment]
@galexrt looks like instead `latest-release` , `latest` work fine.
https://github.com/rook/rook/pull/10768#discussion_r953055248

**Comment by galexrt** [comment]
> @galexrt looks like instead `latest-release` , `latest` work fine. [#10768 (comment)](https://github.com/rook/rook/pull/10768#discussion_r953055248)

Yes, both work, but `latest` redirects to the **latest master** and `latest-release` to the **latest release** docs.

**Review by travisn — CHANGES_REQUESTED** [review]
The backports for #10768 have been merged now, we should be able to close this PR after we confirm the working links after the docs are published in the next 15 minutes.

**Comment by parth-gr** [comment]
> > @galexrt looks like instead `latest-release` , `latest` work fine. [#10768 (comment)](https://github.com/rook/rook/pull/10768#discussion_r953055248)
> 
> Yes, both work, but `latest` redirects to the **latest master** and `latest-release` to the **latest release** docs.
> 
> Because the other doc PRs haven't been backported to make these doc pages also exist in the latest release docs, the links currently 404, so we either backport the other docs PR or make it point to latest master docs for now.

Okay got it

**Pull request closed without merging**
