### PR TITLE
buid: use go-work for mutli-module workspace

### PR DESCRIPTION
**Pull request by subhamkrai**
using go-work which is available from go 1.18,
helps is get rid of `replace()` from go.mod file.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
I'll be looking this PR once #13436 is merged

**Comment by subhamkrai** [comment]
@travisn I think let's hold this PR given the issue with downstream?

**Comment by travisn** [comment]
> @travisn I think let's hold this PR given the issue with downstream?

Sounds good to hold for now until it is clear what is needed.

**Comment by travisn** [comment]
Let's close this for now, not clear if needed

**Pull request closed without merging**
