### PR TITLE
Removing the paranthesis to execute in the shell

### PR DESCRIPTION
**Pull request by MG40**
**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by MG40** [comment]
the $(arg) replaced with $arg

**Review by galexrt — APPROVED** [review]

**Review by leseb — CHANGES_REQUESTED** [review]
https://rook.io/docs/rook/master/development-flow.html#commit-structure

**Comment by galexrt** [comment]
@MG40 Please update your commit message as shown here: https://github.com/rook/rook/blob/master/CONTRIBUTING.md#commit-messages

**Review by galexrt — CHANGES_REQUESTED** [review]
Just noticed that the document contains other cases of paranthesis around the variables below, e.g., line 158-159 and others.

**Review by galexrt — CHANGES_REQUESTED** [review]
Line 84-85 to 92 also contain parathesis that should be removed.

**Review by MG40 — COMMENTED** [review]
ceph: disaster recovery documentation

removing the parenthesis for ceph-mon arguments.


arguments in the command: $(ROOK_CEPH_MON_HOST), $(ROOK_CEPH_MON_INITIAL_MEMBERS), $(ROOK_POD_IP)

the values of the arguments to be passed without the parenthesis

**Comment by MG40** [comment]
ceph: disaster recovery documentation

removing the parenthesis for ceph-mon arguments.

arguments in the command: $(ROOK_CEPH_MON_HOST), $(ROOK_CEPH_MON_INITIAL_MEMBERS), $(ROOK_POD_IP)

What should be: $ROOK_CEPH_MON_HOST, $ROOK_CEPH_MON_INITIAL_MEMBERS, $ROOK_POD_IP


the values of the arguments to be passed without the parenthesis

**Comment by MG40** [comment]
ceph: disaster recovery documentation

removing the parenthesis for ceph-mon arguments.

arguments in the command: $(ROOK_CEPH_MON_HOST), $(ROOK_CEPH_MON_INITIAL_MEMBERS), $(ROOK_POD_IP)

the values of the arguments to be passed without the parenthesis
arguments in the command: $ROOK_CEPH_MON_HOST, $ROOK_CEPH_MON_INITIAL_MEMBERS, $ROOK_POD_IP

**Comment by galexrt** [comment]
Closing in favor of #6447.

**Pull request closed without merging**
