### PR TITLE
added git clone

### PR DESCRIPTION
**Pull request by alexcpn**
**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [x] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

[skip ci]

### CODE REVIEW

**Comment by BlaineEXE** [comment]
It seems to me that it doesn't hurt to add `git clone ...` to all the quickstart guides.

**Comment by travisn** [comment]
@alexcpn Would you mind updating other quickstart guides with this as well? Thanks!

**Comment by alexcpn** [comment]
> @alexcpn Would you mind updating other quickstart guides with this as well? Thanks!

Done

**Comment by alexcpn** [comment]
tried to change the DCO for previous commits and became a mess. Will repoen a new one

**Pull request closed without merging**
