### PR TITLE
Use go modules for dependency management

### PR DESCRIPTION
**Pull request by galexrt**
**Description of your changes:**

This PR will switch to use `go mod` for the dependency management.

Draft status as I need to make sure it works as intended for our setup with Jenkins, crossbuild and so on.

Note: This would drop support for Golang `<1.13`

**Checklist:**

- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

### CODE REVIEW

**Comment by galexrt** [comment]
To note, I can't continue till we update the Golang version in the CI to at least 1.12 or higher.

**Comment by galexrt** [comment]
Thanks to Adam Kraitman for updating the Jenkins and build images!

I have looked into updating the PR but failed as I'm seeing some issues with "go modding" some `k8s.io` pkgs. I'll look into that when I'm back home with a reliable internet connection to get this issue resolved.

**Comment by galexrt** [comment]
I still need to find a way to have the `build/codegen/codegen.sh` script working with `go mod` as there is no `vendor/` dir anymore (by default).

Besides that if the CI is green, this should be good to go after the `codegen.sh` script is fixed.

**Comment by leseb** [comment]
It looks like we need to upgrade the go version on the CI too.
@galexrt is this still draft btw?

**Comment by galexrt** [comment]
@leseb The CI was updated so I'm not sure why the CI failed at the Go version. I have hit up

This is still a draft. I have gotten farther than before now but we seem to have to update most dependencies especially client-go to at least 1.15/1.16 (#4408) (see https://github.com/kubernetes/client-go/blob/master/INSTALL.md#enabling-go-modules) to get around some dependency issues (e.g., older dependencies using a fork of a pkg but the "original" pkg is used as well).

I'll try to work around the issues and / or update the dependencies as needed in lights of #4408.

**Comment by galexrt** [comment]
One more point to mention is that some issues stem from us using `k8s.io/kubernetes` as a dependency / module directly, see https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505725449.

**Comment by galexrt** [comment]
From my side the PR is ready for review now, let's just hope for the CI to run through.

**Comment by galexrt** [comment]
Potentially blocked by https://github.com/rook/operator-kit/pull/35 as seen in the latest CI failure:

```
[...]
# k8s.io/component-base/metrics/legacyregistry
../../../../pkg/mod/k8s.io/component-base@v0.0.0-20191114102325-35a9586014f7/metrics/legacyregistry/registry.go:44:9: undefined: prometheus.InstrumentHandler
# github.com/rook/operator-kit
../../../../pkg/mod/github.com/rook/operator-kit@v0.0.0-20190826143113-5ae9623aed20/client.go:52:32: undefined: serializer.DirectCodecFactory
# github.com/kube-object-storage/lib-bucket-provisioner/pkg/client/clientset/versioned/typed/objectbucket.io/v1alpha1
../../../../pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20191209225510-8423df408133/pkg/client/clientset/versioned/typed/objectbucket.io/v1alpha1/objectbucket.io_client.go:79:32: undefined: serializer.DirectCodecFactory
# github.com/rook/rook/pkg/operator/k8sutil
vet: pkg/operator/k8sutil/node_test.go:202:13: NodeOutOfDisk not declared by package v1
make[1]: *** [go.vet] Error 2
build/makelib/golang.mk:157: recipe for target 'go.vet' failed
make: *** [build.common] Error 2
Makefile:101: recipe for target 'build.common' failed
script returned exit code 1
```

**Comment by leseb** [comment]
@galexrt ready to test again?

**Pull request closed without merging**
