### PR TITLE
ceph: update required rbac for csi

### PR DESCRIPTION
**Pull request by Madhu-1**
**Description of your changes:**

as we are approaching the rook 1.5 release, we are making the required RBAC changes for cephcsi ahead of the cephcsi release to provide a smooth upgrade experience for the users without any RBAC changes in rook minor release.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
[test ceph]

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
LGTM, please just rebase to pick up a separate unit test fix

**Review by BlaineEXE — CHANGES_REQUESTED** [review]
I think the updated roles also need to be added to an `upgrade-from-v1.4-apply.yaml` in the manifests and have an apply step added to CI tests. Does that sound right @travisn ?

**Comment by travisn** [comment]
> I think the updated roles also need to be added to an `upgrade-from-v1.4-apply.yaml` in the manifests and have an apply step added to CI tests. Does that sound right @travisn ?

True, it's also needed in the `upgrade-from-v1.4-apply.yaml`. The CI tests are in need of other changes anyway, let's discuss separately.

**Comment by Madhu-1** [comment]
> I think the updated roles also need to be added to an `upgrade-from-v1.4-apply.yaml` in the manifests and have an apply step added to CI tests. Does that sound right @travisn ?

added new `upgrade-from-v1.4-apply.yaml` file now

**Review by travisn — APPROVED** [review]

**Review by BlaineEXE — APPROVED** [review]

**Pull request merged**
