### PR TITLE
test: add tmate to daily/nightly jobs

### PR DESCRIPTION
**Pull request by BlaineEXE**
Add tmate debugging to daily/nightly jobs to help debugging.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by subhamkrai — COMMENTED** [review]
@BlaineEXE question: You know whose machine we use for self-hosted arm?

**Comment by BlaineEXE** [comment]
> @BlaineEXE question: You know whose machine we use for self-hosted arm?

I don't. @travisn might know. Someone donated it to us.

**Comment by subhamkrai** [comment]
> > @BlaineEXE question: You know whose machine we use for self-hosted arm?
> 
> I don't. @travisn might know. Someone donated it to us.

Yeah, I found the discussion just now it was some upstream user whole provided to us.

The whole reason behind asking this question is since self-hosted machines are not auto-cleaned and it is the responsibility of the github run to clean the machine, so since we have added the tmate we should make sure that if we install something we clean it ourselves. Just wanted to raise this point in general.

**Comment by BlaineEXE** [comment]
Thanks for the info and reminder. That's a great thing to keep in mind.

**Pull request merged**
