### PR TITLE
Restructure docs for storage provider view

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
With the addition of new storage providers in 0.9 it became necessary to restructure the docs based on storage provider. Much more still needs to be done, but this should be a good start. See attached screenshot for a glimpse of the changes from the generated preview (ignore that it's cut off at the bottom since my screen does not have sufficient space).

This PR also includes some small improvements found from reviewing the docs for the 0.9 release.

**Which issue is resolved by this Pull Request:**
This is the start of #1802 

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

[skip ci]

screen shot 2018-12-07 at 11 49 59 pm

### CODE REVIEW

**Comment by yanniszark** [comment]
@travisn That's great and much needed! 
The only thing I would request is leaving more room for each provider's individual category.
For instance, Cassandra may now only have the cassandra-cluster-crd in its docs, but other documents are coming soon about monitoring, upgrades, etc.
Right now, Cassandra CRD is weight 50 and CockroachDB is weight 52, giving room for only 1 more doc before having to change many weights. 
I recommend leaving space for 10 documents per provider, they're free after all! :grin:

**Comment by galexrt** [comment]
@yanniszark I think it is fine as it is right now, as it will either be updated by a PR extending the docs or hopefully soon my rework of the Rook home and docs pages (website).

As I will probably make reworking the website first priority after the v0.9 release.

**Comment by travisn** [comment]
@yanniszark No problem, it was easy enough to change the weights to make it easier to add topics for storage providers in the future. It would be great to have more topics for each of the providers soon so the docs are more symmetrical. I also can't wait to have an overhaul of the docs as suggested in #1802!

**Comment by jbw976** [comment]
ah, looks like i just missed this, but my suggestion would have been to also multiple all the weights by 10 or 100.  so instead of 21, make it 210 or 2100.  that would leave a lot of space for new docs to slide in without any shuffling again.

**Comment by travisn** [comment]
The topics seem to move around more than we slide new topics in between. Oh well, there's always opportunity for another PR another time. :)

**Pull request merged**
