### PR TITLE
operator: remove PdbV1Beta1 support as k8s 1.25 doesnt support it

### LINKED ISSUE #13941: Remove PdbV1Beta1 support as k8s 1.25 doesnt support it
**Is this a bug report or feature request?**
* Bug Report

The minimum version rook is supporting is k8s 1.25, and k8s 1.25 doesn't support it https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
So, there is no need to double-check in the code as all the versions can serve now on `policyv1`.

**Expected behavior:**

The fix would be removing this commit (https://github.com/rook/rook/pull/7977)77813f709353f73208cfab99c2ad7b99049f94db and testing it thoroughly on upgrades from 1.24 to 1.25.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

### PR DESCRIPTION
**Pull request by mmaoyu**
This commit remove PdbV1Beta1 as k8s 1.25 doesnt support it.

Resolves #13941 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by parth-gr** [comment]
I propose to run `git revert` for this commit https://github.com/rook/rook/pull/7977
And then add a second commit for whatever manually/additional changes are required

**Comment by mmaoyu** [comment]
> I propose to run `git revert` for this commit #7977 And then add a second commit for whatever manually/additional changes are required

I've read https://github.com/rook/rook/pull/7977 carefully before I start this task, there are dicussions about how to make code easy delete when pdbv1beta1 cann't be used. 

But revert looks like duplicate work

Could you please explain your concerns

**Comment by parth-gr** [comment]
Either way is fine, I thought to revert would be straightforward.

Can you test the change in your local cluster too?

**Comment by parth-gr** [comment]
and please fix the ci I see commitlint and golangci-lint is failing

**Comment by mmaoyu** [comment]
> Either way is fine, I thought to revert would be straightforward.
> 
> Can you test the change in your local cluster too?

Now all ci success,please take a look at it.
And I've tested in local cluster(kubelet 1.24.0 and 1.28.3), pdb created correctly .

```
kubectl rook-ceph rook version
2024/03/22 07:49:00 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
rook: 8.8
go: go1.21.8


kubectl get pdb -n rook-ceph -o yaml
apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: "2024-03-22T07:50:38Z"
....
```

**Review by parth-gr — APPROVED** [review]

**Pull request merged**
