### PR TITLE
ceph: strip crd description for csv generation

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

The CSV file size cannot be bigger than 1MB so let's remove all the
description fields make it lighter.

With that change the CRDs size went from 692K to 372K so the size was
reduced by almost 50%.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by leseb** [comment]
@obnoxxx @jarrpa FYI

**Comment by subhamkrai** [comment]
@leseb can we start the crds gen gh action just to verify to see how this goes?

**Comment by leseb** [comment]
> @leseb can we start the crds gen gh action just to verify to see how this goes?

I don't know why it did not run.

**Comment by subhamkrai** [comment]
> > @leseb can we start the crds gen gh action just to verify to see how this goes?
> 
> I don't know why it did not run.

actually it start when there are changes in go files

**Comment by leseb** [comment]
> > > @leseb can we start the crds gen gh action just to verify to see how this goes?
> > 
> > 
> > I don't know why it did not run.
> 
> actually it start when there are changes in go files
> 
> ```
>   pull_request:
>     paths:
>     - '**.go'```
> ```

Makes sense.

**Comment by leseb** [comment]
@subhamkrai crd gen is happy https://github.com/rook/rook/pull/7523/checks?check_run_id=2276478493

**Review by subhamkrai — APPROVED** [review]
lgtm

**Review by umangachapagain — APPROVED** [review]
Seems like a good way to reduce size, but I believe it also means `kubectl explain` would be less useful for these CRDs.

**Comment by leseb** [comment]
> Seems like a good way to reduce size, but I believe it also means `kubectl explain` would be less useful for these CRDs.

I was concern about this too but that's a CSV issue at this point.

**Pull request merged**
