### PR TITLE
object: mark endpoint as a optional field

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
fyi @parth-gr

**Review by subhamkrai — APPROVED** [review]
lgtm

**Comment by travisn** [comment]
@BlaineEXE This looks like the source of our recent CI issues in 1.10. Why would the optional flag have been in master, but not the 1.10 branch?

**Comment by BlaineEXE** [comment]
The short answer is the mergify bot. I tested the commit's changes in the 1.10 backport PR to get my PR passing tests, and then cherry picked it to master to refine it. Then mergify merged the backport PR once tests passed.

**Review by BlaineEXE — APPROVED** [review]

**Pull request merged**
