### PR TITLE
ceph: do not use label selector on external svc

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

We must move the endpoint creation after the service monitor otherwise,
the service monitor will override the endpoint values.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]

### CODE REVIEW

**Review by galexrt — APPROVED** [review]

**Comment by umangachapagain** [comment]
@leseb I don't think the issue is due to Service Monitor. It's probably because of Service itself.

https://github.com/rook/rook/blob/e40b462216b06f6b59cf29c4accc8d2c93a1382d/pkg/operator/ceph/cluster/mgr/spec.go#L312 shows that we add `Selector` spec to Service which triggers endpoint creation to point to the selected pod. In case of external cluster, we don't have those pods so endpoint ends up being blank. When you explicitly create an endpoint, it gets replaced when kubernetes reconciles the service. This is just a hypothesis for now, but I strongly feel removing selector from Service for external monitoring should fix all issues (no need to shift things or add watch for disappearing endpoint).

**Comment by galexrt** [comment]
You are right @umangachapagain. If a `selector` is set, an Endpoint is created and reconciled.
The `selector` must be omitted, possibly `nil`ed or just left empty for K8S to not create an Endpoint.

**Comment by leseb** [comment]
> @leseb I don't think the issue is due to Service Monitor. It's probably because of Service itself.
> 
> https://github.com/rook/rook/blob/e40b462216b06f6b59cf29c4accc8d2c93a1382d/pkg/operator/ceph/cluster/mgr/spec.go#L312
> 
> shows that we add `Selector` spec to Service which triggers endpoint creation to point to the selected pod. In case of external cluster, we don't have those pods so endpoint ends up being blank. When you explicitly create an endpoint, it gets replaced when kubernetes reconciles the service. This is just a hypothesis for now, but I strongly feel removing selector from Service for external monitoring should fix all issues (no need to shift things or add watch for disappearing endpoint).

Which reconcile are talking about? When we experienced the bug, ocs-op, rook-ceph and nooba were shutdown and still the endpoint was disappearing around a 10min mark.

**Comment by umangachapagain** [comment]
> > @leseb I don't think the issue is due to Service Monitor. It's probably because of Service itself.
> > https://github.com/rook/rook/blob/e40b462216b06f6b59cf29c4accc8d2c93a1382d/pkg/operator/ceph/cluster/mgr/spec.go#L312
> > 
> > shows that we add `Selector` spec to Service which triggers endpoint creation to point to the selected pod. In case of external cluster, we don't have those pods so endpoint ends up being blank. When you explicitly create an endpoint, it gets replaced when kubernetes reconciles the service. This is just a hypothesis for now, but I strongly feel removing selector from Service for external monitoring should fix all issues (no need to shift things or add watch for disappearing endpoint).
> 
> Which reconcile are talking about? When we experienced the bug, ocs-op, rook-ceph and nooba were shutdown and still the endpoint was disappearing around a 10min mark.

This is done by Kubernetes controllers. Our operators just create the service, it's reconcile is done by K8s itself.

**Comment by leseb** [comment]
Force merging since the last run on 1.15 is affected by https://github.com/rook/rook/issues/5877.

**Pull request merged**
