### PR TITLE
Add fstype: xfs to documentation and examples to move it in line with Ceph recommendations. 

### LINKED ISSUE #1280: Volume mapping hangs when trying to mount a large volume > 5TB
This issue was found by @dimm0 which triggered a side effect issue which is tracked in https://github.com/rook/rook/issues/1214.

From https://github.com/rook/rook/issues/1214#issuecomment-344374292, the RBD command hangs(or take too long) when mapping the large volume. After sometime, Rook times out and issue a SIGTERM on the RBD command and try again.

### PR DESCRIPTION
**Pull request by patrickstjohn**
Description of your changes:
Changes examples and documentation to deviate from the Kubernetes defaults of ext4 to xfs. This moves Rook in line with Ceph recommendations but deviates from a Kubernetes default. 

https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L477

https://github.com/rook/rook/pull/847

Which issue is resolved by this Pull Request:
Resolves #1280 and #1681 

Checklist:
- [x] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.

[skip ci]

### CODE REVIEW

**Comment by jbw976** [comment]
Changes look good to me @patrickstjohn, thanks for your contribution!  Can you please amend your commit to include the sign-off as described in https://github.com/rook/rook/blob/master/CONTRIBUTING.md#certificate-of-origin?  I can merge this after the sign-off is included, let us know if you need any help with that.

**Comment by patrickstjohn** [comment]
@jbw976 No problem. Let me know if you need anything else.

**Comment by galexrt** [comment]
@patrickstjohn DCO sign-off is still "missing". It should just be a line with `Signed-off-by: Patrick St. John <patrickstjohn@hotmail.com>
d7c3762` without `This is my commit message` prepended.

Also has this been verified to work with hyperkube kubelets, just to make sure it is a sane(r) default?

**Comment by patrickstjohn** [comment]
@galexrt Sure thing, I'll work on getting it squashed and edited properly. The testing we've done is on a few clusters running 4cad7573e2617d903a12f5d318f597ec47bc0e67792a04f67ffee3e06c0ad373-kubelet-1.10.1-0.x86_64.rpm

**Comment by jbw976** [comment]
@galexrt does your https://github.com/galexrt/k8s-vagrant-multi-node repo use hyperkube? if so, i could test this change out in that environment.

**Comment by galexrt** [comment]
@jbw976 I don't think so. But running `docker run -it --entrypoint=/bin/bash quay.io/coreos/hyperkube` and then checking if `mkfs.xfs` and the `xfs_*` tools are available should be enough.

@patrickstjohn There is something wrong with your commits, you now have 3 commits. If you need help with squashing, let us know.

**Pull request closed without merging**
