### PR TITLE
misspell

### PR DESCRIPTION
**Pull request by chenhonggc**
Maybe `priviledge` means `privilege`.

[skip ci]

### CODE REVIEW

**Comment by travisn** [comment]
@chenhonggc thanks for submitting the change. Could you sign your commit with `git -s`? You can click on the DCO requirement for more details.

**Comment by kokhang** [comment]
Added [skip ci] so that it doesnt run the ci test since this is just a doc change

**Comment by chenhonggc** [comment]
[skip ci]

**Comment by chenhonggc** [comment]
@travisn  Thanks.

**Pull request closed without merging**
