### PR TITLE
snap package

### PR DESCRIPTION
**Pull request by mikeroyal**
Includes snapcraft.yaml to build [snap](https://snapcraft.io/).

**Description of your changes:**
Feature Pull Request to add snap.
**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../CONTRIBUTING.md#comments)

[skip ci]

### CODE REVIEW

**Comment by mikeroyal** [comment]
Hi @travisn, I simply made the snap because I know there are people who like to use snaps to setup and install. Other than that I am fine the make commands provided in the repo.

**Comment by leseb** [comment]
I think https://github.com/rook/rook/tree/master/cluster is a better place for this `snap`directory`.

**Comment by galexrt** [comment]
@mikeroyal What is the advantage of having the Rook Ceph operator as a snap?
Rook is deployed as a container image to a Kubernetes cluster.
Where does snap come into play there?

**Comment by mikeroyal** [comment]
Hi @galexrt, Snaps utilize containerization when building a snap it's creating a self-contained Linux execution environments. Where any program and all its dependencies can be bundled up into a single file aka snapcraft.yaml. As for deploying to a Kubernetes cluster the snap would work similar in way to [Microk8s ](https://microk8s.io/).

**Comment by galexrt** [comment]
@mikeroyal Can you then deploy built Rook Ceph operator Snap to Kubernetes like a Docker image?
I'm trying to understand where the advantage is as the Rook Ceph operator needs to be run inside the Kubernetes cluster until #3268 is merged. With #3268 merged the operator can be run outside of the Kubernetes cluster (besides development though I don't really see reasons to do that though).

**Comment by mikeroyal** [comment]
Hi @galexrt, yeah I could deploy built Rook Ceph operator Snap to Kubernetes like a Docker image. But reading your last sentence of reasons to do it until #3268 is merged. After I thought about it I think for now a snap may not be best for rook. Though, I would like to possibly revisit this later on when the operator can be run outside of the Kubernetes cluster. I want to thank you for your time and I appreciate the work your doing with rook.

**Pull request closed without merging**
