### PR TITLE
ceph: add more debug logging to obj bucket claims

### PR DESCRIPTION
**Pull request by BlaineEXE**
Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Does not resolve 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
This gives me additional log info here:
```
2020-11-17 23:52:50.044100 D | op-bucket-prov: Delete event for OB: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{StorageClassName: ReclaimPolicy:<nil> ClaimRef:nil Connection:0xc000833d00} Status:{Phase:}}
```

It seems Delete is being called without any info in the struct.

**Review by thotz — APPROVED** [review]
LGTM

**Comment by thotz** [comment]
> This gives me additional log info here:
> 
> ```
> 2020-11-17 23:52:49.634262 D | ceph-object-controller: bucket "ceph-bkt-0c4d1a1a-ad94-49f4-b71b-a1e0a8d4c0c3" already exists
> 2020-11-17 23:52:49.634270 I | ceph-object-controller: Setting user "ceph-user-LB6lU2zH" max buckets to 1
> 2020-11-17 23:52:49.634287 D | exec: Running command: radosgw-admin quota set --uid ceph-user-LB6lU2zH --quota-scope user --max-buckets 1 --rgw-realm=my-store --rgw-zonegroup=my-store --rgw-zone=my-store --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
> 2020-11-17 23:52:50.033018 I | op-bucket-prov: set user "ceph-user-LB6lU2zH" bucket max to 1
> I1117 23:52:50.033072       6 resourcehandlers.go:138]  "msg"="creating Secret" "key"="default/ceph-delete-bucket" "name"="default/ceph-delete-bucket"
> I1117 23:52:50.044024       6 controller.go:297]  "msg"="cleaning up provisioning artifacts" "key"="default/ceph-delete-bucket"
> I1117 23:52:50.044047       6 controller.go:299]  "msg"="deleting provisioned resources" "key"="default/ceph-delete-bucket"
> 2020-11-17 23:52:50.044100 D | op-bucket-prov: Delete event for OB: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{StorageClassName: ReclaimPolicy:<nil> ClaimRef:nil Connection:0xc000833d00} Status:{Phase:}}
> 2020-11-17 23:52:50.044107 I | op-bucket-prov: getting storage class ""
> 2020-11-17 23:52:50.044127 E | op-bucket-prov: error getting class "", retrying. resource name may not be empty
> 2020-11-17 23:52:54.439214 E | op-bucket-prov: error getting class "", retrying. resource name may not be empty
> ```
> 
> It seems Delete is being called without any info in the struct.
> 
> I suspect this is an error with lib-bucket-provisioner here. `err` is not nil here, and `ob` is also not nil, but the `ob` object is also empty:
> 
> ```go
> 	// Should an error be returned, attempt to clean up the object store and API servers by
> 	// calling the appropriate provisioner method.  In cases where Provision() or Revoke()
> 	// return an err, it's likely that the ob == nil, hindering cleanup.
> 	defer func() {
> 		if err != nil && ob != nil {
> 			log.Info("cleaning up provisioning artifacts")
> 			if /*greenfield*/ isDynamicProvisioning && !pErr.IsBucketExists(err) {
> 				log.Info("deleting provisioned resources")
> 				if dErr := c.provisioner.Delete(ob); dErr != nil {
> 					log.Error(dErr, "could not delete provisioned resources")
> 				}
> 			} else /*brownfield*/ {
> 				log.Info("revoking access")
> 				if dErr := c.provisioner.Revoke(ob); dErr != nil {
> 					log.Error(err, "could not revoke access")
> 				}
> 			}
> 			_ = c.deleteResources(ob, configMap, secret, nil)
> 		}
> 	}()
> ```
> 
> From the logs, it seems that it attempts `createSecret` and I believe eventually fails:
> `E1117 23:53:48.319778 6 controller.go:197] error syncing 'default/ceph-delete-bucket': error creating secret for OBC: secrets "ceph-delete-bucket" already exists, requeuing`
> 
> @thotz : What is the purpose of requeuing if the secret already exists rather than updating the secret with new info?

I am suspecting obc key was never removed from queue properly from begining itself. This issue was never hit because [shouldProvision](https://github.com/kube-object-storage/lib-bucket-provisioner/blob/master/pkg/provisioner/helpers.go#L63) in [syncHandler](https://github.com/kube-object-storage/lib-bucket-provisioner/blob/master/pkg/provisioner/controller.go#L245) was handled that condition properly, so checking existing secret was not required since that function was validating for `OB` creation. Now this check no longer working(still wondering why). Please refer [here](https://github.com/rook/rook/pull/6619#issuecomment-729448623) 

@jeffvance @copejon : want to add anything?

**Comment by jeffvance** [comment]
The extra logging in the rook provisioner LGTM. I am also trying to figure out what's the root problem in [6619](https://github.com/rook/rook/pull/6619)

**Review by leseb — APPROVED** [review]

**Pull request merged**
