### PR TITLE
csi: rbd node secret was misspelled

### PR DESCRIPTION
**Pull request by parth-gr**
Corrected CSI_RBD_NODE_SECRET name so it should be
output correctely when called script with
bash format output

Signed-off-by: parth-gr <paarora@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
is this a regression or just for the plain output?

**Comment by parth-gr** [comment]
> is this a regression or just for the plain output?

No regression, yes right it's just for the plain output

**Comment by leseb** [comment]
> > is this a regression or just for the plain output?
> 
> No regression, yes right it's just for the plain output

Why is `gen_json_out` changed then?

**Comment by parth-gr** [comment]
> Why is `gen_json_out` changed then?

Is just because the key of the out_put map got changed to `CSI_RBD_NODE_SECRET` so for calling the secret we need to update the key,
There is no change in the JSON output,

But the bash output will be corrected with the correct secret name that will be used for upstream.

**Review by leseb — APPROVED** [review]

**Comment by parth-gr** [comment]
> I'll let Parth decide it's part of a larger refact for external mode setup so perhaps we can wait for 1.9

Yup it's used for #9552 so we can wait for 1.9.
Thanks:)

**Pull request merged**
