### PR TITLE
ceph: set helm resource policy keep annotation on CRDs in Helm chart

### LINKED ISSUE #6617: helm crd deletion
* Feature Request

**What should the feature do:**

It would be nice if the helm crd's were marked as resource-policy: keep so they wont be accidently deleted on helm chart removal.

See:

https://helm.sh/docs/howto/charts_tips_and_tricks/ has a section:
"Tell Helm Not To Uninstall a Resource"
Should be something like:

```
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
[...]
```

And the corresponding total cleanup documentation should reflect:
kubectl delete -f crds.yaml

This would put another roadblock in place of accidentally deleting a production cluster.

Previously discussed in https://github.com/rook/rook/issues/4037

### PR DESCRIPTION
**Pull request by onedr0p**
**Description of your changes:**

This special annotation will prevent Helm from uninstalling resources (in this case the CRDs) if the user changed the `crds.enabled` setting to `false`

**Which issue is resolved by this Pull Request:**
Resolves #6617

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [x] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [x] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[skip ci]

### CODE REVIEW

**Comment by onedr0p** [comment]
I kept the warning in the markdown table for `crds.enabled` because it's still vaild until the 1.6 release

**Comment by travisn** [comment]
The backport of your original PR was already completed with the merge of #7166, so I would have expected the only change to see in this PR is to add back the error message. Try rebasing on the latest `upstream/release-1.5`.

**Comment by onedr0p** [comment]
Whoops my bad, thought I pulled the latest release-1.5 branch

**Comment by travisn** [comment]
@onedr0p Could you squash the two commits into one? Then it looks good to go!

**Comment by onedr0p** [comment]
Thanks for holding my hand thru this 🤣 should be all good to go now

**Review by travisn — APPROVED** [review]

**Pull request merged**
