### PR TITLE
csi: default to ReadWriteOnceWithFSType for cephfs

### PR DESCRIPTION
**Pull request by humblec**
```
ReadWriteOnceWithFSType: Indicates that volumes will be examined
to determine if volume ownership and permissions should be modified
to match the pod's security policy. Changes will only occur if the
fsType is defined and the persistent volume's accessModes contains
ReadWriteOnce.
```

In between considering we are giving 0777 permission on nodestage
of cephfs shares, we defaulted to NONE. However giving worldwide
permission to the volume is not the right thing and it has been
fixed in cephfs via https://github.com/ceph/ceph-csi/pull/2847

This commit brings it back to the value which is also in parity
with RBD driver.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by humblec** [comment]
Cc @travisn @leseb

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
Need change  at below places

https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml#L71
https://github.com/rook/rook/blob/master/deploy/examples/operator-openshift.yaml#L153

Do we need documentation to change this value in upgraded clusters?

**Comment by humblec** [comment]
> Do we need documentation to change this value in upgraded clusters?

Considering the changes are opt in and out as always, we dont need to ask the users I believe.

**Comment by humblec** [comment]
@Madhu-1 can you revisit the PR?

**Review by Madhu-1 — APPROVED** [review]

**Comment by humblec** [comment]
@leseb @travisn ptal.. thanks,

**Review by leseb — APPROVED** [review]

**Comment by humblec** [comment]
> @humblec
> 
>     * Should this only be merged after we pick up the next CSI release with the related fix?
> 
>     * If someone doesn't use the CSI release with the related fix, is there any concern? Or the new default is ok either way.

Yeah, afaict, it should be fine to pick the change even in absence of CSI fix @travisn

**Pull request merged**
