### PR TITLE
ceph: re-enable ceph manager suite

### LINKED ISSUE #5877: Ceph mgr test intermittently fails with no nodes or devices available
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The CephMgrSuite intermittently fails with errors such as the following:
```
--- FAIL: TestCephMgrSuite (238.55s)
    --- FAIL: TestCephMgrSuite/TestCreateOSD (0.85s)
        ceph_mgr_test.go:195: 
            	Error Trace:	ceph_mgr_test.go:195
            	Error:      	Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc00074d060), Stderr:[]uint8{0x45, 0x72, 0x72, 0x6f, 0x72, 0x20, 0x45, 0x4e, 0x4f, 0x45, 0x4e, 0x54, 0x3a, 0x20, 0x4e, 0x6f, 0x20, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x20, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x20, 0x28, 0x74, 0x72, 0x79, 0x20, 0x60, 0x63, 0x65, 0x70, 0x68, 0x20, 0x6f, 0x72, 0x63, 0x68, 0x20, 0x73, 0x65, 0x74, 0x20, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x60, 0x29, 0xa, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x20, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x20, 0x77, 0x69, 0x74, 0x68, 0x20, 0x65, 0x78, 0x69, 0x74, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x20, 0x32, 0xa}}
            	Test:       	TestCephMgrSuite/TestCreateOSD
        ceph_mgr_test.go:201: 
            	Error Trace:	ceph_mgr_test.go:201
            	Error:      	Expected nil, but got: &json.SyntaxError{msg:"invalid character '.' looking for beginning of value", Offset:1}
            	Test:       	TestCephMgrSuite/TestCreateOSD
        ceph_mgr_test.go:217: 
            	Error Trace:	ceph_mgr_test.go:217
            	Error:      	Should not be: ""
            	Test:       	TestCephMgrSuite/TestCreateOSD
            	Messages:   	No devices available to create test OSD
        ceph_mgr_test.go:218: 
            	Error Trace:	ceph_mgr_test.go:218
            	Error:      	Should not be: ""
            	Test:       	TestCephMgrSuite/TestCreateOSD
            	Messages:   	No nodes available to create test OSD
```

See the example failure [here](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-5837/runs/12/nodes/57/steps/124/log/?start=0).

**Expected behavior:**
Integration tests should pass consistently.

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
**Description of your changes:**

The discovery daemon must be enabled to work rook ceph-mgr module.

**Which issue is resolved by this Pull Request:**
Resolves #5877

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]
[test full]

### CODE REVIEW

**Comment by travisn** [comment]
The github action for the CephMgrSuite still was skipped, not sure why since you removed the line that skipped the test. I added [test full] to see if Jenkins will run the suite.

**Comment by travisn** [comment]
Ok in Jenkins I see now that the CephMgrSuite passed. However, the other test suites are failing, looks like there is a check for the discovery daemonset that needs to be disabled when the discovery pod is disabled. For example:
```
[2021-01-08T21:06:43.185Z] --- FAIL: TestCephFlexSuite (776.28s)
[2021-01-08T21:06:43.185Z]     ceph_installer.go:504: 
[2021-01-08T21:06:43.185Z]         	Error Trace:	ceph_installer.go:504
[2021-01-08T21:06:43.185Z]         	            				ceph_base_deploy_test.go:171
[2021-01-08T21:06:43.185Z]         	            				ceph_base_deploy_test.go:163
[2021-01-08T21:06:43.185Z]         	            				ceph_flex_test.go:104
[2021-01-08T21:06:43.185Z]         	            				suite.go:118
[2021-01-08T21:06:43.185Z]         	            				ceph_flex_test.go:66
[2021-01-08T21:06:43.185Z]         	Error:      	Received unexpected error:
[2021-01-08T21:06:43.185Z]         	            	daemonsets.apps "rook-discover" not found
[2021-01-08T21:06:43.185Z]         	Test:       	TestCephFlexSuite
```

**Comment by travisn** [comment]
I opened #7190 to reenable this test in the github action and we don't need to worry about running it in jenkins. This will simplify the changes, and I believe no need for the discover changes. Shall we close this PR?

**Comment by satoru-takeuchi** [comment]
OK, close.

**Pull request closed without merging**
