### PR TITLE
ceph: Fix Helm 2 build error in the release-1.4 branch

### LINKED ISSUE #6887: release-1.4 branch build is failing due to helm v2 issue
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The release-1.4 build is failing due to the following error with helm v2 as seen [here](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/release-1.4/191/pipeline):
```
[2020-12-28T20:41:58.792Z] + nproc
[2020-12-28T20:41:58.792Z] + build/run make -j2 build.all
[2020-12-28T20:42:02.997Z] Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
[2020-12-28T20:42:02.997Z] make: *** [/home/rook/go/src/github.com/rook/rook/.cache/tools/linux_amd64/helm-v2.16.7] Error 1
[2020-12-28T20:42:03.027Z] ==== building the cross container (this could take minutes the first time)
[2020-12-28T20:42:03.027Z] === installing helm
[2020-12-28T20:42:03.027Z] === ensuring modules are tidied
[2020-12-28T20:42:03.027Z] Creating /home/rook/go/src/github.com/rook/rook/.cache/helm 
[2020-12-28T20:42:03.027Z] Creating /home/rook/go/src/github.com/rook/rook/.cache/helm/repository 
[2020-12-28T20:42:03.027Z] Creating /home/rook/go/src/github.com/rook/rook/.cache/helm/repository/cache 
[2020-12-28T20:42:03.027Z] Creating /home/rook/go/src/github.com/rook/rook/.cache/helm/repository/local 
[2020-12-28T20:42:03.027Z] Creating /home/rook/go/src/github.com/rook/rook/.cache/helm/plugins 
[2020-12-28T20:42:03.027Z] Creating /home/rook/go/src/github.com/rook/rook/.cache/helm/starters 
[2020-12-28T20:42:03.027Z] Creating /home/rook/go/src/github.com/rook/rook/.cache/helm/cache/archive 
[2020-12-28T20:42:03.027Z] Creating /home/rook/go/src/github.com/rook/rook/.cache/helm/repository/repositories.yaml 
[2020-12-28T20:42:03.027Z] Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
[2020-12-28T20:42:03.027Z] build/makelib/helm.mk:32: recipe for target '/home/rook/go/src/github.com/rook/rook/.cache/tools/linux_amd64/helm-v2.16.7' failed
script returned exit code 1
```

**Expected behavior:**
Build must succeed.

**How to reproduce it (minimal and precise):**

Run the build on the release-1.4 branch.

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
**Description of your changes:**

The stable repository of helm chars is moved to a new location. See the following URL for more detail.

https://helm.sh/blog/new-location-stable-incubator-charts/

Closes: https://github.com/rook/rook/issues/6887

**Which issue is resolved by this Pull Request:**

Resolves #6887

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]
[test full]

### CODE REVIEW

**Comment by travisn** [comment]
LGT, though Helm 2.17 may have changed something else since the helm suite failed: 
```
[2020-12-29T10:58:59.603Z] 2020-12-29 10:58:56.687680 D | exec: Running command: /tmp/rook-tests-scripts-helm/linux-amd64/helm search local/rook-ceph
[2020-12-29T10:58:59.603Z] 2020-12-29 10:58:59.341258 E | installer: Rook Operator not installed ,error -> Failed to get Version of helm chart local/rook-ceph, err : Failed to find helm chart  local/rook-ceph 
[2020-12-29T10:58:59.603Z] 2020-12-29 10:58:59.341278 E | integrationTest: Rook was not installed successfully: Failed to get Version of helm chart local/rook-ceph, err : Failed to find helm chart  local/rook-ceph
```

I added `[test full]` and restarted the CI to verify if it was just intermittent.

**Comment by travisn** [comment]
@satoru-takeuchi The failure of the helm test is consistent in the CI. Any more clues on this?

**Comment by satoru-takeuchi** [comment]
@travisn I'll investigated it tomorrow.

**Comment by travisn** [comment]
The integration tests seem to be failing because `helm search` on the local repo isn't working. It's not clear why yet. I opened #6910 in case it turns up simpler to simply convert to helm 3 instead of trying to maintain helm 2 in this branch.

**Comment by satoru-takeuchi** [comment]
It's better to use helm v3 than helm v2 since the latter is already deprecated. Hence #6910 is better solution.

**Pull request closed without merging**
