### PR TITLE
DNM: core: osd replace tool

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
**Description of your changes:**

`osd-replace` is to replace an existing OSD with a new one. This tool is especially useful to replace broken OSDs.

> NOTE: I don't plan to merge this PR. It is just to share my homemade tool based on the request from audiences of my session at Cephalocon 2023.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
This appears similar to the `purge-osd` function of the [krew plugin](https://github.com/rook/kubectl-rook-ceph). How is it different? Perhaps this tool creates the OSD again by starting the operator up again, after the old OSD was purged? How about implementing this command in the krew plugin?

**Comment by satoru-takeuchi** [comment]
> Perhaps this tool creates the OSD again by starting the operator up again, after the old OSD was purged? 

> How is it different?

There are the following differences.

- ceph commands are

**Comment by satoru-takeuchi** [comment]
> Perhaps this tool creates the OSD again by starting the operator up again, after the old OSD was purged? 

Right.

> How is it different?

There are the following differences.

- Run ceph commands from toolbox pods than operator pod.
- Capacity check not to cause other osd's `nearfull` after removing an osd

> How about implementing this command in the krew plugin?

It's OK. However, the priority is low for me for now. As a first step, I'll open a new issue to the krew plugin. Does it make sense?

**Comment by travisn** [comment]
> It's OK. However, the priority is low for me for now. As a first step, I'll open a new issue to the krew plugin. Does it make sense?

Yes, sounds great to open an issue for the krew plugin. It's not urgent, but it sounds useful!

**Comment by satoru-takeuchi** [comment]
> As a first step, I'll open a new issue to the krew plugin.

done

https://github.com/rook/kubectl-rook-ceph/issues/96

**Comment by anthonyeleven** [comment]
OBTW, a while back I was chatting with @travisn about Rook and OSD failures: I wanted to look into the potential for `destroy`ing a faulty OSD to leave the CRUSH entry alone, then deploying the replacement OSD on the same physical device with the same OSD ID.  Looking at the code here, I *think* you aren't re-using the OSD ID?

**Comment by satoru-takeuchi** [comment]
@anthonyeleven My tool doesn't try to reuse osd id intentionally. It just remove an osd and add a new one. Sometimes the the new osd have the same id as the old osd, but sometimes not. The behavior depends on Ceph's implementation.

**Pull request closed without merging**
