### PR TITLE
ceph: embed ceph-csi templates in rook binary

### PR DESCRIPTION
**Pull request by leseb**
Thanks to Golang 1.16, we can now embed files in the Go binary. This
means we don't need to add the CSI templates files to the container
image. They are added in the Go binary at build time.

The existing location of the template must be in the package calling it.
So they moved to pkg/operator/ceph/csi/template. All the files have been
symlinked back to cluster/examples/kubernetes/ceph/csi/template.

Closes: https://github.com/rook/rook/issues/7609
Signed-off-by: Sébastien Han <seb@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
Why do we need symlinks? Seems like we don't need the templates under the cluster examples anymore.

**Comment by leseb** [comment]
> Why do we need symlinks? Seems like we don't need the templates under the cluster examples anymore.

I guess I was thinking that people could deploy manually 🤷🏻‍♂️  but we can leave that up to the ceph-csi official deployment I guess.

**Review by travisn — CHANGES_REQUESTED** [review]
This will be really nice to have, I'm just wondering if we should hold it for a bit until we're sure we don't need to support go 1.15 builds anymore.

**Comment by leseb** [comment]
> This will be really nice to have, I'm just wondering if we should hold it for a bit until we're sure we don't need to support go 1.15 builds anymore.

Yes, this can stay until 1.17 is out I suppose. Assuming we can resurrect the 1.15 support with https://github.com/rook/rook/pull/8394 and its dependencies...

**Review by travisn — COMMENTED** [review]
LGTM after the unit tests ares passing, also if CSI team could review

**Review by Madhu-1 — APPROVED** [review]
LGTM

**Comment by Madhu-1** [comment]
```
=== RUN   TestDaemonSetTemplate
    util_test.go:33: 
        	Error Trace:	util_test.go:33
        	Error:      	Expected nil, but got: failed to unmarshal daemonset template: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.DaemonSet
        	Test:       	TestDaemonSetTemplate
--- FAIL: TestDaemonSetTemplate (0.00s)
=== RUN   TestDeploymentTemplate
    util_test.go:42: 
        	Error Trace:	util_test.go:42
        	Error:      	Expected nil, but got: failed to unmarshal deployment template: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.Deployment
        	Test:       	TestDeploymentTemplate
```

@leseb unit test failure

**Review by travisn — APPROVED** [review]

**Pull request merged**
