### PR TITLE
Fix for Go 1.14 templating

### LINKED ISSUE #5378: Helm templating error: can't give argument to non-function
I'm using the default values.yaml and getting the following errors.

version: v1.3.2

https://github.com/rook/rook/blob/6e5a6c45422c2c04e48bca22cf9a2d05f828082a/cluster/charts/rook-ceph/templates/clusterrole.yaml#L284

```
[rook-ceph]: template: rook-ceph/templates/clusterrole.yaml:284:7: executing "rook-ceph/templates/clusterrole.yaml" at <((.Values.agent) and .Values.agent.mountSecurityMode) and ne .Values.agent.mountSecurityMode "Any">: can't give argument to non-function (.Values.agent) and .Values.agent.mountSecurityMode
```

### PR DESCRIPTION
**Pull request by nyarly**
**Description of your changes:**

Rewrite of line in Helm chart to correctly reflect intent.

**Which issue is resolved by this Pull Request:**
Resolves #5378. See https://golang.org/doc/go1.14#text/template

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [x] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]

### CODE REVIEW

**Comment by travisn** [comment]
The CI is still using go 1.13 and failing with the following error:
```
[ERROR] templates/: render error in "rook-ceph/templates/clusterrole.yaml": template: rook-ceph/templates/clusterrole.yaml:284:37: executing "rook-ceph/templates/clusterrole.yaml" at <.Values.agent.mountSecurityMode>: nil pointer evaluating interface {}.mountSecurityMode
```

Is there a change that will work for both golang 1.13 and 1.14? We don't necessarily need to keep 1.13 support but it would be nice until we update the CI with 1.14.

**Comment by nyarly** [comment]
I was finding that I had that same error with a Go 1.14 environment until I'd turned off RBAC in that values.yaml. It might be a separate issue, exposed by this fix?

I can take a stab at fixing it as well here, if that seems appropriate.

**Comment by nyarly** [comment]
I'm unclear why Jenkins is breaking on this - could someone more familiar weigh in?

**Comment by leseb** [comment]
> I'm unclear why Jenkins is breaking on this - could someone more familiar weigh in?

Not sure this error was related to your change, running the CI one more time.

**Comment by nyarly** [comment]
@travisn Squashed.

**Comment by billimek** [comment]
@travisn it looks like this fix did not make it into the rook-ceph chart 1.3.7 release.  Some of us are stuck with helmreleases (using flux) until, hopefully, this fix is present.

Do you know which helm or rook-ceph release this will go in with?

**Comment by travisn** [comment]
> @travisn it looks like this fix did not make it into the rook-ceph chart 1.3.7 release. Some of us are stuck with helmreleases (using flux) until, hopefully, this fix is present.
> 
> Do you know which helm or rook-ceph release this will go in with?

Ah I didn't realize the blocking nature of this so it didn't get backported to 1.3. I've marked it for backport and it would be included in 1.3.8.

**Pull request merged**
