### PR TITLE
rgw: gateway deployment strategy RollingUpdate on Pacific

### PR DESCRIPTION
**Pull request by micalgenus**
**Description of your changes:**

When the strategy type of deployment is `Recreate`, it terminate at once as follows.

pods
```
NAME                     READY   STATUS        RESTARTS   AGE
echo-bc6fd5bf7-6hlld     1/1     Terminating   0          66d
echo-bc6fd5bf7-9sd2k     1/1     Terminating   0          66d
echo-bc6fd5bf7-bgxvb     1/1     Terminating   0          66d
echo-bc6fd5bf7-cqclp     1/1     Terminating   0          66d
echo-bc6fd5bf7-h4v7k     1/1     Terminating   0          66d
```

endpoints
```
NAME         ENDPOINTS                           AGE
echo         <none>                              689d
```

After that, when all pods are terminated, a new one is created at the same time.

pods
```
NAME                     READY   STATUS    RESTARTS   AGE
echo-97b48fcc6-98k4r     1/1     Running   0          89s
echo-97b48fcc6-hsk7b     1/1     Running   0          89s
echo-97b48fcc6-hwtdd     1/1     Running   0          89s
echo-97b48fcc6-wqbvj     1/1     Running   0          89s
echo-97b48fcc6-x85qq     1/1     Running   0          89s
```

In this case, from the moment the end is started until the new pod is normally running, there is no pod in the kubernetes service endpoints, so it goes to the service unavailable state.

Therefore, it is necessary to change it to `type: RollingUpdate` instead of `type: Recreate` so that rolling updates can be made without downtime.

Before Pacific, creating a deployment as much as the instance was okay, but after Pacific, the replicas was increased in one deployment, so rolling updates were set up one by one as in the previous version.

After changing the strategy, it can be seen that it is restarted normally one by one as follows.

pods
```
NAME                     READY   STATUS    RESTARTS   AGE
echo-85f97cf674-ghb8x    1/1     Running   0          2m13s
echo-85f97cf674-lqsw8    1/1     Running   0          88s
echo-85f97cf674-mcfxd    1/1     Running   0          49s
echo-85f97cf674-zqbcl    1/1     Running   0          3m32s
echo-85f97cf674-zvpsn    1/1     Running   0          2m52s
```

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by leseb — APPROVED** [review]

**Comment by leseb** [comment]
@micalgenus please update your git commit message and we should be good to go. Thanks!

**Review by leseb — CHANGES_REQUESTED** [review]
@micalgenus please update your git commit message and we should be good to go. Thanks!

**Comment by micalgenus** [comment]
Thanks!

**Review by leseb — APPROVED** [review]
I think MDS deserves the same treatment, we can do this in a separate PR though. Thanks!

**Pull request merged**
