### PR TITLE
rbdmirror: Rotate all rbd mirroring logs

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
The rbd mirror daemon logs to two files, one for the local mirror daemon and one log from the other cluster where the mirroring is taking place. The log rotation was only rotating one of the logs. Now we make the log rotation more general to catch all of the rbd mirror logs from different clusters.

If two rbd mirror daemons are running on the same node, there will be duplicate checks for rotating the logs, but the duplication is benign.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by idryomov — APPROVED** [review]
Ack from the RBD perspective

**Comment by idryomov** [comment]
Although noting for posterity that log file names are actually configurable and this can be easily fooled.  In the default configuration, the files in question would be named `ceph-client.rbd-mirror.a.log` and `<CLUSTER_FSID>-client.rbd-mirror-peer.log`.

**Comment by subhamkrai** [comment]
> Although noting for posterity that log file names are actually configurable and this can be easily fooled. In the default configuration, the files in question would be named `ceph-client.rbd-mirror.a.log` and `<CLUSTER_FSID>-client.rbd-mirror-peer.log`.

related question: above means that change from`"*-client.rbd-mirror*"` to  `ceph-client.rbd-mirror.a.log` or `<CLUSTER_FSID>-client.rbd-mirror-peer.log` will be handle by logrotate configuration file depending on rbd daemon?

**Review by subhamkrai — APPROVED** [review]
LGTM, I just have one small question.

**Comment by travisn** [comment]
> > Although noting for posterity that log file names are actually configurable and this can be easily fooled. In the default configuration, the files in question would be named `ceph-client.rbd-mirror.a.log` and `<CLUSTER_FSID>-client.rbd-mirror-peer.log`.
> 
> related question: above means that change from`"*-client.rbd-mirror*"` to `ceph-client.rbd-mirror.a.log` or `<CLUSTER_FSID>-client.rbd-mirror-peer.log` will be handle by logrotate configuration file depending on rbd daemon?

In the log rotate config file the filter will end up as `*-client.rbd-mirror*.log`, so the wildcards will remain. There won't be any more specific replacement of filenames.

**Pull request merged**
