### PR TITLE
docs: Move "How to run tests" instructions to developer

### LINKED ISSUE #11574: Move "How to run tests" instructions to developer
**Is this a bug report or feature request?**
* Feature Request

**What should the change do:**

Let's move the "test framework" instructions to the "contributing" docs section.
https://github.com/rook/rook/blob/master/tests/README.md

I think adding a link or even the contents of that README.md to the https://rook.io/docs/rook/v1.10/Contributing/development-flow/ would make sense.

Any input?

**What is use case behind this feature:**

Making it easier for new comers to find the info on how to test, e.g., new changes.

### PR DESCRIPTION
**Pull request by Javlopez**
**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #11574

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — CHANGES_REQUESTED** [review]
Before we move this to the docs, there is some data that is outdated that really needs to be updated. I'm planning to make a pass on the docs in the next week or two, if we can just hold on this PR for a bit...

**Comment by travisn** [comment]
#12257 has merged now, so after you rebase this it should be ready for merge

**Comment by travisn** [comment]
@Javlopez This needs to be rebased without the merge commits, to be a single commit. It still shows as conflicting, thanks.

**Comment by Javlopez** [comment]
I going to close this and I going to open a new PR

**Pull request closed without merging**
