### PR TITLE
ceph: add github action for helm lint

### PR DESCRIPTION
**Pull request by Madhu-1**
**Description of your changes:**
adding GitHub action for helm lint to catch the static check errors in helm charts.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
[skip ci]

### CODE REVIEW

**Review by leseb — COMMENTED** [review]
Would be nice to fix the complaint :)

**Comment by Madhu-1** [comment]
>templates/clusterrole.yaml: object name does not conform to Kubernetes naming requirements: "psp:rook": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253

@leseb @travisn any suggestion on changing the same? Am I the only one seeing this issue with PSP?

**Comment by Madhu-1** [comment]
Looks like the issue is with helm lint. kubernetes allows the resources to be created with special character `:` in the same.

**Comment by Madhu-1** [comment]
helm lint bug https://github.com/helm/helm/issues/9197 will revisit this PR once we have helm release with the bug fix.

**Comment by travisn** [comment]
@Madhu-1 looks like the referenced bug is fixed?

**Comment by travisn** [comment]
@Madhu-1 Want to update this with a newer version of the helm linter?

**Comment by Madhu-1** [comment]
> @Madhu-1 Want to update this with a newer version of the helm linter?

Done. Thanks for the reminder @travisn

**Comment by Madhu-1** [comment]
CI for helm lint passed https://github.com/rook/rook/pull/6868/checks?check_run_id=2673442410

**Review by leseb — APPROVED** [review]

**Review by subhamkrai — APPROVED** [review]

**Pull request merged**
