### PR TITLE
doc: fix a minor typo in design/object-store.md

### PR DESCRIPTION
**Pull request by ZVampirEM77**
Signed-off-by: Enming.Zhang <zvampirem77@gmail.com>

Fix a minor typo in design/object-store.md

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

[skip ci]

### CODE REVIEW

**Comment by jbw976** [comment]
Thanks for catching this and submitting a fix @ZVampirEM77! Our Jenkins build server is having some issues today, but we'll try to get this merged in soon.  Thanks!

**Comment by jbw976** [comment]
@ZVampirEM77 it looks like Github's request from this PR to the Jenkins server got lost in the ether this morning when Jenkins was down, could you possible ammend your commit in a minor way (e.g., slightly change the commit message) and force push that to your branch in the hopes of giving Jenkins another kick?  Sorry for the hassle.

Anyone know a better way to kick Jenkins when it never created the PR pipeline in the first place? redelivering the webhook request did nothing.

**Comment by jbw976** [comment]
Another option would be to close this PR and open a new one.  That may be easier?

**Comment by ZVampirEM77** [comment]
@jbw976 
Thank you for reviewing~
I have amended my commit message and re-push it again~

**Comment by jbw976** [comment]
Excellent, thank you for following up @ZVampirEM77! We hope to see more contributions from you :)

**Pull request merged**
