### PR TITLE
core: Remove vault server module dependencies

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
The vault server dependencies were pulling a lot of indirect modules that are not necessary for Rook. The modules were only used for testing. The vault github explicitly indicates that:

"Some other projects have made a practice of doing so in order to take advantage of testing tooling that was developed for testing Vault itself. This is not, and has never been, a supported way to use the Vault project."

When attempting to update to vault v1.13.3, we are hitting such an unsupported configuration with go modules
that are impossible to satisfy. By removing the tests that were using the vault server project, we can remove this large set of dependencies, enable updating to v1.13.3, and also reduce the modules pulled in by vault.

Given this reduction in dependencies, perhaps we can even revert #12160 so that we don't have the dependabot issue #12352. 
@s3rj1k Thoughts?

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by subhamkrai — APPROVED** [review]
Happy to get rid of vault dependencies it's been difficult updating those 😄

**Comment by subhamkrai** [comment]
we can close this too #12370

**Review by leseb — APPROVED** [review]
Seeing this PR and remembering the time I spent on those tests makes me sad 😅 . I believe the Vault API is tested as part of the canary test (both KV 1 and 2 are enabled) so it's safe to remove I suppose. Especially if it unblocks the dependency problem.

**Comment by parth-gr** [comment]
`Canary integration tests / encryption-pvc-kms-vault-token-auth (pull_request) Failing after 75m` This one is intermittent, But good to test with this PR.

**Pull request merged**
