### PR TITLE
ceph: disable ceph mgr test temporarily

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

The CI keeps failing intermittently due to
https://github.com/rook/rook/issues/5877 and the fix has not merged yet
so disabling until fixed.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by satoru-takeuchi** [comment]
@leseb Disabling a test may cause other bugs and is the last resort. So it's better to wait the merge of #5884 . And @jmolmo , if you're busy now, I can take over #5884 .

**Comment by leseb** [comment]
> @leseb Disabling a test may cause other bugs and is the last resort. So it's better to wait the merge of #5884 . And @jmolmo , if you're busy now, I can take over #5884 .

What kind of other bugs are thinking about? This suite is not crucial for Rook and these intermittent failures added to the others make the CI experience really difficult currently. I'm just trying to stabilize the CI at this point.

**Comment by satoru-takeuchi** [comment]
> What kind of other bugs are thinking about? 

Any bugs that can be detected by this test. If mgr test fails and its log shows that it comes from #5877 , it's OK. It would also be OK to merge PR iff the failure of the integration test is only caused by #5877  . However, I afraid that disabling it and merging other PRs after that incurs more instability.

> This suite is not crucial for Rook and these intermittent failures added to the others make the CI experience really difficult currently. I'm just trying to stabilize the CI at this point.

I understood your purpose. Then, for example, how about taking one of the following two ways?

- Concentrate on stabilizing CI and stop merging non-critical PRs for a while.
- Merge any kind of PRs iff all failures are caused by unstable test.

As for me, I've used not CI environment but local environment to tracked down the bugs. If mgr test is unstable, I've run only mgr test in my local environment for efficient debugging. I'll update the tests/README.md soon to ease this kind of work.

**Comment by satoru-takeuchi** [comment]
@leseb 

> I'll update the tests/README.md soon to ease this kind of work.

Here it is.
https://github.com/rook/rook/pull/6204

**Pull request merged**
