### PR TITLE
Ceph osd: terminate fatal on pod init failures

### PR DESCRIPTION
**Pull request by BlaineEXE**
Signed-off-by: Blaine Gardner <blaine.gardner@suse.com>

**Checklist:**
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [x] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by galexrt** [comment]
Nice catch!

**Comment by BlaineEXE** [comment]
@travisn yes those changes look about the same

**Comment by BlaineEXE** [comment]
I'm still seeing one change from `make codegen`:
```
diff --git a/pkg/apis/rook.io/v1alpha2/zz_generated.deepcopy.go b/pkg/apis/rook.io/v1alpha2/zz_generated.deepcopy.go
index db7f9989..2efb4fc4 100644
--- a/pkg/apis/rook.io/v1alpha2/zz_generated.deepcopy.go
+++ b/pkg/apis/rook.io/v1alpha2/zz_generated.deepcopy.go
@@ -276,6 +276,13 @@ func (in *Selection) DeepCopyInto(out *Selection) {
                        (*in)[i].DeepCopyInto(&(*out)[i])
                }
        }
+       if in.VolumeClaimTemplates != nil {
+               in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
+               *out = make([]v1.PersistentVolumeClaim, len(*in))
+               for i := range *in {
+                       (*in)[i].DeepCopyInto(&(*out)[i])
+               }
+       }
        return
 }
```

**Comment by travisn** [comment]
@BlaineEXE that looks related to #2309. We can merge this PR independent of that issue.

**Pull request merged**
