### PR TITLE
build: Drop go1.19 support and update go modules to the latest and greatest

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
- Update to latest go modules as much as possible. The go modules are updated to the latest client-go, vault, and other modules. There does not appear to be a combination of modules that will allow us to use vault v1.13.3, so we stick with v1.13.2.
- Require Go 1.20 in the builds. To update to the latest go modules we need to restrict golang support to 1.20 and drop support for 1.19.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by subhamkrai — APPROVED** [review]
Thanks for the PR, 

one question, what error you saw when upgrading the vault to 1.13.3?
```
Error: ../../../go/pkg/mod/github.com/hashicorp/vault@v1.13.3/audit/format.go:148:22: p.NamespacePath undefined (type logical.PolicyInfo has no field or method NamespacePath)
``` 
these one?

**Review by subhamkrai — CHANGES_REQUESTED** [review]
ops seems we need to update these golang version too

https://github.com/rook/rook/blob/1d3f99bc1455520cb1300600abb8b789f4d71a64/go.mod#L3

https://github.com/rook/rook/blob/1d3f99bc1455520cb1300600abb8b789f4d71a64/pkg/apis/go.mod#L3

**Comment by travisn** [comment]
> ops seems we need to update these golang version too

good catch. I thought I had updated those, but I must have reverted them unintentionally when I was experimenting

**Review by subhamkrai — APPROVED** [review]

**Comment by travisn** [comment]
> Thanks for the PR,
> 
> one question, what error you saw when upgrading the vault to 1.13.3?
> 
> ```
> Error: ../../../go/pkg/mod/github.com/hashicorp/vault@v1.13.3/audit/format.go:148:22: p.NamespacePath undefined (type logical.PolicyInfo has no field or method NamespacePath)
> ```
> 
> these one?

Yes, those were the errors. I found that if I updated `github.com/hashicorp/vault/sdk` to a later version this issue was fixed, but then another error was hit. I couldn't find the combination of vault dependencies that worked on the latest vault, whether v1.13.4 or v1.14.0.

**Pull request merged**
