### PR TITLE
ceph: replace setting controller reference with utility function

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
**Description of your changes:**

Some settinc controller reference code can be replaced with `controllerutil.SetControllerReference`. It's better to use it since it provides ownerReference verification.

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by satoru-takeuchi** [comment]
I'd like to replace all code of setting ownerReference with utility functions (controllerutil.Set{Owner,Controller}Reference). Once I tried it in the following PR. However, I gave up to merge it because that PR is too big.

https://github.com/rook/rook/pull/6711

I decided to split #6711 to multiple PRs and try to merge them one by one. This PR is the first one.

**Review by travisn — APPROVED** [review]
This is great to clean up, thanks. The changes look good to me. It will be good to get all these owner references updated in master soon so it can have bake time before the v1.6 release.

The other PR was just too big to test all at the same time? I overlooked it since it was still marked as a draft. I would have thought it might be easier to test as a single big change, instead of testing many smaller changes, but either way is ok with me.

**Comment by satoru-takeuchi** [comment]
I concerned that that PR is too big (over 2000 lines), isn't mechanical code replacing, and is hard to track upstream if the review process take a long time.

Anyway I'll send a first PR by which reviewers can understand the idea how I will try to replace ownerReferences. I'd like to come to an agreement whether this idea make sense.

**Comment by travisn** [comment]
Sounds good, it was certainly nice to have a smaller PR to start with for the concept. :) Feel free to merge this one.

**Pull request merged**
