### PR TITLE
ci: helm integration test is failing on pre-k8s-1.16

### LINKED ISSUE #6755: Helm integration test is failing on pre-k8s-1.16 due to invalid schema
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The helm integration test has been failing since [build 2395](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/2395/pipeline/). As seen in that [test log](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/master/runs/2395/nodes/61/steps/114/log/?start=0):
```
2020-11-18 11:49:51.965350 I | testutil: Running kubectl [create -f -]
The CephCluster "test-cluster" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"ceph.rook.io/v1", "kind":"CephCluster", "metadata":map[string]interface {}{"creationTimestamp":"2020-11-18T11:49:52Z", "generation":1, "name":"test-cluster", "namespace":"helm-ns", "uid":"c5eb4bdc-f11c-46dd-92ff-71ac1182fdbc"}, "spec":map[string]interface {}{"cephVersion":map[string]interface {}{"allowUnsupported":false, "image":"ceph/ceph:v14.2.12"}, "dashboard":map[string]interface {}{"enabled":true}, "dataDirHostPath":"/home/ubuntu/workspace/rook_rook_master/rook-test/helm-ns/test-129268764", "healthCheck":map[string]interface {}{"daemonHealth":map[string]interface {}{"mon":map[string]interface {}{"interval":"10s", "timeout":"15s"}, "osd":map[string]interface {}{"interval":"10s"}, "status":map[string]interface {}{"interval":"5s"}}}, "metadataDevice":interface {}(nil), "mgr":map[string]interface {}{"modules":[]interface {}{map[string]interface {}{"enabled":true, "name":"pg_autoscaler"}, map[string]interface {}{"enabled":true, "name":"rook"}}}, "mon":map[string]interface {}{"allowMultiplePerNode":true, "count":1}, "network":map[string]interface {}{"hostNetwork":false}, "skipUpgradeChecks":true, "storage":map[string]interface {}{"config":map[string]interface {}{"databaseSizeMB":"1024", "journalSizeMB":"1024", "storeType":"bluestore"}, "deviceFilter":interface {}(nil), "useAllDevices":true, "useAllNodes":true}}}: validation failure list:
spec.storage.deviceFilter in body must be of type string: "null"

...

--- FAIL: TestCephHelmSuite (123.84s)
    ceph_installer.go:511: 
        	Error Trace:	ceph_installer.go:511
        	            				ceph_installer.go:495
        	            				ceph_base_deploy_test.go:188
        	            				ceph_base_deploy_test.go:178
        	            				ceph_base_deploy_test.go:161
        	            				ceph_helm_test.go:80
        	            				suite.go:102
        	            				ceph_helm_test.go:52
        	Error:      	Received unexpected error:
        	            	failed to get ceph cluster. cephclusters.ceph.rook.io "test-cluster" not found
        	Test:       	TestCephHelmSuite
    ceph_installer.go:541: 
        	Error Trace:	ceph_installer.go:541
        	            				ceph_installer.go:495
        	            				ceph_base_deploy_test.go:188
        	            				ceph_base_deploy_test.go:178
        	            				ceph_base_deploy_test.go:161
        	            				ceph_helm_test.go:80
        	            				suite.go:102
        	            				ceph_helm_test.go:52
        	Error:      	Received unexpected error:
        	            	failed to wait for clean up jobs to complete. timed out waiting for the condition
        	Test:       	TestCephHelmSuite
```

This looks related to the test method `getDeviceFilter()` in #6506. It is failing when a null value is not supported in the v1beta1.

This appears to only be a test issue.

**Expected behavior:**
Integration tests should pass on all k8s versions

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

### PR DESCRIPTION
**Pull request by subhamkrai**
**Description of your changes:**
testCephHelmSuite is failing in pre-k8s v1.16
due to invalid schema. v1beta1 doesn't support
the null value so returning quotes instead of an empty
string.

Signed-off-by: subhamkrai <srai@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #6755 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by travisn — APPROVED** [review]

**Comment by travisn** [comment]
Of course the test failed on a different intermittent issue...

**Comment by leseb** [comment]
> Of course the test failed on a different intermittent issue...

How come Jenkins ran? Did I miss something?

@subhamkrai @travisn ?

**Comment by subhamkrai** [comment]
> > Of course the test failed on a different intermittent issue...
> 
> How come Jenkins ran? Did I miss something?
> 
> @subhamkrai @travisn ?

@leseb  Jenkins will skip if the body contains `test ceph` or title contains `ceph` which is not the case here. That's why Jenkins ran if I'm not wrong.

**Comment by travisn** [comment]
This test was failing in master builds since master still runs all the k8s versions in jenkins

**Pull request merged**
