### PR TITLE
Adding support for ppc64le architecture

### PR DESCRIPTION
**Pull request by Pensu**
This PR adds support for ppc64le arch.

### CODE REVIEW

**Comment by galexrt** [comment]
@Pensu I haven't found official Ceph packages for the ppc64le arch (see https://download.ceph.com/).
Ceph has to offer official packages for the arch (on Debian/Ubuntu) to be able for Rook to support the arch/platform.

/cc @travisn

**Comment by Pensu** [comment]
Ubuntu has the packages available in artful and later repos: https://packages.ubuntu.com/search?arch=ppc64el&keywords=ceph-mon

**Comment by galexrt** [comment]
@Pensu Rook does not use the Ubuntu package repositories to install Ceph.
The official Ceph package repositories are used, see https://github.com/rook/rook/blob/master/images/rook/Dockerfile.base#L21.

**Comment by Pensu** [comment]
@galexrt Can we use Ubuntu repos for ppc64le? I can create a separate doclerfile for ppc64le and I am ready to provide any support that is required.

**Comment by bassam** [comment]
@Pensu if you'd like to see `ppc64le` builds I think we need to convince the ceph folks to add them upstream. The problem is not building them but testing them. I don't believe there are `ppc64le` machines in the ceph build lab nor in the rook build lab.

**Comment by galexrt** [comment]
@Pensu What is the current status of this PR with the Ceph folks?
Depending on the status, would you mind closing this PR for now and getting back later with either this PR or a new one, to add `ppc64le` support to Rook (Ceph operator).

**Comment by Pensu** [comment]
Closing the PR as the base image has moved to Ceph and the Ceph packages are not being compiled here anymore.

**Pull request closed without merging**
