### PR TITLE
docs: test rendering of console options on website

### PR DESCRIPTION
**Pull request by BlaineEXE**
Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
This is how my examples render on the Rook webpage.

Of note, code snippets within block quotes render in italics. I don't really love that, but it is possible to change the behavior by changing the website's CSS to force code formatting to normal text.
```html
/**
 * Code formatting
 */
pre,
code {
  @include relative-font-size(0.9375);
  border: 1px solid $grey-color-light;
  border-radius: 3px;
  background-color: #eef;
  font-style: normal;  <!--   <=== ADDED THIS   -->
}
```

Also, the `console` formatter doesn't seem to do much on the website. But it makes text blue on GitHub (see bottom).

image

```console
this is blue on github
```

**Comment by BlaineEXE** [comment]
After I change the CSS to not allow code blocks to be in italics, it looks like the below screenshot. I still kind of like Option 2. Option 3 isn't bad, and it does make it clear (possibly more clear) that the two blocks are related.

Options 4, 5, and 6 aren't bad, but we wouldn't be able to have multiline commands, so I think we should avoid those for practicality.

Options 7, 8, and 9 don't have any special behavior from the addition of `$`, `#`, or `>`, so I think we should avoid these as we have been planning. 

image

**Comment by travisn** [comment]
Nice to see it rendered, thanks. Option 2 does look best to me as well, where option 7 still seems valid for code blocks where we don't expect the command to be copied because it has something specific such as a pod name. But going with option 2 everywhere seems reasonable as well.

**Comment by BlaineEXE** [comment]
As a note, the PR in the rook.github.io repo (https://github.com/rook/rook.github.io/pull/106) to render code blocks inside of block quotes as non-italic has already been merged.

**Comment by BlaineEXE** [comment]
Closing this because we do not want to merge it.

**Pull request closed without merging**
