### PR TITLE
Include vendor pkgs in the repository

### LINKED ISSUE #1478: Including vendor pkgs
Is this a bug report or feature request?
* Bug Report

Include vendor repos 

**Bug Report**

What happened:
Currently vendor repos are not committed or tracked, but in event that repos disappears, there will be troubles. This is best seen in https://github.com/jteeuwen/go-bindata/issues/5

What you expected to happen:
All vendor pkgs need to be part of the repo

### PR DESCRIPTION
**Pull request by galexrt**
**Description of your changes:**
This adds the `vendor/` directory to the repository.
I have split it into two commits. One removes the gitignore entry and the second adds the `vendor/` directory.

**Which issue is resolved by this Pull Request:**
Resolves #1478.

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [x] `make vendor` does not cause changes.
- [x] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by galexrt** [comment]
@bassam If a repository we use (Go) code from is deleted, a new user (without the dependencies already downloaded) can't build the code.
It is to prevent such "incidents" as with the most popular example go-bindata which was deleted at some point (thankfully for projects using it, restored (at least in read-only mode)).

Additionally it can potentially reduce build (/CI) times a bit because it "only" needs to download the repository with "everything" in it and not clone the repo and then download the dependencies.

**Comment by bassam** [comment]
This is a trade off.

If we commit the vendor directory and a package is deleted upstream we have a copy of it. I’d argue in this case we also have local copies on our laptops too and could resurrect it. Also we likely would need to find an alternative quickly since it’s no longer maintained. If this is a real concern we could snapshot the vendor directory as part of master builds and store in a bucket.

Build time Is about the same as we can safely cache the vendor directory with a hash of the Gopkg.toml and Gopkg.lock. It’s not been an issue at this time as the bulk of the time is in integrations tests.

My concern is that If we commit the vendor directory we are going to complicate the PR workflow. We will have large commits and would need to ask contributors to split the vendor commits for readability.

I’d argue that streamlining the PR workflow outweighs the risk of a removed package upstream.

Interested to hear what others think.

**Comment by travisn** [comment]
@bassam Agreed that the PR workflow should be kept simple. Another question to consider is what happens if an older release branch gets hit by a repo disappearing. I believe we would be ok in this case if we make sure to backport a fix if it is due to a disappearing repo.

**Comment by bassam** [comment]
yeah building older branches increases the window of risk of a repo disappearing. If we felt that is a high enough risk we can gzip the vendor directory and store in the _outputs of each build, or maybe release builds.

**Comment by jbw976** [comment]
I've never noticed this before in a PR review I've done, not sure what I did, that's odd:
> jbw976 requested changes on behalf of rook/maintainers just now

**Comment by galexrt** [comment]
@travisn what is your stand on this?

**Comment by galexrt** [comment]
Thanks for all the responses!

Closing as we see the risk as low.

**Pull request closed without merging**
