### PR TITLE
Workaround of build failure with centos image

### LINKED ISSUE #1932: arm64 image build failure
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The PR #1887 seems doesn't work on both my amd64 and arm64 server. With the latest code,
On amd64, when I run the `make build.all`, the command will fail with error message like this:
```
Sending build context to Docker daemon  44.23MB
Step 1/9 : FROM ceph/daemon-base:v3.0.5-stable-3.0-luminous-centos-7-x86_64
v3.0.5-stable-3.0-luminous-centos-7-x86_64: Pulling from ceph/daemon-base
469cfcc7a4b3: Already exists 
4baa8ceaca2f: Pull complete 
Digest: sha256:7aac6c3b40b481ce7dfa839f7f556f1f3273b79b65d0a60a770833984af71bec
Status: Downloaded newer image for ceph/daemon-base:v3.0.5-stable-3.0-luminous-centos-7-x86_64
 ---> 6b72e10eb2d6
Step 2/9 : RUN yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*
 ---> Running in 2c662beb0c56
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container: (28, 'Resolving timed out after 30541 milliseconds')
The command '/bin/sh -c yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 1
Makefile:37: recipe for target 'do.build' failed
make[2]: *** [do.build] Error 1
Makefile:30: recipe for target 'ceph.linux_amd64' failed
make[1]: *** [ceph.linux_amd64] Error 2
Makefile:121: recipe for target 'build.all' failed
make: *** [build.all] Error 2
```

On arm64, when I run `make build`, the error message is similar:
```
Step 1/9 : FROM ceph/daemon-base:v3.0.5-stable-3.0-luminous-centos-7-aarch64
v3.0.5-stable-3.0-luminous-centos-7-aarch64: Pulling from ceph/daemon-base
1e9dd4c85ba2: Already exists 
9bfff0e3febd: Already exists 
Digest: sha256:a05d036e87654ae7d27d447969d1d9beeadab6d63b52689742fccb42bc572e16
Status: Downloaded newer image for ceph/daemon-base:v3.0.5-stable-3.0-luminous-centos-7-aarch64
 ---> bc2951f1d7a9
Step 2/9 : RUN yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*
 ---> Running in 966c66e645f8
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot retrieve metalink for repository: epel/aarch64. Please verify its path and try again
The command '/bin/sh -c yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 1
Makefile:37: recipe for target 'do.build' failed
make[2]: *** [do.build] Error 1
Makefile:30: recipe for target 'ceph.linux_arm64' failed
make[1]: *** [ceph.linux_arm64] Error 2
Makefile:110: recipe for target 'build' failed
make: *** [build] Error 2
```
**Expected behavior:**
`make build.all` on amd64 and `make build` on arm64 should succeed.
**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

* Kernel (e.g. `uname -a`):
```
Linux huawei-d05 4.15.2 #1 SMP Mon Jul 23 14:41:48 CST 2018 aarch64 aarch64 aarch64 GNU/Linux
```
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

### PR DESCRIPTION
**Pull request by arm64b**
This PR is a workaround to fix the build issue based on ceph centos docker image

Signed-off-by: Dennis Chen <dennis.chen@arm.com>
Signed-off-by: Bin Lu <Bin.Lu@arm.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #1932 

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] `make vendor` does not cause changes.

### CODE REVIEW

**Comment by arm64b** [comment]
> Isn't this an issue with the Ceph Docker image not setting the right arch for arm64 in the repos?

The build error also happens on amd64 platform...

**Comment by galexrt** [comment]
@arm64b But does `amd64` building only fail on `arm64`?
On my Linux `amd64` machine a `make build.all` for Rook on latest `master` I don't issues even re-run the command with all images deleted:
```
$make build.all
=== helm package rook-ceph
==> Linting /home/atrost/Projects/workspace/go/src/github.com/rook/rook/cluster/charts/rook-ceph
Lint OK

1 chart(s) linted, no failures
Successfully packaged chart and saved it to: /home/atrost/Projects/workspace/go/src/github.com/rook/rook/_output/charts/rook-ceph-v0.8.0-15.g986e930f.tgz
=== helm index
=== go vet
=== go build darwin_amd64
=== go build windows_amd64
=== go build linux_amd64
=== go build linux_arm64
=== docker build build-da9b3fc0/ceph-amd64
sha256:98af915badeffb5fad88759c5af5ec94e3961d579f95d19911594309e91ad94f
=== saving image build-da9b3fc0/ceph-amd64
=== docker build build-da9b3fc0/ceph-toolbox-base-amd64
sha256:8c15d2d3446b5cca656aff60e483bc8555bbbc403cdfaa4a69b3ed188af4fc8c
=== docker build build-da9b3fc0/ceph-toolbox-amd64
sha256:487642261a45f919ce3d057db8e6e07dbe36dc58812c2a2299c97ea6dd6b64ff
=== caching image build-da9b3fc0/ceph-toolbox-base-amd64
=== docker build build-da9b3fc0/cockroachdb-amd64
sha256:7fc4d80f7d4f2fa6f45a6c518dd6f47bf5b5361255c9f496378ba22db953bfae
=== saving image build-da9b3fc0/cockroachdb-amd64
=== docker build build-da9b3fc0/minio-amd64
sha256:5b73e59734b49f24c51ac3fc66feddbfe0b1cf74094e424ed0b72c5d36609771
=== saving image build-da9b3fc0/minio-amd64
=== docker build build-da9b3fc0/ceph-arm64
sha256:ef682ee7a6409ccdfde53cd14b5609e3b79b7f190d26d712ba87f574b70663b3
=== saving image build-da9b3fc0/ceph-arm64
=== docker build build-da9b3fc0/ceph-toolbox-base-arm64
sha256:babebaf0763d100aed4c39b1b9ea0411d55388995a94c0bdc1d85bcb43eeab6d
=== docker build build-da9b3fc0/ceph-toolbox-arm64
sha256:700f66e0669ae831e5f9ffc0c0a786afd237d96ed4b166287255f785b056aa6b
=== saving image build-da9b3fc0/ceph-toolbox-arm64
=== caching image build-da9b3fc0/ceph-toolbox-base-arm64
=== docker build build-da9b3fc0/cockroachdb-arm64
sha256:27c81faf9b7074f161f12cacbdf9151fce7699e44a7d06d2d43b02408d92539d
=== saving image build-da9b3fc0/cockroachdb-arm64
=== docker build build-da9b3fc0/minio-arm64
sha256:e196bc7fb7008f83b1852dc780091d011b826550626a8d36ef5084ab6ab32f5a
=== saving image build-da9b3fc0/minio-arm64
```

**Comment by arm64b** [comment]
@galexrt In my environment, pull the latest code and `make distclean` first, `make build.all` will fail on `amd64` like this:
```
=== docker build build-c76ef25e/ceph-amd64
Sending build context to Docker daemon  44.23MB
Step 1/9 : FROM ceph/daemon-base:v3.0.7-stable-3.0-luminous-centos-7-x86_64
v3.0.7-stable-3.0-luminous-centos-7-x86_64: Pulling from ceph/daemon-base
7dc0dca2b151: Pull complete 
e9d4f4fdcbe2: Pull complete 
Digest: sha256:ed8a1050b4cc219ab483c42dd3bc2ce64d4046e485ddee0aabd5c02137f207ab
Status: Downloaded newer image for ceph/daemon-base:v3.0.7-stable-3.0-luminous-centos-7-x86_64
 ---> e87bce063197
Step 2/9 : RUN yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*
 ---> Running in 613f89b9298d
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container: (28, 'Resolving timed out after 30541 milliseconds')
The command '/bin/sh -c yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 1
Makefile:37: recipe for target 'do.build' failed
make[2]: *** [do.build] Error 1
Makefile:30: recipe for target 'ceph.linux_amd64' failed
make[1]: *** [ceph.linux_amd64] Error 2
Makefile:121: recipe for target 'build.all' failed
make: *** [build.all] Error 2
```

`make build` will fail on `arm64` with similar error message 🦀

**Comment by galexrt** [comment]
@arm64b I don't run into these build issues on my amd64 Linux machine..
```
make build.all
=== installing helm
Creating /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm 
Creating /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm/repository 
Creating /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm/repository/cache 
Creating /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm/repository/local 
Creating /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm/plugins 
Creating /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm/starters 
Creating /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm/cache/archive 
Creating /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm/repository/repositories.yaml 
$HELM_HOME has been configured at /home/atrost/Projects/workspace/go/src/github.com/rook/rook/.cache/helm.
Not installing tiller due to 'client-only' flag having been set
Happy Helming!
=== helm package rook-ceph
==> Linting /home/atrost/Projects/workspace/go/src/github.com/rook/rook/cluster/charts/rook-ceph
Lint OK

1 chart(s) linted, no failures
Successfully packaged chart and saved it to: /home/atrost/Projects/workspace/go/src/github.com/rook/rook/_output/charts/rook-ceph-v0.8.0-21.gadd4bd2f.tgz
=== helm index
=== installing dep
=== updating vendor dependencies
dep: WARNING: branch, version, revision, or source should be provided for "github.com/aws/aws-sdk-go"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/coreos/pkg"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/ghodss/yaml"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/go-ini/ini"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/go-sql-driver/mysql"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/google/uuid"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/gorilla/mux"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/icrowley/fake"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/jbw976/go-ps"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/prometheus/client_golang"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/spf13/cobra"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/spf13/pflag"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/stretchr/testify"
dep: WARNING: branch, version, revision, or source should be provided for "k8s.io/utils"
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  github.com/gorilla/mux
  ✗  github.com/prometheus/client_golang
  ✗  k8s.io/apiserver
  ✗  k8s.io/utils

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies,

=== go vet
=== go build darwin_amd64
github.com/rook/rook/pkg/operator/k8sutil
github.com/rook/rook/pkg/operator/ceph/agent
github.com/rook/rook/pkg/operator/ceph/cluster/mon
github.com/rook/rook/pkg/operator/ceph/cluster/osd/config
github.com/rook/rook/pkg/daemon/discover
github.com/rook/rook/pkg/operator/discover
github.com/rook/rook/pkg/operator/ceph/cluster/mgr
github.com/rook/rook/pkg/operator/ceph/file
github.com/rook/rook/pkg/operator/ceph/object
github.com/rook/rook/pkg/operator/ceph/cluster/osd
github.com/rook/rook/pkg/operator/ceph/cluster
github.com/rook/rook/pkg/daemon/ceph/agent/flexvolume
=== go build windows_amd64
github.com/rook/rook/pkg/operator/k8sutil
github.com/rook/rook/pkg/operator/ceph/agent
github.com/rook/rook/pkg/operator/ceph/cluster/mon
github.com/rook/rook/pkg/operator/ceph/cluster/osd/config
github.com/rook/rook/pkg/daemon/discover
github.com/rook/rook/pkg/operator/discover
github.com/rook/rook/pkg/operator/ceph/cluster/mgr
github.com/rook/rook/pkg/operator/ceph/file
github.com/rook/rook/pkg/operator/ceph/object
github.com/rook/rook/pkg/operator/ceph/cluster/osd
github.com/rook/rook/pkg/operator/ceph/cluster
github.com/rook/rook/pkg/daemon/ceph/agent/flexvolume
=== go build linux_amd64
github.com/rook/rook/pkg/daemon/ceph/agent/flexvolume
=== go build linux_arm64
github.com/rook/rook/pkg/operator/k8sutil
github.com/rook/rook/pkg/operator/ceph/agent
github.com/rook/rook/pkg/operator/ceph/cluster/osd/config
github.com/rook/rook/pkg/operator/ceph/cluster/mon
github.com/rook/rook/pkg/daemon/discover
github.com/rook/rook/pkg/operator/cockroachdb
github.com/rook/rook/pkg/operator/discover
github.com/rook/rook/pkg/operator/minio
github.com/rook/rook/pkg/operator/ceph/cluster/mgr
github.com/rook/rook/pkg/operator/ceph/file
github.com/rook/rook/pkg/operator/ceph/object
github.com/rook/rook/pkg/operator/ceph/cluster/osd
github.com/rook/rook/pkg/daemon/ceph/agent/flexvolume/manager/ceph
github.com/rook/rook/cmd/rook/cockroachdb
github.com/rook/rook/cmd/rook/minio
github.com/rook/rook/pkg/daemon/ceph/osd
github.com/rook/rook/pkg/operator/ceph/cluster
github.com/rook/rook/pkg/daemon/ceph/agent/flexvolume
github.com/rook/rook/pkg/daemon/ceph/agent/cluster
github.com/rook/rook/pkg/operator/ceph/provisioner
github.com/rook/rook/pkg/operator/ceph
github.com/rook/rook/cmd/rook/ceph
github.com/rook/rook/cmd/rook
=== docker build build-da9b3fc0/ceph-amd64
sha256:d1a1be13fdee06a46a3265e2ca584cea596e66b3d06d04444a1f8d7c3161b88c
=== saving image build-da9b3fc0/ceph-amd64
=== docker build build-da9b3fc0/ceph-toolbox-base-amd64
sha256:eb2c701013cdf88ce949eb6562bdeed02eeef3a7b042b684e5a600ddaf0839ea
=== docker build build-da9b3fc0/ceph-toolbox-amd64
sha256:ece75342df06e55bf1199276049be6d849632226992b639c6772848226fdceb2
=== saving image build-da9b3fc0/ceph-toolbox-amd64
=== caching image build-da9b3fc0/ceph-toolbox-base-amd64
=== docker build build-da9b3fc0/cockroachdb-amd64
sha256:36273ed2007c572f4707e01afbb3c2496b6da50fb4d24965daf9a072d96e4bad
=== saving image build-da9b3fc0/cockroachdb-amd64
=== docker build build-da9b3fc0/minio-amd64
sha256:368507cbc57d430de8c29ad7af085c0ce89b5f8749e251e52fe7d8360e942057
=== saving image build-da9b3fc0/minio-amd64
=== docker build build-da9b3fc0/ceph-arm64
sha256:6daea6f14bc5b25c692ae16c294de3c2827b25d2630bc05cae5243a895d4ad8f
=== saving image build-da9b3fc0/ceph-arm64
=== docker build build-da9b3fc0/ceph-toolbox-base-arm64
sha256:8793a2ccdf3fe7e68dbb8eb0e5dbb1fcdb16cd5f8488be4d5e3cf4d161ad7621
=== docker build build-da9b3fc0/ceph-toolbox-arm64
sha256:f08746b3e84f7d2d836a9b1c9cfcab5aa111dd543e14011927f66dff6944adaa
=== saving image build-da9b3fc0/ceph-toolbox-arm64
=== caching image build-da9b3fc0/ceph-toolbox-base-arm64
=== docker build build-da9b3fc0/cockroachdb-arm64
sha256:a6260a56e0ab22a360843ef94378be2a4b0402a9c9c4b1375e1465d28d98c5e5
=== saving image build-da9b3fc0/cockroachdb-arm64
=== docker build build-da9b3fc0/minio-arm64
sha256:1561331ed8e77d9fe1df232e7e3a85db30a3cbf8e8bdb94e446daf66edc5a9cd
=== saving image build-da9b3fc0/minio-arm64
```
Have you installed/enabled the multi platform binfmt thing from here: https://github.com/rook/rook/blob/d898618dd98bbe7e4130eab06103cda5b0fa3bbf/INSTALL.md#building-for-other-platforms ?

**Comment by arm64b** [comment]
> Have you installed/enabled the multi platform binfmt thing from here: https://github.com/rook/rook/blob/d898618dd98bbe7e4130eab06103cda5b0fa3bbf/INSTALL.md#building-for-other-platforms ?

Yes, I've installed/enabled those multi platform binfmt, but the issue is still there. More interesting, when I run `make build` natively on `arm64` server (no multi-platform binfmt needed), the same build issue happens 😭

**Comment by galexrt** [comment]
@arm64b Are you sure that there is no proxy/firewall between Docker daemon/build and the "outside" that either cache/block anything?

I'll look into testing the build in general on an `ARM64-4GB` instance at Scaleway (as this is the "fastest" way for me to try the build on arm64).

**Comment by galexrt** [comment]
@arm64b I just ran `make build.all` on such as server and `make build` works but `make build.all` fails because of `cross platform image build only supported on amd64 host currently.  Stop.`. This is probably because of some qemu packages missing on that machine as I just installed go, dep, build essentials.
https://gist.github.com/galexrt/069a9fc6b736f49a01f6f01e5e069a83

**Comment by arm64b** [comment]
@galexrt , yes, `arm64` server doesn't support cross build now. I will try to build on other `arm64` servers today...

**Comment by jmolmo** [comment]
@arm64b @galexrt : I have found the same issue trying to build (not cross build). Any news?

Environment:
=================
A virtual machine (KVM):
CentOS Linux release 7.5.1804 (Core) 
Derived from Red Hat Enterprise Linux 7.5 (Source)

Installed Go version 1.10.3

Rook: Downloaded latest from master with:
go get github.com/rook/rook


# free -h
              total        used        free      shared  buff/cache   available
Mem:           7.6G        694M        897M         33M        6.1G        6.5G
Swap:            0B          0B          0B

Docker 
Server Version: 1.13.1

# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda4        19G  6.7G   12G  36% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G   34M  3.8G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/vda2      1014M  219M  796M  22% /boot
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/b4d53ee85400d852c6bff3260967afa212f9c4386e95f2342c7d25575429785e/merged
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/11848aed84f3ed41237fd4e20ebd003493471237884a9e8bfd53f743a7472d89/merged
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/bcf5b03d720bf2fd1d48e898c6a6f7f640fe17b1804aa09ba864915ea8a1d098/merged
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/724d233ae81b8a88522f3f01e62e6a18462539e8861d84d20c5698736877b03d/merged
shm              64M     0   64M   0% /var/lib/docker/containers/29174cc2df346d6e934fe7711fed2d559c0f0b78eaf8c4554454e26a74d49e76/shm
shm              64M     0   64M   0% /var/lib/docker/containers/fcedc7c224efe64c30a4aced7aad651177e3b1d4d8822510ffa0152fcda1dd29/shm
shm              64M     0   64M   0% /var/lib/docker/containers/51bd965c90a3c76f9fed3ccd6c9ba32b0ad79b6bf31bdd6a4e08da6c5f5f3b3e/shm
shm              64M     0   64M   0% /var/lib/docker/containers/b5363175969ace389166dcc25a45b707c794527c3f49af2b96d775bb0ca69c51/shm
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/020459e9caa9217da799c82cd8935ebfabac71cd7c035b6082a1b914ef7ef168/merged
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/61c5aa986691ab2aa88066da62fe29365e609c54df8bf8a9db68f49c8bd8853a/merged
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/277b2af09a8ba1e7bc126fd69011bf732cb0e30b17b3d779efa4641c2974da98/merged
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/65a7460eeb78ea3556f3aeaf1ac5bb1cb2780f09fcb16dd5dca4aa6910907183/merged
tmpfs           3.9G   12K  3.9G   1% /var/lib/kubelet/pods/4c34efa5-a12c-11e8-b244-5254003b9e1a/volumes/kubernetes.io~secret/kube-proxy-token-xmdmn
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/4defcda55720a28f45528f259702f6cbaa349de91001e09e8dd4e131eea59e70/merged
shm              64M     0   64M   0% /var/lib/docker/containers/ca298e053481323e975fa3b7819e936fb8b6196bfa1e522387684e4bf82d6723/shm
overlay          19G  6.7G   12G  36% /var/lib/docker/overlay2/bb31163f4b8c4b6f41ff78a2a44d3341670c592885c3defbe253e833123e1cdd/merged
tmpfs           783M     0  783M   0% /run/user/0



Error:
================================================================================


# make distclean
=== cleaning images for build-5dbc0e8c


# make build
=== installing helm
Creating /root/go/src/github.com/rook/rook/.cache/helm 
Creating /root/go/src/github.com/rook/rook/.cache/helm/repository 
...
=== go build linux_amd64
=== docker build build-5dbc0e8c/ceph-amd64
Sending build context to Docker daemon 44.24 MB
Step 1/9 : FROM ceph/daemon-base:v3.0.7-stable-3.0-luminous-centos-7-x86_64
 ---> e87bce063197
Step 2/9 : RUN yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*
 ---> Running in 4822ed943657

Loaded plugins: fastestmirror, ovl
Determining fastest mirrors

...

Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
The command '/bin/sh -c yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 1
make[2]: *** [do.build] Error 1
make[1]: *** [ceph.linux_amd64] Error 2
make: *** [build] Error 2

**Comment by galexrt** [comment]
@arm64b is this build issue still a problem?
Also looking at @jmolmo both you seem to have the problem that the container/Docker daemon is unable to resolve the `mirrorlist.centos.org` name for some reason.

Can you try different DNS servers to see if that fixes the issue(s)?

**Comment by arm64b** [comment]
@galexrt , yes this build issue is still there on `arm64` server. I will try to figure out if the DNS config can solve this problem when I am back office tomorrow.

**Comment by travisn** [comment]
@arm64b did you find a fix for your build environment? since this seems specific to your build, can we close this PR?

**Pull request closed without merging**
