### PR TITLE
build: Update node to 10.x in cross container

### PR DESCRIPTION
**Pull request by thephred**
Signed-off-by: Michael Goff <thephred@gmail.com>

### CODE REVIEW

**Comment by travisn** [comment]
This is the cause of the [master build failure](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/949/pipeline)?

**Comment by thephred** [comment]
Yes this is the build failure @travisn  .
I am not aware of another step to get this to work @jbw976 .

**Comment by jbw976** [comment]
@thephred can you tell if a new cross build container is getting built and used from the full console output in https://jenkins.rook.io/job/rook/job/rook/job/PR-2653/1/consoleFull?  I see `building the cross container (this could take minutes the first time)` printed out 3 times so far in that output, but I think that may be printed anytime `build/run` gets called.  Not sure if I see anything explicit that makes it obvious a new cross build container image is getting built and used.

**Comment by thephred** [comment]
@jbw976 I cannot tell from the output.

**Comment by thephred** [comment]
I believe the code is designed such that the cross build container is always built if needed.

**Pull request merged**
