### PR TITLE
ci: bump canary test on latest 1.26.0 k8s version

### PR DESCRIPTION
**Pull request by subhamkrai**
Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
we are waiting for the support of the latest k8s version from the action provider https://github.com/manusa/actions-setup-minikube/pull/76

**Comment by subhamkrai** [comment]
> > > 
> > 
> > 
> > okay thanks, I'll try above
> 
> Please, also note that I had to release [v2.7.2](https://github.com/manusa/actions-setup-minikube/releases/tag/v2.7.2) an hour ago to fix an incompatibility with crictl v1.26.0 which was released 2 hours ago 😅 Sorry for the inconvenience 🙏

great, will check that.

**Comment by travisn** [comment]
This will be superseded by #11436 so we can close this, right?

**Comment by subhamkrai** [comment]
> This will be superseded by #11436 so we can close this, right?

yes, let's close this

**Pull request closed without merging**
