### PR TITLE
ceph: pin volume replication to release-v0.1 branch

### PR DESCRIPTION
**Pull request by Madhu-1**
**Description of your changes:**

added volume replication operator release-v0.1 branch to the go.mod as we are doing enhancements to the volume replication CRDS. Once we have a release will change this to the release-v0.1 branch.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@leseb @travisn i did run  `make crds` and `make codegen` Looks like CI for crds-gen is failing? can you please tell me what am i missing here?

**Comment by subhamkrai** [comment]
@Madhu-1  I see there are other changes too in crds/resources.yaml?

**Comment by Madhu-1** [comment]
This was due to controller-gen version mismatch (i was using 0.3.0 and rook uses 0.4.0) do we have any check in Makefile to validate this?

**Comment by subhamkrai** [comment]
> This was due to controller-gen version mismatch (i was using 0.3.0 and rook uses 0.4.0) do we have any check in Makefile to validate this?

I don't see a check in Makefile and FYI, rook using specific commit ahead of 0.5 https://github.com/rook/rook/blob/d3c18d001b2f036b0a5ab2dd2780bb5761bf4793/Makefile#L23-L25

**Review by leseb — APPROVED** [review]

**Pull request merged**
