### PR TITLE
core: Fix some misspelled comments

### PR DESCRIPTION
**Pull request by yingshanghuangqiao**
fix some comments

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by obnoxxx — CHANGES_REQUESTED** [review]
Thanks for the PR, @yingshanghuangqiao  !

In general, this looks like a good small improvement to me.

There is a typo in the title and commit message though: "chore" should be "core".

**Review by obnoxxx — CHANGES_REQUESTED** [review]
One more request:

Since you have changed API files, some ci checks are failing. to fix this, please rund `make crds`and `make docs`, commit the resulting changes, and update the PR by force-pushing.

**Review by obnoxxx — APPROVED** [review]
Thanks for adjusting the commit!
This looks much better now.

There is still a failing ci check but I think it is an unrelated flake. @travisn  please check.

LGTM

**Review by travisn — APPROVED** [review]
> There is still a failing ci check but I think it is an unrelated flake. @travisn please check.

Yes it's a known CI issue, unrelated.

**Pull request merged**
