### PR TITLE
build: move to Go 1.19 as default version for building services

### LINKED ISSUE #11176: Build services with updated go version
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Build services with updated go version  

**What is use case behind this feature:**
Twistlock vulnerability scan show a lot of vulnerability in services container image and remedy is to build the services with updated go version or patch version

**Environment**:
In general, applicable to all K8S environment

### PR DESCRIPTION
**Pull request by Rajpratik71**
**Description of your changes:**

Go 1.18.5 and other Go 1.18 version patches provided many vulnerability fixes
but as go.mod doesn't support minor version i.e why moving to next go release

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #11176 

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by travisn** [comment]
@Rajpratik71 Shall we close this? We've confirmed the issues are not in rook, and #11223 will update s5cmd.

**Comment by Rajpratik71** [comment]
> @Rajpratik71 Shall we close this? We've confirmed the issues are not in rook, and #11223 will update s5cmd.

HI @travisn, when we are planning to move to "Go 1.19" for release builds?

**Comment by travisn** [comment]
> > @Rajpratik71 Shall we close this? We've confirmed the issues are not in rook, and #11223 will update s5cmd.
> 
> HI @travisn, when we are planning to move to "Go 1.19" for release builds?

It's convenient to support the last two versions of Go. We could actually go ahead with the changes to all the workflow files to build and release on 1.19, but keep support for 1.18 by reverting build.yml and other changes outside the workflows directory.

**Comment by travisn** [comment]
Looks like since you pushed the branch while closed, it's not letting me reopen it. Go ahead and open a new PR, thanks.

**Comment by Rajpratik71** [comment]
ok Sure.

Thanks @travisn

**Comment by Rajpratik71** [comment]
Opened #11427

**Pull request closed without merging**
