### PR TITLE
helm: remove resource limit

### PR DESCRIPTION
**Pull request by caffeinism**
Remove resource limits to avoid undesirable
deployments of merged values.yaml file.

**Description of your changes:**

It's not for everyone, but for someone unfamiliar with Helm and Kubernetes or Ceph, resources.limits in values.yaml can lead to bad deployments. For example, one person who is not familiar with Ceph wants to deploy Ceph using Rook. Since he doesn't know the exact OSD requirements, he wants to use values.yaml with resources.limits removed.
```
    osd:
      requests:
        cpu: "1000m"
        memory: "4Gi"
```
He happily did `helm install -f my-values.yaml`, but found that Ceph didn't perform well even though he had enough computing resources(But in fact, the worst thing is that you may not discover these truth). Because the settings are merged like this:
```
    osd:
      requests:
        cpu: "1000m"
        memory: "4Gi"
      limits:
        cpu: "2000m"
        memory: "4Gi"
```
The default values for resources.limits don't seem to be sufficient performance for many devices I think. Beginners can make mistakes, and experienced people can set the appropriate value anyway, so I think it's okay to delete it.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — CHANGES_REQUESTED** [review]
It is true that finding the appropriate defaults is difficult since not all clusters have similar characteristics. There was much debate on #9894 on the approach last year, and this was where we settled. 

It would be nice to have profiles and apply different defaults, such as the "large" or "small" cluster defaults, or "none", which would remove all requests and limits for a test environment. But based on past conversations, I think we'll need to keep some limits by default.

**Comment by caffeinism** [comment]
But it seems very difficult. Many factors such as size, type of storage device, CPU clock, etc. must be considered, and I think it is very difficult to set it as the default value. It's nice to have a default value, but I think it's not graceful in the process of merging.

One idea is that you should write down problems as comments (as noted in prepareosd). Specify a default value for limits, but you can point out problems without it. The profile approach seems to complicate the chart...

**Comment by travisn** [comment]
> One idea is that you should write down problems as comments (as noted in prepareosd). Specify a default value for limits, but you can point out problems without it. 

Can you explain this more? I'm not following.

> The profile approach seems to complicate the chart...

Yes, definitely would complicate the chart, just a possible idea going through my head.

**Comment by caffeinism** [comment]
I think I was a little sleepy when I was writing comment😅. I think it's a bad way to get rid of the default limit value altogether. But I thought I needed a guide of something for beginners. (Even a comment in the docs)

**Pull request closed without merging**
