### PR TITLE
CSI: update cephcsi to v2.1.0

### PR DESCRIPTION
**Pull request by Madhu-1**
**Description of your changes:**

cephcsi v2.1.0 is released and doesn't need any deployment template changes. This PR updates the cephcsi image version to v2.1.0

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves https://github.com/rook/rook/issues/4914

**Checklist:**

- [ ] **CommitLint Bot**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
[test ceph]
[test full]

### CODE REVIEW

**Comment by Madhu-1** [comment]
@travisn we have 2 new features in cephcsi. one is rbd static PV support and another one is topology-based rbd provisioning. will send a follow-up PR for that one

more info about v2.1.0 release is present here https://github.com/ceph/ceph-csi/releases/tag/v2.1.0

**Comment by Madhu-1** [comment]
> @Madhu-1 Can we resolve the arm issue [ceph/ceph-csi#671](https://github.com/ceph/ceph-csi/issues/671) before we merge this?

@travisn working on the Fix here https://github.com/ceph/ceph-csi/pull/866

**Comment by humblec** [comment]
@travisn the refrences PR is merged and also the `arm` image is available @ quay.io/cephcsi/cephcsi:v2.1.0-arm64

**Comment by Madhu-1** [comment]
more info on built image
```
docker run quay.io/cephcsi/cephcsi:v2.1.0-arm64 --version
Cephcsi Version: v2.1.0
Git Commit: bad06a1751ef64e8528bb08d6d97ebe8a429b4f8
Go Version: go1.13.8
Compiler: gc
Platform: linux/arm64
```

**Pull request merged**
