### PR TITLE
test: add additional object store, bucket, and peer test

### PR DESCRIPTION
**Pull request by vivekkoya**
An additional tests is added to check for a store belonging to a master zone with one objectstore user, one bucket, and one peer

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [X] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [X] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

Signed-off-by: Vivekanand Koya <<13vivekkoya@gmail.com>>

### CODE REVIEW

**Review by travisn — CHANGES_REQUESTED** [review]
Thanks for the additional unit test. Please just see the [commit structure](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure). Some suggestions:
1. Remove the filename from the commit prefix.
2. Briefly describe the test being added in the commit message such as: `test: add additional object store unit test`
3. Add the DCO signature

**Comment by vivekkoya** [comment]
I have incorporated the suggested changes into the commit. Please let me know if you need anything else.

**Comment by travisn** [comment]
> I have incorporated the suggested changes into the commit. Please let me know if you need anything else.

Thanks for the update, I was trying to make a couple of different points. To be clear, I'd suggest this commit message:
```
test: add an additional object store unit test

Test a store belonging to a master zone with one objectstore user, one bucket, and one peer

Name <email>
```

Also, you need to add the DCO signature (where I added the "Name <email>" example above). The [CI action](https://github.com/rook/rook/pull/13469/checks?check_run_id=19935978774) is failing because it is missing.

**Comment by travisn** [comment]
@vivekkoya Are you still available to update the commit message? Thanks!

**Comment by vivekkoya** [comment]
Yes, I am available.

**Pull request closed without merging**
