### PR TITLE
ceph: update cronjob from v1beta1 to v1

### LINKED ISSUE #7837: CronJob needs to be updated from v1beta1 to v1
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In K8s 1.21, the operator log shows the following warning:
```
W0505 23:52:56.480392       9 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

The crash collector cron job needs to be updated to v1 on K8s 1.21 and newer.

**Expected behavior:**
No warnings in the log about cron job v1beta1 being deprecated.

**How to reproduce it (minimal and precise):**

Install on K8s 1.21 and look at the operator log

### PR DESCRIPTION
**Pull request by subhamkrai**
**Description of your changes:**
this commit update cronjob from v1beta1 to v1

Signed-off-by: subhamkrai <srai@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #7837 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
`make IMAGES="ceph" build` showing this error...looking into this

```1 chart(s) linted, 0 chart(s) failed
Successfully packaged chart and saved it to: /home/srai/go/src/github.com/rook/rook/_output/charts/rook-ceph-v1.6.0-alpha.0.277.g081e2fd9c-dirty.tgz
=== helm index
=== ensuring modules are tidied
=== go vet
# sigs.k8s.io/controller-runtime/pkg/metrics
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/metrics/client_go_adapter.go:134:3: cannot use &latencyAdapter literal (type *latencyAdapter) as type metrics.LatencyMetric in field value:
	*latencyAdapter does not implement metrics.LatencyMetric (wrong type for Observe method)
		have Observe(string, url.URL, time.Duration)
		want Observe(context.Context, string, url.URL, time.Duration)
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/metrics/client_go_adapter.go:135:3: cannot use &resultAdapter literal (type *resultAdapter) as type metrics.ResultMetric in field value:
	*resultAdapter does not implement metrics.ResultMetric (wrong type for Increment method)
		have Increment(string, string, string)
		want Increment(context.Context, string, string, string)
make[1]: *** [build/makelib/golang.mk:156: go.vet] Error 2
make: *** [Makefile:111: build.common] Error 2
```

**Comment by leseb** [comment]
As discussed separately, we need the 0.9 release to get the 1.21 dependency bump.

**Comment by leseb** [comment]
You linked your PR in the field `Resolves` from your PR description.

**Comment by subhamkrai** [comment]
> You linked your PR in the field `Resolves` from your PR description.

updated :)

**Comment by leseb** [comment]
The integration test is likely going to fail now since v1 wasn't know I suppose.

**Comment by subhamkrai** [comment]
> The integration test is likely going to fail now since v1 wasn't know I suppose.

right, I'm looking to handle both by checking the k8s version.

**Comment by subhamkrai** [comment]
due to some reason, I have lost my git origin. I'll have to create new PRs for my existing open PRs. My apologies.
For this, I'll continue in #8114

**Pull request closed without merging**
