### PR TITLE
nfs: the number of containers displayed is wrong due to sidecar

### PR DESCRIPTION
**Pull request by huats**
**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[skip ci]

### CODE REVIEW

**Review by travisn — CHANGES_REQUESTED** [review]
@huats The change looks good. Please see the DCO details link to add a signature to the commit. Thanks!

**Comment by huats** [comment]
> @huats The change looks good. Please see the DCO details link to add a signature to the commit. Thanks!

Sorry for that. I had amended the commmit message to pass the lint test and I forgot to sign it again then...

**Review by BlaineEXE — CHANGES_REQUESTED** [review]
Commit subjects should identify what changes, not what is wrong.

E.g., `nfs: fix number of containers displayed in docs`

**Comment by huats** [comment]
> Commit subjects should identify what changes, not what is wrong.
> 
> E.g., `nfs: fix number of containers displayed in docs`

Changed the commit message

**Review by travisn — APPROVED** [review]

**Review by BlaineEXE — APPROVED** [review]

**Review by BlaineEXE — COMMENTED** [review]
Approved, but the commit message needs a sign-off.

**Comment by huats** [comment]
Sorry for the delay to do the signoff... Can someone point me what can I do to pass that check ? It seems to me that it is not on my side

**Comment by galexrt** [comment]
@huats Please rebase your branch on the latest `master` branch and then re-check what checks have failed.

The current failure is from Jenkins CI run which shows errors due to the branch being quite outdated. So rebasing on latest `master` to get an uptodate picture of the checks is needed.

**Comment by huats** [comment]
Thanks for the feedack.
I honnestly don't know what I can do now. I am only trying to push some minor modification of the doc for NFS and the test that is failing is about the integration suite for ceph upgrade...

**Comment by subhamkrai** [comment]
> Thanks for the feedack.
> I honnestly don't know what I can do now. I am only trying to push some minor modification of the doc for NFS and the test that is failing is about the integration suite for ceph upgrade...

Sometimes tests fails due to intermittent errors. Restarted the test.

**Comment by subhamkrai** [comment]
> Sometimes tests fails due to intermittent errors. Restarted the test.

It's green now👍

**Review by galexrt — APPROVED** [review]
LGTM

**Review by galexrt — CHANGES_REQUESTED** [review]
Woops, seems like the rebase went wrong and there are 3 commits now.

Can you check to "remove" the merge commit and / or squash them from / in your PR branch, for help feel free to join the Rook Slack.

**Review by galexrt — APPROVED** [review]

**Pull request merged**
