### PR TITLE
Specify rook-system as the namespace for Operator

### LINKED ISSUE #1608: Helm Operator docs do not specify namespace
The helm operator  installation documentation does not specify a namespace for the install.  Good practice with helm is to specify the namespace using the --namespace flag on the helm install command, and rook users typically use rook-system for this purpose.
It would be nice if the documentation included specifying the namespace on  the helm command lines.

### PR DESCRIPTION
**Pull request by brettjacobson**
Description of your changes:
Update the helm operator docs to specify rook-system as the namespace.

Which issue is resolved by this Pull Request:
Resolves #1608 

Checklist:
- [x] Documentation has been updated, if necessary.

[skip ci]

### CODE REVIEW

**Comment by brettjacobson** [comment]
Signed-off-by: Brett Jacobson <brett.jacobson42@gmail.com>

**Comment by brettjacobson** [comment]
Or do I need to resubmit the PR all over again with the signoff in the commit message?

**Comment by travisn** [comment]
@brettjacobson you just need to force push the commits to your fork and the PR will pick it up. Would you mind squashing your two commits as well?

**Comment by brettjacobson** [comment]
going to redo the PR

**Pull request closed without merging**
