### PR TITLE
Start toolbox pod with the ceph image and stop building the toolbox image

### PR DESCRIPTION
**Pull request by travisn**
Signed-off-by: travisn <tnielsen@redhat.com>

**Description of your changes:**
The toolbox is a convenience for running tools to troubleshoot the cluster. Since the inception of Rook, we have included a number of tools in the toolbox image that would make it that much easier to troubleshoot. However, the toolbox image with the extra tools is not something we need to ship. All the user needs is a place where they can run the ceph tools. If you want to troubleshoot a ceph cluster, you use the ceph tools that are built into the `rook/ceph` image. Today you can actually connect to the operator or a mon pod and run ceph commands as well. We just don't have a good reason to build and release a toolbox image that contains any more tools than are already in the ceph image. In the rare occasion a user needs non-ceph tools to troubleshoot the cluster, he can run some other container or even install them temporarily in the toolbox container.

This change includes:
- Stop building and publishing the `rook/ceph-toolbox` image
- Start the `rook/ceph` image in the toolbox pod

Documentation updates are still needed to update the documentation to show an alternate way to run tools such as `s3cmd` that were in the toolbox image.

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] `make vendor` does not cause changes.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by bassam** [comment]
this approach looks good to me. looks like the build is failing though.

**Comment by travisn** [comment]
Yes, i'm still investigating the missing link in the tests. I can't find what in this PR is causing the tar file to be missing. Removing the toolbox image should still allow the ceph tar to be generated. Did I miss something in the makefiles?
```
> tests/scripts/makeTestImages.sh load amd64
open ceph-amd64.tar: no such file or directory
```

**Comment by galexrt** [comment]
Only thing, adding a pending release note item in this (skipci) or another PR would be good for the release.

**Comment by travisn** [comment]
@galexrt did you see this new line in PendingReleaseNotes.md, or you're suggesting more info be added? 
```
- The toolbox manifest now creates a deployment based on the `rook/ceph` image instead of creating a pod on a specialized `rook/ceph-toolbox` image.
```

**Comment by galexrt** [comment]
@travisn Yes, adding a point to `Action Required` too would be good.
So that users know they should/have to change.

**Comment by travisn** [comment]
I'm thinking we should just have an action to "see the upgrade guide", which would have all the details for how to upgrade. As a separate PR I'd like to re-work the upgrade guide and update all of that then. Since some of the upgrade will be automated for 0.9 I've been delaying until closer to the release to document the upgrade when it is more clear how much automation we will have.

**Comment by galexrt** [comment]
@travisn Sounds good to me!

**Pull request merged**
