### PR TITLE
OSD: Support crypt type devices

### PR DESCRIPTION
**Pull request by dgonzalezruiz**
This PR adds compatibility to clusters using raw devices that are decrypted at boot time with dmcrypt.

### CODE REVIEW

**Comment by galexrt** [comment]
@dgonzalezruiz You need to sign-off your commits (`git commit -s`).
Also it seems that your `git` client has a "wrong" email set that isn't the same as your GitHub account (no avatar shown for the commits).

**Comment by liewegas** [comment]
This looks like a pretty trivial change, but what I think we really want to see is a move to using the new ceph-volume tool to manage these details so that rook isn't provisioning OSD devices in its own unique way.  (And so that eventually an existing OSD device can be migrated into a rook-managed environment.)

**Comment by jbw976** [comment]
agreed @liewegas, having consistent OSD provisioning with ceph-volume will be a great change.  That's being tracked with #1342

**Comment by dgonzalezruiz** [comment]
`Is this change generally applicable for all crypt devices? i.e. are there crypt devices that would need more work to be supported than the "easy" ones in your environment that are automatically unlocked at boot time?`

In my scenario there would be two crypt devices. The encrypted, raw device, which does not match at all nor has any kind of recognisable filesystem, and the mapped one. It is this mapped one (indexed under `/dev/` with tags like `dm-1`, `dm-2`... the one that does have a readable filesystem the one that would be used by rook. So, I don't see in this sense any kind of trickier crypt device that could be interpreted by rook as usable.

`This looks like a pretty trivial change, but what I think we really want to see is a move to using the new ceph-volume tool to manage these details so that rook isn't provisioning OSD devices in its own unique way. (And so that eventually an existing OSD device can be migrated into a rook-managed environment.)`

Haven't heard of it, but it would be awesome to abstract as much information in CEPH. In my case I just wanted this to be shipped in the next releases, since otherwise I am tied to use mount points (which seem to be decreasing performance and creating storage overhead).

**Comment by dgonzalezruiz** [comment]
@galexrt Should I do a sample signed commit to fix the issue or is it just for the posterity? I have no changes pending

**Comment by dgonzalezruiz** [comment]
@kokhang Let me know if this mets your requirements! I wasn't very sure of where to test it since there were similar types like SSDType which were not being unit tested; they were not being recognized as available disk types.

**Comment by galexrt** [comment]
One question I have is if `crypt` is the "only" other type of device we would want to add now or want to go for others if they are possible (use cases) for usage with Rook.

**Comment by dgonzalezruiz** [comment]
@galexrt I don't know of any other and I can't see any situation in which anyone had a similar request. This is kind of blocking me in the way of reaching a desired state in my rook cluster.

**Pull request merged**
