### PR TITLE
ci: fix an intermittent failure in uninstalling cluster.

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
**Description of your changes:**

Sometimes test suites of Ceph fail due to waiting for cleanup job in Rook uninstallation. In many cases, it doesn't mean this job's hangup. Otherwise, it comes from creating jobs takes a bit long time. Extending timeout resolves this problem.

Here is a log in failure.

```
...
2020-09-30 21:56:05.641957 D | exec: Running command: kubectl delete -n helm-ns cephcluster test-cluster --wait=false
2020-09-30 21:56:06.729630 I | installer: waiting for job(s) to cleanup the host...
2020-09-30 21:56:11.732103 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:16.731761 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:21.731816 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:26.731965 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:31.732026 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:36.732128 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:41.731997 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:46.732277 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:51.731917 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:56.731976 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:01.731952 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:06.732089 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:11.731916 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:16.731865 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:21.731984 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:26.732296 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:31.731969 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:36.732916 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:36.734590 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:36.734731 I | testutil: Running kubectl [delete -f -]
serviceaccount "rook-ceph-osd" deleted
serviceaccount "rook-ceph-mgr" deleted
serviceaccount "rook-ceph-cmd-reporter" deleted
role.rbac.authorization.k8s.io "rook-ceph-osd" deleted
role.rbac.authorization.k8s.io "rook-ceph-mgr" deleted
role.rbac.authorization.k8s.io "rook-ceph-cmd-reporter" deleted
rolebinding.rbac.authorization.k8s.io "rook-ceph-cluster-mgmt" deleted
rolebinding.rbac.authorization.k8s.io "rook-ceph-osd" deleted
rolebinding.rbac.authorization.k8s.io "rook-ceph-mgr" deleted
rolebinding.rbac.authorization.k8s.io "rook-ceph-cmd-reporter" deleted
rolebinding.rbac.authorization.k8s.io "rook-ceph-default-psp" deleted
rolebinding.rbac.authorization.k8s.io "rook-ceph-osd-psp" deleted
rolebinding.rbac.authorization.k8s.io "rook-ceph-mgr-psp" deleted
rolebinding.rbac.authorization.k8s.io "rook-ceph-cmd-reporter-psp" deleted
Error from server (NotFound): error when deleting "STDIN": clusterrolebindings.rbac.authorization.k8s.io "rook-ceph-osd-helm-ns" not found
Error from server (NotFound): error when deleting "STDIN": clusterrolebindings.rbac.authorization.k8s.io "rook-ceph-mgr-cluster-helm-ns" not found
Error from server (NotFound): error when deleting "STDIN": rolebindings.rbac.authorization.k8s.io "rook-ceph-mgr-system helm-ns" not found
2020-09-30 21:57:36.861635 E | utils: Failed to execute stdin: kubectl [delete -f -] : exit status 1
2020-09-30 21:57:36.861658 E | installer: failed to delete cluster roles.  "" not found
2020-09-30 21:57:38.920475 I | installer: removed finalizers from cluster test-cluster
2020-09-30 21:57:38.920494 I | testutil: custom resource helm-ns still exists
2020-09-30 21:57:40.935153 E | installer: failed to remove finalizer. failed to get cluster. cephclusters.ceph.rook.io "test-cluster" not found
2020-09-30 21:57:40.935173 I | testutil: custom resource helm-ns deleted
2020-09-30 21:57:40.935184 D | exec: Running command: kubectl delete namespace helm-ns --wait=false
2020-09-30 21:57:41.015036 D | exec: Running command: kubectl delete namespace helm-ns-system --wait=false
2020-09-30 21:57:41.106870 E | utils: Failed to execute: kubectl [delete namespace helm-ns-system --wait=false] : exit status 1. Error from server (NotFound): namespaces "helm-ns-system" not found
2020-09-30 21:57:41.106909 I | installer: removing the operator from namespace helm-ns-system
2020-09-30 21:57:41.106928 D | exec: Running command: kubectl delete crd cephclusters.ceph.rook.io cephblockpools.ceph.rook.io cephobjectstores.ceph.rook.io cephobjectstoreusers.ceph.rook.io cephobjectrealms.ceph.rook.io cephobjectzonegroups.ceph.rook.io cephobjectzones.ceph.rook.io cephfilesystems.ceph.rook.io cephnfses.ceph.rook.io ceph
clients.ceph.rook.io volumes.rook.io objectbuckets.objectbucket.io objectbucketclaims.objectbucket.io cephrbdmirrors.ceph.rook.io
2020-09-30 21:57:42.997439 D | exec: Running command: /tmp/rook-tests-scripts-helm/linux-amd64/helm delete --purge rook-ceph
2020-09-30 21:57:46.435176 I | installer: done removing the operator from namespace helm-ns-system
2020-09-30 21:57:46.435199 I | installer: removing host data dir /home/ubuntu/workspace/rook_rook_PR-6184/rook-test
2020-09-30 21:57:46.437019 I | testutil: Running kubectl [create -f -]
job.batch/rook-verify-cleanup-8ac78269-0e9d-4d33-93d0-b2bda731b373 created
2020-09-30 21:57:47.282245 I | installer: verifying clean up of /home/ubuntu/workspace/rook_rook_PR-6184/rook-test from node ip-172-31-46-223. err=<nil>
2020-09-30 21:57:47.286042 I | installer: system namespace "helm-ns-system" removed
--- FAIL: TestCephHelmSuite (411.12s)
    ceph_installer.go:568:
                Error Trace:    ceph_installer.go:568
                                                        ceph_installer.go:522
                                                        ceph_base_deploy_test.go:188
                                                        ceph_base_deploy_test.go:178
                                                        ceph_base_deploy_test.go:161
                                                        ceph_helm_test.go:80
                                                        suite.go:102
                                                        ceph_helm_test.go:52
                Error:          Received unexpected error:
                                failed to wait for clean up jobs to complete. timed out waiting for the condition
                Test:           TestCephHelmSuite
```

Related issue: 6358

**Which issue is resolved by this Pull Request:**

Nothing

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test ceph]

### CODE REVIEW

**Comment by satoru-takeuchi** [comment]
I'll request a reviewe once I confirmed this problem didn't happen in three full tests.

**Comment by satoru-takeuchi** [comment]
> I'll request a review once I confirmed this problem didn't happen in three full tests.

Done. So this PR is ready to merge after passing normal Ceph CI.

**Review by leseb — APPROVED** [review]
So again, waiting longer seems to do the trick... Thanks

**Review by travisn — COMMENTED** [review]
I'd like to understand the delay, 90 seconds is already a long time to wait for the cleanup. Were you able to find operator logs or logs from the cleanup jobs to see why they took so long?

**Comment by satoru-takeuchi** [comment]
I saw both logs, however, I couldn't find any suspicious jobs. So I decided to extent the timeout.

**Comment by satoru-takeuchi** [comment]
@travisn 

> Were you able to find operator logs or logs from the cleanup jobs to see why they took so long?

Oops, I told a lie. Although I checked all logs in artifacts of the following CI, there are no logs from the cleanup jobs.

https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6184/30/pipeline/

This problem happened not due to cleanup job itself. Otherwise, it's because that the creating cleanup job was not finished before timeout.

```
2020-09-30 21:56:06.729630 I | installer: waiting for job(s) to cleanup the host...
2020-09-30 21:56:11.732103 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:16.731761 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:21.731816 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:26.731965 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:31.732026 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:36.732128 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:41.731997 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:46.732277 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:51.731917 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:56:56.731976 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:01.731952 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:06.732089 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:11.731916 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:16.731865 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:21.731984 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:26.732296 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:31.731969 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:36.732916 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:36.734590 I | installer: no jobs with label selector "app=rook-ceph-cleanup" found.
2020-09-30 21:57:36.734731 I | testutil: Running kubectl [delete -f -]
```

So I guess it's not Rook's problem and it may be caused by lack of CPU resource or something. However, I have no proof. Please let me know if you have any good ideas on how to investigate this issue more.

**Comment by satoru-takeuchi** [comment]
@travisn 

Here is the last time when the full test passed.

https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/2213/pipeline/59

After that, all v1.16.x test failed due to this problem. It always happened in CephHelmSuite and sometimes happened in CephFlexSuite. Interestingly, this problem has never happened in all other versions.

As far as I know, the changes between the last success and the first failure are as follows.

- K8s version is changed from v1.16.8 to v1.16.13
- VM image is changed
- The device name is changed from xvdX to nvmeXn1

I briefly took a look at all commits between v1.16.8 and v1.16.15, However, I couldn't find any commits that seem to be related to this problem. So I don't know how these changes give rise to this problem yet.

I consider it's better to bypass this problem for now because of the following reasons.

- This problem disappears if the timeout is extended. 
- There is no odd logs when this problem happens and when extending the timeout.
- The full test can't pass wIthout fixing this problem at all.

I'd like to know your opinion. Of course, it's OK to dig into this problem if you wait.

**Comment by satoru-takeuchi** [comment]
I found this problem would come from a CSR-related problem written in #6415 and this PR is insufficient. Close this.

**Pull request closed without merging**
