### PR TITLE
core: compare ceph version with IsExactly instead of DeepEqual

### LINKED ISSUE #10688: external cluster - waiting for ceph monitors upgrade to finish. (Compare CommitID)
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Ceph-object-controller is not able to create ObjectStore. Instead it is stuck with the follwing error message:
```
ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph-external/my-store". waiting for ceph monitors upgrade to finish. current version: 16.2.9-0 pacific. expected version: 16.2.9-0 pacific. will reconcile again in 1m0s
```

Maybe same issue #9544

**Expected behavior:**
Ceph-object-controller should successfully create ObjectStore.

**How to reproduce it (minimal and precise):**

Same #9544

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): Ubuntu 20.04 LTS
* Cloud provider or hardware configuration: On-premise
* Rook version (use `rook version` inside of a Rook Pod): 1.9.8
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.9
* Kubernetes version (use `kubectl version`): v1.20.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On-premise
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

---

Maybe related code : 
https://github.com/rook/rook/blob/v1.9.8/pkg/operator/ceph/object/controller.go#L327

---

Probably because of DeepEquals. I'm using Proxmox and this is a different build commit. It seems that DeepEquals compares up to CommitID.

### PR DESCRIPTION
**Pull request by jclab-joseph**
**Description of your changes:**

compare ceph version with IsExactly instead of DeepEqual

**Which issue is resolved by this Pull Request:**
Resolves #10688

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.

### CODE REVIEW

**Review by subhamkrai — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by satoru-takeuchi** [comment]
Shouldn't we treat external clusters as special cases than converting `DeepEqual()` to `IsExactly()`? I suspect that non-external cluster users might suffer from this change. Let's assume that their Ceph cluster is upgrading from v16.2.10 to the custom Ceph (v16.2.10 + their own patch). If I understand correctly,  Rook with this PR doesn't detect this upgrade because the major, minor, and extra versions are the same between the original version and the desired version.

**Comment by jclab-joseph** [comment]
@satoru-takeuchi So how about comparing up to Build , but not CommitID?

**Comment by satoru-takeuchi** [comment]
@jclab-joseph I want to keep the current behavior as is for non-external clusters. Actually, I am one of the users using my own Ceph container, and I don't use the build version. @travisn Any though?

**Review by travisn — CHANGES_REQUESTED** [review]
Wait, I think the fundamental issue is a bit different... The purpose of this version check is that if the local cluster is upgrading, the object controller should wait for that upgrade to complete for any type of upgrade including if the hash of the image changed. 

But in this scenario, the cluster is external and the object store is being configured with rgw in the local cluster, right? This scenario of running the rgw locally even while the cluster is external hasn't ever felt right to me even though it is possible. The preferred approach IMO is to connect to RGW in the external cluster, as seen in the [object-external.yaml](https://github.com/rook/rook/blob/master/deploy/examples/object-external.yaml) example.

If a fix is needed, we would need this version upgrade check to be skipped completely in the external cluster scenario, and allow the object store always to reconcile.

**Comment by jclab-joseph** [comment]
Suddenly, I have a question.
Even if the Build of ceph is changed, the docker image tag of cephVersion.image is the same as only up to Extra . (unless set to hash)
https://github.com/rook/rook/blob/3d18e780fbe6bb0c814349591552885898c7ffb3/pkg/operator/ceph/cluster/mgr/spec.go#L162
However, as above, if ImagePullPolicy is not Always, the image will not be received again.
In this case, when the version of CephCluster is updated, the Docker image may not be pulled again.
Isn't there a possibility of deadlock in these cases?

**Comment by BlaineEXE** [comment]
> Suddenly, I have a question. Even if the Build of ceph is changed, the docker image tag of cephVersion.image is the same as only up to Extra . (unless set to hash)
> 
> https://github.com/rook/rook/blob/3d18e780fbe6bb0c814349591552885898c7ffb3/pkg/operator/ceph/cluster/mgr/spec.go#L162
> 
> 
> However, as above, if ImagePullPolicy is not Always, the image will not be pulled again.
> In this case, when the version of CephCluster is updated, the Docker image may not be pulled again.
> Isn't there a possibility of deadlock in these cases?

I'm not sure there is a deadlock, but I suppose if someone uses an image tag where the Ceph version can be updated but image name not be updated, maybe the cluster wouldn't end up being updated. But this is why we recommend users use `quay.io/ceph/ceph:vMM.2.B-DATE` images for production: so this doesn't happen.


From my perspective, I think `DeepEqual()` is actually the correct check. If any of the components of the version have changed, it is could be an upgrade.


I think Travis has a good point in his comment here: https://github.com/rook/rook/pull/10696#pullrequestreview-1068407695
If there is no local cluster (because the cluster is external), we may want to skip the check. 

I wonder if there still could be an issue with skipping the check. Would it be better to use `ceph versions` to determine if the parent cluster (whether local or external) is upgrading? Do we care if an external cluster is currently being upgraded? @travisn wdyt?

**Comment by travisn** [comment]
This is why the most specific image tag such as `quay.io/ceph/ceph:v17.2.1-20220623` is recommended, so that a new image would be pulled to match that build. If the `v17.2.1` tag is used, a different would exist when a new base image is available. 

If the only difference is the hash then I could also see that the operator could get stuck if it's waiting for an image that will never be pulled.

**Comment by travisn** [comment]
> I wonder if there still could be an issue with skipping the check. Would it be better to use ceph versions to determine if the parent cluster (whether local or external) is upgrading? Do we care if an external cluster is currently being upgraded? @travisn wdyt?

The purpose of the check is really for a converged cluster as a way for the object controller (and other controllers) to wait for the main cluster upgrade before proceeding with their own upgrade. If the external cluster is being upgraded I don't see that Rook needs to attempt to track that. Skipping the check in external clusters seems correct.

**Comment by BlaineEXE** [comment]
> The purpose of the check is really for a converged cluster as a way for the object controller (and other controllers) to wait for the main cluster upgrade before proceeding with their own upgrade. If the external cluster is being upgraded I don't see that Rook needs to attempt to track that. Skipping the check in external clusters seems correct.

Okay. I think that tracks, yeah. 👍

**Comment by jclab-joseph** [comment]
Created a new PR: #10701

**Comment by jclab-joseph** [comment]
Created a new PR: https://github.com/rook/rook/pull/10701

**Pull request closed without merging**
