### PR TITLE
tests/scripts: Update to not re-create symbolic link

### LINKED ISSUE #2808: minikube.sh up fails while creating symbolic link
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`minikube.sh up` is failing for me on https://github.com/rook/rook/blob/master/tests/scripts/minikube.sh#L132:
```
 minikube ssh "sudo mkdir -p /mnt/sda1/${PWD}; sudo mkdir -p $(dirname $PWD); sudo ln -s /mnt/sda1/${PWD} $(dirname $PWD)/"
```

Output:
```
> ./tests/scripts/minikube.sh up
starting minikube with kubeadm bootstrapper
😄  minikube v0.34.1 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.1 ...
🚀  Launching Kubernetes v1.13.1 using kubeadm ...
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
ln: failed to create symbolic link '/Users/jared/dev/go/src/github.com/rook/rook': File exists
ssh: Process exited with status 1
```

I had to comment out this line in order to proceed.

**Expected behavior:**
`minikube.sh up` to succeed and Rook images to be copied to VM

**How to reproduce it (minimal and precise):**
`minikube.sh up`

### PR DESCRIPTION
**Pull request by nakabonne**
Signed-off-by: Ryo Nakao <nakabonne@gmail.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #2808 

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

[skip ci]

### CODE REVIEW

**Comment by nakabonne** [comment]
@jbw976 I could repro your issue and confirm to proceed normally by my correspondence.

I first tried to execute `ln -sf` he mentioned, but it would failed.
It seems to refuse to overwrite directories because it would be expecting a file:

```
ln: /Users/nakabonne/go/src/github.com/rook/rook: cannot overwrite directory
ssh: Process exited with status 1
```

**Comment by jbw976** [comment]
thank you for confirming that @nakabonne!  I'm getting ready for a demo tomorrow night and i'm able to reproduce this behavior in minikube.sh still with the current master bits, so I dug into it a bit more as well.

I'm honestly questioning the purpose of this offending line in the first place.  What is it actually trying to accomplish?

It was originally added in this commit: https://github.com/rook/rook/commit/82425aafcc96b6b5e2673fe82dff86a157f806bd#diff-dce852bf326054bf0c4ba373aa0e5266

But since it uses `${PWD}`, which I believe gets evaluated on the host machine before the ssh command is executed on the minikube VM, it's dependent on where you run `minikube.sh` from.  e.g., from the `tests/scripts` dir, I get a different corresponding path that fails:
```
> minikube ssh "sudo mkdir -p /mnt/sda1/${PWD}; sudo mkdir -p $(dirname $PWD); sudo ln -s /mnt/sda1/${PWD} $(dirname $PWD)/"
ln: failed to create symbolic link '/Users/jared/dev/go/src/github.com/rook/rook/tests/scripts': File exists
```

It looks like Minikube using the Virtualbox driver maps in your entire `/Users` folder on the Mac, so that's what's causing this file conflict.  The whole `/Users` tree is already there inside the Minikube VM.

Do we even need this line?  I'm not sure it's doing what it was intended to do.  Can we remove it?

**Comment by nakabonne** [comment]
I just removed this offending line and confirmed that `/Users` was removed from inside the Minikube VM after reinstalling the cluster.
```
$ minikube ssh
$ ls /mnt/sda1
data  hostpath-provisioner  hostpath_pv  lost+found  var
```
And then integration test would be able to be run without any problems.

@rootfs  Could you please let me know what kind of situation would be this link used? The comment says “create a link so the default dataDirHostPath will work for this environment”.

**Comment by leseb** [comment]
This was fixed with: https://github.com/rook/rook/pull/3695. Closing this, thanks.

**Pull request closed without merging**
