### PR TITLE
exporter: Don't delete exporter service on daemon deletion

### LINKED ISSUE #13642: rook-ceph-exporter ServiceMonitor deleted during reconcile for wrong ceph cluster (more than one ceph cluster)
After upgrading to Rook `1.12.10` and Ceph Reef `v18.2.1` we noticed that our ceph OSD metrics would "come and go" seemingly randomly.  When the metrics were working on one ceph cluster they would stop working on another cluster.  When looking in the namespaces for these clusters, only one cluster would have a ServiceMonitor `rook-ceph-exporter`, and it would be deleted from the other cluster's namespace.

Basically it looks like `cleanupExporterResources()` doesn't need to be called here since the exporter Service and ServiceMonitor are not related to whether there are ceph pods (regardless of namespace) on a particular node:

https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L210-L213

Because our two ceph clusters do not have any k8s nodes in common, it seems like they will just flip flop between who gets to have the ServiceMonitor, this is because `cephPods` contains a list of [all ceph pods for all ceph clusters](https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L352), but then it only considers them by [namespace in the loop](https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L142)

The Service `rook-ceph-operator` is not affected, but I think that's because the `cleanupExporterResources` function is trying to delete it from the Operator namespace instead of the appropriate ceph cluster namespace: https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L93

So we have some doubts about whether that `cleanupExporterResources` should even be called (ever?) Again, these aren't node-specific resources so there should be no reason to delete the Service or ServiceMonitor unless you actually disable monitoring entirely.   Anything that considers `hasCephPods` is probably doing something unexpected when you have > 1 ceph cluster (>1 namespace) and k8s nodes that don't share pods between them.

### PR DESCRIPTION
**Pull request by travisn**
The exporter service and service monitor should not be deleted if an individual daemon is being removed from a node. As long as the exporter is enabled with v18 and newer, the exporter service and service monitor should exist. Clusters were seeing their metrics stop collection when the exporter service and service monitor would disappear, especially when multiple clusters are configured.

**Issue resolved by this Pull Request:**
Resolves #13642

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by sp98 — APPROVED** [review]

**Comment by rkachach** [comment]
@travisn with the change ceph exporter service is only removed when the version is not supported. Is this the intention behind the fix?

```
		// Cleanup exporter if the ceph version isn't supported
		if !cephVersion.IsAtLeast(MinVersionForCephExporter) {
                                         ....
					result, err := r.cleanupExporterResources(cephCluster.Namespace, namespace, request.Name)
				}
			}
		}

```

**Review by subhamkrai — COMMENTED** [review]
I have the same question as @rkachach when we are going to remove these expoter resources? The pods are removed but the service is removed only if ceph version mismatch.

EDIT: do we have ownerReference set?

**Comment by subhamkrai** [comment]
also, I see similar PR https://github.com/rook/rook/pull/13664

**Comment by umangachapagain** [comment]
There is an ownerreference, so service and servicemonitor is removed when cephcluster is removed.

**Comment by rkachach** [comment]
> There is an ownerreference, so service and servicemonitor is removed when cephcluster is removed.

Thans @umangachapagain what happens if there are multiple clusters?

**Comment by travisn** [comment]
> > There is an ownerreference, so service and servicemonitor is removed when cephcluster is removed.
> 
> Thanks @umangachapagain what happens if there are multiple clusters?

The ownerReference is only referring to the cephcluster CR that owns the exporter resources, so the uninstall of one cluster won't affect the other cluster. But I still want to confirm if the exporter daemon handles the multi-cluster case if daemons from multiple clusters are on the same node.

**Comment by travisn** [comment]
> I have the same question as @rkachach when we are going to remove these expoter resources? The pods are removed but the service is removed only if ceph version mismatch.
> 
> EDIT: do we have ownerReference set?

I don't believe we ever need to remove the exporter unless the cluster is uninstalled, so the ownerReference should be sufficient.

**Review by subhamkrai — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Comment by travisn** [comment]
> The provided labels are not unique across multiple clusters.

Thanks, will open a separate issue for that

**Pull request merged**
