### PR TITLE
Rook Cluster Helm chart

### PR DESCRIPTION
**Pull request by hunter**
This is initial work on a Cluster TPR helm chart. It hasn't been tested but I'm raising the PR early for discussion around configuration. A few notes:

- Creates the Cluster TPR with values following the standard spec. This should mean that the chart doesn't need updates if the TPR spec is updated.
- Creates multiple pools based on a similar config to the Pool TPR. The values contain additonal config for StorageClasses but otherwise passes through the TPR spec
- Adds StorageClasses based on the Pools
- Exposes RGW as a service and ingress if configured
- Includes a ConfigMap for overriding Config

The chart values do become more complex to configure/override when passing through the Cluster/Pool specs but will mean less changes as Rook matures. Thoughts?

### CODE REVIEW

**Comment by travisn** [comment]
The approach looks good. It is certainly more complex than the operator chart with all the settings. I  worry that the complexity will make it difficult to maintain while we're stabilizing the cluster and related specs. It would help if we had an e2e test that verifies that the helm chart is valid. @dangula let's discuss what that would look like.

**Comment by travisn** [comment]
Since i'm a helm newby, could you also clarify the utility of the cluster helm chart? At a glance it seems like we're turning some simple yaml files into complex parametized yaml files. The benefits would need to be significant to justify the maintenance of the chart.

The chart is also creating a pool. The cluster must be running before the pool can be created. Does helm know how to start things in dependency order and wait for a certain state before continuing?

**Comment by jefflaplante** [comment]
The cool thing about helm charts is the ability to drive the yaml kubernetes manifest files with variables in the values.yaml file. That allows the 'infrastructure' of the chart to stay consistent and give you configuration flexibility in a single place. You can think of the values.yaml file like an attributes/default.rb file in a chef cookbook. The cookbook doesn't have to change, just the variables driving it. While that does look intimidating at first glance of the template kubernetes yaml files, it's very powerful.

**Comment by jefflaplante** [comment]
@travisn - you are right to be concerned about creating the pool in the same helm chart. I would recommend splitting that up since the infrastructure needs to be up and running before you can create a pool. Helm currently doesn't have a way of waiting as you need. However,  you can get past it with init containers. See this: https://github.com/kubernetes/helm/issues/1713

**Comment by travisn** [comment]
@jefflaplante thanks for the background. I guess since the sample values.yaml looks almost the same as the original yaml, it didn't seem like much of a gain.

**Comment by bassam** [comment]
also is it common for helm charts to create "resources" after installation? For example, is there a helm chart that creates a database for mysql, or just a helm chart for mysql? Creating a cluster/pool using helm seems like its gone beyond "package management" -- which is my naive understanding of helm.

**Comment by jefflaplante** [comment]
@bassam - It depends on the helm chart and what an accepted norm is. For Mysql you just get mysql installed but you're not creating or importing databases with the default as chart creators wouldn't know what you want. However, with something like rook, it's still not usable until you have at least one pool created. So, perhaps for rook you *do* want to have a default pool. That could be configurable in the values.yaml. It's all about building blocks. You could totally also just have the helm chart install rook and defer to an application specific helm chart for creating a pool. Examples would be very helpful in all of this.

**Comment by jefflaplante** [comment]
@travisn - yeah, from a 'just make it work' perspective, the values.yaml just looks like abstraction for the sake of abstraction which in general is simply annoying. The benefit is granting the chart's users the ability to change configuration parameters in one simple place rather than having to diving into the implementation details and changes lots of things in there instead. Messier and more prone to error.

**Comment by hunter** [comment]
Good discussion!

@jefflaplante covered the importance of configuration management. There is not a huge benefit for the only cluster/pool TPRs but combined with handling related services does offer some use - the lifecycle (upgrades/downgrades in helm) and also creating additional resources related to the cluster (RGW services/ingress and StorageClasses).

I wasn't aware that there would be a problem in ordering of the creation of pool vs cluster TPRs. I'd assumed that the rook operator would just wait until the cluster is running/healthy before trying to create the pools. There is talk of adding some ordering for an upcoming Helm release but for now I can look at splitting charts if we want to go that route. I'd imagine that it would add a fair amount of complexity.

@travisn on the topic of testing/validation. It's easy enough to run `helm lint` offline (no Tiller requirement) and potentially add the [template](https://github.com/technosophos/helm-template) plugin to do offline template expansion for verification (also possible online with the built-in `--debug --dry-run` flags for installation but it requires Tiller running).

**Comment by TimJones** [comment]
@hunter I would be careful about trusting `helm lint`. As far as I've seen it really only checks that the chart can be rendered to valid YAML, not that it makes valid Kubernetes resources I.E. `helm line` can show everything OK, then `helm install` croaks with a Kubernetes error.

**Comment by hunter** [comment]
@TimJones Agreed. I've run into the same issues. It does serve its purpose as a quick sanity check before requiring a connection to Tiller (although as mentioned the `helm template` plugin gets 90% of the way there)

**Comment by v1k0d3n** [comment]
is there any way to get this added? this has been hanging out for a while, and it would be really nice to have. it could be iterated on to take it further if needed. i would like to have more options in addition to what we're currently using on the openstack-helm side (if possible): https://github.com/openstack/openstack-helm/tree/master/ceph (which @hunter is well aware of).

**Comment by travisn** [comment]
@hunter I assume you're still working on some changes?

**Comment by hunter** [comment]
I haven't had much of a chance to revisit with all the latest rook changes. I'll take a closer look early next week to update

**Comment by hunter** [comment]
I've made some updates to match the latest config changes. The chart deployment appears to work correctly (although I assume will need CRD changes when they land)

**Comment by jbw976** [comment]
There is a new effort on rook cluster helm charts that has fresh momentum in #1545.  I'm going to close this one down and proceed on the new one.  I've asked the PR author to incorporate any of the useful ideas from this PR into his new one, so we aren't losing anything of value.  Thanks for your effort and start on this @hunter!

**Pull request closed without merging**
