### PR TITLE
build: bump to golang version 1.16

### LINKED ISSUE #7938: Build with golang 1.16
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
It's time to move to golang 1.16 in the builds as a requirement. The builds currently allow for either 1.15 or 1.16 for flexibility while 1.16 was recently out, but now we need to take advantage of 1.16 for issues such as #7609 and #7913. 

This should be as simple as:
- Update the github actions to use golang 1.16
- Set the [required build version](https://github.com/rook/rook/blob/master/build/makelib/golang.mk#L51) to `1.16`

**What is use case behind this feature:**
Build with updated features and dependencies.

### PR DESCRIPTION
**Pull request by subhamkrai**
this commit bump to golang version 1.16.

Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #7938 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test]

### CODE REVIEW

**Review by sp98 — APPROVED** [review]

**Review by travisn — CHANGES_REQUESTED** [review]
LGTM, we just need to wait until Jenkins is updated with 1.16, it should be done next week...

**Review by travisn — APPROVED** [review]
Jenkins is running 1.16 now, let's proceed!

**Comment by travisn** [comment]
@subhamkrai Please open a backport PR for this to release-1.6, the bot won't pick it up since it includes the actions. Thanks!

**Comment by subhamkrai** [comment]
> @subhamkrai Please open a backport PR for this to release-1.6, the bot won't pick it up since it includes the actions. Thanks!

I'll open PR soon.

**Comment by subhamkrai** [comment]
> > @subhamkrai Please open a backport PR for this to release-1.6, the bot won't pick it up since it includes the actions. Thanks!
> 
> I'll open PR soon.

#8044

**Pull request merged**
