### PR TITLE
RFC: ceph: fix OSD node removal

### PR DESCRIPTION
**Pull request by k0da**
This fixes: https://github.com/rook/rook/issues/3428

With useAllNodes set to true, osd removal is only started when node
either removed or node affinity doesn't match. Thus provisioner job
will never be started. Even latter is wrong, we don't want to provision
OSD for just removed OSD from crushmap.

Signed-off-by: Dinar Valeev <k0da@opensuse.org>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/v1.0/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [x] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [x] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../CONTRIBUTING.md#comments)
- [x] Add the flag for skipping the CI if this PR does not require a build. See [here](/INSTALL.md#skip-ci) for more details.

// CI control
[test ceph]

### CODE REVIEW

**Comment by BlaineEXE** [comment]
I don't fully understand the commit comment. Please include a description of the old behavior and reasoning behind why that is incorrect. Then a second paragraph about what the new behavior is and how it is correct.

Work that we are planning for v1.1 or v1.2 is to change Rook's behavior around OSD removal. Notably, Rook should never be removing OSDs from the CRUSH map, though it can still remove OSD deployments from Kubernetes. I want to make sure that this matches the expectations you had when creating this PR.

@travisn I don't know a whole lot about the removal cleanup process from the log message in the issue (`op-osd: done waiting for removal cleanup on node ii-k8s-worker01.example.com`). I'm also not sure how many nodes the cluster from the issue has; if only one node, this could be an issue only in the one-node case.

**Comment by BlaineEXE** [comment]
Marking as feature for now since this change seems like it might have some fairly large implications.

**Comment by travisn** [comment]
Agreed, there are other changes coming to OSDs where it would be good to do a full review of the OSD removal behavior.

**Comment by travisn** [comment]
There are multiple parts to this cleanup that would make sense at the same time. In addition to removing the cleanup job on the specific node, at a minimum, the job for cleaning up the OSDs on the node will no longer be triggered. Remove the corresponding job code. You can search for `getRemovedDevices` and `removeDevices`, and any cleanup methods they call.

At the same time i'd like to consider what OSD resources are removed automatically. Removing the OSD daemon deployments makes sense. However, removing the OSD from the CRUSH map is in question. There was a lot of discussion in [this PR](https://github.com/rook/rook/pull/3117#pullrequestreview-249125768) about whether to remove it at the ceph level. How to proceed with this discussion could certainly be a separate PR.

**Comment by leseb** [comment]
@travisn should we close this in favor of https://github.com/rook/rook/pull/4478?

**Comment by travisn** [comment]
This will be resolved with #4478 since we won't be resolving osds anymore. Let's go with that one.

**Pull request closed without merging**
