### PR TITLE
ceph: use latest 14.2.2 code

### PR DESCRIPTION
**Pull request by leseb**
14.2.2 is out and along with it numerous fixes so let's use it.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

[test ceph]

### CODE REVIEW

**Comment by Madhu-1** [comment]
@ajarr @leseb is this images having all the changes required for cephcsi cephfs to work?

**Comment by leseb** [comment]
@Madhu-1 if they are in 14.2.2 then yes.

**Comment by leseb** [comment]
@travisn done.

**Comment by BlaineEXE** [comment]
It looks like it failed the ARM build.

**Comment by leseb** [comment]
@BlaineEXE yes, it looks like the 14.2.2 arm64 was build last week so their timestamp don't match, I'm rebuilding arm right now.

**Comment by travisn** [comment]
We've had this issue before with the different timestamps, the fix was to use the condition `ifeq ($(GOARCH),amd64)` to handle the different images for different arch.

**Comment by travisn** [comment]
@Madhu-1 Per discussion with @ajarr all the critical changes needed for csi-cephfs should be in 14.2.2. The fixes coming in 14.2.3 will include improvements, but should not include api changes. The timeline for 14.2.3 is still unknown so let's proceed with the assumption that Rook v1.1 will release based on 14.2.2.

**Comment by zhujingfa** [comment]
Using 14.2.2 I failed with rook-operater log, may be helpful. 14.2.1 is working.
```
2019-08-20 07:52:02.925811 I | exec: Running command: ceph orchestrator set backend rook --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/382927740
2019-08-20 07:52:04.208195 I | exec: no valid command found; 10 closest matches:
mon dump {<int[0-]>}
mon stat
fs set-default <fs_name>
fs add_data_pool <fs_name> <pool>
fs rm_data_pool <fs_name> <pool>
fs set <fs_name> max_mds|max_file_size|allow_new_snaps|inline_data|cluster_down|allow_dirfrags|balancer|standby_count_wanted|session_timeout|session_autoclose|allow_standby_replay|down|joinable|min_compat_client <val> {--yes-i-really-mean-it}
fs flag set enable_multiple <val> {--yes-i-really-mean-it}
fs ls
fs get <fs_name>
osd tree-from {<int[0-]>} <bucket> {up|down|in|out|destroyed [up|down|in|out|destroyed...]}
Error EINVAL: invalid command
2019-08-20 07:52:04.208961 I | cephclient: command failed. trying again...

```

**Comment by travisn** [comment]
@zhujingfa That error should have been resolved when the operator retried the operation. Is there another failure you're seeing? If so, please open a new issue on this, thanks.

**Pull request merged**
