### PR TITLE
backport : update ci k8s versions

### PR DESCRIPTION
**Pull request by dangula**
CI

Update K8s versions in CI pipeline and add new node for fixed k8s version v1.6.1

(cherry picked from commit 0a67f84c530419d29c0e4ac6fb08d728c8b53532)

### CODE REVIEW

**Comment by dangula** [comment]
The CI build for k8s 1.6.1 is failing becuse of https://github.com/rook/rook/issues/1209, the fix https://github.com/rook/rook/pull/1211 is not backported to release-0.6 branch.

**Comment by jbw976** [comment]
Good debugging @dangula. Backporting this update to our CI environments to the 0.6 release branch was intended as a "nice to have" so that if we happen to do another 0.6 release then we will have this expanded pipeline ready to go for it.

I don't think we want to backport other fixes to 0.6, that we didn't already intend to release, just so that this expanded pipeline will work.  I'm thinking we will not take this PR into 0.6 because of this.

**Comment by jbw976** [comment]
Wait a minute, we probably do want to actually backport the fix for #1211 since it prevents Rook from working on 1.6.1.

**Comment by dangula** [comment]
#1209 for fix for regression caused by https://github.com/rook/rook/issues/1186 and  PR  https://github.com/rook/rook/pull/1188.

**Comment by travisn** [comment]
let's reopen this if we decide on an 0.6.3 release

**Pull request closed without merging**
