### PR TITLE
ci: disk in github action increased to 75G from 64G

### PR DESCRIPTION
**Pull request by subhamkrai**
the disk size in the github action machine has
increased from 64G to 75G.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by sp98** [comment]
@subhamkrai Can you check if this is something we can fix on the fly? So don't have to fix it again if the disk size increases in future.

**Comment by sp98** [comment]
> @subhamkrai Can you check if this is something we can fix on the fly? So don't have to fix it again if the disk size increases in future.

Other option would have have this is a global variable. So future changes can go only in file. This would help making in lots of files in one go.

**Comment by subhamkrai** [comment]
> > @subhamkrai Can you check if this is something we can fix on the fly? So don't have to fix it again if the disk size increases in future.
> 
> Other option would have have this is a global variable. So future change in the disk size can go only in file only.

I agree we need do better work handling this, will work on this in separate PR later

**Comment by travisn** [comment]
As discussed we will get this merged to handle the new disk size, then follow up to investigate the remaining CI failures. At least this gives us green CI for some of the integration tests where a single OSD is used.

**Comment by subhamkrai** [comment]
```
sudo lsblk --paths --list | grep -P '\s+/mnt$' | grep -Po '^[/a-z]+'|
``` 

This not working once we do formatting or partition change for canary-tests

**Comment by travisn** [comment]
> I tried few things, but that didn't worked so I guess ready for review

Ok, we can follow up separately on how to avoid the size-based filter. Will merge once the CI is completed.

**Comment by BlaineEXE** [comment]
This is the second time GH has changed the disk size in 3ish months I think. We probably should figure out how to use a different filter for selecting the disk.

**Comment by travisn** [comment]
> I tried few things, but that didn't worked so I guess ready for review

@subhamkrai Which tests do you expect to fail even after the size change? Just some canary tests? Looks like some upgrade and other integration tests are also failing, even though I thought I had seen them pass on a previous run.

**Comment by subhamkrai** [comment]
> > I tried few things, but that didn't worked so I guess ready for review
> 
> @subhamkrai Which tests do you expect to fail even after the size change? Just some canary tests?

Yes,

> Looks like some upgrade and other integration tests are also failing, even though I thought I had seen them pass on a previous run.

@travisn seems like those tested are cancelled in the middle not failed.

**Comment by subhamkrai** [comment]
seems like the CI started with debug mode and then cancelled

**Review by travisn — APPROVED** [review]
> seems like the CI started with debug mode and then cancelled

Going ahead with the merge, and will keep investigating the remaining issues with a separate PR...

**Pull request merged**
