### PR TITLE
build: use new S3 buckets

### LINKED ISSUE #1517: helm repo index was not updated for v0.7
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:  I ran the rook/promote target on Jenkins to promote v0.7 to alpha, but the index files on https://charts.rook.io/ (both alpha and master) have not been updated to v0.7.

What you expected to happen:  The alpha and master helm repos to have been updated to v0.7.

```
$ helm repo add rook-alpha https://charts.rook.io/alpha
"rook-alpha" has been added to your repositories
$ helm search rook
NAME               VERSION    DESCRIPTION
rook-alpha/rook    v0.6.2     File, Block, and Object Storage Services for yo...
```

### PR DESCRIPTION
**Pull request by bassam**
Description of your changes:

Backport changes to 0.7 release

Which issue is resolved by this Pull Request:
Resolves #1517

Checklist:
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by jbw976** [comment]
The jenkins build looks successful for this PR: https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-1527/2/pipeline.  The check looks to be linking to an undefined location:
http://unconfigured-jenkins-location/job/rook/job/rook/job/PR-1527/1/display/redirect

Not sure what's up with that.  Maybe since this is the first CI build run on the 0.7 branch?

**Comment by bassam** [comment]
no clue. we could relax the check to dislodge this.

**Comment by travisn** [comment]
the bad link could be due to deleting the build agents for #1528

**Comment by jbw976** [comment]
I think it was related to deleting the agents, because the broken link also appeared on an older PR that was not the 0.7 release branch (https://github.com/rook/rook/pull/1509 but a new build is running now)

**Pull request merged**
