### PR TITLE
osd: refactor osd removal code

### PR DESCRIPTION
**Pull request by karthik-us**
Making the osd removal code more concise.

Fixes: #13292

### CODE REVIEW

**Review by subhamkrai — COMMENTED** [review]
at L91 can we also check `if err !=nil && !forceOSDRemoval{`
?

**Comment by karthik-us** [comment]
> at L91 can we also check `if err !=nil && !forceOSDRemoval{` ?

Changed it to `if err != nil && forceOSDRemoval {` and included the err condition without the force option in the else if flow.

**Comment by parth-gr** [comment]
@karthik-us just a suggestion for future you should self-assign the issue before opening a PR, something like this https://rook.io/docs/rook/latest-release/Contributing/development-flow/#self-assign-issue

**Review by subhamkrai — COMMENTED** [review]
@karthik-us did you test osd-removal locally after your changes?

**Comment by karthik-us** [comment]
> @karthik-us did you test osd-removal locally after your changes?

Since this was just a refactoring of the logic, I did not test it. Will test and update.

**Review by rkachach — CHANGES_REQUESTED** [review]
TBH I find the new logic a little bit harder to follow. What about something like:

```
for {
    isSafeToDestroy, err := client.OsdSafeToDestroy(clusterdContext, clusterInfo, osdID)
    if err != nil {
        if forceOSDRemoval {
            logger.Errorf("failed to check if osd %d is safe to destroy, but force removal is enabled so proceeding with removal. %v", osdID, err)
            break
        }
        logger.Errorf("failed to check if osd %d is safe to destroy, retrying in 1m. %v", osdID, err)
        time.Sleep(1 * time.Minute)
        continue
    }

    if isSafeToDestroy || forceOSDRemoval {
        if forceOSDRemoval {
            logger.Infof("osd.%d is NOT ok to destroy but force removal is enabled so proceeding with removal", osdID)
        } else {
            logger.Infof("osd.%d is safe to destroy, proceeding", osdID)
        }
        break
    }

    logger.Warningf("osd.%d is NOT ok to destroy, retrying in 1m until success", osdID)
    time.Sleep(1 * time.Minute)
}

```

BTW: please, make sure to test the changes very well covering all the scenarios as OSD removal is critical .

**Comment by travisn** [comment]
The behavior is expected to be functionally the same, or is there some bug fix? Not sure it's worth changing and risking a regression.

**Comment by karthik-us** [comment]
> The behavior is expected to be functionally the same, or is there some bug fix? Not sure it's worth changing and risking a regression.

Hi @travisn, the behavior is functionally same with the current proposed code as well as the one suggested by @rkachach. The current change removes a duplication, decreases the overall lines of code and the line length. The later suggestion is almost similar to the existing code except few changes in the non error case in fetching the safeToDestroy info.

I did test a few scenarios with the current chageset, and it did seem to work without any regressions.

**Comment by karthik-us** [comment]
> TBH I find the new logic a little bit harder to follow. What about something like:
> 
> ```
> for {
>     isSafeToDestroy, err := client.OsdSafeToDestroy(clusterdContext, clusterInfo, osdID)
>     if err != nil {
>         if forceOSDRemoval {
>             logger.Errorf("failed to check if osd %d is safe to destroy, but force removal is enabled so proceeding with removal. %v", osdID, err)
>             break
>         }
>         logger.Errorf("failed to check if osd %d is safe to destroy, retrying in 1m. %v", osdID, err)
>         time.Sleep(1 * time.Minute)
>         continue
>     }
> 
>     if isSafeToDestroy || forceOSDRemoval {
>         if forceOSDRemoval {
If we go with this change, the forceOSDRemoval should be in the else part. Otherwise, even if safe to destroy is ture, and the force flag is set, we will get a wrong msg that OSD is not ok to be destroyed.
>             logger.Infof("osd.%d is NOT ok to destroy but force removal is enabled so proceeding with removal", osdID)
>         } else {
>             logger.Infof("osd.%d is safe to destroy, proceeding", osdID)
>         }
>         break
>     }
> 
>     logger.Warningf("osd.%d is NOT ok to destroy, retrying in 1m until success", osdID)
>     time.Sleep(1 * time.Minute)
> }
> ```
> 
> BTW: please, make sure to test the changes very well covering all the scenarios as OSD removal is critical .

**Pull request closed without merging**
