### PR TITLE
Minio: add a test case

### PR DESCRIPTION
**Pull request by phantooom**
Signed-off-by: xiaorui.zou <xiaorui.zou@gmail.com>

**Description of your changes:**

add a minio test case for ValidateObjectStoreSpec

### CODE REVIEW

**Comment by phantooom** [comment]
fixed @travisn

**Comment by galexrt** [comment]
@phantooom Are you sure you fixed the commit message with more details?
The commit still only has one line. It would be good to have a message on the

**Comment by galexrt** [comment]
@phantooom would you mind telling us why you closed the PR?
The change itself looks sane, just the commit message needed a bit more detail about the change added to it.

**Comment by phantooom** [comment]
@galexrt  i found that func had been test in a high level func test case.
 https://github.com/rook/rook/blob/master/pkg/operator/minio/controller_test.go#L191

**Comment by galexrt** [comment]
@phantooom I see. It is good to mention that when closing a Pr, so we know what is going on :slightly_smiling_face:

**Comment by phantooom** [comment]
i see

**Pull request closed without merging**
