### PR TITLE
security: update vault to 1.13.3

### PR DESCRIPTION
**Pull request by subhamkrai**
updating vault to latest version which
include some cve fixes.

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by travisn** [comment]
There are some build errors:
```
Error: ../../../go/pkg/mod/github.com/hashicorp/vault@v1.13.3/audit/format.go:148:22: p.NamespacePath undefined (type logical.PolicyInfo has no field or method NamespacePath)
Error: ../../../go/pkg/mod/github.com/hashicorp/vault@v1.13.3/audit/format.go:358:22: p.NamespacePath undefined (type logical.PolicyInfo has no field or method NamespacePath)
```

**Comment by subhamkrai** [comment]
> There are some build errors:
> 
> ```
> Error: ../../../go/pkg/mod/github.com/hashicorp/vault@v1.13.3/audit/format.go:148:22: p.NamespacePath undefined (type logical.PolicyInfo has no field or method NamespacePath)
> Error: ../../../go/pkg/mod/github.com/hashicorp/vault@v1.13.3/audit/format.go:358:22: p.NamespacePath undefined (type logical.PolicyInfo has no field or method NamespacePath)
> ```

yess, seems like we need to golang version/controller runtime

**Comment by travisn** [comment]
Superseded by #12455.

**Comment by raghavendra-talur** [comment]
I believe the CVE isn't addressed yet. The minimum version of vault to upgrade to is 1.13.5. Please refer to https://discuss.hashicorp.com/t/hcsec-2023-24-vaults-ldap-auth-method-allows-for-user-enumeration/56714

**Comment by travisn** [comment]
> I believe the CVE isn't addressed yet. The minimum version of vault to upgrade to is 1.13.5. Please refer to https://discuss.hashicorp.com/t/hcsec-2023-24-vaults-ldap-auth-method-allows-for-user-enumeration/56714

Maybe you already saw since it's closed again, but the update to v1.13.5 was in #12672.

**Pull request closed without merging**
