### PR TITLE
ceph: do not merge nodeAffinity (bp #7192)

### PR DESCRIPTION
**Pull request by subhamkrai**
**Description of your changes:**
this commit is kind of bp PR for 7192 and 7247
directly to release branch as there was conflicts
due some removed stroage providers.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
it is not ready for review...I think mixed a few commands and have some conflicts.

**Comment by subhamkrai** [comment]
> it is not ready for review...I think mixed a few commands and have some conflicts.

it's ready now...I forgot to switch from `master` to `release-1.5` :smiley:

**Review by leseb — APPROVED** [review]

**Review by leseb — CHANGES_REQUESTED** [review]
Use `cherry-pick -x`

**Comment by subhamkrai** [comment]
I have one extra change...I rebase soon

**Review by travisn — COMMENTED** [review]
In the 2nd commit, if you could describe more the changes specifically. When writing the commit messages they should be self descriptive, assume there is no other context from the PR.

**Comment by subhamkrai** [comment]
> In the 2nd commit, if you could describe more the changes specifically. When writing the commit messages they should be self descriptive, assume there is no other context from the PR.

Commit message updated.

**Review by leseb — CHANGES_REQUESTED** [review]
Why do you need 26a344fa8087cd09b4112a9d792412f267d77905? Just solve the conflicts directly from the commit suffering from the conflicts. There is no need for a separate commit.

**Comment by subhamkrai** [comment]
> Why do you need [26a344f](https://github.com/rook/rook/commit/26a344fa8087cd09b4112a9d792412f267d77905)? Just solve the conflicts directly from the commit suffering from the conflicts. There is no need for a separate commit.

Most of the changes in the 3rd commit(commit that you pointed) are for storage providers which are removed from master and that's why I kept in a separate commit. And only change is related to the conflict that I will move to commit which has conflict. The first 2 commits are cherry-picked so don't want to have other changes in that commit. Maybe the commit message is not clear for the 3rd commit. Let me know if it okay to keep it in separate or not.

**Comment by subhamkrai** [comment]
> > Why do you need [26a344f](https://github.com/rook/rook/commit/26a344fa8087cd09b4112a9d792412f267d77905)? Just solve the conflicts directly from the commit suffering from the conflicts. There is no need for a separate commit.
> 
> Most of the changes in the 3rd commit(commit that you pointed) are for storage providers which are removed from master and that's why I kept in a separate commit. And only change is related to the conflict that I will move to commit which has conflict. The first 2 commits are cherry-picked so don't want to have other changes in that commit. Maybe the commit message is not clear for the 3rd commit. Let me know if it okay to keep it in separate or not.

Decided to go with Sebastien suggestion. Thanks

**Review by leseb — APPROVED** [review]

**Pull request merged**
