### PR TITLE
Use truncated node name for missed sections

### LINKED ISSUE #2272: Upgrade from v0.7 to v0.8 for nodes with long hostname broken
**Is this a bug report or feature request?**
* Bug Report

**Bug Report**

**Expected behavior:**
New OSD Deployments to replace the existing OSDs running in one ReplicaSets per node.

**Deviation from expected behavior:**
New OSD Deployments have extended the Ceph cluster as new OSDs and not replaced the existing in ReplicaSets running OSDs per node.

**How to reproduce it (minimal and precise):**
Have nodes with a long node name (e.g., `ip-192-78-13-122.eu-central-1.compute.internal`).

**Additional information:**
~~I'm not sure if the issue is only happening when `metadataDevice` is used in the cluster.~~ Confirmed by another user running into this.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v0.7.x to v0.8.3
* Kubernetes version (use `kubectl version`): seems to be unrelated to K8S version

### PR DESCRIPTION
**Pull request by galexrt**
**Description of your changes:**
This fixes additional "problematic sections" as a user affected by this problem reported that running just the bash snippet didn't fix it for him, but running a Rook version based on release-0.8 branch with those fixes in worked for him when doing the upgrade.

I would add the bash snippet/issue link to the release notes when a backport for v0.8 has been decided.

**Which issue is resolved by this Pull Request:**
Resolves #2272.

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by travisn** [comment]
@galexrt in the integration tests, we change the host name to verify that we handle a different name. What if we modify the `ChangeHostnames()` and `RestoreHostnames()` functions to use a long hostname instead of just a short prefix? The upgrade integration test doesn't currently rename the hostname either (see [here](https://github.com/rook/rook/blob/master/tests/framework/installer/ceph_installer.go#L463)), but I don't recall why 0.8 tests disabled it. Note that the check for 1.11 in that test was simply so some tests will run with a normal hostname.

**Comment by galexrt** [comment]
@travisn Sure. Should it be the "default" that all tests are executed with long hostnames?

**Comment by travisn** [comment]
@galexrt yes, sounds good to always use a long host name for the tests where it's modified. But we should still have some tests that use the original short hostname. Switching on the k8s version should be a simple enough differentiator.

**Comment by galexrt** [comment]
@travisn and in which K8s versions should we use long hostnames?

**Comment by travisn** [comment]
@galexrt the host name is currently changed for 1.11 and newer and you could use that same flag. But as long as at least one of the versions modifies the host names it will be fine.

**Comment by galexrt** [comment]
@travisn CI is green. I split it into two commits. One adding the missing usage of TruncateNodeName and the second being the hostname change test prefix change to be longer.
PTAL

**Comment by travisn** [comment]
@galexrt Anyone with long hostnames in 0.7 or 0.8 would need to run through [this script](https://github.com/rook/rook/issues/2272#issuecomment-437149250) during upgrade, correct?

**Comment by galexrt** [comment]
@travisn Yes. Though some users reported that running the bash snippet was enough while others reported that it only worked when running the bash snippet and a patched `v0.8` version.

**Pull request merged**
