### PR TITLE
Fix typo in resource name in the instructions

### PR DESCRIPTION
**Pull request by pre**
**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
[skip ci]

### CODE REVIEW

**Review by subhamkrai — COMMENTED** [review]
Please add signoff and commit message.
For details https://github.com/rook/rook/blob/master/CONTRIBUTING.md#certificate-of-origin

**Comment by travisn** [comment]
@Madhu-1 We need this change, right? Would be good to get it in even if someone else needs to take it over.

**Review by Madhu-1 — APPROVED** [review]
LGTM, but need to fix commit message.

**Comment by Madhu-1** [comment]
> @Madhu-1 We need this change, right? Would be good to get it in even if someone else needs to take it over.

@travisn yes we need this change :+1:

**Comment by travisn** [comment]
> > @Madhu-1 We need this change, right? Would be good to get it in even if someone else needs to take it over.
> 
> @travisn yes we need this change 👍

We'll probably need to open a new PR since the author hasn't responded.

**Comment by Madhu-1** [comment]
> > > @Madhu-1 We need this change, right? Would be good to get it in even if someone else needs to take it over.
> > 
> > 
> > @travisn yes we need this change +1
> 
> We'll probably need to open a new PR since the author hasn't responded.

i can do that.

**Comment by pre** [comment]
I didn’t respond as I made this change in www.github.com with a web browser, and the suggested review changes required too much effort. 

Cheers 😀

**Pull request closed without merging**
