### PR TITLE
ceph: added discover devices interval to helm charts

### PR DESCRIPTION
**Pull request by jaxels10**
On request from Alexander Trost, I have added the ROOK_DISCOVER_DEVICES_INTERVAL variable to cluster/charts/rook-ceph/values.yaml and to cluster/charts/rook-ceph/templates/deployment.yaml.

Signed-off-by: Jesper Axelsen <jesperbaxelsen@gmail.com>

**Description of your changes:
On request from Alexander Trost, I have added the ROOK_DISCOVER_DEVICES_INTERVAL variable to cluster/charts/rook-ceph/values.yaml and to cluster/charts/rook-ceph/templates/deployment.yaml.**

**Which issue is resolved by this Pull Request: ROOK_DISCOVER_DEVICES_INTERVAL not included in the Helm charts**
Resolves #

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [x] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [x] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by jaxels10** [comment]
Thought I fixed the previous issue with capital letters in the commit message, but I didn't

**Review by subhamkrai — COMMENTED** [review]
@jaxels10 just update your commit title ...replace `Added` with `added` or for complete look 342d7f3b3522a5c62b33f07c75afabd3b4226e9b. Thanks

**Comment by jaxels10** [comment]
> @jaxels10 just update your commit title ...replace `Added` with `added` or for complete look https://rook.io/docs/rook/master/development-flow.html#commit-structure. Thanks

Hi @subhamkrai. Thanks a lot for the link. I have submitted a different pull request, cause I couldn't find the place to edit... https://github.com/rook/rook/pull/7141

**Comment by subhamkrai** [comment]
> > @jaxels10 just update your commit title ...replace `Added` with `added` or for complete look https://rook.io/docs/rook/master/development-flow.html#commit-structure. Thanks
> 
> Hi @subhamkrai. Thanks a lot for the link. I have submitted a different pull request, cause I couldn't find the place to edit... #7141

JFYI, you could change by running `git commit --amend -s `

**Comment by jaxels10** [comment]
> > > @jaxels10 just update your commit title ...replace `Added` with `added` or for complete look https://rook.io/docs/rook/master/development-flow.html#commit-structure. Thanks
> > 
> > 
> > Hi @subhamkrai. Thanks a lot for the link. I have submitted a different pull request, cause I couldn't find the place to edit... #7141
> 
> JFYI, you could change by running `git commit --amend -s `

Ahh okay, I was not aware of this. Thanks for the tip mate 👍

**Pull request closed without merging**
