### PR TITLE
csi: update the CSI-Addons sidecar to v0.8.0

### PR DESCRIPTION
**Pull request by nixpanic**
**Which issue is resolved by this Pull Request:**

Quite some improvements have been included in the recently released
v0.8.0 of the CSI-Addons sidecar for Kubernetes. Rook users will benefit
from running the latest version of the sidecar when deploying Ceph-CSI.

See-also: https://github.com/csi-addons/kubernetes-csi-addons/releases/tag/v0.8.0

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by nixpanic** [comment]
/cc @Rakshith-R

This isn't ready for merging yet, the CSI-Addons release is still pending.

**Review by Rakshith-R — APPROVED** [review]

**Comment by Rakshith-R** [comment]
https://github.com/csi-addons/kubernetes-csi-addons/actions/runs/7247843216/job/19742605675

Release should be out in 15-20 minutes.

**Comment by travisn** [comment]
As a future work item, we should enable the addons in the rook CI to get some level of validation. If the CI can pass before the release even exists, it is a problem. :)

**Comment by Rakshith-R** [comment]
> As a future work item, we should enable the addons in the rook CI to get some level of validation. If the CI can pass before the release even exists, it is a problem. :)

Yes, opened an issue to track this https://github.com/rook/rook/issues/13438.

The release is out now.
https://github.com/csi-addons/kubernetes-csi-addons/releases/tag/v0.8.0

**Comment by nixpanic** [comment]
> @nixpanic I see csi-addons new version is released, ready to merge?
> 
> cc @Rakshith-R

Yes, this should be ready to go.

**Comment by subhamkrai** [comment]
> > @nixpanic I see csi-addons new version is released, ready to merge?
> > cc @Rakshith-R
> 
> Yes, this should be ready to go.

@nixpanic  one more question, is this required for Cephfs fencing?

**Review by travisn — APPROVED** [review]

**Comment by nixpanic** [comment]
> > > @nixpanic I see csi-addons new version is released, ready to merge?
> > > cc @Rakshith-R
> > 
> > 
> > Yes, this should be ready to go.
> 
> @nixpanic one more question, is this required for Cephfs fencing?

No, but it enhances the predictability of how NetworkFencing (and some other CSI-Addons operations) are executed.

**Pull request merged**
