### PR TITLE
support ipv6

### LINKED ISSUE #1629: support ipv6
Is this a bug report or feature request?

* Feature Request

**Feature Request**

Are there any similar features already existing:  
not found

What should the feature do: 
support ipv6 address of ceph pod

What would be solved through this feature: 
make rook work in  ipv6 kubernetes cluster

Does this have an impact on existing features: 
no

**Environment**:
* OS (e.g. from /etc/os-release):  centos 7
* Kernel (e.g. `uname -a`):  4.1.0.el7
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):  0.7.0
* Kubernetes version (use `kubectl version`):  v1.10.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  baremetal
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
```  
  cluster:
    id:     77a42a1c-1278-45e3-80be-ecf75633e780
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon2,rook-ceph-mon1,rook-ceph-mon0
    mgr: rook-ceph-mgr0(active)
    osd: 9 osds: 9 up, 9 in
 
  data:
    pools:   1 pools, 100 pgs
    objects: 51415 objects, 200 GB
    usage:   618 GB used, 32900 GB / 33519 GB avail
    pgs:     100 active+clean
```

Rook does not work in ipv6 environment because it join host and ip pair directly by `fmt.Sprintf("%s:%d", host, port) `
I suggest using `net.JoinHostPort` instead

### PR DESCRIPTION
**Pull request by zmlcc**
join host and port using `net.JoinHostPort`

Also add some changes include:
rename NetworkInfo.NetworkInfoIPv4 to NetworkInfo.NetworkInfo
rename NetworkInfo.ClusterAddrIPv4 to NetworkInfo.ClusterAddr
rename command flag public-ipv4 to public-ip
rename command flag private-ipv4 to private-ip
rename ROOK_PUBLIC_IPV4 to ROOK_PUBLIC_IP
rename ROOK_PRIVATE_IPV4 to ROOK_PRIVATE_IP

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #1629

### CODE REVIEW

**Comment by jbw976** [comment]
@zmlcc could you change this PR so that it would be merged into master instead of the 0.7 release branch?  I think we'd only want this in master instead of putting it into an older release. Thanks!

**Comment by galexrt** [comment]
@zmlcc As @jbw976 wrote, can you please change the target of the PR to `master`.
If there is no response till Saturday, I'm going to pick up this PR to get this feature in.

**Comment by zmlcc** [comment]
Sorry for late response
I changed target to `master ` and patch the code
Hope it works

**Comment by zmlcc** [comment]
Integration Tests Failed Because K8s 1.6.x **DO NOT**  support CRD !!!

**Comment by travisn** [comment]
@zmicc support for 1.6 has actually been removed as of a couple days ago. If you rebase you should not see 1.6 in the builds anymore.

**Comment by jbw976** [comment]
Hmm, I started a new build (as opposed to replaying one) and it's still trying to include k8s 1.6 in the pipeline: https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-1630/3/pipeline

The branch has the removal of 1.6 from the jenkinsfile, this must be some weird Jenkins caching:
https://github.com/ucloudlab/rook/commits/ipv6-support
https://github.com/ucloudlab/rook/commit/656d2233d744df898f4bad3feb2ad33a91aca293#diff-58231b16fdee45a03a4ee3cf94a9f2c3

**Comment by zmlcc** [comment]
@jbw976   I add one blank line in `Jenkinsfile` and it worked

**Comment by travisn** [comment]
@zmlcc thanks for working on this, it will be great to get in. Any questions about the changes @jbw976 requested? This will help us ensure upgrades are compatible.

**Comment by zmlcc** [comment]
Delete origin branch by accident

**Comment by zmlcc** [comment]
I open new PR #1769 ,  let's continue to talk there

**Pull request closed without merging**
