### PR TITLE
ci: do not run the pipeline if PR is draft

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

If the PR is a draft, it's not ready for review and most likely the CI
pipeline should not run as the code might be broken in some places.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[skip ci]

### CODE REVIEW

**Comment by travisn** [comment]
@leseb Why not allow the CI to run? The author of a draft PR might be troubleshooting CI issues as well. We don't generally have a shortage of CI agents so it seems fine to let it run by default. [skip ci] can always be added.

**Comment by leseb** [comment]
> @leseb Why not allow the CI to run? The author of a draft PR might be troubleshooting CI issues as well. We don't generally have a shortage of CI agents so it seems fine to let it run by default. [skip ci] can always be added.

If they want to troubleshoot with the CI then I'd suggest not marking the PR as a draft. I guess it's a fine line, we need to decide where to draw it.
I'm just trying to save CI resources so draft PR are not taking slave and important PRs have to wait.

**Comment by travisn** [comment]
> > @leseb Why not allow the CI to run? The author of a draft PR might be troubleshooting CI issues as well. We don't generally have a shortage of CI agents so it seems fine to let it run by default. [skip ci] can always be added.
> 
> If they want to troubleshoot with the CI then I'd suggest not marking the PR as a draft. I guess it's a fine line, we need to decide where to draw it.
> I'm just trying to save CI resources so draft PR are not taking slave and important PRs have to wait.

Not many PRs are marked as in progress so this may not help us with the CI resources enough. When there is a backlog in the CI it's fine to cancel the non-essential builds. Around releases we do this commonly already.

**Comment by leseb** [comment]
> > > @leseb Why not allow the CI to run? The author of a draft PR might be troubleshooting CI issues as well. We don't generally have a shortage of CI agents so it seems fine to let it run by default. [skip ci] can always be added.
> > 
> > 
> > If they want to troubleshoot with the CI then I'd suggest not marking the PR as a draft. I guess it's a fine line, we need to decide where to draw it.
> > I'm just trying to save CI resources so draft PR are not taking slave and important PRs have to wait.
> 
> Not many PRs are marked as in progress so this may not help us with the CI resources enough. When there is a backlog in the CI it's fine to cancel the non-essential builds. Around releases we do this commonly already.

Well you know that very few people read the doc so `[skip ci]` is not used as much as it should. And they are people actually using the draft functionality.
Also, it's annoying to have to kill job manually so if this could be reduced by this PR...

It's still bringing (maybe small) benefits, so I  don't see why we should not to it. I guess I get frustrated when I see a "useless" CI run... that's all :)

**Pull request merged**
