### PR TITLE
WIP: Minio integration test

### LINKED ISSUE #1804: End to end integration test for Minio
We need an end to end integration test for Minio to sanity/smoke test its basic functionality as part of continuous integration.  This test should be dependent on #1788 so that we ensure our test solution scales as more providers are added.

### PR DESCRIPTION
**Pull request by tonya11en**
**Description of your changes:**
Minimal Minio integration test. Note that this PR is open to verify that the integration test can run in the remote environment. It's currently not ready for review.

**Which issue is resolved by this Pull Request:**
Resolves #1804

### CODE REVIEW

**Comment by jbw976** [comment]
@tonya11en do you have a timeframe for when you'd be able to get back to this minio integration test PR?

**Comment by tonya11en** [comment]
@jbw976 sorry for the delay, I'll try to address the comments this weekend.

**Comment by jbw976** [comment]
@tonya11en any update or ETA for when you could take another look at these minio integration tests?

**Comment by jbw976** [comment]
@tonya11en did you mean to close this?  I'll take over the effort if you aren't going to get back to it.

**Pull request closed without merging**
