### PR TITLE
rgw: bulk data pool by default

### LINKED ISSUE #14770: CephObjectStore data pools should have bulk flag set by default
RGW data pools are expected to be large, so mark them as "bulk" so that the PG autoscaler will treat them accordingly (see https://docs.ceph.com/en/reef/rados/operations/placement-groups/) In short, it will precreate a full number of PGs, so that the cluster works with optimal performance from day 1.

CephFS volumes already do this by default for its data pools [1] the same logic should apply for Object. 

[1] https://github.com/ceph/ceph/blob/main/src/pybind/mgr/volumes/fs/operations/volume.py#L84-L86

### PR DESCRIPTION
**Pull request by arttor**
Closes #14770

sets bulk=true for rgw osd data pool by default

### CODE REVIEW

**Review by BlaineEXE — COMMENTED** [review]
It would probably be nice to have a note of this in PendingReleaseNotes.md. It'll be good for users to have as a note, if it's relevant for them

**Review by travisn — CHANGES_REQUESTED** [review]
Actually, I'd like to suggest a different approach as I ponder this more... What if we just add the `bulk: true` setting to all of the object examples such as [object.yaml](https://github.com/rook/rook/blob/master/deploy/examples/object.yaml#L21)? Then we won't be forcing the flag, it will be an obvious setting in the object.yaml, and nobody should be surprised by it.

**Comment by arttor** [comment]
@travisn just tested with `object-test.yaml` locally and it seems working:
```shell
bash-5.1$ ceph osd pool get my-store.rgw.buckets.data bulk
bulk: true
bash-5.1$ ceph osd pool get my-store.rgw.meta bulk
bulk: false
```

My understandig that Rook has a diffrent behaviour from RGW which sets `bulk` flag for data pool automatically according to this PR https://github.com/ceph/ceph/pull/51497.  

Should we revert this change and update examples instead?

**Comment by BlaineEXE** [comment]
I would suggest that we consider doing both. I think it's okay for Rook to default `bulk = true` (as in this PR), but we do want to make sure users can opt out if needed. That seems to be the strategy Ceph itself has taken.

**Comment by travisn** [comment]
Yeah, I was also concerned with the code changes that there was no way to opt out. If we just revert this and update the examples, it avoids all those concerns.

**Comment by arttor** [comment]
> However, maybe the bigger concern with the current Rook-defaulting behavior is whether this will cause data movement in brownfield clusters when users upgrade. If bulk=true causes data movement, then maybe Travis' suggestion is best.

You are right. I've just asked @dvanders and he says that setting `bulk: true` may increase number of PG and it will move data. I will revert changes and update examples.

Alternatively, i can set `bulk=option` [only on pool creation](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/client/pool.go#L432). But in this case i will have to add extra arg to multiple functions.

**Comment by travisn** [comment]
Ok, how about we add it to examples for now? Later we can always add code, if we realize more of a requirement.

**Comment by arttor** [comment]
> Ok, how about we add it to examples for now? Later we can always add code, if we realize more of a requirement.

done

**Review by travisn — CHANGES_REQUESTED** [review]
LGTM, there is just one more place in the helm chart [values.yaml](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L590-L594) to update

**Comment by arttor** [comment]
> LGTM, there is just one more place in the helm chart [values.yaml](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L590-L594) to update

added

**Review by travisn — APPROVED** [review]

**Pull request merged**
