### PR TITLE
Add k8s 1.11 to the test matrix

### LINKED ISSUE #1840: Enable CI tests for K8s 1.11
Since K8s 1.11 was released, Jenkins needs to add it to the pipeline.

### PR DESCRIPTION
**Pull request by travisn**
Signed-off-by: travisn <tnielsen@redhat.com>

**Description of your changes:**
With the release of K8s 1.11, Rook needs to run the integration tests there. This PR also updates the older versions to their latest dot releases.

**Which issue is resolved by this Pull Request:**
Resolves #1840

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] `make vendor` does not cause changes.

### CODE REVIEW

**Comment by travisn** [comment]
@jbw976 yes, the template has been added in jenkins for 1.11. I'll check if minikube has 1.11 support yet.

**Comment by travisn** [comment]
@jbw976 minikube v0.28.0 still shows the newest version of k8s available is v1.10.0. For now we can use the multi-node env with kubeadm to get v1.11.0

**Comment by jbw976** [comment]
@travisn yeah we only use the localkube bootstrapper for 1.7, so using kubeadm bootstrapper for 1.11 now should hopefully work with minimal effort for us.

**Comment by jbw976** [comment]
did you want to make the minikube.sh update (to make 1.11 the default?) to be part of this script?

**Comment by travisn** [comment]
@jbw976 i see now, yes I'll make 1.11 the default

**Comment by travisn** [comment]
Note that to bring up 1.11 with minikube requires the latest and greatest [v0.28.1](https://github.com/kubernetes/minikube/releases/tag/v0.28.1) due to [this issue](https://github.com/kubernetes/minikube/issues/2942).

**Pull request merged**
