### PR TITLE
Remove rook-api and rookctl

### PR DESCRIPTION
**Pull request by ichekrygin**
### Overview
Removing deprecated components: `rook-api` and `rookctl`

Which issue is resolved by this Pull Request:
Related to #1122, #704 and #1412 (PR: #1471)

### Pending Changes
Needed documentation update

Checklist:
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by travisn** [comment]
Nice to have this cleaned up. A couple thoughts:
- You should be able to remove `pkg/daemon/api` as well
- With rookctl removed, I really don't see a compelling reason to use the toolbox pod anymore. What I'm suggesting is out of scope of this PR, but we should just be able to connect to any rook pod and run ceph commands to troubleshoot. The other part is that we just need to generate the ceph config in the default location instead of a custom location which requires all the args to the ceph tools.

**Comment by bassam** [comment]
Would be great to complete this work @ichekrygin @jbw976 @travisn. What can we do in the short term to fix the unit tests to not use rook-api?

**Comment by travisn** [comment]
The tests do use the api quite extensively, so we would either need to disable those tests or work through fixing them. The basic steps would include:
1) Remove the method `CreateRestAPIClient`, which is called during setup of all tests. This is blocking everything from running
2) Remove the references to `restClient`. Some of these references can be replaced by CRD create/deletes such as for object, file, and pools. There is already test code that does that, so it should be straight forward to get rid of that code path
3) Some functionality is obsolete through the API around the object store users and buckets. In object.go we would just need to remove those tests.
4) Getting rook status may be a bit of work to call the ceph tools instead

**Comment by jbw976** [comment]
Also this entire file can be removed since it is specifically testing block operations via the rook rest API: https://github.com/rook/rook/blob/master/tests/integration/block_createBlock_api_test.go

**Comment by travisn** [comment]
Replacing this with #1573

**Pull request closed without merging**
