### PR TITLE
ceph: update csi sidecar version references to the latest

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by humblec** [comment]
@travisn ptal.. thanks!

**Comment by humblec** [comment]
```
Run timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
+ timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
Defaulted container "fs-mirror" out of: fs-mirror, chown-container-data-dir (init)
waiting for connection to peer
```

**Comment by humblec** [comment]
cc @leseb

**Comment by leseb** [comment]
> ```
> Run timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
> + timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
> Defaulted container "fs-mirror" out of: fs-mirror, chown-container-data-dir (init)
> waiting for connection to peer
> ```

Unrelated. Waiting for @travisn to approve.

**Comment by leseb** [comment]
> > ```
> > Run timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
> > + timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
> > Defaulted container "fs-mirror" out of: fs-mirror, chown-container-data-dir (init)
> > waiting for connection to peer
> > ```
> 
> Unrelated. Waiting for @travisn to approve.

Ah sorry I thought it was https://github.com/rook/rook/pull/8803, nevermind.

**Review by leseb — CHANGES_REQUESTED** [review]
You don't need 3 commits for this. One will suffice. Thanks

**Comment by humblec** [comment]
> You don't need 3 commits for this. One will suffice. Thanks

@leseb consolidated to one commit. ptal .. thanks.

**Review by leseb — APPROVED** [review]

**Review by travisn — APPROVED** [review]

**Pull request merged**
