### PR TITLE
docs: update Example Configurations document 

### PR DESCRIPTION
**Pull request by chienfuchen32**
Some link fixing in [Example Configurations](https://rook.io/docs/rook/v1.9/Getting-Started/example-configurations/\#block-devices)
**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by chienfuchen32** [comment]
@parth-gr confirm the changes for me, please

**Comment by parth-gr** [comment]
> @parth-gr confirm the changes for me, please

looks good:)

**Comment by parth-gr** [comment]
one more place if you can change this too https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Block-Storage-RBD/rbd-mirroring.md#restore-the-backup-on-cluster-2 correct directory,

**Comment by chienfuchen32** [comment]
> one more place if you can change this too https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Block-Storage-RBD/rbd-mirroring.md#restore-the-backup-on-cluster-2 correct directory,

cool, thanks for the reminder.

**Review by subhamkrai — APPROVED** [review]
LGTM, please squash the commits. 

Thanks for the PR.

**Review by travisn — CHANGES_REQUESTED** [review]
@chienfuchen32 Thanks for the fix! Could you just squash to a single commit? They are the same fix and same message, so we prefer one commit.

**Review by travisn — APPROVED** [review]

**Pull request merged**
