### PR TITLE
build: Update default ceph version to v17.2.7

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
The default ceph version in the docs and examples is updated to v17.2.7 for the new patch release of Quincy.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
Related: https://github.com/rook/rook/issues/12099

**Comment by travisn** [comment]
Opened issue #13136 to track the OSD issues with v17.2.7.

**Review by subhamkrai — COMMENTED** [review]
This is not planned to merge before the issue is fixed. right?

**Comment by travisn** [comment]
> This is not planned to merge before the issue is fixed. right?

Correct, we first need a fix before merging.

**Comment by travisn** [comment]
Closing this, as we will need to wait for v17.2.8 for the fix to ceph-volume.

**Pull request closed without merging**
