### PR TITLE
ceph: genericize alerts

### PR DESCRIPTION
**Pull request by muff1nman**
In the case of multiple clusters with different scrape jobs
these alerts can be more useful if separated out by job

**Checklist:**

- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [x] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

[skip ci]

### CODE REVIEW

**Comment by umangachapagain** [comment]
@anmolsachan PTAL.

**Comment by umangachapagain** [comment]
@muff1nman Thanks for the PR. We currently sync the alerting rules from https://github.com/ceph/ceph-mixins. So, your changes here will be overwritten unless you update at `ceph-mixins`. Could you do that? It's straightforward.

**Comment by leseb** [comment]
@muff1nman any updates here? Any plan to address @umangachapagain suggestion?

**Comment by muff1nman** [comment]
I'll take a look.

**Pull request closed without merging**
