### PR TITLE
operator: start one mon at a time

### PR DESCRIPTION
**Pull request by travisn**
Backport the mon startup improvement to 0.5.1

### CODE REVIEW

**Comment by jbw976** [comment]
should there be some sort of link/note in the commit that it was cherry picked from commit xyz in master?

**Comment by travisn** [comment]
good point, will add the cherry pick comment

**Comment by bassam** [comment]
I dont think you need it in the commit

**Comment by bassam** [comment]
just make a note in the PR and the merge commit will point at the PR. otherwise you need to amend the commits which is a pain

**Comment by travisn** [comment]
Cherry picked from 0af953f2e288adf1ede2ab8e4f313115b2115451

**Pull request merged**
