### PR TITLE
fix arm64 image builds

### LINKED ISSUE #1872: arm64 images are using 64bit images and binaries
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
arm64 images download, then contain x86_64 binaries

**Expected behavior:**
arm64 binaries

**How to reproduce it (minimal and precise):**

Pull on an arm64 device, image will refuse to run. Extracting a binary and running through `file` shows it to be x86_64.
I checked the binary format with the following commands:
```shell
$ docker run --rm -it -v $PWD/tmp:/app busybox cp /bin/busybox /app/
$ docker run --rm -it -v $PWD/tmp:/app --entrypoint /app/busybox rook/ceph:master cp /bin/sh /app/
$ file tmp/sh
tmp/sh: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=765c505bb8a234fcd64ede405fa7fcb25734f06a, stripped
```

 https://i.imgur.com/xEC3Ryx.png

**Environment**:
* OS (e.g. from /etc/os-release): HypriotOS 64bit build (Debian 9 Stretch)
* Kernel (e.g. `uname -a`): Linux pi-cluster-2 4.14.37-hypriotos-v8 #1 SMP PREEMPT Sun Apr 29 17:26:16 UTC 2018 aarch64 GNU/Linux
* Cloud provider or hardware configuration: Raspberry Pi 3B+
* Rook version (use `rook version` inside of a Rook Pod): master
* Kubernetes version (use `kubectl version`): 1.10.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): N/A

### PR DESCRIPTION
**Pull request by bassam**
**Description of your changes:**
We have not been building on arm64 for a long while due to a bug in the makefiles. The CEPH_BASE_IMAGE was set once for amd64 and not again when we cross build, result in amd64 images even on arm architectures.

This fixes the issue but since we've not been building on arm64 the actual image build fails. @BlaineEXE can you please take a look as it seems related to centos packages for arm64.

**Which issue is resolved by this Pull Request:**
Resolves #1872

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [x] `make vendor` does not cause changes.

### CODE REVIEW

**Comment by bassam** [comment]
Failure I'm seeing when running `make build.all`:

```
=== docker build build-685c02d8/ceph-arm64
Sending build context to Docker daemon  41.74MB
Step 1/9 : FROM ceph/daemon-base:v3.0.5-stable-3.0-luminous-centos-7-aarch64
 ---> bc2951f1d7a9
Step 2/9 : RUN yum --assumeyes install         net-tools         nmap-ncat &&     yum clean all && rm -rf /tmp/* /var/tmp/*
 ---> Running in d48cb9dfc653
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot retrieve metalink for repository: epel/aarch64. Please verify its path and try again
```

**Comment by travisn** [comment]
@bassam i also saw that error locally when i was trying to get the arm build going, but it looks like jenkins succeeded with these changes. There's not a way to get access to the jenkins images since they weren't published, is there?

**Comment by travisn** [comment]
@BlaineEXE are you available to look at this?

**Comment by arm64b** [comment]
> Failure I'm seeing when running make build.all

Is this command `make build.all` running on `amd64` instead of `arm64`? IIRC, currently `arm64` doesn't support cross build and I've tested the local container images built on `arm64`, it works. So I guess this is issue for the cross build on `amd64`...

**Comment by BlaineEXE** [comment]
I think I understand that this issue is caused because the Makefile from `images/` is only called once (getting the first value of x86_64) whereas the Makefile from `images/ceph{,-toolbox}` is called for each arch, which gives the correct result.

My initial thought is that the ceph image base version coming from a file seems to unnecessarily obfuscate the ceph base image being used. Can `CEPH_BASE_IMAGE_BASE` (or similar) not be set in the place where `CEPH_BASE_IMAGE` is set now? 

I'm starting to test the builds now to double check that the fix works on my machine.

This is kind of an aside, but I'm also beginning to look forward to a future where there are many backends for rook. The `images` directory may begin to be bloated if every backend has a `backend` and `backend-toolbox` image. Would it make sense to nest the `ceph` and `ceph-toolbox` images into a dir called `ceph` and have the `images/ceph/Makefile` in turn call the `images/ceph/ceph/Makefile` and `images/ceph/ceph-toolbox/Makefile`?

**Comment by travisn** [comment]
@BlaineEXE thanks for taking a look. Did you also try the changes in this PR and hit the issues with the arm64 `yum` packages?

With multiple backends we do likely need to factor these images differently. It is looking like the more common pattern is that there would be one image per storage provider instead of two, and the main image would just include the provider's tools. I even question if we need a rook toolbox. You can connect to the operator or mon pods to run the `ceph` commands so the common scenario does not require a toolbox.

**Comment by BlaineEXE** [comment]
I'm building w/o these changes and then going to try with them afterwards. I haven't gotten to the arm builds yet. It's going slow. From Bassam's output, it looks like there may be an issue with an upstream centos repo?

I do see two benefits to having a toolbox container:
 - The running ceph containers save space by not having unnecessary packages (fio, s3cmd, ...)
 - The running ceph containers can be hardened aggressively sometime in the future. This would involve removing yum, bash, and many other things that if a malign party got access, would hinder their ability to get through to the rest of the system. The toolbox would be run only when needed, which would limit the attack surface.

**Comment by BlaineEXE** [comment]
This may be something I'm missing, but how do we know that the arm64 builds are actually amd64? When I build without this patch, and run the arm version, I get an error that suggests it is trying to use arm (aarch64).

```
> docker run -it build-78e016c3/ceph-toolbox-base-arm64 bash
/lib/ld-linux-aarch64.so.1: No such file or directory
```

**Comment by travisn** [comment]
#1872 had repro steps to test the image by copying out a binary and looking at its arch.  Using the same repro steps I was able to verify that the upstream ceph arm64 image was the expected architecture, but the rook image was not.

**Comment by bassam** [comment]
I'm all good on this one. @travisn feel free to merge when ready.

**Pull request merged**
