### PR TITLE
csi: Again remove attacher sidecar from CephFS rook deployment

### PR DESCRIPTION
**Pull request by humblec**
This reverts commit 40081cbcd20e7af65351fe2037feac0836737327.

The reason or why we are reverting this commit :

CephFS CSI driver dont implement Controller PUBLISH/UNPUBLISH operation so attacher sidecar  is not required and it got removed via https://github.com/rook/rook/commit/4bfd88dc4df5656acce945d29364e481cb777466

however in absence of the attacher sidecar the  behavior of RWO volume mounting on more than one node got visible which caused some of the acceptance test to fail , thus a revert of the PR was done via https://github.com/rook/rook/commit/40081cbcd20e7af65351fe2037feac0836737327

We were bit in hurry to accept this revert and the plan was to conclude the outcome of the change and bring back or do revert of the revert accordingly. 

It has been concluded that,  

- [x] CephFS is RWX in nature, so more than one node mount shouldnt be an issue  ie RWO volumes any way has multi access so single node or multi node does not make difference here.
If real multi access has to be verified, RWOP accessmode of CephFS volumes can be the right acceptance test.
https://kubernetes.io/blog/2021/09/13/read-write-once-pod-access-mode-alpha/
- [x]  There is no backward compatibility break here.
- [x]  There is also no functional issue or data corruption sort of issue exist with this change.

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by mykaul** [comment]
A revert of a revert... It's always good to provide a one-liner on why we are reverting anything.

**Comment by Madhu-1** [comment]
IMHO its a behavioral change for cephfs RWO PVC. Technically RWO and RWX will behave in the same way anyone can use it on any nodes. if we really want to do it we need to document it.

**Comment by agarwal-mudit** [comment]
/hold
There is a comment from @ShyamsundarR on the epic https://issues.redhat.com/browse/RHSTOR-3332

**Comment by humblec** [comment]
> IMHO its a behavioral change for cephfs RWO PVC. Technically RWO and RWX will behave in the same way anyone can use it on any nodes. if we really want to do it we need to document it.

Yeah, documentation is a fair ask.


>CephFS tests are failing, also marking as changes requested to discuss the change in behavior.

Sure. regarding the test failure, its just a revert so I think its spurious. can look into detail though.

>There is a comment from @ShyamsundarR on the epic https://issues.redhat.com/browse/RHSTOR-3332

I have responded on the same.

**Pull request closed without merging**
