### PR TITLE
ci: Enable flex integration suite on K8s 1.11

### PR DESCRIPTION
**Pull request by subhamkrai**
since this #8422 pr merged in branch 1.7,
ci(master/release integration test) is
failing for flex suite because it is not
able to set up minikube with error
```
Specified Kubernetes version 1.11.10 is less than the oldest
supported version: v1.14.0

! You can force an unsupported Kubernetes version via the --force flag
```
https://github.com/rook/rook/runs/3186798720?check_suite_focus=true

because in that pr we added new k8s version
v1.11.10 for flex suite test.

we are now trying with macos hyperkit for k8s v1.11.10.

Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
#8422

**Comment by subhamkrai** [comment]
it is for branch release-1.7

**Comment by subhamkrai** [comment]
not sure if adding --force will also work, locally it is failing
```
minikube start --kubernetes-version 1.11.10 --force
😄  minikube v1.21.0 on Fedora 34
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
❗  Specified Kubernetes version 1.11.10 is less than the oldest supported version: v1.14.0

🧯  Kubernetes 1.11.10 is not supported by this release of minikube

🆕  Kubernetes 1.20.7 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.20.7
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
E0729 10:32:48.473067   20324 cache.go:211] Error caching images:  cached images list: version too old: 1.11.10
🐳  Preparing Kubernetes v1.11.10 on Docker 20.10.7 ...

❌  Exiting due to K8S_INSTALL_FAILED: kubeadm images: version too old: 1.11.10

╭────────────────────────────────────────────────────────────────────╮
│                                                                    │
│    😿  If the above advice does not help, please let us know:      │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                    │
│    Please attach the following file to the GitHub issue:           │
│    - /home/srai/.minikube/logs/lastStart.txt       
```

also, we need to fix this as CI will be failing in push to release-1.7 branch

**Review by leseb — CHANGES_REQUESTED** [review]
We need a better commit message. What's the failure? Why do you need `--force`, what does it do?

**Review by travisn — CHANGES_REQUESTED** [review]
Could we test this before merge on a temporary action on K8s 1.11 in the PR?

**Comment by subhamkrai** [comment]
> Could we test this before merge on a temporary action on K8s 1.11 in the PR?

@travisn it is failing https://github.com/rook/rook/pull/8424/checks?check_run_id=3193079686#step:4:85
it requires older version of minikube but using older minikube will not support latest k8s version

**Comment by travisn** [comment]
> > Could we test this before merge on a temporary action on K8s 1.11 in the PR?
> 
> @travisn it is failing https://github.com/rook/rook/pull/8424/checks?check_run_id=3193079686#step:4:85
> it requires older version of minikube but using older minikube will not support latest k8s version

Sounds good if we can use an older version of minikube just for that test.

**Comment by subhamkrai** [comment]
> > > Could we test this before merge on a temporary action on K8s 1.11 in the PR?
> > 
> > 
> > @travisn it is failing https://github.com/rook/rook/pull/8424/checks?check_run_id=3193079686#step:4:85
> > it requires older version of minikube but using older minikube will not support latest k8s version
> 
> Sounds good if we can use an older version of minikube just for that test.

k8s v1.11.10 is supported in minikube 1.9.0 and older but in action not able to setup minikube, I tried other combinations like changing /manusa/actions-setup-minikube version but it is not working.

**Comment by travisn** [comment]
Worst case we could trigger Jenkins just to run K8s 1.11 when it is time for a release. The risk of regression for the flex driver is very low since we haven't touched it in so long. 
@leseb Any other ideas for running the flex tests on K8s 1.11?

**Comment by subhamkrai** [comment]
> Worst case we could trigger Jenkins just to run K8s 1.11 when it is time for a release. The risk of regression for the flex driver is very low since we haven't touched it in so long.
> @leseb Any other ideas for running the flex tests on K8s 1.11?

it is docker that is making minikube setup to fail

**Comment by leseb** [comment]
> > Worst case we could trigger Jenkins just to run K8s 1.11 when it is time for a release. The risk of regression for the flex driver is very low since we haven't touched it in so long.
> > @leseb Any other ideas for running the flex tests on K8s 1.11?
> 
> it is docker that is making minikube setup to fail

It's funny to see docker failing as a dependency when using the bare driver...
You could try to use a macos runner with a minikube hyperkit driver.

**Comment by travisn** [comment]
Per discussion, let's not worry about this action due to the following:
- The K8s 1.11 flex tests will be run in Jenkins with #8481, so we have validation that the flex suite does run on 1.11.
- The flex tests anyway run with the CI on 1.15 or newer
- Risk of regression that only affects the flex driver older than k8s 1.15 is extremely low. We have not touched the flex driver or even fixed issues in many releases.
- The flex driver is being removed in v1.8, so investment in continued tests is limited.

**Pull request closed without merging**
