### PR TITLE
ceph: moved multus support out of experimental

### LINKED ISSUE #6748: Take multus out of experimental mode
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Take multus out of the experimental mode.

**What is use case behind this feature:**
Currently, multus support for Rook Ceph is not complete because of https://github.com/ceph/ceph-csi/issues/1323 
After the above issue is fixed, we can have a full multus support.

### PR DESCRIPTION
**Pull request by rohan47**
**Description of your changes:**
moved multus support out of experimental.

**Which issue is resolved by this Pull Request:**
Resolves #6748

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[skip ci]

### CODE REVIEW

**Review by leseb — CHANGES_REQUESTED** [review]
Waiting for Ceph-CSI 3.3 to be in Rook.

**Review by travisn — COMMENTED** [review]
What's the status on #7546? It would be good to merge that one as part of declaring multus as stable.

**Comment by rohan47** [comment]
> What's the status on #7546? It would be good to merge that one as part of declaring multus as stable.

@travisn 
Not able to test the code yet,
do you mean that this PR should move to #7546 
it makes sense to move this PR to #7546 as a separate commit.

**Comment by travisn** [comment]
> > What's the status on #7546? It would be good to merge that one as part of declaring multus as stable.
> 
> @travisn
> Not able to test the code yet,
> do you mean that this PR should move to #7546
> it makes sense to move this PR to #7546 as a separate commit.

No I don't think we need to combine the two PRs, I was really suggesting that we merge #7546 before we declare it stable with this PR.

**Review by leseb — CHANGES_REQUESTED** [review]
Honestly, https://github.com/rook/rook/pull/7546 is just a feature. It is not needed to mark the implementation as stable. It's time to move forward :) 

Please rebase and clear the PendingReleaseNotes.md note.

**Review by leseb — APPROVED** [review]

**Review by travisn — APPROVED** [review]
Looks good for stable since Ceph-CSI 3.3 and Rook v1.6!

**Pull request merged**
