### PR TITLE
DNM: Autogen crd docs EXAMPLE

### PR DESCRIPTION
**Pull request by galexrt**
**Description of your changes:**

TODO Add PR description.

Just a quick example without changing too much from the original code of prometheus/prometheus project, see https://github.com/galexrt/rook/blob/0ff2b68b0d54319f1dc88eb11bfd5f333b78cf94/Documentation/ceph-cluster-crd-new.md for an example output (without any more code comments added to the ceph types).

@travisn @BlaineEXE @leseb What do you think of the example output structure?

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

[skip ci]

**^ Till the code is ready for review**

### CODE REVIEW

**Comment by galexrt** [comment]
@travisn @leseb I have updated the autogen crd docs example files to show better what could be done by splitting up the CRD files for Ceph.
This is an example auto generated CephCluster CRD doc: https://github.com/rook/rook/blob/beefb72f500e3056970e65d7748b7b786ac3cb71/Documentation/ceph-cluster-crd.md
Running `make docs` would regenerate the Ceph CRD docs right now already.

(Please only look at the last commit, as this PR is based on the PR #4166)

**Comment by BlaineEXE** [comment]
I kind of like the second option by splitting up the CRD files. I think the logical separation is nice, and it's a less overwhelming page to view.

**Comment by leseb** [comment]
@galexrt status?

**Comment by leseb** [comment]
Closing this due to inactivity. Feel free to re-open. Thanks.

**Pull request closed without merging**
