### PR TITLE
csi: remove findCSIChange from predicate

### PR DESCRIPTION
**Pull request by Madhu-1**
**Description of your changes:**

findCSIChange will work only for single line values/configuration in the configmap. If the value is multiline, the regex will not
be able to indentify the change because of it no configurations will be applied to the csi driver. Removing this check so that if there is any update on the configmap, we will reconcile the csi driver.

Note:- This might look heavy, but updating the config map is not a frequent event.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by subhamkrai — COMMENTED** [review]
@Madhu-1  can we do similar to this for all the CSI keys or is this too much to handle or manage in the future?
https://github.com/rook/rook/blob/69ccd11b97b8bbfe1ccc5e7dc981fe39dfa89840/pkg/operator/ceph/predicate.go#L67-L78

**Comment by Madhu-1** [comment]
> @Madhu-1 can we do similar to this for all the CSI keys or is this too much to handle or manage in the future?
> 
> https://github.com/rook/rook/blob/69ccd11b97b8bbfe1ccc5e7dc981fe39dfa89840/pkg/operator/ceph/predicate.go#L67-L78

Yes, it will work, but we need to check for all supported keys, and this might be too much, if we do so, we might have a chance to forget where and all we need to change when we introduce a new configuration kind of maintenance burden if we all think it good to have this kind of check we can do it.

**Comment by subhamkrai** [comment]
> > @Madhu-1 can we do similar to this for all the CSI keys or is this too much to handle or manage in the future?
> > https://github.com/rook/rook/blob/69ccd11b97b8bbfe1ccc5e7dc981fe39dfa89840/pkg/operator/ceph/predicate.go#L67-L78
> 
> Yes, it will work, but we need to check for all supported keys, and this might be too much, if we do so, we might have a chance to forget where and all we need to change when we introduce a new configuration kind of maintenance burden if we all think it good to have this kind of check we can do it.

okay, that makes sense. Thanks for explaining.

**Review by travisn — APPROVED** [review]
Agreed that it's best to reconcile every time since the configmap updates are rare, even if in some cases the reconcile may not be necessary.

**Pull request merged**
