### PR TITLE
ci: update K8s version for stability

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
**Description of your changes:**

K8s v1.16.13 is used in CI. In this version, there is a serious bug which causes a continuous restart of both kube-scheduler
and kube-controller-manager. It results in the instability of CI.

This bug is fixed in v1.16.14 or later by the following PR.

https://github.com/kubernetes/kubernetes/pull/93208

Both #6415 and #6390, which only happen in v1.16.13, would be caused by this issue.

**Which issue is resolved by this Pull Request:**

Probably #6415 and #6390.

**Checklist:**

- [o] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [o] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [o] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [o] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [o] Documentation has been updated, if necessary.
- [o] Unit tests have been added, if necessary.
- [o] Integration tests have been added, if necessary.
- [o] Pending release notes updated with breaking and/or notable changes, if necessary.
- [o] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [o] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test full]

### CODE REVIEW

**Comment by satoru-takeuchi** [comment]
I intentionally don't run the full test because the CI for this PR runs with the old Jenkinsfile that uses K8s v1.16.13 and then CI would always fail in the integration test in v1.16.x.

**Comment by leseb** [comment]
> I intentionally don't run the full test because the CI for this PR runs with the old Jenkinsfile that uses K8s v1.16.13 and then CI would always fail in the integration test in v1.16.x.

Are you sure the CI does not pick up your Jenkins file change?

**Comment by satoru-takeuchi** [comment]
> Are you sure the CI does not pick up your Jenkins file change?

Yes, when I last tried it about one month ago about another PR.

I read it as well.
https://github.com/rook/rook/pull/4984#issuecomment-596423036
> Could I ask you a question? How can I change Jenkins setting on this CI? I've already revised Jenkinsfile to use go mod and pushed that commit (https://github.com/rook/rook/pull/4984/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3L65), but it doesn't seem to apply changes to Jenkins.

https://github.com/rook/rook/pull/4984#issuecomment-596579033
> @leseb @moricho can't change the Jenkinsfile because "admin" permissions in the Jenkins are required AFAIK

However, I recalled I get the access right of Jenkins recently. If it's  "admin" permission. CI can pick up my Jenkinsfile. I'll try it anyway.

**Comment by leseb** [comment]
> > Are you sure the CI does not pick up your Jenkins file change?
> 
> Yes, when I last tried it about one month ago about another PR.
> 
> I read it as well.
> [#4984 (comment)](https://github.com/rook/rook/pull/4984#issuecomment-596423036)
> 
> > Could I ask you a question? How can I change Jenkins setting on this CI? I've already revised Jenkinsfile to use go mod and pushed that commit (https://github.com/rook/rook/pull/4984/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3L65), but it doesn't seem to apply changes to Jenkins.
> 
> [#4984 (comment)](https://github.com/rook/rook/pull/4984#issuecomment-596579033)
> 
> > @leseb @moricho can't change the Jenkinsfile because "admin" permissions in the Jenkins are required AFAIK
> 
> However, I recalled I get the access right of Jenkins recently. If it's "admin" permission. CI can pick up my Jenkinsfile. I'll try it anyway.

Yes let's try, thanks!

**Comment by satoru-takeuchi** [comment]
@leseb Unfortunately CI seems to run with the old Jenkinsfile. The problematic v1.16.13 is used.

https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6421/3/pipeline/59
> running tests on k8s version v1.16.13

Can I get admin permission? Or should I fallback to non-full test?

**Comment by travisn** [comment]
> @leseb Unfortunately CI seems to run with the old Jenkinsfile. The problematic v1.16.13 is used.
> 
> https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6421/3/pipeline/59
> 
> > running tests on k8s version v1.16.13
> 
> Can I get admin permission? Or should I fallback to non-full test?

Jenkins should pick up changes to the Jenkinsfile for any member of the rook github team, so I don't see why the CI isn't picking up the change. I'd suggest we go ahead and merge. The 1.16 builds have certainly been unreliable lately, so it can't get any worse!

**Review by travisn — APPROVED** [review]

**Comment by satoru-takeuchi** [comment]
@travisn @leseb 

This problem didn't happen in a full test after merging this PR.
https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6184/40/pipeline/58

```
2020-10-12 22:23:11.420498 I | installer: Installing rook on k8s v1.16.15
...
--- PASS: TestCephFlexSuite (547.45s)
    --- PASS: TestCephFlexSuite/TestBlockStorageMountUnMountForDifferentAccessModes (151.45s)
    --- PASS: TestCephFlexSuite/TestBlockStorageMountUnMountForStatefulSets (84.45s)
    --- PASS: TestCephFlexSuite/TestFileSystem (121.26s)
...
--- PASS: TestCephHelmSuite (618.20s)
    --- PASS: TestCephHelmSuite/TestARookInstallViaHelm (0.04s)
    --- PASS: TestCephHelmSuite/TestBlockStoreOnRookInstalledViaHelm (112.60s)
    --- PASS: TestCephHelmSuite/TestFileStoreOnRookInstalledViaHelm (128.59s)
    --- PASS: TestCephHelmSuite/TestObjectStoreOnRookInstalledViaHelm (196.39s)
....
```

Before this PR, CephFlexSuite sometimes failed and CephHelmSuite failed in most cases.

**Pull request merged**
