### PR TITLE
Revert "csi: remove attacher sidecar from CephFS rook deployment"

### PR DESCRIPTION
**Pull request by agarwal-mudit**
This reverts commit 4bfd88dc4df5656acce945d29364e481cb777466.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

This is blocking the downstream ci, let's revert the commit till we have a proper resolution for #10692

### CODE REVIEW

**Review by subhamkrai — APPROVED** [review]
LGTM

**Review by Madhu-1 — APPROVED** [review]
This should fix https://github.com/rook/rook/issues/10692

**Comment by humblec** [comment]
@agarwal-mudit @travisn actually this revert is not required or its not the right approach for the issue reported. RWO volumes in this case can be mounted in more than one Node and no issues with that! more or less, CephFS is RWX in nature and also if the user really wanted to have (real) RWO access , they have to use RWOP accessmode.

**Comment by agarwal-mudit** [comment]
This a temporary measure to unblock the whole release, we can take it back once everything is clear.

**Comment by humblec** [comment]
@agarwal-mudit sure, the RCA is pretty much same as https://github.com/rook/rook/pull/10695#issuecomment-1211964900, however we can bring back accordingly.

**Pull request merged**
