### PR TITLE
Fix helm chart to allow multiple filesystems

### PR DESCRIPTION
**Pull request by SerialVelocity**
**Description of your changes:**
If you enable `allowMultipleFilesystems`, the chart will generate an invalid yaml file.

(@leseb for SA)

**Which issue is resolved by this Pull Request:**
Resolves an error introduced in #7307

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by SerialVelocity** [comment]
Can this be backported to 1.6.x too?

**Review by travisn — CHANGES_REQUESTED** [review]
The change looks good, we just need a commit message that the bot will be happy about. See [this topic](https://rook.io/docs/rook/master/development-flow.html#commit-structure). Basically, you need to add the "ceph: <title>" prefix to the subject, and also if you could add a sentence or two in the commit description about the change. Thanks!

**Comment by travisn** [comment]
@SerialVelocity Also note that this flag is not required to run multiple filesystems on Ceph Pacific since it is fully supported there. Multiple filesystems isn't recommended prior to Pacific. Have you tried Pacific?

**Comment by SerialVelocity** [comment]
@travisn Yes, I know it isn't required for Pacific. I recently upgraded and hit 
https://tracker.ceph.com/issues/50656 so I had to add `bluestore allocator = bitmap` to my config.

But when I was upgrading from 1.5.x to 1.6.2 I hit this bug so thought I may as well fix it.

**Comment by SerialVelocity** [comment]
Fixed the commit message

**Comment by subhamkrai** [comment]
> Fixed the commit message

one error `subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]`

**Comment by SerialVelocity** [comment]
Probably fixed now?

**Review by travisn — APPROVED** [review]

**Pull request merged**
