### PR TITLE
golang 1.11 support

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

Changes to support golang 1.11

Resolves # NA

- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [x] `make vendor` does not cause changes.
- [x] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by ganeshmaharaj** [comment]
go fmt has a change to it's heuristic that deals with spaces described [here](https://github.com/golang/go/commit/542ea5ad91367d2b40589942cc5757a4d5f43f97) and that is causing formatting that will break all other previous versions. Leaving this PR here to get some time figure this out.

**Comment by bassam** [comment]
@ganeshmaharaj thanks. can you please also update the go version in our build container: https://github.com/rook/rook/blob/master/images/cross/Dockerfile#L40

**Comment by ganeshmaharaj** [comment]
`exec: "gcc": executable file not found in $PATH` is that error from the CI build. i am guessing we need to build that into the default image? @bassam any pointers on where i could specify that?

**Comment by bassam** [comment]
what happens when you run the changes with go 10.x? Make we can make the makefile handle both scenarios.

**Comment by ganeshmaharaj** [comment]
when you run `make` with golang 1.10 you will have `go fmt` failing with formatting issues on the sources files changed in this patch. I have not been able to find a way keep both version of `go fmt` happy with a single set of sources. I will try to dig into that see if that is something that can be done.

**Comment by bassam** [comment]
See https://github.com/golang/go/issues/26397 for the gofmt issues. Looks like the go fmt behavior changed in 1.11 and the best solution is to use a specific version of gofmt regardless of go version

**Comment by bassam** [comment]
@ganeshmaharaj here's a proposed fix: https://github.com/bassam/rook/commit/5c951d308e5187a732ff162c75696fe6ec312dbd

It uses a consistent version of gofmt regardless of what's running on the host.

**Comment by ganeshmaharaj** [comment]
@bassam thanks for the patch. yes, this will definitely do it for forcing a single go fmt version. i have cherry-picked your patch onto the branch.

**Comment by ganeshmaharaj** [comment]
```
2018-09-12 16:53:22.485694 E | utils: Failed to execute: kubectl [delete --grace-period=0 pod setup-block-rwo] : Failed to complete 'kubectl': exit status 1. . Error from server (NotFound): pods "setup-block-rwo" not found

2018-09-12 16:53:22.485739 I | exec: Running command: kubectl delete --grace-period=0 pod setup-block-rwx

2018-09-12 16:53:22.577856 E | utils: Failed to execute: kubectl [delete --grace-period=0 pod setup-block-rwx] : Failed to complete 'kubectl': exit status 1. . Error from server (NotFound): pods "setup-block-rwx" not found

2018-09-12 16:53:22.577890 I | exec: Running command: kubectl delete --grace-period=0 pod rwo-block-rw-one

2018-09-12 16:53:22.667696 E | utils: Failed to execute: kubectl [delete --grace-period=0 pod rwo-block-rw-one] : Failed to complete 'kubectl': exit status 1. . Error from server (NotFound): pods "rwo-block-rw-one" not found

2018-09-12 16:53:22.667735 I | exec: Running command: kubectl delete --grace-period=0 pod rwo-block-rw-two

2018-09-12 16:53:22.771247 E | utils: Failed to execute: kubectl [delete --grace-period=0 pod rwo-block-rw-two] : Failed to complete 'kubectl': exit status 1. . Error from server (NotFound): pods "rwo-block-rw-two" not found

2018-09-12 16:53:22.771279 I | exec: Running command: kubectl delete --grace-period=0 pod rwo-block-ro-one
```
Errors seem to be unrelated to the issue. I wonder why i am not seeing the system and dmesg logs from the build. Wondering if i need to rebase my branch to the latest master to pickup the `Jenkinsfile` change for it to show here.

**Pull request merged**
