### PR TITLE
ci: test pr

### LINKED ISSUE #10157: golangCI linter should report gostatic errors
**Is this a bug report or feature request?**
* Bug Report

Our golangCI linter not reporting go static errors but seems like static check lint is enabled by default in golangCI lint https://golangci-lint.run/usage/linters/
Maybe we updating golangCI works.
more details https://github.com/rook/rook/pull/10147#issuecomment-1108728369

**Deviation from expected behavior:**
golangCI linter does not report gostatic errors

**Expected behavior:**
golangCI linter should report gostatic errors

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

### PR DESCRIPTION
**Pull request by subhamkrai**
this is test PR

Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #10157

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@galexrt any ideas golangci lint GitHub action not able to detect gostatic errors or behaviour weirdly in CI. Updating versions didn't help

**Comment by subhamkrai** [comment]
> @subhamkrai I have a suspicion that it might be the `--timeout=6m` that is not enough (anymore) as looking at the logs in GitHub Actions I have a an empty `Error:` bar: image
> 
> If that is not the culprit, can you try to enable the `staticcheck` by adding it to the `-E` flag, even though it should be enabled by default https://golangci-lint.run/usage/linters/

I tried both seems like not working

**Comment by subhamkrai** [comment]
@galexrt I increased the time to `20m` the test didn't fail. Also, in my local run the test is not failing
```code
rai@ ~/go/src/github.com/rook/rook (check-golancg-ci) 
$ golangci-lint run ./... --timeout=10m
srai@ ~/go/src/github.com/rook/rook (check-golancg-ci) 
```

**Comment by galexrt** [comment]
@subhamkrai Are you using VS Code? If so, do you also see the staticcheck issues in the problems list for Rook (e.g., run CTRL+Shift+P and then `Go: Lint Workspace`)?

Maybe the upstream project https://github.com/golangci/golangci-lint knows why the staticcheck issues are not appearing (always) during the CI but only when run manually in VS Code, could you please check with them?

**Comment by subhamkrai** [comment]
> @subhamkrai Are you using VS Code? If so, do you also see the staticcheck issues in the problems list for Rook (e.g., run CTRL+Shift+P and then `Go: Lint Workspace`)?

Yes
> 
> Maybe the upstream project https://github.com/golangci/golangci-lint knows why the staticcheck issues are not appearing (always) during the CI but only when run manually in VS Code, could you please check with them?

https://github.com/golangci/golangci-lint/discussions/2901

**Comment by subhamkrai** [comment]
I didn't hear from the golangci team, was thinking of closing this pr 😞

**Comment by subhamkrai** [comment]
@galexrt ^^

**Comment by galexrt** [comment]
Yeah, let's close this for now.

**Pull request closed without merging**
