### PR TITLE
ci: Canary tests on PVCs are failing when creating OSDs

### PR DESCRIPTION
**Pull request by satoru-takeuchi**
**Description of your changes:**

Debug the recent failures of canary tests.

Canary tests fail in high possibility [like this raw-disk test](https://github.com/rook/rook/actions/runs/4045947962/jobs/6958124962).  This problem is not completely consistent. One example is that there is at least one [succeeded raw-disk test](https://github.com/rook/rook/actions/runs/4040950738/jobs/6947054870).

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by satoru-takeuchi** [comment]
> + return current status: cluster: id: e130a535-e865-4b59-b111-99901ebfe277 health: HEALTH_WARN mon a is low on available space OSD count 1 '<' osd_pool_default_size 3 services: mon: 1 daemons, quorum a '(age' '6m)' mgr: 'a(active,' since '5m)' osd: 1 osds: 1 up '(since' '5m),' 1 in '(since' '5m)' data: pools: 0 pools, 0 pgs objects: 0 objects, 0 B usage: 4.8 MiB used, 6.0 GiB / 6 GiB avail pgs:

monstore might be small.

**Comment by satoru-takeuchi** [comment]
sshed to [this test's runner](https://github.com/rook/rook/actions/runs/4059946388/jobs/6991753089).

```
$ kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph -s
  cluster:
    id:     b5ff6326-ea93-43b3-8917-c2c475956457
    health: HEALTH_WARN
            mon a is low on available space
            OSD count 1 < osd_pool_default_size 3

  services:
    mon: 1 daemons, quorum a (age 13m)
    mgr: a(active, since 12m)
    osd: 1 osds: 1 up (since 11m), 1 in (since 11m)

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   4.8 MiB used, 6.0 GiB / 6 GiB avail
    pgs:


$ kubectl -n rook-ceph get pod
NAME                                            READY   STATUS             RESTARTS      AGE
csi-cephfsplugin-5fp8j                          2/2     Running            0             9m54s
csi-cephfsplugin-provisioner-75b9f74d7b-6ktw7   5/5     Running            0             9m53s
csi-nfsplugin-bqkxc                             2/2     Running            0             9m53s
csi-nfsplugin-provisioner-7554fddd47-9fwdx      4/4     Running            0             9m53s
csi-rbdplugin-gqcnq                             2/2     Running            0             9m54s
csi-rbdplugin-provisioner-66d48ddf89-pjgzc      5/5     Running            0             9m54s
rook-ceph-mgr-a-c7db49b8f-68rwh                 1/1     Running            0             8m47s
rook-ceph-mon-a-859b546d74-gbr7v                1/1     Running            0             9m44s
rook-ceph-operator-649dfd8dcd-zt6tg             1/1     Running            0             10m
rook-ceph-osd-0-68bdff74f9-kl87s                1/1     Running            0             7m59s
rook-ceph-osd-prepare-set1-data-097cx4-7p24q    0/1     CrashLoopBackOff   3 (19s ago)   92s
rook-ceph-osd-prepare-set1-data-1kfbr5-jvfvt    0/1     CrashLoopBackOff   3 (36s ago)   95s
rook-ceph-osd-prepare-set1-data-2llpjq-jsr2p    0/1     Completed          0             8m25s
rook-ceph-tools-54bdbfc7b7-d9slj                1/1     Running            0             10m
$ kubectl -n rook-ceph logs rook-ceph-osd-prepare-set1-data-097cx4-7p24q
[2023-02-01 06:46:57,432][ceph_volume.main][INFO  ] Running command: ceph-volume --log-path /var/log/ceph/set1-data-097cx4 raw prepare --bluestore --data /mnt/set1-data-097cx4
[2023-02-01 06:46:57,437][ceph_volume.util.disk][WARNING] CEPH_VOLUME_ALLOW_LOOP_DEVICES is set in your environment, so we will allow the use of unattached loop devices as disks. This feature is intended for development purposes only and will never be supported in production. Issues filed based on this behavior will likely be ignored.
[2023-02-01 06:46:57,533][ceph_volume.util.system][WARNING] Executable lvs not found on the host, will return lvs as-is
[2023-02-01 06:46:57,533][ceph_volume.process][INFO  ] Running command: lvs --noheadings --readonly --separator=";" -a --units=b --nosuffix -S lv_path=/mnt/set1-data-097cx4 -o lv_tags,lv_path,lv_name,vg_name,lv_uuid,lv_size
[2023-02-01 06:46:57,749][ceph_volume.process][INFO  ] Running command: /usr/bin/lsblk -P -o NAME,KNAME,PKNAME,MAJ:MIN,FSTYPE,MOUNTPOINT,LABEL,UUID,RO,RM,MODEL,SIZE,STATE,OWNER,GROUP,MODE,ALIGNMENT,PHY-SEC,LOG-SEC,ROTA,SCHED,TYPE,DISC-ALN,DISC-GRAN,DISC-MAX,DISC-ZERO,PKNAME,PARTLABEL
[2023-02-01 06:46:57,767][ceph_volume.process][INFO  ] stdout NAME="loop0" KNAME="loop0" PKNAME="" MAJ:MIN="7:0" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="" SIZE="6G" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="512" LOG-SEC="512" ROTA="0" SCHED="none" TYPE="loop" DISC-ALN="0" DISC-GRAN="0B" DISC-MAX="0B" DISC-ZERO="0" PKNAME="" PARTLABEL=""
[2023-02-01 06:46:57,767][ceph_volume.process][INFO  ] stdout NAME="loop1" KNAME="loop1" PKNAME="" MAJ:MIN="7:1" FSTYPE="ceph_bluestore" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="" SIZE="6G" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="512" LOG-SEC="512" ROTA="1" SCHED="none" TYPE="loop" DISC-ALN="0" DISC-GRAN="4K" DISC-MAX="4G" DISC-ZERO="0" PKNAME="" PARTLABEL=""
[2023-02-01 06:46:57,767][ceph_volume.process][INFO  ] stdout NAME="loop2" KNAME="loop2" PKNAME="" MAJ:MIN="7:2" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="" SIZE="6G" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="512" LOG-SEC="512" ROTA="0" SCHED="none" TYPE="loop" DISC-ALN="0" DISC-GRAN="0B" DISC-MAX="0B" DISC-ZERO="0" PKNAME="" PARTLABEL=""
[2023-02-01 06:46:57,767][ceph_volume.process][INFO  ] stdout NAME="loop4" KNAME="loop4" PKNAME="" MAJ:MIN="7:4" FSTYPE="ceph_bluestore" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="" SIZE="6G" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="512" LOG-SEC="512" ROTA="0" SCHED="none" TYPE="loop" DISC-ALN="0" DISC-GRAN="4K" DISC-MAX="4G" DISC-ZERO="0" PKNAME="" PARTLABEL=""
[2023-02-01 06:46:57,767][ceph_volume.process][INFO  ] stdout NAME="sda" KNAME="sda" PKNAME="" MAJ:MIN="8:0" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="Virtual Disk    " SIZE="14G" STATE="running" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="512" LOG-SEC="512" ROTA="1" SCHED="mq-deadline" TYPE="disk" DISC-ALN="0" DISC-GRAN="32M" DISC-MAX="4G" DISC-ZERO="0" PKNAME="" PARTLABEL=""
[2023-02-01 06:46:57,767][ceph_volume.process][INFO  ] stdout NAME="sda1" KNAME="sda1" PKNAME="sda" MAJ:MIN="8:1" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="" SIZE="6G" STATE="" OWNER="ceph" GROUP="ceph" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="512" LOG-SEC="512" ROTA="1" SCHED="mq-deadline" TYPE="part" DISC-ALN="32505856" DISC-GRAN="32M" DISC-MAX="4G" DISC-ZERO="0" PKNAME="sda" PARTLABEL="osd-1"
[2023-02-01 06:46:57,767][ceph_volume.process][INFO  ] stdout NAME="sda2" KNAME="sda2" PKNAME="sda" MAJ:MIN="8:2" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="" SIZE="6G" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="512" LOG-SEC="512" ROTA="1" SCHED="mq-deadline" TYPE="part" DISC-ALN="32505856" DISC-GRAN="32M" DISC-MAX="4G" DISC-ZERO="0" PKNAME="sda" PARTLABEL="osd-2"
[2023-02-01 06:46:57,771][ceph_volume.process][INFO  ] stdout NAME="sdb" KNAME="sdb" PKNAME="" MAJ:MIN="8:16" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="Virtual Disk    " SIZE="86G" STATE="running" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="4096" LOG-SEC="512" ROTA="1" SCHED="mq-deadline" TYPE="disk" DISC-ALN="0" DISC-GRAN="2M" DISC-MAX="4G" DISC-ZERO="0" PKNAME="" PARTLABEL=""
[2023-02-01 06:46:57,771][ceph_volume.process][INFO  ] stdout NAME="sdb1" KNAME="sdb1" PKNAME="sdb" MAJ:MIN="8:17" FSTYPE="ext4" MOUNTPOINT="/var/lib/ceph/crash" LABEL="cloudimg-rootfs" UUID="760924d9-efa3-415d-b09e-38a41f2a7979" RO="0" RM="0" MODEL="" SIZE="85.9G" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="4096" LOG-SEC="512" ROTA="1" SCHED="mq-deadline" TYPE="part" DISC-ALN="1048576" DISC-GRAN="2M" DISC-MAX="4G" DISC-ZERO="0" PKNAME="sdb" PARTLABEL=""
[2023-02-01 06:46:57,771][ceph_volume.process][INFO  ] stdout NAME="sdb14" KNAME="sdb14" PKNAME="sdb" MAJ:MIN="8:30" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="" SIZE="4M" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="4096" LOG-SEC="512" ROTA="1" SCHED="mq-deadline" TYPE="part" DISC-ALN="1048576" DISC-GRAN="2M" DISC-MAX="4G" DISC-ZERO="0" PKNAME="sdb" PARTLABEL=""
[2023-02-01 06:46:57,771][ceph_volume.process][INFO  ] stdout NAME="sdb15" KNAME="sdb15" PKNAME="sdb" MAJ:MIN="8:31" FSTYPE="vfat" MOUNTPOINT="" LABEL="UEFI" UUID="037A-8499" RO="0" RM="0" MODEL="" SIZE="106M" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="4096" LOG-SEC="512" ROTA="1" SCHED="mq-deadline" TYPE="part" DISC-ALN="1048576" DISC-GRAN="2M" DISC-MAX="4G" DISC-ZERO="0" PKNAME="sdb" PARTLABEL=""
[2023-02-01 06:46:57,772][ceph_volume.process][INFO  ] Running command: /usr/sbin/blkid -c /dev/null -p /mnt/set1-data-097cx4
[2023-02-01 06:46:57,775][ceph_volume.process][INFO  ] stdout /mnt/set1-data-097cx4: PART_ENTRY_SCHEME="gpt" PART_ENTRY_NAME="osd-1" PART_ENTRY_UUID="2e586bfb-3103-4194-a7b0-40ef849b1d49" PART_ENTRY_TYPE="0fc63daf-8483-4772-8e79-3d69d8477de4" PART_ENTRY_NUMBER="1" PART_ENTRY_OFFSET="2048" PART_ENTRY_SIZE="12582912" PART_ENTRY_DISK="8:0"
[2023-02-01 06:46:57,780][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 159, in main
    self.args = parser.parse_args(self.argv)
  File "/usr/lib64/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.6/argparse.py", line 1824, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python3.6/argparse.py", line 2265, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib64/python3.6/argparse.py", line 2294, in _get_value
    result = type_func(arg_string)
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/arg_validators.py", line 82, in __call__
    super().get_device(dev_path)
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/arg_validators.py", line 23, in get_device
    self._device = Device(dev_path)
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/device.py", line 137, in __init__
    self.available_lvm, self.rejected_reasons_lvm = self._check_lvm_reject_reasons()
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/device.py", line 624, in _check_lvm_reject_reasons
    rejected.extend(self._check_generic_reject_reasons())
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/device.py", line 581, in _check_generic_reject_reasons
    if self.is_acceptable_device:
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/device.py", line 490, in is_acceptable_device
    return self.is_device or self.is_partition
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/device.py", line 485, in is_device
    return self.device_type in valid_types
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/device.py", line 454, in device_type
    return self.blkid_api['TYPE']
KeyError: 'TYPE'
: exit status 1
```

**Comment by satoru-takeuchi** [comment]
```
$ sudo lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop1     7:1    0    6G  0 loop
loop4     7:4    0    6G  0 loop
sda       8:0    0   14G  0 disk
├─sda1    8:1    0    6G  0 part
└─sda2    8:2    0    6G  0 part
sdb       8:16   0   86G  0 disk
├─sdb1    8:17   0 85.9G  0 part /
├─sdb14   8:30   0    4M  0 part
└─sdb15   8:31   0  106M  0 part /boot/efi
$ sudo blkid
/dev/sda1: PARTLABEL="osd-1" PARTUUID="2e586bfb-3103-4194-a7b0-40ef849b1d49"
/dev/sdb1: LABEL="cloudimg-rootfs" UUID="760924d9-efa3-415d-b09e-38a41f2a7979" TYPE="ext4" PARTUUID="4cac852b-afba-447b-b3e7-c002155c1305"
/dev/sdb15: LABEL_FATBOOT="UEFI" LABEL="UEFI" UUID="037A-8499" TYPE="vfat" PARTUUID="a3bd274f-3b4b-4f86-8f8b-50de5921638f"
/dev/loop1: TYPE="ceph_bluestore"
/dev/loop4: TYPE="ceph_bluestore"
/dev/sda2: PARTLABEL="osd-2" PARTUUID="ec5d7757-ebc3-4613-a406-773950cb3163"
/dev/sdb14: PARTUUID="294b3901-770d-435f-b08e-151e016890f0"
$ sudo blkid
/dev/sda1: PARTLABEL="osd-1" PARTUUID="2e586bfb-3103-4194-a7b0-40ef849b1d49"
/dev/sdb1: LABEL="cloudimg-rootfs" UUID="760924d9-efa3-415d-b09e-38a41f2a7979" TYPE="ext4" PARTUUID="4cac852b-afba-447b-b3e7-c002155c1305"
/dev/sdb15: LABEL_FATBOOT="UEFI" LABEL="UEFI" UUID="037A-8499" TYPE="vfat" PARTUUID="a3bd274f-3b4b-4f86-8f8b-50de5921638f"
/dev/loop1: TYPE="ceph_bluestore"
/dev/loop4: TYPE="ceph_bluestore"
/dev/sda2: PARTLABEL="osd-2" PARTUUID="ec5d7757-ebc3-4613-a406-773950cb3163"
$ ls -l /dev/loop
loop-control  loop0         loop1         loop2         loop3         loop4         loop5         loop6         loop7
runner@fv-az198-869:~/work/rook/rook$ losetup -l
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                                                                                                  DIO LOG-SEC
/dev/loop1         0      0         0  0 /home/runner/data1.img                                                                                                       0     512
/dev/loop4         0      0         0  0 /var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/local-vol-loop-dev1/da7fb594-78af-4785-85e9-0e9e656cbc83   0     512
$ kubectl -n rook-ceph get pvc
NAME               STATUS   VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS   AGE
rook-ceph-mon-a    Bound    local-vol1            10Gi       RWO            manual         27m
set1-data-097cx4   Bound    local-vol5            6Gi        RWO            manual         25m
set1-data-1kfbr5   Bound    local-vol6            6Gi        RWO            manual         25m
set1-data-2llpjq   Bound    local-vol-loop-dev1   6Gi        RWO            manual         25m
runner@fv-az198-869:~/work/rook/rook$ kubectl -n rook-ceph get pv
NAME                  CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                        STORAGECLASS   REASON   AGE
local-vol-loop-dev1   6Gi        RWO            Retain           Bound       rook-ceph/set1-data-2llpjq   manual                  27m
local-vol1            10Gi       RWO            Retain           Bound       rook-ceph/rook-ceph-mon-a    manual                  27m
local-vol2            10Gi       RWO            Retain           Available                                manual                  27m
local-vol3            10Gi       RWO            Retain           Available                                manual                  27m
local-vol5            6Gi        RWO            Retain           Bound       rook-ceph/set1-data-097cx4   manual                  27m
local-vol6            6Gi        RWO            Retain           Bound       rook-ceph/set1-data-1kfbr5   manual                  27m
```

**Comment by satoru-takeuchi** [comment]
I picked up some test results. Failed tests were run on GitHub-hosted runner v2.301.1 though succeeding tests were run on v2.300.2. v2.301.1 might be bad at least for Rook. Still investigating...

**Comment by subhamkrai** [comment]
> I picked up some test results. Failed tests were run on GitHub-hosted runner v2.301.1 though succeeding tests were run on v2.300.2. v2.301.1 might be bad at least for Rook. Still investigating...

here in canary test https://github.com/rook/rook/actions/runs/4080948009/jobs/7033894205 it is passing with v2.301.1 too

**Comment by subhamkrai** [comment]
the mon size issue can be resolved by adding 
```
mon compact on start = true
```
ceph.conf not sure about other osd issues

**Comment by satoru-takeuchi** [comment]
@subhamkrai Strictly speaking, canary tests corresponding to OSD on PVC fail consistently with v2.301.1.

**Comment by subhamkrai** [comment]
> @subhamkrai Strictly speaking, canary tests corresponding to OSD on PVC fail consistently with v2.301.1. In addition, there seems to be no problem in `lvm-pvc`.

I agree, the last time when all the CI passed it was v2.300.x and the problem is we can't control this version.

but what could be the possible change that breaks CI, I see pvc/pv are created but I'm not good osd logs so not sure what's is going on

**Comment by subhamkrai** [comment]
> > @subhamkrai Strictly speaking, canary tests corresponding to OSD on PVC fail consistently with v2.301.1. In addition, there seems to be no problem in `lvm-pvc`.
> 
> I agree, the last time when all the CI passed it was v2.300.x and the problem is we can't control this version.
> 
> but what could be the possible change that breaks CI, I see pvc/pv are created but I'm not good osd logs so not sure what's is going on

@travisn @BlaineEXE @sp98 ^^

**Comment by satoru-takeuchi** [comment]
I'll modify this PR to get some information (e.g. `lsblk` and `blkid`) and compare the difference between the runner v2.301.1 and my local environment (and v2.300.2 if I can win the runner-lottery).

**Comment by subhamkrai** [comment]
> I'll modify this PR to get some information (e.g. `lsblk` and `blkid`) and compare the difference between the runner v2.301.1 and my local environment (and v2.300.2 if I can win the runner-lottery).

sure, Thanks

**Comment by satoru-takeuchi** [comment]
very similar issue
https://tracker.ceph.com/issues/56573

**Comment by satoru-takeuchi** [comment]
This problem is probably caused because `ceph-volume raw prepare` is called with an unexpected path("/mnt/set1-data-0htrf4") in OSD on PVC.

```
stdbuf -oL ceph-volume --log-path /var/log/ceph/set1-data-0htrf4 raw prepare --bluestore --data /mnt/set1-data-0htrf4
```

In this case, the device path should be a kernel name like "/dev/sdb1".

The next step is to find the root cause and how to fix (or bypass) this problem.

**Comment by subhamkrai** [comment]
> This problem is probably caused because `ceph-volume raw prepare` is called with an unexpected path("/mnt/set1-data-0htrf4") in OSD on PVC.
> 
> ```
> stdbuf -oL ceph-volume --log-path /var/log/ceph/set1-data-0htrf4 raw prepare --bluestore --data /mnt/set1-data-0htrf4
> ```
> 
> In this case, the device path should be a kernel name like "/dev/sdb1".
> 
> The next step is to find the root cause and how to fix (or bypass) this problem.

Thanks @satoru-takeuchi  for tracing the issues

**Comment by travisn** [comment]
> This problem is probably caused because `ceph-volume raw prepare` is called with an unexpected path("/mnt/set1-data-0htrf4") in OSD on PVC.
> 
> ```
> stdbuf -oL ceph-volume --log-path /var/log/ceph/set1-data-0htrf4 raw prepare --bluestore --data /mnt/set1-data-0htrf4
> ```
> 
> In this case, the device path should be a kernel name like "/dev/sdb1".
> 
> The next step is to find the root cause and how to fix (or bypass) this problem.

@satoru-takeuchi The osd should have an init container that copies the device path to the path that you are seeing under `/mnt`. So this looks expected, although it seems to be a problem for the CI now. The OSDs on PVs have been working a long time like this. Did you find any more clues? Thanks for your investigation. I will help dedicate more time to this tomorrow as well so we can unblock the releases hopefully soon.

**Comment by travisn** [comment]
@leseb If you have a minute, any thoughts from this thread on why the canary tests are failing now for OSDs on PVCs? thanks!

**Comment by satoru-takeuchi** [comment]
@travisn OK, I understood. I confirmed another logs and actually this uses a device name under /mnt.

https://gist.github.com/haslersn/57251739d58ee88dd643237cc847e16e#file-rook-ceph-osd-prepare-ssd-sata-0-data-8mqrmn-L236

> Did you find any more clues? 

Not yet.

I'd like to share my progress anyway. ceph-volume filed with the log that claims the missing of 'TYPE' field in the output of blkid command against the data device, and actually this field is missing. The corresponding code is [here](https://github.com/ceph/ceph/blob/main/src/ceph-volume/ceph_volume/util/device.py#L457). In this case, the output of blkid is used iff ceph-volume failed to get device type information from both sysfs or lsblk.

I'll compare the difference of these information in both the CI  environment and my local environment. I guess there is something wrong when the device name is neither a kernel name, nor a name created by udev.

Just FYI, I didn't have an extra time yesterday. In addition, probably I can also do nothing today due to other works. I'll resume this investigation tomorrow.

**Comment by travisn** [comment]
I see that OSDs are being provisioned on loop devices with PVs, so I opened #11645 to experiment with that.

**Comment by satoru-takeuchi** [comment]
I succeeded to reproduce this problem in my local environment.

**Comment by satoru-takeuchi** [comment]
Tests in my local environments:
```
rook v1.10.0, ceph v17.2.0 => succeeded
rook v1.10.0, ceph v17.2.5 => fail
rook v10.10.0, ceph v17.2.4 => fail
rook v1.10.0, ceph v17.2.3 => succeeded
rook v1.10.10, ceph v17.2.3 => succeeded
rook master, ceph v17.2.3 => succeeded
```

Now I confirmed that canary tests for OSD on PVC using partitions pass. 

NOTE:
Even though all tests passed in v17.2.3, it doesn't explain why this failure happened recently. The CI started to use v17.2.5 on Oct. 21st, 2022. It worked without any problem for months.

> 270b565f18 deploy/examples/cluster-on-local-pvc.yaml                  (subhamkrai      2022-10-21 19:31:25 +0530 176)     image: quay.io/ceph/ceph:v17.2.5

**Comment by satoru-takeuchi** [comment]
The original problem was fixed by #11646

**Pull request closed without merging**
