### PR TITLE
build: fix bad quotation in make help

### PR DESCRIPTION
**Pull request by sam6258**
**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by obnoxxx** [comment]
@mergifyio rebase

**Review by parth-gr — APPROVED** [review]

**Review by obnoxxx — COMMENTED** [review]
The change looks clean and reasonable, but some CI check is failing. I doubt that it is related, but needs to be fixed nonetheless.

What confuses me is the fact that locally, the context of the patch in the Makefile looks very different, but it nonetheless seems to be cleanly based  on current master.

**Comment by BlaineEXE** [comment]
I think this change looks good, but the CephHelmSuite both tests failed. Re-running to see if they pass

**Comment by travisn** [comment]
> I think this change looks good, but the CephHelmSuite both tests failed. Re-running to see if they pass

The only remaining failure looks like a known issue

**Pull request merged**
