### PR TITLE
fix error when operator is deployed by helm chart

### LINKED ISSUE #2020: Failed to create ceph cluster using rook operator which is deployed by helm.
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
the service account which is associated with operator pod don't have access to creating configmap in target namespace

**Expected behavior:**
create a ceph cluster after cluster resource is created 

```
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: vd[b-c]
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
```
**How to reproduce it (minimal and precise):**

```shell
helm install ceph-rook-cluster-0.1.0.tgz --set rbacEnable=true
cat >abc.yml <<EOF
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: vd[b-c]
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
EOF
kubectl apply -f abc.yml
```

**Environment**:
* OS (e.g. from /etc/os-release): centos
* Kernel (e.g. `uname -a`): Linux testhost1 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: none
* Rook version (use `rook version` inside of a Rook Pod): v0.8.1
* Kubernetes version (use `kubectl version`): 1.9.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): not available

### PR DESCRIPTION
**Pull request by MartinForReal**
**Description of your changes:**
update access list in helm chart to fix error when operator failed to create configmaps,secrets,deployments and other resources. 
**Which issue is resolved by this Pull Request:**
Resolves #2020 

**Checklist:**
- [x] Documentation has been updated, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [x] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [x] `make vendor` does not cause changes.

### CODE REVIEW

**Comment by travisn** [comment]
@MartinForReal did @galexrt's [suggestions](https://github.com/rook/rook/issues/2020#issuecomment-412484330) not work for you? We actually factored these privileges out intentionally into the cluster.yaml.

**Comment by MartinForReal** [comment]
Since this is a access configuration and no need to update docs.

**Comment by MartinForReal** [comment]
@travisn I see. I need to restart operator pod after I applied the configurations. But I want to write a chart to deploy a new ceph cluster.  I think this can't be done right now.

**Comment by travisn** [comment]
To create a cluster helm chart, note that PR #1676 is still in progress. The 0.8 release changed a number of areas including the RBAC refactoring so the PR needs some more effort.

What did not work for you unless you restarted the operator? Is it because you didn't have the RBAC setup when the cluster CRD was created? If the roles are created at the same time as the cluster CRD it should just work in a helm chart. This is the normal flow without a helm chart and a restart of the operator is not necessary.

**Comment by MartinForReal** [comment]
according to [helm best practise](https://docs.helm.sh/chart_best_practices/#custom-resource-definitions) custom resource definition and custom resource should not be packed into the same package or it would raise error "crd not defined".

**Comment by travisn** [comment]
I believe the Rook charts would follow that best practice. The operator chart installs the [CustomResourceDefinition](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/resources.yaml#L3) types, while the proposed [cluster chart](https://github.com/rook/rook/pull/1676) would create the `kind` Cluster. Or is there something else that you're referring to?

**Comment by MartinForReal** [comment]
Yes. I created another chart to install custom resources and rbac configurations.  And I need to restart operator pod in order to make rbac configuration take effect.

**Comment by travisn** [comment]
@MartinForReal can you share the operator log of what failed before you restarted the operator? This seems like it should be the same scenario as creating cluster.yaml, which works fine to create the RBAC rules at the same time as the CRD.

**Comment by galexrt** [comment]
The Ceph Cluster CRD quickstart will be updated in #2035 with the RBAC rules.

**Comment by MartinForReal** [comment]
Thanks!@galexrt @travisn

**Pull request closed without merging**
