### PR TITLE
WIP: Update Rook to build on the K8s 1.16 client

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
Update Rook from building on K8s 1.14 to the 1.16 client libraries. As expected, this involves some changes to generated code, updating properties that no longer exist, and other related changes from updated dependencies. This change is needed to support topologySpreadConstraints as described in #4387.

This relies on changes from other dependencies to update to k8s 1.16 before this can merge. Temporarily the Gopkg.toml is pulling in branches from my forks to workaround until these PRs merge:
- [ ] Operator kit: https://github.com/rook/operator-kit/pull/35
- [ ] Bucket provisioner: https://github.com/kube-object-storage/lib-bucket-provisioner/pull/177

**Checklist:**

- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [ ] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

### CODE REVIEW

**Comment by travisn** [comment]
Let's hold off on this change. The `EvenPodsSpread` feature gate looks like it will still be in alpha for 1.17 that is getting released soon, so we should target Rook v1.3 to support the topology spread constraints.

**Comment by satoru-takeuchi** [comment]
I guess that we need to update the dependency of grpc too.

I failed to build with this branch as follows.

```
$ GO111MODULE=off dep ensure -vendor-only 
$ GO111MODULE=off build/run make -j8 IMAGES=ceph build
...
=== go vet
# github.com/rook/rook/vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory
vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go:134:37: undefined: grpc.WithContextDialer
build/makelib/golang.mk:160: recipe for target 'go.vet' failed
make[1]: *** [go.vet] Error 2
Makefile:101: recipe for target 'build.common' failed
make: *** [build.common] Error 2
```

Although grpc exports WithContextDialer from v1.19.0, this branch depends on grpc v1.18.0. So I modified Gopkg.lock as follows and then build succeeded.

```
diff --git a/Gopkg.lock b/Gopkg.lock
index a559f523..98664aa6 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -825,8 +825,8 @@
     "tap",
   ]
   pruneopts = "UT"
-  revision = "a02b0774206b209466313a0b525d2c738fe407eb"
-  version = "v1.18.0"
+  revision = "2fdaae294f38ed9a121193c51ec99fecd3b13eb7"
+  version = "v1.19.0"

 [[projects]]
   digest = "1:abeb38ade3f32a92943e5be54f55ed6d6e3b6602761d74b4aab4c9dd45c18abd"
```

CMIIW. I'm not so familiar with `dep`.

**Comment by travisn** [comment]
I'll close this for now. We should consider updating the k8s client we're using when we do the work to move to the controller runtime.

**Comment by satoru-takeuchi** [comment]
@travisn Do you plan to move to controller-runtime in v1.3? Supporting TopologySpreadConstraints depends on k8s 1.16 (*1) client. Since this feature is essential for most of OSD on PVC users, I'd like to merge this feature in v1.3, if possible.

*1) We are also waiting for the promotion of this feature from alpha to beta.

**Comment by travisn** [comment]
Yes, I anticipate it is something in the very near future in the v1.3 timeline.

**Comment by satoru-takeuchi** [comment]
Thanks. I'd like to contribute to the moving to controller-runtime.

**Comment by travisn** [comment]
@satoru-takeuchi thanks, let me get back to you in a few days to start thinking about it...

**Comment by travisn** [comment]
@leseb Has actually already started investigating the controller runtime. You could follow up on #1981.

**Pull request closed without merging**
