### PR TITLE
follow symlinks when copying ceph include files.  Exclude external di…

### PR DESCRIPTION
**Pull request by jbw976**
…r from glide tool

Addresses #461

### CODE REVIEW

**Comment by bassam** [comment]
Should we exclude the build, scripts an other dirs?

**Comment by jbw976** [comment]
good point @bassam, made another commit with more dirs to exclude.  ran `glide update` and resultant glide.lock and dependency count remained the same.  will squash that commit after PR approval.

**Comment by bassam** [comment]
What's the Jenkins failure?

**Comment by jbw976** [comment]
Since the Jenkins failure appears to be intermittent and associated with #463, any objection to proceeding with the merge?  It would be nice to get this `glide` fix into master for the rest of the team.

**Comment by bassam** [comment]
Sgtm

**Pull request merged**
