### PR TITLE
core: improve the executeCommandWithTimeout function implem.

### PR DESCRIPTION
**Pull request by parth-gr**
**Description of your changes:**

here is the example https://go.dev/play/p/2QaP4dVTXl7 by which we understand signal actual skips to send the error message to the parent function,
So instead removing the signal would be a good idea.

We can discuss more on how to improve it

Actual problem noticed in the logs:

Logs Printed:
```
I | exec: exec timeout waiting for process radosgw-admin to return. Sending interrupt signal to the process
I | ceph-object-controller: multisite configuration for object-store ocs-storagecluster-cephobjectstore is complete
```
So that means the call went to create multisite resources, but the command timeout,
So instead of returning the error it just passes the signal(cmd.Process.Signal(os.Interrupt)) by which instead of raising the error it suppresses it and just returned to the grandparent function call which says it was successfull.

Logs would expected:

https://github.com/rook/rook/blob/0a680153f2a0d086f22fe7273761525f8d6c8386/pkg/operator/ceph/object/objectstore.go#L451

Before it prints `I | ceph-object-controller: multisite configuration for object-store ocs-storagecluster-cephobjectstore is complete
`
Moreover, I would expect an error as the cmd wasn't successful in creating the zonegroups.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
Can you describe more about the change? Did this come from a code analysis, or some bug report with this method?

**Comment by parth-gr** [comment]
> Can you describe more about the change? Did this come from a code analysis, or some bug report with this method?

There is surely a bug with the above method, updating the description

**Comment by travisn** [comment]
@parth-gr The current implementation before your changes is a two-phased approach to terminating the process:
1. Send an interrupt signal to the process
2. After another timeout if it is still not stopped, then kill the process

This is expected rather than immediately just kill the process. 

The go playground you linked above kills the same process that is running. I don't see the parallel to this Rook code since Rook is killing a different process. Shall we close this? Or else we can discuss more to clarify, thanks.

**Comment by travisn** [comment]
@parth-gr Shall we close this, or still investigating?

**Comment by parth-gr** [comment]
> @parth-gr Shall we close this, or still investigating?

In progress

**Comment by parth-gr** [comment]
The parent code is not executed, https://go.dev/play/p/_R5tQhuVp4z

Which is the same problem in the operator

**Comment by travisn** [comment]
Per discussion, the issue seems that the OSDs were down, causing the pool init to fail.

**Comment by parth-gr** [comment]
I cant find a reason why such logs are triggered
```
I | exec: exec timeout waiting for process radosgw-admin to return. Sending interrupt signal to the process
I | ceph-object-controller: multisite configuration for object-store ocs-storagecluster-cephobjectstore is complete
```
So in a meanwhile can we propose that if the cephobjectuser fails we should watch for it and should reconcile cephobjectstore controller?
```
2024-01-07T13:00:00.443297359Z 2024-01-07 13:00:00.443220 E | ceph-object-store-user-controller: failed to reconcile CephObjectStoreUser "openshift-storage/ocs-storagecluster-cephobjectstoreuser". failed to initialized rgw admin ops client api: failed to create or retrieve rgw admin ops user: failed to create object user "rgw-admin-ops-user". error code 1 for object store "ocs-storagecluster-cephobjectstore": failed to create s3 user. 2024-01-07T13:00:00.427+0000 3ff9c2df760  0 ERROR: could not find zonegroup (ocs-storagecluster-cephobjectstore)
2024-01-07T13:00:00.443297359Z 2024-01-07T13:00:00.427+0000 3ff9c2df760  0 ERROR: failed to start notify service ((2) No such file or directory
2024-01-07T13:00:00.443297359Z 2024-01-07T13:00:00.427+0000 3ff9c2df760  0 ERROR: failed to init services (ret=(2) No such file or directory)
2024-01-07T13:00:00.443297359Z couldn't init storage provider. : exit status 5
```
@thotz @travisn @BlaineEXE

**Comment by travisn** [comment]
> So in a meanwhile can we propose that if the cephobjectuser fails we should watch for it and should reconcile cephobjectstore controller?

If the cephobjectstoreuser reconcile fails, it will retry, right? If the cephobjectstore controller fails, it will also retry its reconcile. And if ceph components are down (e.g. if no OSDs are created or running) then these would continue to fail until ceph is healthy for rgw commands to succeed. As long as we retry reconcile on failure, I'm not sure any change is needed.

**Comment by travisn** [comment]
After reviewing this again, I would recommend no change is needed to this method and we can close the PR

> I see it happens with block pool too
> 
> ```
> 2023-10-25T07:27:06.260530535Z 2023-10-25 07:27:06.260469 I | exec: exec timeout waiting for process rbd to return. Sending interrupt signal to the process
> 2023-10-25T07:27:06.268166427Z 2023-10-25 07:27:06.268131 E | ceph-block-pool-controller: failed to reconcile CephBlockPool "openshift-storage/ocs-storagecluster-cephblockpool". failed to create pool "ocs-storagecluster-cephblockpool".: failed to create pool "ocs-storagecluster-cephblockpool".: failed to initialize pool "ocs-storagecluster-cephblockpool" for RBD use. : signal: interrupt
> ```
> 
> Not confident now the original issue will solve its problem, should we consider increasing the timeout?

This example actually shows that the behavior in the timeout is correct in this exec method. After the timeout, the exec returns an error from the timeout, which then causes the reconcile of the pool to fail, which allows the pool reconcile to retry later. But the issue with the RGW was that it ignores the error returned by the exec. Hopefully #12817 fixed that error handling issue.

**Pull request closed without merging**
