### PR TITLE
csi: remove unwanted RBAC of csi driver

### LINKED ISSUE #4841: Revisist RBAC rules for ceph-csi
**Is this a bug report or feature request?**
* Bug Report

There are few RBAC which are not required are getting deployed when we use common.yaml, we need to remove the unwanted RBAC rules for cephcsi

**Deviation from expected behavior:**
There are more RBAC for cephcsi which are not required
**Expected behavior:**
only required RBAC should be granted for ceph-csi

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

### PR DESCRIPTION
**Pull request by Madhu-1**
**Description of your changes:**
Removed unwanted RBAC from the previous versions of the driver.

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue is resolved by this Pull Request:**
Resolves #4841

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by Madhu-1** [comment]
Add DNM as still need to test with older supported versions.

**Review by travisn — COMMENTED** [review]
Nice cleanup!

**Comment by travisn** [comment]
> > @travisn what are the minimal kubernetes we need to test this with. Need to make sure it works with the supported kubernetes versions with Rook.
> 
> IIRC 1.16.x is the minimum k8s supported version

Correct, 1.16 is the min version, the CI tests with it as well.

**Comment by travisn** [comment]
> Correct, 1.16 is the min version, the CI tests with it as well.

With the merge of #10123, K8s 1.17 is now the min version for Rook v1.9

**Comment by Madhu-1** [comment]
Tests passed with 1.17.17 [here](https://github.com/rook/rook/runs/6188008041?check_suite_focus=true)

**Comment by Madhu-1** [comment]
Tests passed for 1.23.0 [here](https://github.com/rook/rook/runs/6188008103?check_suite_focus=true)

**Comment by Madhu-1** [comment]
@travisn CI passed on all the kubernetes versions are we good to go? if yes I can remove CI changes.

**Comment by travisn** [comment]
> @travisn CI passed on all the kubernetes versions are we good to go? if yes I can remove CI changes.

Sounds great to go ahead after the CI changes are reverted. Do you think this should be backported to 1.9? I'm thinking we could just leave it in master to include in 1.10 unless there is a need to backport.

**Comment by Madhu-1** [comment]
> > @travisn CI passed on all the kubernetes versions are we good to go? if yes I can remove CI changes.
> 
> Sounds great to go ahead after the CI changes are reverted. Do you think this should be backported to 1.9? I'm thinking we could just leave it in master to include in 1.10 unless there is a need to backport.

Sounds good. Lets keep it for 1.10 AFAIC we don't need this for 1.9

**Comment by Madhu-1** [comment]
@travisn removed extra commit. PTAL

**Review by travisn — APPROVED** [review]

**Pull request merged**
