### PR TITLE
ceph: use debug log level for integration tests

### PR DESCRIPTION
**Pull request by BlaineEXE**
Debug logging can help track down stubborn bugs and flaky issues better
than info level. Use it for our integration tests.

Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>

@parth-gr mentioned in the huddle today that he has been seeing flakiness in the CI on CephObjectStores. Two links are below. To help debug these issues and other issues better, I suggest enabling DEBUG logging for all integration tests (and backporting to 1.6).
- https://github.com/rook/rook/pull/8267/checks?check_run_id=3000203585
- https://github.com/rook/rook/pull/7977/checks?check_run_id=3019442267

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by subhamkrai — APPROVED** [review]

**Comment by subhamkrai** [comment]
We can see the smoke test suite failing for both k8s versions here too with the same error.

**Review by parth-gr — APPROVED** [review]
Yes, DEBUG logging will be a good idea for future CI issues/failures to get the root cause.

**Review by leseb — APPROVED** [review]

**Comment by leseb** [comment]
I'm still a bit hesitant to turn DEBUG on always since using it inherently introduces new timing in the code execution. This might obfuscate errors that INFO level will surface. Let's discuss today during the huddle.

**Review by travisn — CHANGES_REQUESTED** [review]
My main concern with enabling debug logging always is that it makes troubleshooting issues much more difficult because there is so much more noise to dig through. I also share similar concerns with @leseb that it could change normal execution. 

Instead of merging this, how about we instead use this as a troubleshooting PR and rerun the tests until we hit the intermittent issue for investigation?

**Pull request closed without merging**
