### PR TITLE
ci: set tmate for 120min in case of ci failure

### PR DESCRIPTION
**Pull request by subhamkrai**
this commit enable tmate session for every ci failure
with 120min timeout.

Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by leseb — APPROVED** [review]

**Comment by leseb** [comment]
Working as expected.

**Review by leseb — COMMENTED** [review]
can we have `timeout-minutes` at the top level instead that on each task?

**Comment by subhamkrai** [comment]
> can we have `timeout-minutes` at the top level instead that on each task?

yes, looks like we can do.

**Comment by subhamkrai** [comment]
> > can we have `timeout-minutes` at the top level instead that on each task?
> 
> yes, looks like we can do.

for integration test we have 30min timeout...you want to add a timeout for others too? or something else

**Comment by leseb** [comment]
> > > can we have `timeout-minutes` at the top level instead that on each task?
> > 
> > 
> > yes, looks like we can do.
> 
> for integration test we have 30min timeout...you want to add a timeout for others too? or something else

The timeout is for the go test only before it fails. We can keep it this way.

**Review by leseb — CHANGES_REQUESTED** [review]
https://github.com/rook/rook/pull/8183#issuecomment-866682014

**Comment by subhamkrai** [comment]
@leseb I think I was wrong earlier, it can have a timeout for each job or job.steps https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

**Comment by leseb** [comment]
> @leseb I think I was wrong earlier, it can have a timeout for each job or job.steps https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

Ok the step level sounds good.

**Review by leseb — APPROVED** [review]

**Pull request merged**
