### PR TITLE
docs: add kustomize folder for crds

### LINKED ISSUE #10467: Move or copy deploy/examples/crds.yaml to deploy/crds/
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Move or create a new directory with the CRDs to `/deploy/crds` e.g.

```
deploy/
    crds/
        cephblockpools.ceph.rook.io.yaml
        cephclusters.ceph.rook.io.yaml
        ...
        kustomization.yaml # (see below)
```

```yaml
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cephblockpools.ceph.rook.io.yaml
  - cephclusters.ceph.rook.io.yaml
  - ...
```

**What is use case behind this feature:**

This would be very useful to install the CRDs with Kustomize, for example:

`kubectl apply -k ./path/to/folder/containing/file/below`

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rook/rook//deploy/crds?ref=v1.9.5
```

Thanks!

### PR DESCRIPTION
**Pull request by onedr0p**
Signed-off-by: Devin Buhl <devin@buhl.casa>

**Description of your changes:**

Add kustomize folder with symlink to crds.yaml and a kustomization

**Which issue is resolved by this Pull Request:**
Resolves #10467

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
Perhaps we need another level of directories in case there are other kustomize scenarios? What about adding these files under `deploy/kustomize/crds/`? But my experience with kustomize is limited, wdyt?

**Comment by BlaineEXE** [comment]
I have found that we already have enough of a time providing user support for helm and example deployment methods. My inclination would be to leave it up to users to do the `kustomize` layout for themselves. At the end of the day, I think kustomize is straightforward enough that we can rely on users to handle that themselves and not prescript it for them.

**Comment by onedr0p** [comment]
I could see in the future if you folks want to branch out and support a full kustomize installation. It would be neat to support that in the future instead of all the example manifests.

I'll go ahead and put the crds in a subfolder incase that is an option ya'll are looking to explore in the future.

**Comment by travisn** [comment]
> I have found that we already have enough of a time providing user support for helm and example deployment methods. My inclination would be to leave it up to users to do the `kustomize` layout for themselves. At the end of the day, I think kustomize is straightforward enough that we can rely on users to handle that themselves and not prescript it for them.

Are you saying it may not make sense for Rook to include kustomize config since everyone will have their own customization?

**Comment by onedr0p** [comment]
I'd still be interested in this!

**Comment by travisn** [comment]
> I could see in the future if you folks want to branch out and support a full kustomize installation. It would be neat to support that in the future instead of all the example manifests because it's a bit more structured.

@onedr0p Could you expand on what it would mean to support a full kustomize install? More structure around the examples would certainly be a plus, but how would it look?

**Comment by onedr0p** [comment]
Ideally you could have a `deploy/kustomize` folder with all the resources, that people could `kubectl apply --kustomize` although I am not sure if that is all worth the effort given all the different options people can have. People would need to patch the base resources as an overlay with their custom config. Thinking it over it sounds like a mess, but at least having the CRDs be available would fit the use case I mentioned above and in the linked issue.

**Comment by travisn** [comment]
Yeah there are so many possible configurations, I'm not seeing how to organize it with the kustomizations. Since everyone would have there own kustomizations, it seems like they should just be managed separately from rook.

**Comment by travisn** [comment]
Closing per discussion that it's difficult to define generally applicable customizations.

**Pull request closed without merging**
