### PR TITLE
docs: use `rbac.authorization.k8s.io/v1` consistently

### PR DESCRIPTION
**Pull request by galexrt**
**Description of your changes:**

This replaces any uses of `rbac.authorization.k8s.io/v1beta1` with
`rbac.authorization.k8s.io/v1` affecting RBAC objects like ClusterRole
and ClusterRoleBindings, etc.
This is done as some RBAC objects used the `v1beta1` and others already
using `v1`.

Signed-off-by: Alexander Trost <galexrt@googlemail.com>

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [x] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.
- [x] Pending release notes updated with breaking and/or notable changes, if necessary.
- [x] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [x] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by galexrt** [comment]
Jenkins failed on `aws_1.15.x` as did #6082. Both failed on the Cassandra tests.

Restarting once more here as well.

**Comment by travisn** [comment]
@galexrt I see that support for `v1beta1` is being removed in v1.20, which means we certainly need to make this change. 
 In what release was `rbac.authorization.k8s.io/v1` first included? It must be at least back to v1.14 since the tests are passing, but want to confirm how far back we can still support with this change.

**Comment by galexrt** [comment]
@travisn Reason behind "replacing" the `v1beta1` usage with `v1`, is that `v1` and `v1beta1` is used "all around the YAMLs" and not just one of them.

From a K8S 1.8 blog post it seems to be available even since then (https://kubernetes.io/blog/2017/10/using-rbac-generally-available-18/), but I can't seem to find a K8S v1.11 documentation.
Looking at the "Authenticating" doc page from 31. August 2018 shows only examples using `v1` and not `v1beta1` RBAC api usages, see https://web.archive.org/web/20180831202811/https://kubernetes.io/docs/reference/access-authn-authz/authentication/.

From some works on OpenShift, the RBAC `v1` (and `v1beta1`) API should work there as well.

**Comment by travisn** [comment]
@galexrt To confirm how far v1 is available, how about if you update the jenkinsfile in your PR to run the CI on the same versions as the [release branch](https://github.com/rook/rook/blob/release-1.4/Jenkinsfile#L154-L155)? Then we can revert the change to the jenkinsfile before merging.

**Comment by galexrt** [comment]
I just checked the Rook release branches `release-1.1` and `release-1.0`, in those (old) branches we have already had a "good" mix of `v1beta1` and `v1` RBAC APIs.

This just makes our RBAC API usages consistently throughout the files.

I will push a second commit to replace any `v1beta1` K8S clientset usages in the code (mostly / only in `tests/`).

**Comment by leseb** [comment]
> Do we need to apply a new schema for the 1.4 to 1.5 upgrade? Or do we keep it this way (beta) for existing clusters?

@galexrt ^

**Comment by galexrt** [comment]
@leseb A new schema? Do you mean an "upgrade" YAML file? I don't think so.
At least on an OCP 3.11 cluster (so K8S 1.11), e.g., a Role created with RBAC `v1beta1` api version is returned with `v1` api version. So the RBAC objects are "already" stored as v1.
On a K8S 1.18 cluster, the same applies, the Rook Ceph RBAC v1beta1 objects when retrieved `oc get -o yaml` are all having `v1` as the api version.

**Pull request merged**
