### PR TITLE
mgr: run the watch side car config on /etc/ceph

### LINKED ISSUE #9385: watch-active sidecar /var/lib/rook: permission denied on 1.8.0
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```
─❯ k logs -f deploy/rook-ceph-mgr-a -c watch-active | grep failed
2021-12-10 14:12:17.780890 C | rookcmd: failed to write connection config: failed to write keyring "client.admin" to /var/lib/rook/rook-ceph: failed to create keyring directory for /var/lib/rook/rook-ceph/client.admin.keyring: mkdir /var/lib/rook: permission denied
```

**Expected behavior:**

Upgrade to 1.8.0 to be successful

**How to reproduce it (minimal and precise):**

Attempt to upgrade to 1.8.0

**File(s) to submit**: N/A

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Focal
* Kernel (e.g. `uname -a`): 5.4
* Cloud provider or hardware configuration: N/A
* Rook version (use `rook version` inside of a Rook Pod): 1.8.0
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.6
* Kubernetes version (use `kubectl version`): 1.22.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HealthOK

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

We don't need to use /var/lib/rook for the ceph config and keyring, so
let's use /etc/ceph which has the right permissions too. Also, we need
to run with the ceph user since the rook image defaults to the "rook"
user.

Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #9385

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
Just checking:
since `/etc/ceph` is mounted with `ceph.conf` from the `rook-config-override` configmap, will this be writing any data to the `/etc/ceph/ceph.conf` file that would mess with the override?

**Comment by leseb** [comment]
> Just checking: since `/etc/ceph` is mounted with `ceph.conf` from the `rook-config-override` configmap, will this be writing any data to the `/etc/ceph/ceph.conf` file that would mess with the override?

Good point, I need to check and merge, if not done already.

**Review by travisn — COMMENTED** [review]
LGTM, if you could just confirm that it's been tested on OpenShift where the privs would be more critical.

**Review by travisn — APPROVED** [review]
Testing on openshift looks good for both 1 or 2 mgrs, and the watch-active sidecar is running successfully. The OSDs also were created without any issues.

**Pull request merged**
