### PR TITLE
ci: adding gosec tool in ci

### LINKED ISSUE #4578: Enable gosec tool with CI
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Prevent code quality issues from being introduced by running the `gosec` tool as part of the CI. 

In order to enable this tool, we first need to have a clean slate from gosec as mentioned in #3765, which is in progress with #4498.

**What is use case behind this feature:**
Increasing code quality.

### PR DESCRIPTION
**Pull request by subhamkrai**
this commit will add gosec check in ci
and it will help us increase code quality.

Signed-off-by: subhamkrai <subhamkumarrai03@gmail.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #4578

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[skip ci]

### CODE REVIEW

**Comment by leseb** [comment]
@subhamkrai what are the last errors about?

**Comment by subhamkrai** [comment]
> @subhamkrai what are the last errors about?
we need to trigger CI again As #5923 has been merged so I believe we'll get clean CI

**Comment by leseb** [comment]
> > @subhamkrai what are the last errors about?
> 
> we need to trigger CI again As #5923 has been merged so I believe we'll get clean CI

Ok so please rebase and push :)

**Comment by subhamkrai** [comment]
Done.

**Pull request merged**
