### PR TITLE
test: update usage of tmate pod manifest

### PR DESCRIPTION
**Pull request by BlaineEXE**
Update the usage of the tmate pod manifest to fix a couple minor issues and to expand the example to be an easy copy-paste.

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by subhamkrai — APPROVED** [review]

**Comment by subhamkrai** [comment]
@BlaineEXE have you tried this https://github.com/mxschmitt/action-tmate#detached-mode ?

**Comment by travisn** [comment]
@BlaineEXE This is still valid, right? Ready to merge?

**Review by subhamkrai — CHANGES_REQUESTED** [review]
I think we don't need this pr and probably we can delete the file too

**Comment by travisn** [comment]
The detached tmate was solved by #12579, right? So we don't need this tmate config anymore?

**Pull request closed without merging**
