### PR TITLE
core: remove double imported packages

### PR DESCRIPTION
**Pull request by galexrt**
**Description of your changes:**

This removes double package imports. Example:
```
"github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
cephv1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
```
Only one is now being used as shown in [go-staticcheck
ST1019](https://staticcheck.io/docs/checks#ST1019).

Signed-off-by: Alexander Trost <galexrt@googlemail.com>

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by subhamkrai — COMMENTED** [review]
@galexrt commitlint is failing

**Comment by galexrt** [comment]
> @galexrt commitlint is failing

Yeah, I have seen that yesterday and tried to fix it. For some reason commitlint shows an empty line where there shouldn't be one.. Maybe the code block is messing with it? I'll try changing the commit message a few more times to see if that fixes it.

**Review by travisn — APPROVED** [review]
Is there a CI check we can add to prevent future duplicate imports?

**Comment by galexrt** [comment]
@travisn We could look into adding the [go staticcheck](https://github.com/dominikh/go-tools) to the CI.

go-staticcheck is reporting other "issues" like the following:
image

One nit I have with go-staticcheck is that as far as I have found out you can only ignore a check globally and not on a per file/line basis. I can bring it up at the next community meeting to get some feedback on it. What are your thoughts?

**Comment by subhamkrai** [comment]
> @travisn We could look into adding the [go staticcheck](https://github.com/dominikh/go-tools) to the CI.

FYI, We have golangci linter in our CI which contains this check too, we have to figure out why static check is not working or even it is enabled or not.

> 
> go-staticcheck is reporting other "issues" like the following: image
> 
> One nit I have with go-staticcheck is that as far as I have found out you can only ignore a check globally and not on a per file/line basis. I can bring it up at the next community meeting to get some feedback on it. What are your thoughts?

**Pull request merged**
