### PR TITLE
rgw: fix typo on crd endpoint address

### PR DESCRIPTION
**Pull request by microyahoo**
The rgw endpoint address had a typo

Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by subhamkrai — APPROVED** [review]

**Comment by subhamkrai** [comment]
@travisn any idea why this typos are not caught by CI?

**Comment by travisn** [comment]
> @travisn any idea why this typos are not caught by CI?

Good question, perhaps the check doesn't know how to detect issues with hyphenated words

**Comment by microyahoo** [comment]
hi @subhamkrai, @travisn, we use `[misspell](https://github.com/client9/misspell)` linter to check all source codes, maybe we can add it to ci runner.

```console
~/go/src/deeproute/rook (nit ✗) go install github.com/client9/misspell/cmd/misspell@latest                         
go: downloading github.com/client9/misspell v0.3.4
~/go/src/deeproute/rook (nit ✗) git ls-files | grep -v vendor | xargs misspell
Documentation/Contributing/development-flow.md:98:53: "manifestes" is a misspelling of "manifests"
Documentation/CRDs/specification.md:5559:82: "adressable" is a misspelling of "addressable"
design/ceph/osd-migration.md:169:33: "developemnt" is a misspelling of "developments"
pkg/apis/ceph.rook.io/v1/types.go:1616:83: "adressable" is a misspelling of "addressable"
```

**Comment by BlaineEXE** [comment]
The spell checker used by Rook is designed not to return many false errors. The implementation of the spell checker looks for common misspellings and suggests corrections based on `misspelling -> correction` dictionary entries. It's possible that the hyphenation is the issue as Travis mentioned. It's also possible that `adressable -> addressable` isn't in the spell checker's dictionary.

**Pull request merged**
