### PR TITLE
Added ceph-reboot-script using the Container Linux Update Operator

### PR DESCRIPTION
**Pull request by hacor**
Signed-off-by: hacor <hacornelis@gmail.com>

This page should be the final version of PR #1492 

[skip ci]

### CODE REVIEW

**Comment by christianhuening** [comment]
I just tried this on my system and it's working great!

**Comment by jbw976** [comment]
@hacor great this looks good to go except for Github is showing the Jenkins build to have failed when it actually succeeded just fine: https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-1582/1/pipeline

Can you rebase from the latest in master?  that will give jenkins a kick to give you a green I expect.  I want to figure out why this is randomly happening with Github/Jenkins, it's getting frustrating.

**Comment by hacor** [comment]
@jbw976 Do I still need to take action, because I see all positive on the [Jenkins link](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-1582/1/pipeline) you provided.
Thanks for letting me now!

**Comment by christianhuening** [comment]
@hacor One question: Would it make sense to add a noout, nodown flag prior to the planned reboot? Where would you add that? It feels sort of wrong to do that in your script. What do you think?

**Comment by hacor** [comment]
@christianhuening If I understood correctly it feels like you want to change the order/procedure of the [CoreOS Update Operator](https://github.com/coreos/container-linux-update-operator). I think such a step need to be added to the update operator itself rather than Rook. We just implemented the `Update Operator` the way it's described to use it.

**Comment by hacor** [comment]
After having a conversation with @christianhuening it might be interesting to add an extra step into the procedure:
- Node gets the `reboot annotation`
- The `ceph-reboot-script` get's fired
- Ceph get's the `noout` option to hold the cluster from immediately rebalancing
- The node reboots
- An `after-reboot-check` deletes the Ceph `noout`flag

**Pro's**
- The cluster doesn't immediately start rebalancing all OSDs for a simple reboot
- The script could check the node for an extra annotation set by the user `set-noout=false` to avoid setting the `noout` flag. From what I see, this should only be set when a node get's completely deleted.

**Cons**
- For a longer reboot period it might be necessary to rebalance the cluster, but this can't be fortoled. This depends on how much replicas are used.

It's difficult to make a decision on this one. So we're interested to hear what you think?

**Comment by galexrt** [comment]
@hacor I think adding the `noout` flag would be a good idea in general.
In Ceph when the `noout` flag is set, the cluster status will enter `HEALTH_WARN` so the administrator should be alerted of the "issue" if it stays longer.

**Comment by chaosaffe** [comment]
I think this is a solid idea. A longer duration of `HEALTH_WARN` should trigger administrative response, and we don't want to waste disk/network/cycles doing an unneeded rebalance. Could also speed up the cluster rollover since we aren't waiting to undo the rebalance that would have happened while the node was down.

**Comment by hacor** [comment]
Sorry for the late reply! All seems clear! I’ll update the script upcoming week. Happy Easter!

**Comment by christianhuening** [comment]
lgtm - nice addition!

**Comment by hacor** [comment]
Tomorrow I'll do some more testing. New cluster is now booting to make sure everything works just fine!

**Comment by jbw976** [comment]
Great, thanks for the follow up @hacor.  @galexrt did you already get a chance to look at the latest additions?  I'll take a look later on if not.

@hacor we've had issues with our Jenkins CI setup recently (which i think are now fixed). Would it be possible for you to rebase from master and force push that so you can give Jenkins a kick? Something like:
```
git fetch --all
git rebase upstream/master
git push -f hacor
```

**Comment by christianhuening** [comment]
I am very appreciative of that solution! Will incorporate it into our deployment now and see how it fares for the next update round of CoreOS and/or K8s (to 1.10.1 then)

**Comment by hacor** [comment]
@jbw976 I think all you asked is done!
And it seems Jenkens is happy 👍

**Comment by galexrt** [comment]
@jbw976 Yes, I took another look and it LGTM.
@hacor Could you please rebase on latest master? Let's see if that solves the CI issue.

**Pull request merged**
