### PR TITLE
ceph: update helm version to support crd deployment ordering

### PR DESCRIPTION
**Pull request by intlabs**
**Description of your changes:**
Currently, Helm v2.16.7 is used, but this Helm v3 has been released for some time.
To use the latest version of Helm v3 is beneficial as it provides significantly better support for deployments that require CRDs, such as the ability to deploy both CRDs and CRs for them simultaneously within a single release.

Signed-off-by: Pete Birley pete@port.direct

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

[test full]

### CODE REVIEW

**Comment by BlaineEXE** [comment]
I think renaming `templates` to `crds` isn't quite what should happen. I would think only CRDs should live there, not all templates (including roles, bindings, etc.).

**Comment by intlabs** [comment]
@BlaineEXE thats exactly what's done here - only the CRDs are moved. I'll push a revision to fix the gate asap.

**Comment by BlaineEXE** [comment]
My bad @intlabs. I had stuff a little mixed up. I've been looking into how Helm can help more with Rook, and I'm really glad to see this PR. Thanks, and I look forward to seeing an update for the gates soon.

**Comment by BlaineEXE** [comment]
If we are dropping support for Helm v2 and moving to Helm v3, we should also update our testing.

`HELM_VERSION` in `helm.mk` I think needs update, yes @travisn? It looks like there is also a `wget` in `test/scripts/helm.sh` that doesn't use `HELM_VERSION` that also needs updated. And if we move to Helm v3, the tiller stuff in that `.sh` script probably needs removed also?

**Comment by travisn** [comment]
> If we are dropping support for Helm v2 and moving to Helm v3, we should also update our testing.

Does this change remove support for helm 2? Or just change the build to use helm 3? If the side effect is that helm 2 is no longer supported, we need to be very clear about the transition path. 

> `HELM_VERSION` in `helm.mk` I think needs update, yes @travisn? It looks like there is also a `wget` in `test/scripts/helm.sh` that doesn't use `HELM_VERSION` that also needs updated. And if we move to Helm v3, the tiller stuff in that `.sh` script probably needs removed also?

That sounds right, though I'm not super familiar with the helm build.

**Comment by BlaineEXE** [comment]
I think by updating the version to `v2`, Helm v2 is no longer supported. If I'm reading the docs right.
https://helm.sh/docs/topics/v2_v3_migration/

**Comment by travisn** [comment]
@intlabs A few questions:
- Does Rook's [helm documentation](https://rook.github.io/docs/rook/v1.3/helm-operator.html) need any updates for helm 3? For example:
   - Mention that helm 3 is required
   - Any update to the example commands?
- Are there any considerations in the migration from helm 2 to 3? The [helm guide](https://helm.sh/docs/topics/v2_v3_migration/) leads me to believe that Rook will be ok with upgrade scenarios.

**Comment by leseb** [comment]
@intlabs any plan to pursue this work? Thanks

**Comment by intlabs** [comment]
@leseb I'll get this fixed up over the weekend

**Comment by invidian** [comment]
Would be great to get this PR merged.

**Comment by travisn** [comment]
> Would be great to get this PR merged.

Agreed we should get this in for v1.5, thanks for the reminder! I wasn't able to push to this PR, so opened #6556 to look into it.

**Pull request closed without merging**
