### PR TITLE
docs: delete duplicate words and revise the names of some methods

### PR DESCRIPTION
**Pull request by momantech**
**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — CHANGES_REQUESTED** [review]
@momantech Thanks for the updates. Did you use a tool to detect these typos? Just wondering if it could be used in the CI in the future to catch similar issues.

Please just review the [commit structure](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure) to update the commit description.

**Review by travisn — CHANGES_REQUESTED** [review]
@momantech The commitlint CI check is still failing due to an unexpected commit prefix. You could use `docs:` for the prefix. Also it would be great if you could have a description sentence in the commit message, as requested in the [commit structure](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure). Thanks!

**Review by travisn — COMMENTED** [review]
The commitlint is really picky for the commit message, it needs to be all lower-case.

✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]

**Review by subhamkrai — COMMENTED** [review]
can you also add some commit description? Thanks

**Review by travisn — APPROVED** [review]

**Pull request merged**
