### PR TITLE
ci: install yq in daily nightly job

### LINKED ISSUE #10180: arm64 daily integration test is failing to run the operator
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Since [run 194](https://github.com/rook/rook/runs/5209079116?check_suite_focus=true) on Feb 16th, the [arm64 integration daily test](https://github.com/rook/rook/actions/workflows/daily-nightly-jobs.yml?page=3) has been failing. 

No other rook or ceph pods are running besides the operator. The test just says it's waiting for the csi driver to start, which is really the first test of something running.
```
waiting for csi pods to be ready
waiting for csi pods to be ready
waiting for csi pods to be ready
...
```

The operator log shows that it basically started:
```
2022-04-27 00:35:59.384822 I | rookcmd: starting Rook v1.9.0-alpha.0.143.gd5070dc41 with arguments '/usr/local/bin/rook ceph operator'
2022-04-27 00:35:59.398202 I | rookcmd: flag values: --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-level=INFO, --operator-image=, --service-account=
2022-04-27 00:35:59.398212 I | cephcmd: starting Rook-Ceph operator
```

But then the operator pod description shows it's in crash loop backoff:
```
    Last State:     Terminated
      Reason:       Error
      Message:      failed to get pod: Get "https://10.96.0.1:443/api/v1/namespaces/rook-ceph/pods/rook-ceph-operator-65ddb87bcb-jdgkt": dial tcp 10.96.0.1:443: i/o timeout
      Exit Code:    1
...
Events:
  Warning  BackOff    87s (x69 over 19m)  kubelet            Back-off restarting failed container
```

**Expected behavior:**
Passing tests

**How to reproduce it (minimal and precise):**

See the daily tests

### PR DESCRIPTION
**Pull request by subhamkrai**
installing yq in daily nightly job and remove once the job is done

Signed-off-by: subhamkrai <srai@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #10180 

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
Thanks for the update, fingers crossed for a passing arm64 test soon!
How much trouble would it be to test the arm64 build in a PR first before we merge?

**Comment by subhamkrai** [comment]
> Thanks for the update, fingers crossed for a passing arm64 test soon! How much trouble would it be to test the arm64 build in a PR first before we merge?

It should not be much, I'll have to modify the cronJob to just run on my pr

**Comment by subhamkrai** [comment]
we passed that stage https://github.com/rook/rook/actions/runs/3240548131/jobs/5311396385 but still not green.
 we can open diff pr for that and I'll revert extra changes.

**Comment by travisn** [comment]
> we passed that stage https://github.com/rook/rook/actions/runs/3240548131/jobs/5311396385 but still not green. we can open diff pr for that and I'll revert extra changes.

Sounds good to go ahead with this, thanks for verifying

**Review by travisn — APPROVED** [review]

**Pull request merged**
