### PR TITLE
ceph: add ceph storage faq section

### PR DESCRIPTION
**Pull request by Bessonov**
As discussed in Slack, the first entries to the FAQ section.

[skip ci]

### CODE REVIEW

**Comment by BlaineEXE** [comment]
@travisn how does foqual work? Do we get to tell foqual in slack how to answer things, or is it configured by maintainers somewhere?

**Comment by jbw976** [comment]
@BlaineEXE, foqal scrapes all the Rook docs and the slack history to come up with a set of questions and answers that it will automatically provide privately to users when they ask a question on Slack.  We have imported all that data but we have to go through all the Q/A pairs and approve them.  I'm happy to give you an invite and you can start walking through and approving the ones you think look helpful :)

**Comment by leseb** [comment]
What's the status of that PR?

**Comment by Bessonov** [comment]
@leseb I see a discussion about foqual.

**Comment by leseb** [comment]
Closing since we have foqual. Thanks.

**Pull request closed without merging**
