### PR TITLE
helm: update cephfs storageclass parameters

### PR DESCRIPTION
**Pull request by caffeinism**
**Description of your changes:**
- I changed it to the same as deploy/example/csi because it seems that the wrong parameter was entered in storageclass of cephfs.

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [x] Unit tests have been added, if necessary.
- [x] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
@Madhu-1 @Rakshith-R Any concerns with this change? It seems correct to me to match the implementation of the [cephfs storage class](https://github.com/rook/rook/blob/master/deploy/examples/csi/cephfs/storageclass.yaml). Looks like this has been incorrect since the cluster chart was created long ago.

**Review by Rakshith-R — APPROVED** [review]
Thanks, This looks good to me.

**Comment by Madhu-1** [comment]
> @Madhu-1 @Rakshith-R Any concerns with this change? It seems correct to me to match the implementation of the [cephfs storage class](https://github.com/rook/rook/blob/master/deploy/examples/csi/cephfs/storageclass.yaml). Looks like this has been incorrect since the cluster chart was created long ago.

I see a parameter change in the storageclass. As storageclass updates are not allowed, I would like to get this upgrade tested and see if it works.

**Review by travisn — CHANGES_REQUESTED** [review]
Marking as changes requested until the upgrade is validated.

**Comment by caffeinism** [comment]
When I tried updating, it was actually impossible to update the parameters of StorageClass. 👀

```
StorageClass.storage.k8s.io "ceph-filesystem" is invalid: parameters: Forbidden: updates to parameters are forbidden.
```

This parameter looks somewhat wrong in context, but there is no problem with the operation, so should it be kept for consistency in updates?

**Comment by Madhu-1** [comment]
> When I tried updating, it was actually impossible to update the parameters of StorageClass. eyes
> 
> ```
> StorageClass.storage.k8s.io "ceph-filesystem" is invalid: parameters: Forbidden: updates to parameters are forbidden.
> ```
> 
> This parameter looks somewhat wrong in context, but there is no problem with the operation, so should it be kept for consistency in updates?

Yes that's true. we cannot update the parameters and this extra parameter is of no use for cephfs but no harm.

**Comment by Rakshith-R** [comment]
> > When I tried updating, it was actually impossible to update the parameters of StorageClass. eyes
> > ```
> > StorageClass.storage.k8s.io "ceph-filesystem" is invalid: parameters: Forbidden: updates to parameters are forbidden.
> > ```
> > 
> > This parameter looks somewhat wrong in context, but there is no problem with the operation, so should it be kept for consistency in updates?
> 
> Yes that's true. we cannot update the parameters and this extra parameter is of no use for cephfs but no harm.

Lets keep `csi.storage.k8s.io/fstype: ext4` with a note in comment telling that it is just for backward compatibility and has no affect for cephfs storageclass ?

**Comment by travisn** [comment]
How about if we only create the storage class at initial install, and skip updates in all future helm upgrades? I've opened #11398 with this proposal and we can do it separately from this PR. Then we can wait on this PR until that is done. If someone wants to take up that fix, please comment on it, otherwise i'll try to take it up in the next few days. Thanks!

**Pull request closed without merging**
