### PR TITLE
Doc and extension

### PR DESCRIPTION
**Pull request by gcmalloc**
This pull request add two small aesthetic changes

* Uniforming the extensions of the kubernetes manifests
* Adding link to rook-tools and rook-client in the README

### CODE REVIEW

**Comment by travisn** [comment]
@gcmalloc  thanks for the changes, those inconsistent names were bugging me. There just are a couple more places to change as well:
- The soft links in the `demo/kubernetes/1.5` folder
- A test failed that is still using `rook-client.yml`

**Comment by gcmalloc** [comment]
What about changing toolbox to rook-tool ?

**Comment by travisn** [comment]
I'd prefer to stick with rook-tools since there are multiple tools in the container.

**Comment by travisn** [comment]
the changes all look good. Could you just remove the merge commit from the history?

**Comment by travisn** [comment]
note that another PR has been merged, so you'll also need to git fetch and rebase as described here: https://github.com/rook/rook/blob/master/Documentation/development-flow.md#updating-your-fork

**Comment by gcmalloc** [comment]
yep, should be ok now

**Comment by travisn** [comment]
perfect thanks, i'll merge after the build completes

**Pull request merged**
