### PR TITLE
ci: simplify the codegen workflow a bit

### PR DESCRIPTION
**Pull request by obnoxxx**
**Description of changes:** 

the codegen ci workflow was previously fixed by copying the checkout dir to the GOPATH. With the updated codegen tooling, this alignment is not a requirement any more.

This simplifies the codegen workflow again by reverting the earlier changes that added the copy mechanism.

This reverts commit 714f80a80a4de1e104123d720301e6e74799b758.
This reverts commit f32d3df99530e6721d693a9f43a59cc6a0848449.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by obnoxxx** [comment]
removing draft since the codegen ci check passed, as predicted.

**Comment by BlaineEXE** [comment]
Will you apply a temporary commit that changes an API field? I'd like to make sure the test will fail as needed.

**Comment by obnoxxx** [comment]
@BlaineEXE  wrote:
> Will you apply a temporary commit that changes an API field? I'd like to make sure the test will fail as needed.

done. Let's see

**Comment by obnoxxx** [comment]
@BlaineEXE : with the test commit on API, codegen has failed as it should.

**Comment by BlaineEXE** [comment]
Great! Remove that test commit, and we can merge this

**Comment by obnoxxx** [comment]
@BlaineEXE  wrote:
> Great! Remove that test commit, and we can merge this

done.

**Review by BlaineEXE — APPROVED** [review]

**Pull request merged**
