### PR TITLE
ceph: change imagepullpolicy for csi-snapshot image

### LINKED ISSUE #3885: How can I set `imagePullPolicy: IfNotPresent ` for csi-snapshotter!
How can I set it to 'IfNotPresent'.
```shell
[root@master-0 ~]# kubectl get pods -n rook-ceph  csi-rbdplugin-provisioner-749df6d8bf-h2blc  -o jsonpath='{.spec.containers[?(@.name=="csi-snapshotter")].imagePullPolicy}'
Always
```
rook version: 1.1.0

### PR DESCRIPTION
**Pull request by awalker125**
Signed-off-by: awalker60 <awalker125@users.noreply.github.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #3885

**Checklist:**

- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [X] Documentation has been updated, if necessary.
- [X] Unit tests have been added, if necessary.
- [X] Integration tests have been added, if necessary.
- [X] Pending release notes updated with breaking and/or notable changes, if necessary.
- [X] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [X] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [X] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](https://github.com/rook/rook/blob/master/CONTRIBUTING.md#comments)
- [X] Add the flag for skipping the CI if this PR does not require a build. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for more details.

### CODE REVIEW

**Comment by awalker125** [comment]
Not sure why CI failed from the log. It doesn't seem to be related to my change?

**Comment by Madhu-1** [comment]
> @Madhu-1 Was the `imagePullPolicy: always` needed previously? Perhaps when we were using the canary tag?

@travisn not sure why the image policy was always, this can be changed to match other images pull policy

**Comment by Madhu-1** [comment]
> Not sure why CI failed from the log. It doesn't seem to be related to my change?

This is nothing to do with this PR.

@leseb @travisn can we merge this one?

**Comment by Madhu-1** [comment]
@awalker125 we need better PR heading

**Comment by awalker125** [comment]
Is the new heading any better?

**Comment by Madhu-1** [comment]
> Is the new heading any better?

how about something like `change imagepullpolicy for csi-snapshot image`

**Comment by awalker125** [comment]
Yeah that sounds good

**Comment by leseb** [comment]
@Madhu-1 do we need a backport for this?

**Comment by Madhu-1** [comment]
> @Madhu-1 do we need a backport for this?

@leseb this is not a bug fix, it's just an enhancement. if required we can backport it.

**Comment by leseb** [comment]
> > @Madhu-1 do we need a backport for this?
> 
> @leseb this is not a bug fix, it's just an enhancement. if required we can backport it.

Ok so backport then.

**Pull request merged**
