### PR TITLE
docs: add vscode badge to the README

### PR DESCRIPTION
**Pull request by leseb**
**Description of your changes:**

Clicking on the badge will bring you to a page on open.vscode.dev,
where you can choose how to continue in VS Code

Signed-off-by: Sébastien Han <seb@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
this looks new/exciting to me, I'll have to read more about the second option `Developing inside a Container`.  But is good that we don't always have to clone a repo to gothrogh the codebase.

**Review by travisn — CHANGES_REQUESTED** [review]
Instead of adding a badge, what about a link from the [development flow](https://github.com/rook/rook/blob/master/Documentation/development-flow.md)?

**Comment by leseb** [comment]
> Instead of adding a badge, what about a link from the [development flow](https://github.com/rook/rook/blob/master/Documentation/development-flow.md)?

What's wrong with the badge? 🙂

**Comment by travisn** [comment]
> > Instead of adding a badge, what about a link from the [development flow](https://github.com/rook/rook/blob/master/Documentation/development-flow.md)?
> 
> What's wrong with the badge? 🙂

All the current badges are related to project status. To me this badge doesn't fit the pattern. If we add this, we could have an explosion of badges such as to join the community meeting, launch the docs, etc...

**Pull request closed without merging**
