### PR TITLE
core: Cleanup blockpool with annotation

### PR DESCRIPTION
**Pull request by Madhu-1**
This is similar to #14052 we did for radosnamespace and this is an extension to support cleanup at the blockpool level to cleanup the images and the snapshots in a pool. 

Motive:- I saw an issue where users are using scripts to cleanup the resources, I thought it's better to have the functionality in Rook itself.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

Note:-  I tried to keep the changes minimal as much as possible and reuse whatever we have for the rados namespace cleanup (with little modification)

If this is good, i would like to do one final round of testing before merging.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
LGTM, will hold off approving until your testing is confirmed. 

Next, do we need to clean up the CephFilesystem as well?

**Comment by Madhu-1** [comment]
```text
[🎩︎]mrajanna@li-2cfbef4c-22d9-11b2-a85c-a3e4a93c405f rbd $]kuberc logs po/cleanup-cephblockpool-replicapool-r4p8x
2024/10/24 07:35:58 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
2024-10-24 07:35:58.378460 I | rookcmd: starting Rook v1.15.0-alpha.0.292.g4e2971731-dirty with arguments '/usr/local/bin/rook ceph clean CephBlockPool'
2024-10-24 07:35:58.378489 I | rookcmd: flag values: 
2024-10-24 07:35:58.378954 I | cleanup: starting clean up of CephBlockPool "replicapool" resource
2024-10-24 07:35:58.378977 D | exec: Running command: rbd ls -l replicapool --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json
2024-10-24 07:35:58.418423 I | cleanup: successfully cleaned up CephBlockPool "replicapool" resource
[🎩︎]mrajanna@li-2cfbef4c-22d9-11b2-a85c-a3e4a93c405f rbd $]kuberc get cephblockpool
NAME          PHASE   TYPE         FAILUREDOMAIN   AGE
builtin-mgr   Ready   Replicated   host            21m
```

Tested it, it works as expected

**Comment by Madhu-1** [comment]
> LGTM, will hold off approving until your testing is confirmed.
> 
> Next, do we need to clean up the CephFilesystem as well?

@travisn i assume this is not required because we always use subvolumegroup and subvolume concept and we already have cleanup job for subvolumegroup

**Comment by travisn** [comment]
> > LGTM, will hold off approving until your testing is confirmed.
> > Next, do we need to clean up the CephFilesystem as well?
> 
> @travisn i assume this is not required because we always use subvolumegroup and subvolume concept and we already have cleanup job for subvolumegroup

Yeah, that's probably sufficient. Though perhaps for consistency it could help on the CephFilesystem so that all subvolumegroups would be automatically cleaned up, instead of annotating each svg individually.

**Review by travisn — APPROVED** [review]

**Comment by Madhu-1** [comment]
> > > LGTM, will hold off approving until your testing is confirmed.
> > > Next, do we need to clean up the CephFilesystem as well?
> > 
> > 
> > @travisn i assume this is not required because we always use subvolumegroup and subvolume concept and we already have cleanup job for subvolumegroup
> 
> Yeah, that's probably sufficient. Though perhaps for consistency it could help on the CephFilesystem so that all subvolumegroups would be automatically cleaned up, instead of annotating each svg individually.

Yeah we could try that, let me see if i can take care of it.

**Pull request merged**
