### PR TITLE
object: do not add objectstore endpoint to zone when sync is disabled

### LINKED ISSUE #12533: CephObjectStore with disabled replication traffic should be added to Zone endpoints
* Bug Report

As previously reported in [this comment](https://github.com/rook/rook/issues/12272#issuecomment-1632770630) and [this PR](https://github.com/rook/rook/pull/12327#issuecomment-1637486526), it seems that when CephObjectStores have the option `disableMultisiteSyncTraffic` set to `true`, the operator should not add the CephObjectStore endpoint to the Zone endpoints.

We deployed two CephObjectStore as recommended when scaling the number of gateways (one CephObjectStore dedicated to running the replication threads, and the other gateways dedicated to serving user traffic). We noticed that this broke the replication. Modifying the Zone manually to only keep the endpoint of the CephObjectStore that run sync threads restarted the replication. 

I had a look at the code. It seems that the method `setMultisite` in `pkg/operator/ceph/object/objectstore.go` should not be called when `DisableMultisiteSyncTraffic` is set to `true`.

If stopping calling the line https://github.com/rook/rook/blob/647a4e3534a41015aae9bc3ed21e12b10a9f9192/pkg/operator/ceph/object/controller.go#L447 is okay to you, I could create a new PR. We may need a new unit test too.

### PR DESCRIPTION
**Pull request by polyedre**
Gateways that do not run the sync threads should not be accessible from one of the Zone endpoint. If this is the case, the synchronization might stop working.

When the CephObjectStore has the option
`spec.gateway.disableMultisiteSyncTraffic` set to `true`, we must ensure that the objectstore endpoint is not present in the Zone endpoint.

Resolves #12533

**I tried to add some unit tests, but struggled to add one. There is currently no tests that verify that the ObjectStore endpoint is added to or removed from the Zone endpoints.**

However, I manually tested the following scenarios:
1. Creating a new Zone and a new CephObjectStore A without sync: endpoints are empty
2. Adding a new ObjectStore B with sync: endpoint contain B's endpoint 
3. Enabling the sync on A: endpoints contain A and B's endpoints
4. Disabling the sync on A again: endpoint contain B's endpoint

**Checklist:**

- [x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [x] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [x] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [x] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [x] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by BlaineEXE — CHANGES_REQUESTED** [review]
Two really minor code related requests for now. I think the behavior makes sense, and I'm glad to see that the change is minor.

I'd like @alimaredia to take a look to double check the behavior logic.

And @polyedre could you add a unit test for this case? I think it can be fairly simple, but regression tests are a good practice.

**Comment by polyedre** [comment]
Thanks for the quick review! I updated the code with your two requests.

As explained in the PR message, I tried to add a unit test but struggled because there is currently no test that verifies that the Zone endpoint is modified when a new objectstore is reconciled. I've already spent some time on the subject, but to no avail. I'll try again if I have time early next week.

**Comment by alimaredia** [comment]
If we're already not testing to check to make sure the object-stores endpoints are being added to the zone's endpoints list then I don't think we need further testing. 

That being said, since adding customEndpointsList is an option in the Zone and is the preferred method/overrides the option for object-stores to be added in I'm not too worried about testing this,

**Review by alimaredia — APPROVED** [review]

**Review by BlaineEXE — APPROVED** [review]

**Comment by BlaineEXE** [comment]
Approved! I'm re-running the failed object test which I want to make sure passes before merging this. Otherwise, looks good, and thanks for the quick follow-up @polyedre !

**Comment by BlaineEXE** [comment]
Thanks again @polyedre !

**Pull request merged**
