### PR TITLE
[WIP] ci: update canary tests to ubuntu 20.04 (please ignore)

### PR DESCRIPTION
**Pull request by ideepika**
- test canary test failures
- support k8s depreciation of 18.04

Signed-off-by: Deepika Upadhyay <deepika@koor.tech>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by satoru-takeuchi** [comment]
@ideepika Can we close this PR? Now CI is run on top of ubuntu-2004 runner.

**Comment by subhamkrai** [comment]
> @ideepika Can we close this PR? Now CI is run on top of ubuntu-2004 runner.

@satoru-takeuchi we have most of the CI running of 20.04 but not all we noticed in some canary tests we're getting OSD pods not coming due to some partition issue or something. For example this ci https://github.com/rook/rook/blob/master/.github/workflows/canary-integration-test.yml#L273

**Comment by satoru-takeuchi** [comment]
@subhamkrai OK, understood.

**Comment by subhamkrai** [comment]
> @subhamkrai OK, understood.

@satoru-takeuchi anyway do you have any idea what changed in ubuntu 20.04 that our osd is not coming, for more details https://github.com/rook/rook/actions/runs/2964654735/jobs/4744664883

It will good to have the fix for the issue since ubuntu 18.04 will removed soon.

**Comment by satoru-takeuchi** [comment]
@subhamkrai I'll take a look at it and get back to you later.

**Comment by satoru-takeuchi** [comment]
This problem might come from the diferrence of the available resources between ubuntu18.04 worker and 20.04 worker.. My assumption is that osds couldn't start in ubuntu20.04 due to lack of resources like free disk space and availae memory.

The following PR might mitigate CI failures in Ubuntu20.04.
https://github.com/rook/rook/pull/10990

I'll run the two osd canary test on top of ubuntu20.04 worker with the latest main including #10990 .

**Comment by subhamkrai** [comment]
> This problem might come from the diferrence of the available resources between ubuntu18.04 worker and 20.04 worker.. My assumption is that osds couldn't start in ubuntu20.04 due to lack of resources like free disk space and availae memory.
> 
> The following PR might mitigate CI failures in Ubuntu20.04. #10990
> 
> I'll run the two osd canary test on top of ubuntu20.04 worker with the latest main including #10990 .

Not sure if that is the reason since integration tests are using 20.04 and some canary tests are also using 20.04. FWIW, while moving some of the canary tests to 20.04 that are currently running I had to little tweak like here https://github.com/rook/rook/pull/10876/commits/9bd83a0fab5ecc982673fc28cf8379d529d51277#diff-52941359541463e1524cc79b54cadacab9ee93f3a54a0c738fc61e2c6bf936afR46 to the script for partitioning the disk.

**Comment by satoru-takeuchi** [comment]
> Not sure if that is the reason since integration tests are using 20.04 and some canary tests are also using 20.04

I confirmed that there isn't resource starvation in ubuntu 20.04.

Instead, I found that the partition of extra disk was not removed in ubuntu 20.04. Here are the results of {df,free,lsblk} just after formatting the extra disk.

ubuntu18.04
https://github.com/rook/rook/actions/runs/3067342292/jobs/4953522692#step:5:132
```
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0   86G  0 disk 
├─sda1    8:1    0 85.9G  0 part /
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part /boot/efi
sdb       8:16   0   14G  0 disk
```

sdb doesn't exist and test works well.

ubuntu20.04
https://github.com/rook/rook/actions/runs/3067342292/jobs/4953522873#step:5:151
```
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0    0 67.8M  1 loop /snap/lxd/22753
loop1     7:1    0   62M  1 loop /snap/core20/1587
loop2     7:2    0   47M  1 loop /snap/snapd/16292
sda       8:0    0   86G  0 disk 
├─sda1    8:1    0 85.9G  0 part /
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part /boot/efi
sdb       8:16   0   14G  0 disk 
└─sdb1    8:17   0   14G  0 part 
```

sdb1 still alive and then test fails because we can't create osd on top of sdb. I logged in to the runner and confirmed that someone still use sdb1 and so this partition can't be removed.

I'm now investigating why this difference happens and how to resolve this problem. Please let me know if you have any idea.

**Comment by subhamkrai** [comment]
> > Not sure if that is the reason since integration tests are using 20.04 and some canary tests are also using 20.04
> 
> I confirmed that there isn't resource starvation in ubuntu 20.04.
> 
> Instead, I found that the partition of extra disk was not removed in ubuntu 20.04. Here are the results of {df,free,lsblk} just after formatting the extra disk.
> 
> ubuntu18.04 https://github.com/rook/rook/actions/runs/3067342292/jobs/4953522692#step:5:132
> 
> ```
> NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
> sda       8:0    0   86G  0 disk 
> ├─sda1    8:1    0 85.9G  0 part /
> ├─sda14   8:14   0    4M  0 part 
> └─sda15   8:15   0  106M  0 part /boot/efi
> sdb       8:16   0   14G  0 disk
> ```
> 
> sdb doesn't exist and test works well.
> 
> ubuntu20.04 https://github.com/rook/rook/actions/runs/3067342292/jobs/4953522873#step:5:151
> 
> ```
> NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
> loop0     7:0    0 67.8M  1 loop /snap/lxd/22753
> loop1     7:1    0   62M  1 loop /snap/core20/1587
> loop2     7:2    0   47M  1 loop /snap/snapd/16292
> sda       8:0    0   86G  0 disk 
> ├─sda1    8:1    0 85.9G  0 part /
> ├─sda14   8:14   0    4M  0 part 
> └─sda15   8:15   0  106M  0 part /boot/efi
> sdb       8:16   0   14G  0 disk 
> └─sdb1    8:17   0   14G  0 part 
> ```
> 
> sdb1 still alive and then test fails because we can't create osd on top of sdb. I logged in to the runner and confirmed that someone still use sdb1 and so this partition can't be removed.
> 
> I'm now investigating why this difference happens and how to resolve this problem. Please let me know if you have any idea.

I don't know the fix at the moment but I believe that is a good hint to find the fix

**Comment by ideepika** [comment]
hey @satoru-takeuchi did you have any new findings?

**Comment by satoru-takeuchi** [comment]
@ideepika Not yet. I couldn't worked on this problem for several days. But I'll do it again next week.

**Comment by satoru-takeuchi** [comment]
All runnner became ubuntu 20.04 in #11004.

**Pull request closed without merging**
