### PR TITLE
Distinguishing the Rook operator from the current storage technology Ceph

### PR DESCRIPTION
**Pull request by leseb**
This is an attempt to avoid confusion for the end users.
Rook is not the storage entity, it's the orchestrator that currently deploys Ceph.
Other backends might follow but now everything (deployment, code,
examples) is being done with Ceph.

Ceph is the storage technology so anything related to configuration
should highlight Ceph and not Rook.

I believe it's crucial that users make the distinction between the
rook-operator/agent AND the Ceph cluster (mon,osd,rgw,mds,mgr etc).

This commits helps clarifying this by naming rook all the
variables/options related to the deployment and 'ceph' what's related to
the storage.

Signed-off-by: Sébastien Han <seb@redhat.com>

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [x] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

### CODE REVIEW

**Comment by syndbg** [comment]
If the goal of the project is to provide more than Ceph as a storage backend, what's the point of exposing Ceph?

**Comment by leseb** [comment]
It's not so much about exposing Ceph, it's more giving the right exposure, and this starts by stopping to say things like "Rook cluster." Rook is not the cluster; Rook is an operator. Ceph is the cluster, the storage technology.

Basically, if you're choosing the 'ceph' backend, your namespace should be 'ceph' not 'rook'.

I'm just re-arranging the wording to avoid the confusion.

**Comment by bassam** [comment]
I'd suggest we wait on changing wording until we make more progress on backend refactoring.

**Comment by liewegas** [comment]
Hmm,
- I wouldn't change /var/lib/rook -> /var/lib/ceph because the content/structure you find there is different.
- Naming the ceph *cluster* namespace 'rook' seems very confusing to me.  If the cluster type in that namespace is ceph, why not reflect that in the namespace name?  Then if you deploy two backends you'll have a 'ceph' namespace and a 'gluster' (or whatever) namespace, not 'rook' and 'rook2' (or whatever).  This clarifies what the namespace is to the user: the 'rook-whatever' one contains rook, the 'ceph' one contains a ceph cluster, etc.  
- If I understand the 'name' property for the ceph cluster, that's the cluster name used inside the container when deploying ceph, correct?  IMO this should be removed complete and the ceph cluster should always be called 'ceph'.  This is the default for all of the ceph tooling and the cluster name machinery is currently used only for identify multiple clusters to clients--not on the server.  (Otherwise the primary effect here is that you have to type '--cluster rook' for any CLI command executing within the container.)

**Comment by travisn** [comment]
- The name of the namespace is really just an example in the yaml files and documentation. It could be named `rook`, `ceph`, `rook-ceph`, or use any other namespace that exists with other pods in it. I would agree that if there are multiple backends, you would likely want the name of the backed in the namespace for clarity. So the question is really what the namespace should be called in the samples.
- Agreed that internally to the pods, the default ceph name should be used to work more naturally with the tools, similarly to comments in #1347

**Comment by travisn** [comment]
note that `rook-ceph` would follow the pattern we have for the system namespace `rook-system`, but again it's just a sample.

**Comment by leseb** [comment]
@liewegas as far as I saw the current `/var/lib/rook` contains mon/osd stores and the equivalent of `/etc/ceph` so this is purely Ceph.

Even though there is currently a single backend only and Rook's goal is to abstract storage, Rook still appears to be described as the storage technology. Abstracting the storage doesn't mean becoming the storage itself.
I know the current yamls are "examples" only but that not the feeling everyone gets if new to Rook.

I still see value in this PR to at least clarify and differentiate technologies.

**Comment by travisn** [comment]
@leseb @bassam @jbw976 thoughts on using the namespace `rook-ceph` in the examples?

**Comment by leseb** [comment]
@travisn `rook-ceph` is fine with me, the approach `rook-$backend` is useful.

**Comment by kokhang** [comment]
-1. I also in the camp of against exposing internal backends on the Rook APIs or documentations. 

I am not aware about the level of confusion in our users. To me, and i think most K8S users, Rook 'is' a storage cluster. It provides storages to K8s apps. It integrates with the K8S storage controller and provides storage by abstracting a lot of the challenge of running and managing a complex backend solution like ceph or gluster. 

> Naming the ceph cluster namespace 'rook' seems very confusing to me. If the cluster type in that namespace is ceph, why not reflect that in the namespace name? Then if you deploy two backends you'll have a 'ceph' namespace and a 'gluster' (or whatever) namespace, not 'rook' and 'rook2' (or whatever). This clarifies what the namespace is to the user: the 'rook-whatever' one contains rook, the 'ceph' one contains a ceph cluster, etc.

If we are to go on this route, then we should look into converting the `Cluster` object to `CephCluster`. That way users can explicitly specify the backend. But i dont think users need to be exposed to this. 

The main reason i have seen users come to Rook is for the desire of "i want a distributed persistent storage for my k8s cluster", or "I want a RWX storage for my K8S app" or "I want a storage solution for my baremetal K8S". I still havent yet seen users come to us "because they just want to run ceph in their K8S cluster".

**Comment by leseb** [comment]
@kokhang ultimately one of Rook's goal is to provide multi-backends, so we have to highlight them a way or another in the API/documentation.

If you think Rook is a storage cluster, then I think there might be a misunderstanding. Rook is **not** a storage cluster, Rook doesn't write/read any data. It doesn't do anything with container's data. Rook **orchestrates** cluster deployments/lifecycle.

As Rook is getting more mature, and with potentially more backend I believe starting the distinction now is better.

I believe @travisn's last suggestion is a good start and not too disruptive.

**Comment by kokhang** [comment]
@leseb I am looking at this from the API perspective. Currently in Rook, the way to create the storage cluster is by creating the `Cluster`, `Filesystem` and `ObjectStore` objects, which i think reinforces the interpretation of Rook being the "storage cluster". Similarly in the K8S API, when K8S users wants to create a storage volume, the `Kind` is  `provisioner: rook.io/block`.

Based on the API, I feel that Rook is a storage cluster for Kubernetes, and an alternative to other storage like EBS and GPD. I see the storage provisioner backens, whether is ceph or gluster, as an implementation and configuration detail. Just the same way I see the storage mapping, whether is kernel rbd, nbd, iscsi, etc. These to me are all details and config params within Rook.

If we want users to denote whether the cluster is a ceph cluster, they can do this by providing a name to the Rook `Cluster`. See here. https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-cluster.yaml#L9

I dont think we need to change our documentations and manifests to denote this.

**Comment by bassam** [comment]
Rook is cloud-native storage orchestrator and not a storage system on its own. We need to be clear about that in documentation and everywhere else. Rook is not trying to coopt Ceph or other backends, but instead, complement them.

There is an effort in the 0.8 release to add another backend to rook and I believe that will help us figure out the abstractions around CRDs etc. It will also help clear the confusion about rook's role. I'd like to hold off on making any changes until we get the multiple backend design completed.

/cc @jbw976

**Comment by leseb** [comment]
@bassam sounds about right to me, glad to see we are on the same page. I can rework this once the new backend lands so then we will have a clear distinction. Thanks.

@kokhang the API and so forth the abstraction is not an issue, things look good on this aspect. Also since the goal is to have multi storage backends, they must be exposed a way or another, which means users will have to decide at some point too. Just like you mentioned I think there should be a clear distinction between Rook being the Orchestrator and its numerous backends.
One more thing, people saying "give me a storage cluster I don't care about the rest" are likely developer playing around, not operators. Currently, operators do know Ceph is underneath because that's the only backend. If you are going to production you must decide which backend to use. You can't abstract everything for the good of end-user-developers only.
To conclude, the way the API works is fine, once the new backend lands we will have the clear distinctions between Rook (its goal/role and API) and its storage backends; moreover, one backend might be more suitable than another so going with the default without knowing won't work. Thanks.

**Comment by bassam** [comment]
@leseb recommend closing this for now in favor of the multiple backend work started in #1587.

**Comment by leseb** [comment]
Sure.

**Pull request closed without merging**
