### PR TITLE
Fix driver name in ceph csi driver

### PR DESCRIPTION
**Pull request by Madhu-1**
**Description of your changes:**
This PR fixes the driver name as per csi specification and also simplifies the socket directory name
inside csi containers.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by Madhu-1** [comment]
@rootfs @travisn PTAL

**Comment by rootfs** [comment]
@Madhu-1 @travisn CSI smoke test did run on k8s 1.13.1 , can you add more logging around [here](https://github.com/rook/rook/blob/master/tests/integration/ceph_csi_test.go#L43) and see what happened?

https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-2839/runs/1/nodes/48/steps/96/log/?start=0

```
PASS: TestSmokeSuite/TestBlockCSI_SmokeTest (0.01s)
```

**Comment by Madhu-1** [comment]
> @Madhu-1 @travisn CSI smoke test did run on k8s 1.13.1 , can you add more logging around [here](https://github.com/rook/rook/blob/master/tests/integration/ceph_csi_test.go#L43) and see what happened?
> 
> https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-2839/runs/1/nodes/48/steps/96/log/?start=0
> 
> ```
> PASS: TestSmokeSuite/TestBlockCSI_SmokeTest (0.01s)
> ```

@rootfs sorry, i didn't get you, what you want me to log you want me to add in that function? can you please elaborate little more?

**Comment by rootfs** [comment]
@Madhu-1 can you check why CSI smoke test is not running (it exit in just 0.01s)? Can you add logging around the smoke test to see why it doesn't start?

**Comment by Madhu-1** [comment]
Yeah you are correct, let me put some logs and check

**Comment by Madhu-1** [comment]
@rootfs the csi driver is not in running state, so the tests are getting skipped

https://github.com/rook/rook/pull/2839/files#diff-2aebb1a389c20e3b14d7e4f70b43671eR45

```
=== RUN   TestSmokeSuite/TestBlockCSI_SmokeTest
2019-03-20 06:51:43.066150 I | integrationTest: $$$$$$$$$$$$$$$$$$$$$$$$$$$ if Ceph csi driver running = false
```

**Comment by Madhu-1** [comment]
@rootfs @travisn from the logs, i see only roles and configmaps are getting created
```
configmap/csi-rbd-config created
configmap/csi-cephfs-config created
serviceaccount/rook-csi-rbd-attacher-sa created
clusterrole.rbac.authorization.k8s.io/rbd-external-attacher-runner created
clusterrolebinding.rbac.authorization.k8s.io/rbd-csi-attacher-role created
serviceaccount/rook-csi-rbd-plugin-sa created
clusterrole.rbac.authorization.k8s.io/rbd-csi-nodeplugin created
clusterrolebinding.rbac.authorization.k8s.io/rbd-csi-nodeplugin created
serviceaccount/rook-csi-rbd-provisioner-sa created
clusterrole.rbac.authorization.k8s.io/rbd-external-provisioner-runner created
clusterrolebinding.rbac.authorization.k8s.io/rbd-csi-provisioner-role created
serviceaccount/rook-csi-cephfs-plugin-sa created
clusterrole.rbac.authorization.k8s.io/cephfs-csi-nodeplugin created
clusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-nodeplugin created
serviceaccount/rook-csi-cephfs-provisioner-sa created
clusterrole.rbac.authorization.k8s.io/cephfs-external-provisioner-runner created
clusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-provisioner-role created
``` 
but why the csi pods are not creating ?

**Comment by travisn** [comment]
@Madhu-1 I suspect the csi plugin pod is failing to start. The test will be skipped if this is false:
```
return k8sh.IsPodWithLabelPresent("app=csi-rbdplugin", installer.SystemNamespace(namespace))
```
Do you see an error if you start the csi driver in a local test cluster?

**Comment by Madhu-1** [comment]
@travisn

am facing below issue while running integration tests

```
rook-ceph-mon-a-6c77c98cc9-wsq7j   0/1     Error    2          28s
[🎩]mrajanna@localhost scripts $]
[🎩]mrajanna@localhost scripts $]kubectl get po -nblock-k8s-ns
NAME                               READY   STATUS   RESTARTS   AGE
rook-ceph-mon-a-6c77c98cc9-wsq7j   0/1     Error    2          31s
[🎩]mrajanna@localhost scripts $]kubectl logs po/rook-ceph-mon-a-6c77c98cc9-wsq7j -nblock-k8s-ns
debug 2019-03-21 04:34:55.842 7fb15bb77a00  0 ceph version 13.2.5 (cbff874f9007f1869bfd3821b7e33b2a6ffd4988) mimic (stable), process ceph-mon, pid 1
debug 2019-03-21 04:34:55.844 7fb15bb77a00 -1 error: monitor data filesystem reached concerning levels of available storage space (available: -2147483648% 0 B)
you may adjust 'mon data avail crit' to a lower value to make this go away (default: 5%)
```
```
[🎩︎]mrajanna@localhost scripts $]minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.4G     0  1.4G   0% /dev
tmpfs           1.5G     0  1.5G   0% /dev/shm
tmpfs           1.5G   18M  1.5G   2% /run
tmpfs           1.5G     0  1.5G   0% /sys/fs/cgroup
tmpfs           1.5G   20K  1.5G   1% /tmp
/dev/sda1        17G  3.0G   13G  20% /mnt/sda1
/hosthome        79G   72G  6.4G  92% /hosthome
$ 

```

* Steps followed to run integration tests
 * brought up kube cluster using ./scripts/minikube.sh up  (virtualbox)
 * ran ./integration.sh tests.v

**Comment by rootfs** [comment]
looks csi test not running
```
=== RUN   TestSmokeSuite/TestBlockCSI_SmokeTest
2019-03-21 06:29:42.931025 I | integrationTest: $$$$$$$$$$$$$$$$$$$$$$$$$$$ if Ceph csi driver running = false
```

**Comment by Madhu-1** [comment]
@rootfs yes, even I added more logs, looks like we are not starting csi driver in the test cases.

**Comment by travisn** [comment]
@Madhu-1 still blocked on triggering the integration tests?

**Comment by Madhu-1** [comment]
@travisn am not able to run the tests locally.

**Comment by travisn** [comment]
ok, i'll take a look tomorrow

**Comment by travisn** [comment]
@Madhu-1 There is an error in the operator log that is causing the csi drivers not to be started:
```
2019-04-05 18:22:59.047351 I | operator: ######### server major and minor version 1 13
2019-04-05 18:22:59.047775 I | operator: ######### kube major and minor version 1 13
2019-04-05 18:22:59.047795 I | operator: ######### check version true
2019-04-05 18:22:59.047799 I | operator: Ceph CSI driver is enabled, validate csi param
2019-04-05 18:22:59.047807 I | operator: Ceph CSI driver is enabled, validate csi param
########################### are we starting the CSI driver ########################
2019-04-05 18:22:59.049784 W | operator: failed to start Ceph csi drivers: failed to load rbd plugin template: error converting YAML to JSON: yaml: line 52: did not find expected '-' indicator
```

I don't see that error when I start the cluster with the `operator-with-csi.yaml` and following the doc instructions. There must be an error in the yaml in the integration tests.

Please rebase your changes to pick up the latest in master as well.

**Comment by Madhu-1** [comment]
@travisn am getting something different error as  no file or directory

`2019-04-08 17:16:38.350359 E | installer: failed to start CSI driver in namespace smoke-ns, error -> failed to load rbd plugin template: open : no such file or directory
`

**Comment by Madhu-1** [comment]
figured out what's the issue, will fix and update this PR

**Comment by Madhu-1** [comment]
following mentioned [steps](https://github.com/rook/rook/pull/2839#issuecomment-480379350) to  do integration testing. facing issues with `minikube` to do integration testing, not able to test changes locally.

```
[🎩]mrajanna@localhost rook $]kubectl get po -nsmoke-ns-system
NAME                                READY   STATUS              RESTARTS   AGE
csi-cephfsplugin-nh9vv              0/2     RunContainerError   0          4m49s
csi-cephfsplugin-provisioner-0      1/2     ErrImagePull        0          4m49s
csi-rbdplugin-4fjk9                 0/2     RunContainerError   0          4m49s
csi-rbdplugin-attacher-0            1/1     Running             1          4m49s
csi-rbdplugin-provisioner-0         1/3     ImageInspectError   0          4m49s
rook-ceph-agent-qf5zn               1/1     Running             0          4m49s
rook-ceph-operator-7f5858cb-clb6h   1/1     Running             0          4m51s
rook-discover-4gzcl                 1/1     Running             0          4m49s


  rook-ceph-admin-keyring:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-admin-keyring
    Optional:    false
  rook-ceph-mgr-token-p9nkp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-mgr-token-p9nkp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               2m19s                default-scheduler  Successfully assigned smoke-ns/rook-ceph-mgr-a-644677ccc7-c9446 to minikube
  Warning  FailedCreatePodSandBox  0s (x11 over 2m19s)  kubelet, minikube  Failed create pod sandbox: open /etc/resolv.conf: no such file or directory



Normal   Created    101s   kubelet, minikube  Created container
  Warning  Failed     101s   kubelet, minikube  Error: failed to start container "csi-rbdplugin": Error response from daemon: OCI runtime create failed: open /var/run/docker/runtime-runc/moby/csi-rbdplugin/state.json: no such file or directory: unknown
```

**Comment by travisn** [comment]
@Madhu-1 Minikube has an issue when running in minikube. Enabling `bidirectional` mounts kills docker. By disabling the two bidirectional properties in [this source yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml#L71) you can get past that error, but then of course the csi driver doesn't work properly. We really need to figure out this issue on minikube so it doesn't block the local testing. For now I'd suggest going ahead and push your change to let jenkins test it. Could you open an issues for this minikube issue though? thanks

**Comment by Madhu-1** [comment]
https://github.com/kubernetes/minikube/issues/4072

**Comment by Madhu-1** [comment]
@travisn CI passed locally PTAL
```
[🎩︎]mrajanna@localhost k8s-cluster $]kubectl get po -nsmoke-ns-system
NAME                                READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-provisioner-0      2/2     Running   0          2m25s
csi-cephfsplugin-z2hz6              2/2     Running   0          2m25s
csi-cephfsplugin-zgwwl              2/2     Running   0          2m25s
csi-rbdplugin-54w89                 2/2     Running   0          2m25s
csi-rbdplugin-gchpv                 2/2     Running   0          2m25s
csi-rbdplugin-provisioner-0         4/4     Running   0          2m25s
rook-ceph-agent-4w2q6               1/1     Running   0          2m26s
rook-ceph-agent-75692               1/1     Running   0          2m26s
rook-ceph-operator-7f5858cb-s7749   1/1     Running   0          2m28s
rook-discover-vkkth                 1/1     Running   0          2m26s
rook-discover-vrh2s                 1/1     Running   0          2m26s
```
```

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc-csi
  namespace: smoke-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-csi-rbd
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-test-rbd
  namespace: smoke-ns
spec:
  containers:
  - name: csi-test-rbd
    image: busybox
    command:
        - sh
        - "-c"
        - "touch /test/csi.test && sleep 3600"
    imagePullPolicy: IfNotPresent
    env:
    volumeMounts:
    - mountPath: /test
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
       claimName: rbd-pvc-csi
       readOnly: false
  restartPolicy: Never
2019-04-10 18:20:16.148151 I | testutil: Running kubectl [create -f -]
persistentvolumeclaim/rbd-pvc-csi created
pod/csi-test-rbd created
2019-04-10 18:20:26.459600 I | testutil: waiting for pod csi-test-rbd in namespace smoke-ns to be running
2019-04-10 18:20:36.464305 I | testutil: waiting for pod csi-test-rbd in namespace smoke-ns to be running
2019-04-10 18:20:46.476750 I | testutil: waiting for pod csi-test-rbd in namespace smoke-ns to be running
2019-04-10 18:20:46.480353 I | testutil: kubectl create manifest:

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc-csi
  namespace: smoke-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-csi-rbd
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-test-rbd
  namespace: smoke-ns
spec:
  containers:
  - name: csi-test-rbd
    image: busybox
    command:
        - sh
        - "-c"
        - "touch /test/csi.test && sleep 3600"
    imagePullPolicy: IfNotPresent
    env:
    volumeMounts:
    - mountPath: /test
      name: csivol
  volumes:
  - name: csivol
    persistentVolumeClaim:
       claimName: rbd-pvc-csi
       readOnly: false
  restartPolicy: Never
2019-04-10 18:20:46.480388 I | testutil: Running kubectl [delete -f -]
persistentvolumeclaim "rbd-pvc-csi" deleted
pod "csi-test-rbd" deleted
job.batch/rook-cleanup-bf3b89f7-eae9-414a-bdc0-2a03bcd818f6 created
2019-04-10 18:21:58.059680 I | installer: removing /home/mrajanna/workspace/src/github.com/rook/rook/tests/integration/rook-test from node test-prefix-this-is-a-very-long-hostname-worker1. err=<nil>
2019-04-10 18:21:58.071653 I | testutil: restoring hostname of node master to master
2019-04-10 18:21:58.093197 I | testutil: restoring hostname of node worker0 to worker0
2019-04-10 18:21:58.127600 I | testutil: restoring hostname of node worker1 to worker1
--- PASS: TestSmokeSuite (231.91s)
    --- PASS: TestSmokeSuite/TestBlockCSI_SmokeTest (68.25s)
PASS
ok  	github.com/rook/rook/tests/integration	231.923s
[🎩︎]mrajanna@localhost rook $]
```

**Pull request merged**
