### PR TITLE
Codegen update for the object store user

### PR DESCRIPTION
**Pull request by travisn**
Signed-off-by: travisn <tnielsen@redhat.com>

**Description of your changes:**
The codegen was performed for the object store user some time ago. This will update the codegen with the latest and greatest k8s tools referenced by rook.

**Checklist:**
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.
- [ ] Comments have been added or updated based on the standards set in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md#comments)

### CODE REVIEW

**Comment by galexrt** [comment]
Mhh if I run `make codegen` on current `master` I ran into issues with dependencies not being found for codegen, after running `make vendor` I had changes in Gopkg.
Do you also get Gopkg changes when running `make vendor` in `master` right now?

**Comment by travisn** [comment]
@galexrt yes, i did see a couple minor changes for the Gopkg.lock. Don't we have a CI check to prevent that from happening? I was thinking it was just my local environment. And were you able to run `make codegen` after running `make vendor`?

**Comment by galexrt** [comment]
Yes, after `make vendor`, `make codegen` worked fine.
Not having done a full compare with your PR, it at least seems to have produced the same codegen output locally for me as in the PR.

**Comment by travisn** [comment]
Interestingly, the `make vendor` issue must not be in master or else we would have `dirty` tags on the published images, but the images are ok: https://hub.docker.com/r/rook/ceph/tags/. I'll add the vendor change to this PR.

**Comment by galexrt** [comment]
@travisn I just remembered that I run `go get -u github.com/golang/dep/cmd/dep` just a few days ago. As my gopkg are mostly format changes that maybe the "issue" on my side. 
Could you see if `go get dep` and then `make vendor` also causes formatting changes in Gopkg for you?

**Pull request merged**
