### PR TITLE
ceph: Fix typo in dashboard admin password

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
**Description of your changes:**

Corrected secret name in one-liner for getting admin password from kubernetes.

**Checklist:**

- [X] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [X] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [X] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [X] Documentation has been updated, if necessary.
- [X] Unit tests have been added, if necessary.
- [X] Integration tests have been added, if necessary.
- [X] Pending release notes updated with breaking and/or notable changes, if necessary.
- [X] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [X] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by valentin-krasontovitsch** [comment]
I actually don't know which name is correct - the one that contains `admin`, or the one without... the truth (what secret gets setup, what secret gets read to fetch the credential) seems to be hidden in a different repository. still have to figure out which one...

**Comment by parth-gr** [comment]
> I actually don't know which name is correct - the one that contains `admin`, or the one without... the truth (what secret gets setup, what secret gets read to fetch the credential) seems to be hidden in a different repository. still have to figure out which one...

@valentin-krasontovitsch the secret is created with the name `rook-ceph-dashboard-password` so no need to change the command, you can change the name `rook-ceph-dashboard-admin-password` written in the description.
Also, do the Signed-off-by DCO is complaining Refer:https://rook.github.io/docs/rook/v1.6/development-flow.html#commit-structure.

**Comment by valentin-krasontovitsch** [comment]
Ah thank you wasn't sure if I was the one who was supposed to sign off on it : D

Thanks for pointing out the correct name! I've replaced the commit with the right name, and signed off on it.

Please, would you point me in the right direction for where I could have found that information myself?

I wanted to look at the operator, and figured maybe there's a repo with a docker image for it somewhere, but then I saw that in the rook deployment of the operator, you just run `ceph operator` - so that makes me think perhaps this is a ceph built-in? Sorry, I'm a bit confused, but would really like to learn more about the inner workings of rook : )

**Comment by leseb** [comment]
> Ah thank you wasn't sure if I was the one who was supposed to sign off on it : D
> 
> Thanks for pointing out the correct name! I've replaced the commit with the right name, and signed off on it.
> 
> Please, would you point me in the right direction for where I could have found that information myself?

It's part of your PR description in the checklist that you checked.
` Commit Message Formatting: Commit titles and messages follow guidelines in the developer guide.`

> 
> I wanted to look at the operator, and figured maybe there's a repo with a docker image for it somewhere, but then I saw that in the rook deployment of the operator, you just run `ceph operator` - so that makes me think perhaps this is a ceph built-in? Sorry, I'm a bit confused, but would really like to learn more about the inner workings of rook : )

**Comment by valentin-krasontovitsch** [comment]
Oh thanks but I didn't mean the thing about the signature - I meant where is the secret name encoded?

**Comment by parth-gr** [comment]
> Oh thanks but I didn't mean the thing about the signature - I meant where is the secret name encoded?

You can check this code https://github.com/rook/rook/blob/3f0b42fd5927ffb208b540f1fbdf297648afed16/pkg/operator/ceph/cluster/mgr/dashboard.go#L44, if you have the rook-ceph cluster created then you can directly get all the secrets created : `kubectl get secret -nrook-ceph`

or if you need to explore more you can start with the [Rook Documentation](https://rook.github.io/docs/rook/v1.6/)

**Comment by valentin-krasontovitsch** [comment]
ah, there it is! thanks a lot for the code link! now i know where i can start digging : )

**Comment by leseb** [comment]
Close since there is no activity. Feel free to re-open if needed. Thanks

**Comment by valentin-krasontovitsch** [comment]
sorry it seems like i fixed the changes as described upon getting my questions answered, so the commit can just be merged to fix the typo... O:)

**Comment by valentin-krasontovitsch** [comment]
i guess i might have to change the commit message, as the linter seems unhappy (though the logs are no longer available...)

**Comment by travisn** [comment]
Yes, the linter likes to complain about the commit subject. Try this:
```
docs: fix typo in dashboard admin password
```

**Review by travisn — APPROVED** [review]

**Pull request merged**
