### PR TITLE
DNM: rgw: temporary   api change to test the codegen ci  workflow

### PR DESCRIPTION
**Pull request by obnoxxx**
***Description:***

This chane is not intended for merging. It is meant to be a temporary change to test whether the codegen api workflow is functioning as intended.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by obnoxxx** [comment]
To summarize:

The change of this commit produces both crd and codegen changes. This is confirmed by the crds-gen and build workflows. however the codegen workflow passes  while the build  workflow shows the failure expected from the codegen workflow.

I am anyway  confused why the build workflow duplicates the crds-gen and codegen workflows 🤷🏼

**Comment by subhamkrai** [comment]
> To summarize:
> 
> The change of this commit produces both crd and codegen changes. This is confirmed by the crds-gen and build workflows. however the codegen workflow passes while the build workflow shows the failure expected from the codegen workflow.

With your changes, I think only the CRD test and build test is intended to fail. I don't see why Codegen should also fail as there are no changes for codegen CI.

> 
> I am anyway confused why the build workflow duplicates the crds-gen and codegen workflows 🤷🏼

I don't have the reason why it is a duplicate, but it's good to have it in one single place I guess only in the build test.

**Comment by obnoxxx** [comment]
@subhamkrai  wrote:
> > To summarize:
> > The change of this commit produces both crd and codegen changes. This is confirmed by the crds-gen and build workflows. however the codegen workflow passes while the build workflow shows the failure expected from the codegen workflow.
> 
> With your changes, I think only the CRD test and build test is intended to fail. I don't see why Codegen should also fail as there are no changes for codegen CI.

right, this PR does not change the  CI at all, just some API piece to trigger codegen to result in modified files.

Because the codegen and the build workflow per form perform the exact same codegen related operations and checks, I expected both of them to fail and not just one.





> 
> > I am anyway confused why the build workflow duplicates the crds-gen and codegen workflows 🤷🏼
> 
> I don't have the reason why it is a duplicate, but it's good to have it in one single place I guess only in the build test.

I think the most logical place to do codegen validation checks is in a workflow called codegen and not build. So for me, to remove duplication would mean to keep the test in the codegen workflow only instead of in the build workflow.

Of course, for a complete build, we need to first run codegen, but this should IMHO be done via Make target dependencies instead of duplicated workflow actions, and the build workflow  should definitely at least skip the duplicate validation check for modified codegen files.

**Comment by obnoxxx** [comment]
@subhamkrai  wrote:
> > To summarize:
> > The change of this commit produces both crd and codegen changes. This is confirmed by the crds-gen and build workflows. however the codegen workflow passes while the build workflow shows the failure expected from the codegen workflow.
> 
> With your changes, I think only the CRD test and build test is intended to fail. I don't see why Codegen should also fail as there are no changes for codegen CI.

To summarize: this PR only contains API changes that do trigger the codegen part of the build workflow to fail.
Since the codegen workflow performs the exact same codegen related actions as the build workflow, it should fail as well.

The fact that the codegen workflow succeeded proves that we have an issue with the codegen workflow in the CI. The question is: what is the issue and how can it be fixed?

**Comment by obnoxxx** [comment]
replying to myself:
> @subhamkrai wrote:
> 
> > > To summarize:
> > > The change of this commit produces both crd and codegen changes. This is confirmed by the crds-gen and build workflows. however the codegen workflow passes while the build workflow shows the failure expected from the codegen workflow.
> > 
> > 
> > With your changes, I think only the CRD test and build test is intended to fail. I don't see why Codegen should also fail as there are no changes for codegen CI.
> 
> To summarize: this PR only contains API changes that do trigger the codegen part of the build workflow to fail. Since the codegen workflow performs the exact same codegen related actions as the build workflow, it should fail as well.
> 
> The fact that the codegen workflow succeeded proves that we have an issue with the codegen workflow in the CI.

I fact,  the build workflow fails the  crd generated files validation check, just like the crds-gen workflow.

So this has proven nothing about the codegen workflow yet. It seems to be consistent.



>  The question is: what is the issue and how can it be fixed?

**Comment by obnoxxx** [comment]
I tried this change locally and `make codegen`resulted in changed files, specifically this one: `pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go`


Same result on these four systems:

* Fedora 40
* MacOS 14.6.1
* Ubuntu 18.04.6


So at least we  have an inconsistency between CI and local dev environments.

@BlaineEXE  - FYI.

**Comment by obnoxxx** [comment]
Update: the failing build workflow shows that the codegen check is actually working in theCI, just not in the dedicated workflow:

https://github.com/rook/rook/actions/runs/10900859746/job/31514642284?pr=14723#step:6:16

**Comment by obnoxxx** [comment]
I saw the build ci check failing, reporting modified files from `make crds`, `make codegen`, and make `gen-rbac`, most specifically `make crds`: https://github.com/rook/rook/actions/runs/10900859746/job/31514642284?pr=14723#step:6:18 .
After committing the results of `make crds` and updating the PR, these errors are gone from the CI runs but some Canary inregration test is failing. I am not quite sure yet what is the insight gained from this.

**Comment by obnoxxx** [comment]
Since the ci seems to behave differently than local Fedora and MacOS dev environments, I wanted to test locally with ubuntu which is what the ci is using.

On Ubunrtu 18.04, I had `make  codegen`produce a modified file `pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go`.

on Ubuntu 22.04 (which is what the ci is using, the same file was modified.

**Comment by obnoxxx** [comment]
Additional finding on ubuntu:

`make codegen`errored out because of the shebang line in `/build/codegen`codegen.sh`: 

```console
vagrant@ubuntu:~/go/src/github.com/rook/rook$ make codegen
/usr/bin/env: invalid option -- 'S'
Try '/usr/bin/env --help' for more information.
Makefile:165: recipe for target 'codegen' failed
make: *** [codegen] Error 125
vagrant@ubuntu:~/go/src/github.com/rook/rook$ 
```
after removing `-S`from the script, the error is different:
```console
vagrant@ubuntu:~/go/src/github.com/rook/rook$ make codegen
/usr/bin/env: 'bash -e': No such file or directory
Makefile:165: recipe for target 'codegen' failed
make: *** [codegen] Error 127
vagrant@ubuntu:~/go/src/github.com/rook/rook$ 
```

only after removing the `-e`from the shebang line as well did `make codegen`run.
This problem was the same on ubuntu 22.04 and 18.04

since this kind of problem does not happen on my local Fedora and MacOS systems, this poses the question why `make codegen`does not fail like this in the github ci's ubuntu runners.

**Comment by obnoxxx** [comment]
Update on latest findings:

a few codegen ci runs with a different  modifications to make the codegen workflow more verbose 
 have shown this:


* `make codegen`runs succwssfully in the ci
* git shows no changed file afterwards
* the contents of the file that is changed in my local systems is indeed unchanged.

so:

* In contrast to  an earlier suspicion,  `git` does not seem to be the culprit here.
* On the contrary, codegen itself is not working as it should, in the ci.


I will investigate the codegen tooling

**Review by travisn — COMMENTED** [review]
It's working now, the key was to copy the source dir under github.com

**Comment by obnoxxx** [comment]
> It's working now, the key was to copy the source dir under github.com

Thanks so much for helping here, @travisn ! My earkier attempts with `mv` instead of `cp`had not been successful.

The only remaining open question for me is this:

Why does `make codegen` not catch the modified file but the later invocation of the validation script does?

So overall, now the codegen workflow fails as expected with this change, but not at the expected step in the workflow.



I have created a n=ew PR #14883  with the resulting overall change to the codegen workflow file and will rebase this one for continued analysis.

**Comment by obnoxxx** [comment]
Now the fix has been merged as #14883 , we don't need this PR any more. closing.

**Pull request closed without merging**
