### PR TITLE
ci: update ubuntu image to 22.04

### PR DESCRIPTION
**Pull request by subhamkrai**
updating ubuntu image to 22.04 from 20.04 which is used in ci test

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by Madhu-1 — COMMENTED** [review]
changing in these many places is tough work and also error prone, we should work on central configuration file and read that?

**Comment by subhamkrai** [comment]
> changing in these many places is tough work and also error prone, we should work on central configuration file and read that?

last time I checked there was no option to have common place for these we can have composite action for `.steps.*`  till step section we have to define for example `name`, `runs-on` and so.

**Review by obnoxxx — APPROVED** [review]
LGTM

**Review by BlaineEXE — APPROVED** [review]

**Comment by Madhu-1** [comment]
> > changing in these many places is tough work and also error prone, we should work on central configuration file and read that?
> 
> last time I checked there was no option to have common place for these we can have composite action for `.steps.*` till step section we have to define for example `name`, `runs-on` and so.

Discussed with @subhamkrai about the alternative which we will explore and make subsequent changes where in the future we will make these changes in only one place.

**Review by Madhu-1 — APPROVED** [review]

**Comment by BlaineEXE** [comment]
Merging this. Thanks @subhamkrai !  Should we backport this to 1.14 also?

**Comment by subhamkrai** [comment]
> Merging this. Thanks @subhamkrai ! Should we backport this to 1.14 also?

Thanks and yes, let's backport it to 1.14

**Pull request merged**
